### ISSUE TITLE
Undeclared dependency on System.Net.Http

### ISSUE THREAD

**Issue by mqudsi** [stripe/stripe-dotnet#1001]
I'm on a plane right now so it's a little difficult to provide the exception logs (I'll post them when I can) but the latest version of Stripe for .NET deployed to .NET 4.6/4.7 via NuGet has an undeclared dependency on System.Net.Http which isn't resolved by the package manager. 

When deployed, a runtime exception is thrown by StripeRequestor at initialization. Installing the Http library via Nuget takes care of the problem.

**Comment by ob-stripe** [comment]
Hi @mqudsi, sorry for the late reply!

Are you still observing this issue? If so, could you provide some steps so we can try and reproduce it on our end?

**Comment by ob-stripe** [comment]
Closing this since the issue has been stale for a while, and as far as I can tell the dependency on `System.Net.Http` is properly declared in `Stripe.net.csproj`. Feel free to reply if you can provide more information though!
