### ISSUE TITLE
Customize the card view name and etc

### ISSUE THREAD

**Issue by ravenet** [stripe/stripe-dotnet#1009]
Hi,

I am using stripe to pay in our company website, but in the stripe V3, the design of the card elements is generated by stripe so we could not customize it.

For example,

Cardholder name,
card number
security no

all these should be customized in terms of the design.  how we can do it?. In V2 we have done it., but in V3 unable to do it.
Thank you

**Comment by remi-stripe** [comment]
@ravenet Github issues should be about bugs or feature requests for the stripe-dotnet library so the best solution here would be to contact our support team here: https://support.stripe.com/email
