### ISSUE TITLE
Project builds, but cannot publish

### ISSUE THREAD

**Issue by Zebranet** [stripe/stripe-dotnet#1010]
Hi there,

I've got a really curious one here.  I've implemented Stripe.Net into my web application, and all is well in testing.  I can make the calls and get data returned.  I can build and re-build the project locally, but as soon as I try to publish it, I get errors on all lines of code involving Stripe.

I get the following on publish:

'StripeConfiguration' is not a member of 'stripe'.

Type 'Stripe.StripeChargeService' is not defined.

Type 'Stripe.StripeChargeCreateOptions' is not defined.

I've tried both naming the Stripe commands directly (as above), or just referenced it at the top of the code, but neither work.

I'm running .Net 4.5 on the server and all the rest.  It's almost as if it doesn't want to work in a live environment.  

Does anyone out there have any ideas?  I'm using VS 2015 Community, and up until adding Stripe.Net, the project was compiling and pubishing without error.  I take these lines of code out, and it will publish without issue.  I've used the NuGet tool to install it into the project, so I'm at a bit of a loss. I'm using 10.4.0.0 of Stripe.net

Many thanks in advance.

**Comment by Zebranet** [comment]
Ignore me.  I'm an idiot!  I'd got another class called Stripe when I was testing.  Just removed that and, low and behold, it's worked.

Feel free to give me a kicking for being stupid.

**Comment by remi-stripe** [comment]
@Zebranet Glad to hear that you were able to figure it out quickly :)
