### ISSUE TITLE
Some errors with a vb.net version of the code

### ISSUE THREAD

**Issue by vbwyrde** [stripe/stripe-dotnet#1012]
To be honest, I do not know if this is a bug.  It may be.  At the very least it's confusing me and I imagine others might be in the same boat.  I took the c# code and used Telerik to translate it into vb.net which is what my project uses.  I don't typically have a problem doing so.  In this case I took the code and applied it to a new asp.net page.  I made no further modifications other than to add the Imports Stripe.  I am using the stripe.net version 10.4.0.0.  The code shows numerous places where the error reads "is not accessible in this context because it is 'Friend'."  I also am getting errors on the Me.ApplyAllParameters object which says "not a member of the stripe connect stripe oauth token service".  I realize that since I used a converter to create the vb.net version of this code the conversion may have been flawed.  However, I've done these types of conversions hundreds of times and have not had issues with it, so I'm inclined to think it's something else, and possibly an issue with the stripe dll somehow.  Anyway, if you can help me to understand this I'd very much appreciate it.  And apologies in advance if it's just some dumb oversight on my part!

Here is the code:

```vbnet
Imports Stripe
Imports Stripe.Infrastructure
Imports System.IO
Imports System.Threading
Imports System.Threading.Tasks
Imports System.Web.Script.Serialization
Imports Newtonsoft.Json

Public Class StripeConnect
    Inherits System.Web.UI.Page

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load

    End Sub

    Public Class StripeOAuthTokenService
        Inherits StripeService
        Public Sub New(Optional apiKey As String = Nothing)
            MyBase.New(apiKey)
        End Sub

        'Sync
        Public Overridable Function Create(createOptions As StripeOAuthTokenCreateOptions, Optional requestOptions As StripeRequestOptions = Nothing) As StripeOAuthToken
            Return Mapper(Of StripeOAuthToken).MapFromJson(Requestor.PostStringBearer(Me.ApplyAllParameters(createOptions, Urls.OAuthToken, False), SetupRequestOptions(requestOptions)))
        End Function

        Public Overridable Function Deauthorize(clientId As String, stripeUserId As String, Optional requestOptions As StripeRequestOptions = Nothing) As StripeOAuthDeauthorize
            Dim url = ParameterBuilder.ApplyParameterToUrl(Urls.OAuthDeauthorize, "client_id", clientId)
            url = ParameterBuilder.ApplyParameterToUrl(url, "stripe_user_id", stripeUserId)

            Return Mapper(Of StripeOAuthDeauthorize).MapFromJson(Requestor.PostString(url, SetupRequestOptions(requestOptions)))
        End Function

        'Async
        Public Overridable Function CreateAsync(createOptions As StripeOAuthTokenCreateOptions, Optional requestOptions As StripeRequestOptions = Nothing, Optional cancellationToken As CancellationToken = Nothing) As Task(Of StripeOAuthToken)
            Return Mapper(Of StripeOAuthToken).MapFromJson(Await Requestor.PostStringBearerAsync(Me.ApplyAllParameters(createOptions, Urls.OAuthToken, False), SetupRequestOptions(requestOptions), cancellationToken))
        End Function

        Public Overridable Function DeauthorizeAsync(clientId As String, stripeUserId As String, Optional requestOptions As StripeRequestOptions = Nothing, Optional cancellationToken As CancellationToken = Nothing) As Task(Of StripeOAuthDeauthorize)
            Dim url = ParameterBuilder.ApplyParameterToUrl(Urls.OAuthDeauthorize, "client_id", clientId)
            url = ParameterBuilder.ApplyParameterToUrl(url, "stripe_user_id", stripeUserId)

            Return Mapper(Of StripeOAuthDeauthorize).MapFromJson(Await Requestor.PostStringAsync(url, SetupRequestOptions(requestOptions), cancellationToken))
        End Function

    End Class

End Class
```

**Comment by ob-stripe** [comment]
Hey @vbwyrde, apologies for the late reply.

Unfortunately, I don't think we can help here as VB is not among the list of programming languages officially supported by Stripe.

If you have requests for specific changes that we could apply to the library to make the conversion to VB work better, we'd be happy to evaluate them, but at this time we have no plans for ensuring that the library works when transpiled to VB.
