### ISSUE TITLE
Help @ Support That doesn't email you back with professionalism 

### ISSUE THREAD

**Issue by Ezpzgp** [stripe/stripe-dotnet#1013]
-- Removing text that is not for this repository --

**Comment by Ezpzgp** [comment]
please call at 937 623 4866

**Comment by remi-stripe** [comment]
@Ezpzgp This repository is here to talk about code, not to talk about support. I have removed your message to avoid leaking your personal information to anyone.

Please contact our support team instead: https://support.stripe.com/email

I am locking this conversation to avoid it spreading.
