### ISSUE TITLE
Unable to connect to the remote server

### ISSUE THREAD

**Issue by renjithr2081** [stripe/stripe-dotnet#1015]
Hello , 

I am using Stripe.NET 2.8.0 and started getting 'Unable to connect to the remote server' on the line
chargeService.Create

But when the customer tries 2nd time it works mostly
Any ideas?

**Comment by ob-stripe** [comment]
Hi @renjithr2081, sorry for not replying sooner. This sounds like a connectivity issue on your end and not an issue with the library itself.

If you're still having this issue, I would recommend that you reach out to your network administrator / hosting provider and ask them to check the connectivity between your server and Stripe's API servers at `api.stripe.com`.

I'm going to close the issue, but feel free to reply if you believe this is truly an issue with the stripe-dotnet library.
