### ISSUE TITLE
StripeInvoiceService.ListUpcomingLineItems wrong options object

### ISSUE THREAD

**Issue by martijn-broekstra** [stripe/stripe-dotnet#1023]
The ListUpcomingLineItems call uses the StripeUpcomingInvoiceOptions object as options object but this is not a StripeListOptions object. So I can't page the upcoming invoice line items.

**Comment by gh-stripe** [comment]
Hey @martijn-broekstra, thanks for reporting the issue! We're looking into it.

**Comment by ob-stripe** [comment]
This was fixed in 22.0.0.

`ListUpcomingLineItems` now accepts a new `UpcomingInvoiceListLineItemsOptions` argument. The new class accepts all the same parameters as the previous `UpcomingInvoiceOptions` class, but also accepts pagination parameters.
