### ISSUE TITLE
How set billing property when create subscription ?

### ISSUE THREAD

**Issue by tranleanhthe** [stripe/stripe-dotnet#1030]
The model in StripeSubscriptionCreateOptions was not "billing" property. So how we can change "billing" ? 

        public DateTime? BillingCycleAnchor { get; set; }
        public bool BillingCycleAnchorNow { get; set; }
        public bool BillingCycleAnchorUnchanged { get; set; }
        [JsonProperty("customer")]
        public string CustomerId { get; set; }
        [JsonProperty("subscription_items_array")]
        public List<StripeSubscriptionItemOption> Items { get; set; }

**Comment by ob-stripe** [comment]
@tranleanhthe There is no `billing` parameter in subscription creation requests: https://stripe.com/docs/api#create_subscription.

Additionnally, GitHub issues are specifically for bugs or feature requests in the stripe-dotnet library, not for support requests, so I'm going to close the issue. Please send a message to support using the form at https://support.stripe.com/email to explain what you're trying to do exactly.

**Comment by tranleanhthe** [comment]
https://stripe.com/docs/subscriptions/ach-credit
But other language have "billing" parameter. Why .Net doesn't have ?

**Comment by ob-stripe** [comment]
My bad @tranleanhthe! You are correct, this is a preview feature that is not yet supported by the .NET library at the moment.

Reopening the issue as this is a legitimate feature request. We will try to release an update to support this soon.
