### ISSUE TITLE
Customer in StripeBankAccount

### ISSUE THREAD

**Issue by lehne** [stripe/stripe-dotnet#1032]
I am trying to handle the customer.source.created event. The JSON object getting sent has a field called customer with the customer ID in it, but the Entity classes in Stripe.net do not have a field for customer ID.
Example:
```
{
  "object": {
...
"customer": "cus_45hdlkjdflkjend",
```

I am de-serializing as such:
```Mapper<Source>.MapFromJson(evt.Data.Object);```
Should there be a customer field or should I just access using the dynamic evt.Data.Object.customer?

**Comment by ob-stripe** [comment]
Hi @lehne, thanks for reporting this. I've pushed a patch for this in #1034 and we will release an update soon.
