### ISSUE TITLE
StripePlan class only Integer amounts.

### ISSUE THREAD

**Issue by c-cortes** [stripe/stripe-dotnet#1036]
Detected when you list all your Stripe plans, StripePlanService.List returns a list of StripePlan objects. 

The problem is StriplePlan.Amount is defined as Integer value, and if you define a Plan with for example 9.90€, the service returns 990€ when you list your plans with Stripe.Net library.

Solution: Please convert the value type to Decimal or Double.

**Comment by remi-stripe** [comment]
@c-cortes This is expected behaviour. Our [documentation](https://stripe.com/docs/currencies#zero-decimal) says:

> All API requests expect amounts to be provided in a currency’s smallest unit. For example, to charge $10 USD, provide an amount value of 1000 (i.e, 1000 cents).

So if the plan is for USD you have to divide the amount by 100.

**Comment by c-cortes** [comment]
Ok, I understand. 

Thanks for help.
