### ISSUE TITLE
How can get all customer are using a plan ?

### ISSUE THREAD

**Issue by tranleanhthe** [stripe/stripe-dotnet#1041]
Hi,
I want to get all clients using a plan with the plan.
Currently, Strip.Net does not have an API for that. I have to grab all the clients and filter. This makes the website slow if there are many customers.
I would like to update prices for a plan and update with all customers who are using this plan.
How to get all the customers are using a plan ?

**Comment by ob-stripe** [comment]
Hey @tranleanhthe. The API itself does not accept a `plan` parameter when [listing customers](https://stripe.com/docs/api#list_customers).

What you can do instead is [list subscriptions](https://stripe.com/docs/api#list_subscriptions) with the [`plan`](https://stripe.com/docs/api#list_subscriptions-plan) parameter, then retrieve the [`customer`](https://stripe.com/docs/api#subscription_object-customer) attribute of each [subscription object](https://stripe.com/docs/api#subscription_object).

This is already possible with Stripe.NET, by setting [`PlanID`](https://github.com/stripe/stripe-dotnet/blob/cf95812d14c39efad38747e8ab3d2ecb4c8204d6/src/Stripe.net/Services/Subscriptions/StripeSubscriptionListOptions.cs#L17) in `StripeSubscriptionListOptions `.
