### ISSUE TITLE
Can't find Delete method in StripeSubscriptionService

### ISSUE THREAD

**Issue by tranleanhthe** [stripe/stripe-dotnet#1043]
Hi,
I can't find Delete method in StripeSubscriptionService but I read document it have.
https://stripe.com/docs/api/dotnet#cancel_subscription.
Is have missing ? or Have other way to cancel a subscription ?

**Comment by ob-stripe** [comment]
Hey @tranleanhthe! The API documentation is incorrect: the service method you need to call is actually called [`Cancel`](https://github.com/stripe/stripe-dotnet/blob/19f473e2d6175d471406f019a8039092a19a1e7f/src/Stripe.net/Services/Subscriptions/StripeSubscriptionService.cs#L61), not `Delete`.

Thanks for bringing this to our attention -- I'll let the docs team know about this issue and we'll fix the example shortly.
