### ISSUE TITLE
System.IO.FileLoadException as soon as I reference Stripe.StripeConfiguration

### ISSUE THREAD

**Issue by c0ndensate** [stripe/stripe-dotnet#1045]
As soon as I reference Stripe.StripeConfiguration.SetApiKey

System.IO.FileLoadException: 'Could not load file or assembly 'Stripe.net, Version=11.6.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)'

I have spent about 2 hours trying to get around this to no avail. Please help.

Update: a little more research suggests that I must download the entire codebase and recompile and sign with my own code signing utility. Does this sound correct?

**Comment by ob-stripe** [comment]
Hey @c0ndensate, sorry for the late reply!

@fred-stripe @anelder-stripe Can you take a look at this issue? It sounds related to #40.

**Comment by c0ndensate** [comment]
Here is the solution that worked for me.
1) Download Stripe.net from github and load Stripe.net.sln in Visual Studio 
2) Compile Stripe.net project (don't compile tests)
3) Obtain stripe.net.dll from bin\Release\net45 folder
4) In your actual project, remove reference to Stripe.net and replace the file and re-add reference

This issue can be closed

**Comment by ob-stripe** [comment]
Thanks a lot for the information @c0ndensate! We appreciate it and will try to fix the library so these steps are not necessary.

Closing the issue for now.

**Comment by ac1dphr3aq** [comment]
lol

**Comment by yellowfever13** [comment]
This is still broken, at least a problem with the same symptoms still exists.  net core 5 project, works fine locally, when I publish and place on production server, FileNotFoundException for stripe dll. Tried the nuget package, got the repo and compiled myself, can't get anything to work. This is super frustrating after spending hours developing against Stripe, now I may have to pivot to another payment provider.  The "sign the assembly" option did not change my outcome.

**Comment by ob-stripe** [comment]
HI @yellowfever13, sorry to hear you're having trouble with the library. Does the error message you're seeing also mention "A strongly-named assembly is required"?

If so, it likely means your production environment is set to require strong-named assemblies. Per Microsoft's own documentation:
> For .NET Core, strong-named assemblies do not provide material benefits.

If it's an option at all, I would recommend disabling strong-named assemblies in your production environment.

If that isn't an option, you can try signing the Stripe.net assembly yourself using a tool such as this one: https://brutaldev.com/post/net-assembly-strong-name-signer.
