### ISSUE TITLE
Subscription renewal remain unpaid ..

### ISSUE THREAD

**Issue by amitkaushal80** [stripe/stripe-dotnet#1051]
Upon Subscription renewal only two event get fired. These events are invoice.created, customer.subscription.updated. And these events are successful. No other events like charge.successed got fired. Dashboard shows invoice unpaid. What could be the reason and how to resolve it?

**Comment by ob-stripe** [comment]
@amitkaushal80 This does not sound like an issue with the .NET library. Please log into your Stripe account and send another message using the form at https://support.stripe.com/email to describe the problem. Make sure to include the IDs of the subscription and of the events.
