### ISSUE TITLE
Error thrown when filename passed to FileUploadService doesn't match a known extension

### ISSUE THREAD

**Issue by fred-stripe** [stripe/stripe-dotnet#1053]
This code doesn't check the return value from the MimeTypes.GetMimeType(filename)—which causes the .NET framework to throw an exception when a null mimeType is passed:

https://github.com/stripe/stripe-dotnet/blob/96cdbaffa5609ab6f8c4925342247c5a8be6f0ac/src/Stripe.net/Infrastructure/MimeTypes.cs

You can test this by passing an empty filename, or one without an exception—either should trigger the exception.

**Comment by ob-stripe** [comment]
Fixed in v11.8.2.
