### ISSUE TITLE
3D secure handling

### ISSUE THREAD

**Issue by jgauffin** [stripe/stripe-dotnet#1070]
The 3D secure service is marked as obsolete, but I cannot figure out how to use the `Stripe3DSecureCreateOptions`  with the `StripeSourceService`.

Or is that class also obsolete?

A comment from you in issue #861 says that one should look at a test too see how everything should be done now when `Stripe3DSecureService`, but both tests are using the `Stripe3DSecureService`.

The API reference for Sources doesn't include information for 3D secure sources. And the `stripe.js` API is different from the source object in the `API Reference`. 

In stripe.js I create a source like this:

            Stripe.createSource({
                type: 'three_d_secure',
                amount: @(Model.TotalRaw.ToString("####") + "00"),
                currency: "usd",
                three_d_secure: {
                    customer: customerId,
                    card: cardSource
                },
                redirect: {
                    return_url: "@Url.Action("Completed", new {id = Model.OrganizationId})"
                }
            }).then(function(result) {
                if (result.error) {
                    var $form = $('#payment-form');
                    $form.find('.payment-errors').text(response.error.message).addClass('active');
                    $form.find('button').prop('disabled', false);
                } 
            });

But how is it done with the C# client?

The closest I come is this:

                var opts1 = new StripeSourceCreateOptions
                {
                    Type = "three_d_secure",
                    ThreeDSecureCardOrSourceId = ctx.CardSource,
                    Amount = (int)amount*100,
                    Currency = "usd",
                    
                }

However, 3dsecure needs a redirect to allow the client to authenticate against the bank. How do I get that URL from stripe? Should the 3dsecure source be attached to the customer (like it's possible with `Stripe3DSecureCreateOptions`) ?

**Comment by remi-stripe** [comment]
@jgauffin The `Stripe3DSecureCreateOptions` is deprecated. It was for the old 3DS implementation. Since then we released Sources which is an abstraction on top of all payment methods in our API. This allows you to re-use the same logic on creation or charges with some specific information per Source.

To create a 3DS Source, the code would look like this:

```
            var threeDSCreateOptions = new StripeSourceCreateOptions
            {
                Type = StripeSourceType.ThreeDSecure,
                Amount = 1234,
                Currency = "eur",
                RedirectReturnUrl = "http://no.where/webhooks",
                ThreeDSecureCardOrSourceId = "src_XXXXX"
            };

            var sourceService = new StripeSourceService();
            var source3DS = sourceService.Create(threeDSCreateOptions);
```
