### ISSUE TITLE
Application name for a charge

### ISSUE THREAD

**Issue by HakanL** [stripe/stripe-dotnet#1073]
How can I see the application name that is associated with a charge. I have a web store connected to Stripe, and on my charges I have the Application (Id) as "ca_XXXXX". Is there a call to determine what the name of the connected application is for ca_XXXXX?

Thanks!

**Comment by ob-stripe** [comment]
Hi @HakanL. The only way of getting the name of the application is by expanding the `application` attribute when fetching the charge API resource.

Currently, the library doesn't support this, but I've pushed a fix in #1074. We should be able to release an updated version of the library soon.

**Comment by ob-stripe** [comment]
Fixed in v11.10.0.

**Comment by HakanL** [comment]
Thanks!
