### ISSUE TITLE
Feature Request: Make 'empty' lists return an empty collection instead of null

### ISSUE THREAD

**Issue by zacherkkila** [stripe/stripe-dotnet#1075]
I find it kind of frustrating to have to perform `null` checks constantly for things like subscriptions

For example:

```
if(customer.Subscriptions != null)
{
    List<StripeSubscription> subscriptions = customer.Subscriptions.Where(x => x.foo == bar).ToList();
}
```

An empty list seems like a better option, am I missing something or is there a reason why something like the following wouldn't work?

```
[JsonProperty("subscriptions")]
public StripeList<StripeSubscription> Subscriptions { get; set; } = new StripeList<StripeSubscription>();
```

**Comment by zacherkkila** [comment]
I guess I sort of answered my own question with a suitable workaround, just wrote a simple extension method that will work for my needs

```
public static class StripeCustomerExtension
{
    public static StripeList<StripeSubscription> getSubscriptions(this StripeCustomer customer)
    {
        return customer.Subscriptions == null ? new StripeList<StripeSubscription>() : customer.Subscriptions;
    }
}
```

**Comment by remi-stripe** [comment]
cc @ob-stripe as something we likely want to fix to match our other libraries!
