### ISSUE TITLE
In my project solution in api didn't start

### ISSUE THREAD

**Issue by skulster29** [stripe/stripe-dotnet#1079]
Please only file issues here that you believe represent actual bugs or feature requests for the Stripe.net library.

If you're having general trouble with your Stripe integration, please reach out to Stripe support using the form at https://support.stripe.com/ (preferred) or via email to support@stripe.com.

If you are reporting a bug, please include your OS version, .NET version and the version of the Stripe.net library you're using, as well as any other details that may be helpful in reproducing the problem.

**Comment by ob-stripe** [comment]
@skulster29 Please write to support at https://support.stripe.com/email and include details about your issue: what your environment is, what error message you're seeing, etc.
