### ISSUE TITLE
Order object - Status Transitions - Fulfilled is actually returned as 'fulfiled' in json

### ISSUE THREAD

**Issue by robkite** [stripe/stripe-dotnet#1085]
StripeStatusTransitions.cs:
```
[JsonConverter(typeof(StripeDateTimeConverter))]
[JsonProperty("fulfilled")]
public DateTime? Fulfilled { get; set; }
```

However the actual property returned in json is missing an 'l': fulfiled (as per the documentation - https://stripe.com/docs/api/dotnet#order_object).

Seems this was probably a typo originally, but as they now don't match then this property is never populated from the json response.

Changing to the below should fix the issue (unless anyone wants to change the actual json response?):
```
[JsonConverter(typeof(StripeDateTimeConverter))]
[JsonProperty("fulfiled")]
public DateTime? Fulfilled { get; set; }
```

**Comment by remi-stripe** [comment]
@robkite Thanks a lot for the detailed report! I'll push a fix for this and we'll release it in the next few days!
