### ISSUE TITLE
Stripe.net Version 11.10  -  StripeChargeCreateOptions() does not have "Source" property

### ISSUE THREAD

**Issue by ShabariRepo** [stripe/stripe-dotnet#1087]
https://stripe.com/docs/api/node#create_charge
- Trying to add the source property here for the above mentioned method
- I see that it is there in version 4 but not in 11.10
- however there is a property called SourceTokenOrExistingTokenID is this the replacement
- in the older versions the **Source** property was an object whereas this one is just a string
- also I see the card details listed as **SourceCard** class property wondering if this is the change here from the older versions to the newer?

![image](https://user-images.githubusercontent.com/10635357/34651689-2d159720-f3a1-11e7-9b38-d0209bc21edf.png)

Thanks in advance

**Comment by ShabariRepo** [comment]
so quick update:
- I charged what used to be the source{ tokenId } under the now SourceTokenOrExistingSourceId
- and the test charge was registered in Stripe
- Based on that, I am assuming this is the new property instead of going through Source obj
- **** If I am right please close the issue and hopefully this article will serve as a search result for someone with the same question
- if not or this is not the best practice, if someone could elaborate as to how they operate in v11.10 that would be awesome

Thank you & Happy Striping in 2018 🚀

**Comment by ob-stripe** [comment]
Hi @ShabariRepo, `SourceTokenOrExistingSourceId` is indeed the property you want to use. You can view a simple example in the API reference: https://stripe.com/docs/api/dotnet#create_charge.

`SourceCard` is used when directly supplying raw card information. It is strongly recommended you do _not_ use this method as it greatly increases the burden of PCI compliance, cf. https://stripe.com/docs/security#validating-pci-compliance.
