### ISSUE TITLE
StripeSourceCreateOptions does not have a statement_descriptor property

### ISSUE THREAD

**Issue by AFallad** [stripe/stripe-dotnet#1088]
Hello,

I'm trying to create a source and add data to the top level statement_descriptor property (https://stripe.com/docs/api#create_source-statement_descriptor) however the class StripeSourceCreateOptions.cs does not contains a property that maps to it, I can see that bancontact[statement_descriptor], ideal[statement_descriptor] and sofort[statement_descriptor] are mapped, but not the top level statement_descriptor.

Thanks in advance for your help!

**Comment by remi-stripe** [comment]
@AFallad Thanks a lot for the report! I'll work on a PR and hopefully push a fix in the next few days!
