### ISSUE TITLE
StripeSourceUsage.SingleUse is incorrect

### ISSUE THREAD

**Issue by AFallad** [stripe/stripe-dotnet#1092]
Hello, while doing some testing I noticed that I was getting this response 

`{
  "error": {
    "type": "invalid_request_error",
    "message": "Invalid usage: must be one of reusable or single_use",
    "param": "usage"
  }
}
`

Seems that the following line has a - instead of _
https://github.com/stripe/stripe-dotnet/blob/6eed728ac94da6b686a6417b22679e3193f0d1b8/src/Stripe.net/Constants/StripeSourceUsage.cs#L6

Thanks in advance for your help!

**Comment by remi-stripe** [comment]
@AFallad Thanks for the report. We have a PR up that fixes this here https://github.com/stripe/stripe-dotnet/pull/1084 and it will get merged into the next release of stripe-dotnet hopefully later this week.
