### ISSUE TITLE
StripeCharge does not have a Card member

### ISSUE THREAD

**Issue by BendicoE** [stripe/stripe-dotnet#1095]
I'm trying to access the card information of a charge. But the .Source.Card member of th StripeCharge is always null. However, in the Stripe dashboard, I can see that the charge event data has a "card" member within the "source" member that contains card information. Is there a way to access this information in Stripe.NET?

**Comment by ob-stripe** [comment]
Hi @BendicoE. This is basically the same issue as #1090: the [`Source`](https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Entities/StripeCharge.cs#L300) attribute on `StripeCharge` objects is a `Source` object, which does not yet handle wrapping `StripeSource` (confusing, I know!).

I'm closing this issue as a duplicate. We're still working on fixing #1090, thanks for your patience!
