### ISSUE TITLE
StripeAccountService (Get/GetAsync) returns StripeAccount object with null CurrenciesSupported

### ISSUE THREAD

**Issue by adrianbontea** [stripe/stripe-dotnet#1098]
The `CurrenciesSupported` array is null on the returned `StripeAccount` object when using both the sync and async methods.

- Package version: 12.1.0
- Assembly version: 12.1.0.0
- Target framework: .Net Framework 4.6.1

An older version of the client correctly returns the `CurrenciesSupported` array on  `StripeAccount`:

- Package version: 5.2.0
- Assembly version: 5.2.0.0
- Target framework: .Net Framework 4.6.1

Also verified that Stripe Account API correctly returns the `currencies_supported` field via curl

**Comment by remi-stripe** [comment]
@adrianbontea In API version [2016-03-07](https://stripe.com/docs/upgrades#2016-03-07), a change was introduced where the list of currencies supported by a given Stripe account were removed:

> Removes the currencies_supported property from the Account object. You can find a list of supported currencies by retrieving a Country Spec object for the country of the account.

This has been live for almost 2 years now and stripe-dotnet explicitly enforces a recent API version so this change is explicitly enforced in the library. 

You need to use the CountrySpec API instead to see what currencies are supported on an account based on the country it's from.

**Comment by adrianbontea** [comment]
Thanks!
