### ISSUE TITLE
Missed BillingCycleAnchorNow in the StripeSubscriptionUpdateOptions

### ISSUE THREAD

**Issue by shatskiy** [stripe/stripe-dotnet#1101]
I'm migrating from one of the old version this library and I've missed BillingCycleAnchorNow during update subscription. I see, that this option still exists in the StripeSubscriptionCreateOptions but it's not present in the StripeSubscriptionUpdateOptions. For example, I'd like update subscription - end trial and set new billing cycle anchor.

Is there some new approach to set this property maybe? But I can see this option in the API documentation for subscription update - https://stripe.com/docs/api#update_subscription or https://stripe.com/docs/subscriptions/billing-cycle#api

**Comment by remi-stripe** [comment]
@shatskiy It's a new property we added a few days ago. We're working on adding all features in https://github.com/stripe/stripe-dotnet/pull/1099 and will make sure to also add the option for updates!

**Comment by ob-stripe** [comment]
This was fixed in #1099 and released in stripe-dotnet 13.0.0.
