### ISSUE TITLE
Suggestion: Services should have a real parameterless constructor

### ISSUE THREAD

**Issue by slimCODE** [stripe/stripe-dotnet#1104]
Having a real parameterless constructor allows classes to be used as generic types in methods with a `where T : new()` clause. A good example in the context of this library would be a service builder method that ensures only one instance of any given service is created:

```csharp
        private TService GetStripeService<TService>() where TService : StripeService, new()
        {
            var key = typeof(TService);

            if (!_services.TryGetValue(key, out var service))
            {
                lock(_services)
                {
                    if (!_services.TryGetValue(key, out service))
                    {
                        _services[key] = service = new TService();
                    }
                }
            }

            return service as TService;
        }
```

Since all Stripe .NET services have an optional `apiKey` parameter, replaced by `null` at compile-time, the above construction cannot be made. We have to remove the `new()` constraint and either use builders or reflection to create instances, which is less "elegant".

**Comment by ob-stripe** [comment]
Fixed in 13.1.0.
