### ISSUE TITLE
Missing StripePlan Name

### ISSUE THREAD

**Issue by adams-hub** [stripe/stripe-dotnet#1106]
Why was StripePlan Name changed to Nickname?
Nickname is not set in the plan dashboard and is null. How do I get the plan name now?

**Comment by ob-stripe** [comment]
Hi @adams-hub, the library was updated to reflect the changes in this API version: https://stripe.com/docs/upgrades#2018-02-05.

As this is not a bug with the library, I'm closing the issue. Please reach out to support at https://support.stripe.com/email if you have more questions.

**Comment by arammarm** [comment]
This is still an issue why did you close?

**Comment by remi-stripe** [comment]
@arammarm The Plan API Resource doesn't have a `name` property and instead has a `nickname` property as documented [here](https://stripe.com/docs/api/plans/object#plan_object-nickname). The PHPDocs in the library reflect the most recent API version and that changed back in 2018 which was almost 5 years ago.

**Comment by Modaouche** [comment]
in this doc [here](https://stripe.com/docs/api/plans/object#plan_object-nickname) like @remi-stripe said
They added detail about nickname:

nickname:
string
A brief description of the plan, __hidden from customers__.
