### ISSUE TITLE
Retrieve Active Redemption data for Coupon

### ISSUE THREAD

**Issue by DonaldRecord** [stripe/stripe-dotnet#1108]
Hello,

First off, this is a question - not a bug, and any help would be greatly appreciated. I am using the v13.0.1 of the library.

On the dashboard, at the URL "https://dashboard.stripe.com/coupons/{couponId}", I want the data in the "Active Redemptions" section via the API. 

I did not see any mention of it in the API document, nor is it returned by the coupon service. Is it possible to obtain this from the .NET Client?

Please let me know, thank you.

**Comment by ob-stripe** [comment]
Hi @DonaldRecord. The ability to retrieve customers that have an active discount with a specific coupon applied to them is limited to the dashboard for now.

I recommend you reach out to support at https://support.stripe.com/email if you have any questions, or if this is a feature that you'd like to see in the API.

**Comment by DonaldRecord** [comment]
Alright, will do. Thank you for the fast response.
