### ISSUE TITLE
Missing prorate option on StripeSubscriptionCreateOptions

### ISSUE THREAD

**Issue by daithimaolain** [stripe/stripe-dotnet#1113]
The stripe docs for creating a subscription (https://stripe.com/docs/api#create_subscription) refer to a prorate boolean option, which appears to be missing from the `StripeSubscriptionCreateOptions` class.

**Comment by ob-stripe** [comment]
Hi @daithimaolain, thanks for the report! It appears we forgot to add this new parameter in version 13.0.0. We'll release a fix shortly.

**Comment by ob-stripe** [comment]
Fixed in 13.2.0.
