### ISSUE TITLE
 StripeRedirect does not have a property for failure_reason

### ISSUE THREAD

**Issue by AFallad** [stripe/stripe-dotnet#1118]
Hello again,

I noticed the failure_reason does not have a mapping to the StripeRedirect model, hopefully it can be added.
https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Entities/Sources/StripeRedirect.cs

![image](https://user-images.githubusercontent.com/9258996/36762752-be64e0f2-1bea-11e8-8d33-bbf89a2e476e.png)

Thanks in advance for the help!

**Comment by brandur-stripe** [comment]
Oops. Yes that's absolutely right. I've added a patch in #1119. Thanks for reporting!

**Comment by ob-stripe** [comment]
Fixed in 13.3.0.
