### ISSUE TITLE
StripeCharge class should have fee property

### ISSUE THREAD

**Issue by SLaks** [stripe/stripe-dotnet#1120]
This is for the fee charged by Stripe, and is separate from `ApplicationFee`.

Sample JSON:

```json
    "fee": 465,
    "fee_details": [
      {
        "amount": 465,
        "amount_refunded": 0,
        "application": null,
        "currency": "usd",
        "description": "Stripe processing fees",
        "type": "stripe_fee"
      }
    ],
```

**Comment by ob-stripe** [comment]
Hi @SLaks. [`fee`](https://stripe.com/docs/api#balance_transaction_object-fee) and [`fee_details`](https://stripe.com/docs/api#balance_transaction_object-fee_details) are attributes of [balance_transaction](https://stripe.com/docs/api#balance_transaction_object) objects.

You can retrieve the balance_transaction object for a given charge using the charge's [`balance_transaction`](https://stripe.com/docs/api#charge_object-balance_transaction) attribute. This attribute is also expandable so you can expand it inline when retrieving the charge.

stripe-dotnet already supports this, e.g.:

```c#
var balanceService = new StripeBalanceService();
var chargeService = new StripeChargeService();

StripeCharge charge = chargeService.Get("ch_...");
StripeBalanceTransaction transaction = balanceService.Get(charge.Id);
int fee = transaction.Fee;
```
