### ISSUE TITLE
Suggestion: Redirect failure_reason class with consts

### ISSUE THREAD

**Issue by AFallad** [stripe/stripe-dotnet#1121]
Hello!

Since https://github.com/stripe/stripe-dotnet/issues/1118 is being implemented, it would also be convenient to have a StripeSourceRedirectFailureReason with the consts listed in https://stripe.com/docs/api#source_object-redirect-failure_reason for this new field. Just like some other classes have (https://github.com/stripe/stripe-dotnet/tree/master/src/Stripe.net/Constants)

Thanks in advance for the response, I really apreciate the effort.

**Comment by ob-stripe** [comment]
Hey @AFallad, I'm going to close this issue so we can centralize feedback on the PR itself (#1119), but I agree that a const or enum would be preferable.
