### ISSUE TITLE
Can't create card token nullReferenceException at System.Reflection.MonoProperty.GetValue

### ISSUE THREAD

**Issue by saikoryu** [stripe/stripe-dotnet#1124]
Hi, I've implemented to code simple here to create a token but I always get this error. 

```c#
public static string CreateToken(string cardNumber, int cardExpMonth, int cardExpYear, string cardCVC, string addressZip)
{
    string stripeId = ConfigManager.GetValue("stripe_id");

    StripeConfiguration.SetApiKey(stripeId);

    var tokenOptions = new StripeTokenCreateOptions()
    {
        Card = new StripeCreditCardOptions()
        {
            Number = cardNumber,
            ExpirationYear = cardExpYear,
            ExpirationMonth = cardExpMonth,
            Cvc = cardCVC,
            AddressZip = addressZip
        }
    };

    var tokenService = new StripeTokenService();
    StripeToken stripeToken = tokenService.Create(tokenOptions);

    return stripeToken.Id; // This is the token
}
```
Error : 

```
{System.NullReferenceException: Object reference not set to an instance of an object.
  at System.Reflection.MonoProperty.GetValue (System.Object obj, System.Object[] index) [0x00027] in <ac68d71563574e6dae68a0d9aff12bbf>:0 
  at Stripe.Infrastructure.ParameterBuilder.ApplyAllParameters (Stripe.StripeService service, Stripe.StripeBaseOptions obj, System.String url, System.Boolean isListMethod) [0x0002f] in <1694782dfa1349c3b7d95eb59341fd5f>:0 
  at Stripe.StripeTokenService.Create (Stripe.StripeTokenCreateOptions createOptions, 
...
```

**Comment by ob-stripe** [comment]
@saikoryu Your code looks correct. Can you make sure that all your variables (the 5 method arguments, plus `stripeId`) have non-null values? Also, which version of stripe-dotnet are you using?

**Comment by saikoryu** [comment]
Thanks for the fast reply. Yes I made sure that every parameters and stripeId aren't null. I am using the latest version released today v13.3.0.

**Comment by ob-stripe** [comment]
🤔  Your code works, I tested it with the most basic app: https://gist.github.com/ob-stripe/e1beeab0464f2b192547f9b6344f8761. (The only thing I changed is that I replaced `ConfigManager.GetValue` with `Environment.GetEnvironmentVariable` to get the API key.)

I've googled a bit and this seems to be a Xamarin linking issue. Are you using Xamarin? If so, could you try disabling linking?

**Comment by ob-stripe** [comment]
@saikoryu You shouldn't need to add this line, the library already takes care of this.

In your Xamarin project options, can you make sure that you use the native options? Cf. https://developer.xamarin.com/guides/cross-platform/application_fundamentals/transport-layer-security/

**Comment by saikoryu** [comment]
Hi, it worked! I am using now the native options. Thank you so much for your help and support. I am impressed by your reply delays.

**Comment by ob-stripe** [comment]
\o/ You're welcome, glad I could help!
