### ISSUE TITLE
Filter plans by currency

### ISSUE THREAD

**Issue by sagostinho** [stripe/stripe-dotnet#1127]
I think it could be useful to filter plans by currency, in case we need to show plans for a specific country or continent. If you could add a currency string argument to "List all plans" function it would be great!!

Thanks in advance.

**Comment by remi-stripe** [comment]
@sagostinho This is not something the API supports at the moment which is why it's not implemented in the .NET library. You can always raise this feature request with our support team though: https://support.stripe.com/email
