### ISSUE TITLE
Redirect after successful payment

### ISSUE THREAD

**Issue by enkodellc** [stripe/stripe-dotnet#1130]
Is it possible to set it up to redirect to a thank you page after a successful payment. I could not find any documentation or settings on Stripe to do this can you point me in the right direction?

**Comment by ob-stripe** [comment]
@enkodellc GitHub issues are specifically for bugs or feature requests in the stripe-dotnet library. Please reach out to support at https://support.stripe.com/email.

**Comment by enkodellc** [comment]
Support said there is no option built into Stripe dashboard, just an email. So is this a Stripe feature that is missing... which I believe it is and not a stripe-dotnet feature?  Maybe I am wrong but this seems like a pretty basic feature.
