### ISSUE TITLE
NRE when trying to get Subscription data using StripeEventUtility.ParseEventDataItem

### ISSUE THREAD

**Issue by robfarmergt** [stripe/stripe-dotnet#1132]
```c#
var stripeEvent = StripeEventUtility.ConstructEvent(json, stripeSignature, "secret");
var subscription = StripeEventUtility.ParseEventDataItem<StripeSubscription>(stripeEvent.Data);
```

Getting `Object reference not set to an instance of an object.` with the code above for webhook `customer.subscription.udpated` event.

Stripe API version: 2018-02-06
Stripe.NET: 13.3.1

I'd like to bind the event's Data object to the appropriate Stripe.NET object but can't seem to get it to work properly. Am I doing something wrong is is there a possible mismatch between the Stripe API version and Stripe.NET? I tried upgrading the API version to the latest but have the same problem.

**Comment by ob-stripe** [comment]
Hi @robfarmergt. I think you want to use `stripeEvent.Data.Object` instead of just `stripeEvent.Data`.

cc @fred-stripe as I'm not very familiar with this API and this is related to #1129.

**Comment by robfarmergt** [comment]
@ob-stripe that was it! thanks so much.

**Comment by ob-stripe** [comment]
\o/ Glad I could help!
