### ISSUE TITLE
Expanding options causes a Stripe error

### ISSUE THREAD

**Issue by KevinBurton** [stripe/stripe-dotnet#1133]
I am making a call like:

```
                var stripeOptions = new StripeChargeListOptions()
                {
                    Limit = request.Limit,
                    StartingAfter = request.StartingAfter
                };

                var chargeService = new StripeChargeService {ExpandDestination = true, ExpandOnBehalfOf = true, ExpandBalanceTransaction = true, ExpandTransfer = true};
                var charges = await chargeService.ListAsync(stripeOptions).ConfigureAwait(false);
                if (charges == null)
                {
                    return new StripeProviderError(EStripeProviderErrorCode.InvalidRequest, "Unable to fetch the charge.");
                }

                return charges;
```
This consistently returns an exception with the message 'Error while communicating with one of our backends.  Sorry about that!  We have been notified of the problem.  If you have any questions, we can help at https://support.stripe.com/'. As far as I can tell the error only happens when I set the "expand" options to true as above. When I just use the standard constructor for the charge service I don't get this error.

**Comment by remi-stripe** [comment]
@kevin-stripe usually those errors happen when something unexpected was sent to the API. I've tried to reproduce on my account but your code works as expected for me. It's likely something specific to your own account, for example a deleted connected account that you try to expand.

The best solution here would be to reach out to our support team directly and they can investigate failures into your logs to figure out what's causing this. You can reach them here: https://support.stripe.com/email

**Comment by remi-stripe** [comment]
@KevinBurton ^ this was for you (damn auto-complete!)

**Comment by KevinBurton** [comment]
It seems that it is memory related. If I specify these expansions

```
	            ExpandDestination = true,
	            ExpandOnBehalfOf = true,
	            ExpandBalanceTransaction = true,
	            ExpandTransfer = true

```

Along with a `Limit` of 50 it works fine. But if I specify a `Limit` of 1000 I get an error.

**Comment by remi-stripe** [comment]
The maximum value for `Limit` is 100 per the [docs](https://stripe.com/docs/api#pagination-limit).

I don't think it's the memory issue, it's just that one of your charge must be in an unexpected state and when you paginate it and try to expand it fails. Otherwise, it might just be a timeout because you try to expand too many things at once on a large list. Our support team can investigate this for you though as it's not a bug in the library.

**Comment by KevinBurton** [comment]
So why does the expansion depend on the page size to work? If I expand 50 objects all with expansion it works if I expand 100 objects (specifying a Limit of 1000 seems to be capped at 100) it doesn't and I get the error 
```
Error while communicating with one of our backends.  Sorry about that!  We have been notified of the problem.  If you have any questions, we can help at https://support.stripe.com/.
```

**Comment by KevinBurton** [comment]
The error message alone seems to be a bug because it doesn't mention a timeout or expansion problems?

**Comment by remi-stripe** [comment]
Then it's the second part of my answer: Something is too slow to respond and it ends up as a timeout. 

This is really out of scope for the github issue though as it is not a bug with the library nor anything we can modify on this side. The call fails server-side and our support team would be able to investigate and help.

**Comment by KevinBurton** [comment]
So
```
Error while communicating with one of our backends.  Sorry about that!  We have been notified of the problem.  If you have any questions, we can help at https://support.stripe.com/.
```
is just a catch all error message? When an unexplainable error occurs this is the error message?

**Comment by remi-stripe** [comment]
@KevinBurton I would recommend that you move this discussion over to our support channel as this is unrelated to the library. I'm sorry but this would really help here as they can look up all your requests and investigate what is causing this specific error message.

Please contact them here: https://support.stripe.com/email

**Comment by KevinBurton** [comment]
Now it seems due to some kind of validation error. If I specify a limit of
1000 (which is above the documented 100 value) it fails with the expansion
values. If I specify 100 it works.

**Comment by remi-stripe** [comment]
@KevinBurton then it seems even more important to ask our support team. I will lock the thread as we went over this a few times and this is clearly not a library bug and would need investigation from our support team!
