### ISSUE TITLE
Please add support for "product" for the list all plans request. (API 2018-02-28)

### ISSUE THREAD

**Issue by DataEstate** [stripe/stripe-dotnet#1134]
I assumed this would be simply adding a field in StripePlanListOptions?

**Comment by ob-stripe** [comment]
Hi @DataEstate, yes, this should be trivial to add. I'll submit a PR.

**Comment by DataEstate** [comment]
Thank you!

**Comment by ob-stripe** [comment]
Released in 13.5.0, which will appear in NuGet shortly.
