### ISSUE TITLE
Charges to a non-connected account

### ISSUE THREAD

**Issue by KevinBurton** [stripe/stripe-dotnet#1136]
I get a list of all charges using

```
                var chargeService = new StripeChargeService();
                var charges = await chargeService.ListAsync(stripeOptions).ConfigureAwait(false);
```
 Then I get a list of all connected accounts with

```
                var accountService = new StripeAccountService();
                var accounts = await accountService.ListAsync(stripeRequest);
```
I am finding that there are charges to accounts that are not listed in the account list. Specifically when I look at the StripeCharge there is a DestinationId and OnBehalfOfId properties. There are some account id's in the charges (either DestinationId or OnBehalfOfId) that are not listed in the list of accounts (StripeAccount property Id). I can get the account details of the accounts that are not in the connected account list with 
```
                var accountService = new StripeAccountService();
                var account = await accountService.GetAsync(request.StripeAccountId).ConfigureAwait(false);
```
So I know that these accounts exist. There seems to be a property of the account that would prevent an account from being listed with ListAsync yet the account still exists? These are all "custom" accounts.

**Comment by remi-stripe** [comment]
@KevinBurton that doesn't look like an issue with the library here and more an issue with the data, and potentially deleted custom accounts on your platform. You should talk to our support team instead and provide as much details as you can, including clear example charge and account ids and they can help you debug this.
