### ISSUE TITLE
Use ConfigureAwait(false) for all async method calls

### ISSUE THREAD

**Issue by chrisdpratt** [stripe/stripe-dotnet#1141]
Libraries are encouraged to always use `ConfigureAwait(false)` on async methods to prevent possible deadlocks. This doesn't seem to be happening at all in the .NET Stripe client library. For example, this method from `StripeBasicService`:

```c#
public virtual async Task<EntityReturned> GetEntityAsync(string url, StripeRequestOptions requestOptions, CancellationToken cancellationToken, StripeBaseOptions options = null)
{
    return Mapper<EntityReturned>.MapFromJson(
        await Requestor.GetStringAsync(
                this.ApplyAllParameters(options, url),
                SetupRequestOptions(requestOptions),
                cancellationToken
        ).ConfigureAwait(false)
    );
}
```

I wouldn't mind submitting a pull request, if I can find some time to make these changes myself. My organization is simply considering using Stripe at this point, so until or if we actually pull the trigger on that, I'd have to do this in my personal time. Still, let me know if you'd like any help.

For what it's worth, overall I'm very pleased with how well the Stripe .NET library is implemented. Braintree's is a nightmare. So, kudos.

More information:
* https://blogs.msdn.microsoft.com/seteplia/2018/02/14/one-user-scenario-to-rule-them-all/
* https://channel9.msdn.com/Series/Three-Essential-Tips-for-Async/Async-library-methods-should-consider-using-Task-ConfigureAwait-false-

**Comment by ob-stripe** [comment]
Hi @chrisdpratt. Thanks for the suggestion! I don't have experience with async programming in C# / .NET, but AFAICT your request makes sense.

If you can submit a PR for this, we'll be happy to review it and merge it. I'll tag this as `future` for now.

**Comment by xt0rted** [comment]
Give Roslynator ([analyzers](https://www.nuget.org/packages/Roslynator.Analyzers/), [code fixes](https://www.nuget.org/packages/Roslynator.CodeFixes/)) a look. That has a rule that can be turned on to enforce `.ConfigureAwait(false)` on all awaited tasks. If it's set as a build error then it can help ensure future contributions don't deviate from the pattern. It also has as a code fix that'll add the `.ConfigureAwait(false)` to all awaited tasks in a given file, project, or solution. Should make quick work of this update.
