### ISSUE TITLE
StripeView is not supported

### ISSUE THREAD

**Issue by aleksandrsmyk** [stripe/stripe-dotnet#1149]
In Xamarin Component Store StripeView is existed. But In the nugget package it is not presented.
When will you plan to add support for StripeView

**Comment by remi-stripe** [comment]
@aleksandrsmyk `StripeView` seems to be something that Xamarin built in their own library that is not maintained by Stripe so you would need to ask them directly about it.

The stripe-dotnet library is mostly used server-side to interact with Stripe's API as a whole. It is possible to use it client-side to collect card details and create a Token or a Source but you would have to build your own UI for this as it's not a feature we offer today.
