### ISSUE TITLE
Get customer by email / Check if email is already used

### ISSUE THREAD

**Issue by aboulinguez** [stripe/stripe-dotnet#1156]
Hi,

Is there a way to check if an email address is already used by an existing user, or maybe get a customer by just passing its email address ?

Thanks for your help.

Best regards,

Antoine Boulinguez.

**Comment by remi-stripe** [comment]
@aboulinguez You can use the List Customers [API](https://stripe.com/docs/api#list_customers) and filter with the `email` [parameter](https://stripe.com/docs/api#list_customers-email).

At the moment, the library does not support this filter but I'll add this now!

**Comment by aboulinguez** [comment]
Hi @remi-stripe 

Thanks for your answser. I was already using the "List" method and I will now wait for your update to use the `email` parameter.

Any idea of the delay before seeing the parameter to be available?

Thanks again!

Antoine.

**Comment by remi-stripe** [comment]
@aboulinguez The code is ready and needs to be reviewed and deployed so I'd say a few days!

**Comment by aboulinguez** [comment]
@remi-stripe  It sounds great. Thanks!

**Comment by remi-stripe** [comment]
@aboulinguez we just released 15.5.0 with the fix: https://github.com/stripe/stripe-dotnet/blob/master/CHANGELOG.md#1550---2018-04-16

**Comment by bronthulke** [comment]
@remi-stripe I'm very thankful for your fix for this as I need the ability to do this now... however I can see that the fix went into 15.5.0, but I have 16.3.0 and the fix isn't in that version.  Is there some way I can get the fix?

Thanks!

**Comment by remi-stripe** [comment]
@bronthulke That is really strange, it's like that PR was never merged in the end. We'll investigate and likely release a new version tomorrow or early next week.

cc @ob-stripe this was merged in https://github.com/stripe/stripe-dotnet/pull/1157 do you know what's going on and why it never made it to master after all? Master has no `email` field: https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Services/Customers/StripeCustomerListOptions.cs

**Comment by ob-stripe** [comment]
Released in 16.4.0, which should appear on NuGet soon.

**Comment by bronthulke** [comment]
Thanks so much for resolving this so quickly, guys!
