### ISSUE TITLE
StripeSubscriptionCreateOptions BillingCycleAnchorTime invalid int error

### ISSUE THREAD

**Issue by ucworkshop** [stripe/stripe-dotnet#1161]
When Trying to create a subscription, I am getting an error that BillingCycleAnchor is not a valid int. I can see in the developers log in stripe dashboard that date was passed in as a string instead of the Epoch time in seconds:
![stripedateerror](https://user-images.githubusercontent.com/15143995/39020684-62b4b5f8-43f3-11e8-9737-7e0b9b09f13f.png)

**Comment by ucworkshop** [comment]
Forgot to mention - I have stripe api set to version 2018-02-28 (latest).

For what it is worth, changing the BillingCycleAnchor a bit made everything work for me - sorry I am not sure how to get the unit tests to run or how to get a pull request setup (new to github) - but thought I would at least post this here:

![image](https://user-images.githubusercontent.com/15143995/39061565-4f5cb73e-448a-11e8-8f3d-076e48c3339a.png)

**Comment by remi-stripe** [comment]
@ucworkshop Sorry for the issue, that's a bug I introduced unfortunately. I have a PR up as a fix and hopefully can get it merged soon.

**Comment by ob-stripe** [comment]
Fixed in 15.6.2.
