### ISSUE TITLE
Add support of  payout_schedule configuration

### ISSUE THREAD

**Issue by emnbdx** [stripe/stripe-dotnet#1167]
Hi,

I can't find any solution to configure payout_scheduled on Connect account with your nuget package. You can find this field here:
https://stripe.com/docs/api/curl#update_account

Best regards,
Eddy

**Comment by remi-stripe** [comment]
@emnbdx This is part of the `StripeAccountSharedOptions` class and all those parameters are defined [here](https://github.com/stripe/stripe-dotnet/blob/1513cbc55daea6a5bd4af4efcc440cc66f8cf972/src/Stripe.net/Services/Account/StripeAccountSharedOptions.cs#L90-L104)

**Comment by emnbdx** [comment]
@remi-stripe  thank for your answer i'm just going back to close my issue because I found the solution looking at the code...
Sorry for this.
