### ISSUE TITLE
Nuget doesn't have 15.6.2

### ISSUE THREAD

**Issue by winzig** [stripe/stripe-dotnet#1168]
Should Nuget automatically pick up the new release? It's been over 24 hours and it's [still not showing](https://www.nuget.org/packages/Stripe.net/) the 15.6.2 release as available.

**Comment by ob-stripe** [comment]
Thanks for the report @winzig. It looks like the build on Appveyor failed due a transient issue. I'll restart the build.

**Comment by ob-stripe** [comment]
Update: the error wasn't transient, it's because the test suite uses Bitcoin in some tests and Stripe no longer supports Bitcoin. I'm working on a fix in a #1169. I'll update here once the test suite is fixed and the version is released on Nuget.

**Comment by winzig** [comment]
I now see 15.6.2 on Nuget, thanks!
