### ISSUE TITLE
Stripe API missing documentation of property found in StripeInvoiceListOptions?

### ISSUE THREAD

**Issue by winzig** [stripe/stripe-dotnet#1170]
The [StripeInvoiceListOptions object](https://github.com/stripe/stripe-dotnet/blob/45a10753b5ca16be4646f62cf865173b61ac98eb/src/Stripe.net/Services/Invoices/StripeInvoiceListOptions.cs#L29) allows for filtering on boolean "paid" status for invoices. Yet when I read [the Stripe API docs](https://stripe.com/docs/api/go#list_invoices) on this endpoint, it doesn't mention the `paid` flag. I just want to make sure I'm understanding this option correctly, and that it will allow me to retrieve unpaid invoices from the current user?

What I would really love is to be able to pull up the invoice that is causing the subscription to be "past_due," but there doesn't appear to be a filter option specifically related to that, so I was going to try and retrieve unpaid invoices created since their subscription due date.

**Comment by remi-stripe** [comment]
@winzig That's correct, this filter will let you list invoices that have not been paid yet. The API docs sometimes don't have all the filters available but it should work as expected.
