### ISSUE TITLE
Bank account fields always null in StripeToken object

### ISSUE THREAD

**Issue by jathomas9** [stripe/stripe-dotnet#1175]
When calling the Get on a StripeTokenService a token is returned but all of the the bank account fields are NULL. I can see the values in the StripeResponse object. Below is the code I am using.

```
var tokenService = new StripeTokenService();
var stripeToken = tokenService.Get(*Id*);
```

For now I am just retrieving the values from the StripeReponse object

Any help would be appreciated.

**Comment by remi-stripe** [comment]
@jathomas9 Thanks for the report! I pushed a fix in https://github.com/stripe/stripe-dotnet/pull/1176

**Comment by jathomas9** [comment]
Awesome!
