### ISSUE TITLE
Add ability to set tax amount on Upcoming Invoice request

### ISSUE THREAD

**Issue by bcrobinson** [stripe/stripe-dotnet#1179]
The stripe api has the ability to set a tax rate on the upcoming invoice request
https://stripe.com/docs/api#upcoming_invoice-subscription_tax_percent
But the `StripeUpcomingInvoiceOptions` class is missing this property.

I have a branch that has the fix on it but I am having trouble running the unit tests (https://github.com/bcrobinson/stripe-dotnet/tree/invoice_add_tax). If I can get the unit tests to run the I'll submit the pull request, but as you can see from the change it's rather trivial.

Are there any help pages on how to get the unit tests running? I've set the `STRIPE_TEST_SK` to our test account one but it seems like there's more configuration on that account that I'll need to do.

**Comment by remi-stripe** [comment]
@bcrobinson If you're not sure how to run the unit tests you can also push your branch and our CI will run the tests automatically.

Just in case, here's how I run the tests (though I'm using the command line on OSX)

```
# For XUnit
STRIPE_TEST_SK=sk_test_.... dotnet test ./src/Stripe.Tests.XUnit/Stripe.Tests.XUnit.csproj /p:TargetFramework=netcoreapp1.1

# For MSpec
STRIPE_TEST_SK=sk_test_.... dotnet test ./src/Stripe.net.Tests/Stripe.net.Tests.csproj /p:TargetFramework=netcoreapp1.1
```
