### ISSUE TITLE
Signature time validation does not handle server time skew in the past

### ISSUE THREAD

**Issue by samuelkdavis** [stripe/stripe-dotnet#1183]
The Stripe signature docs state "Our libraries have a default tolerance of five minutes between the timestamp and the current time" - [source](https://stripe.com/docs/webhooks/signatures#replay-attacks
)

However the logic around this is ([source](https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Services/Events/StripeEventUtility.cs#L50)):

`if (serverTime - webhookTimestamp > tolerance)`

If the servers time drifts into the future, this will correctly throw an error. If the server time lags into the past however, the time validation becomes significantly less useful.

To fit the definition, absolute value looks like it'd solve this

`if (Math.Absolute(serverTime - webhookTimestamp) > tolerance)`

Stripe version: current master, 16.1.0

**Comment by samuelkdavis** [comment]
I added this in the github ui by directly editing the file

https://github.com/stripe/stripe-dotnet/pull/1184

CI is passing, but you may want to double check everything else is correct (this could and probably should be considered a breaking change)

**Comment by jaymedavis** [comment]
I would think it should be placed on the developer to work with and send utc. I’m very curious what the use case is this applies in? Wouldn’t a lower utc time stamp still be a positive number? A negative number would occur with a future time utc, right?

**Comment by jaymedavis** [comment]
Is your scenario sticking the web hook in a queue? If so, couldn’t you update the timestamp when it’s pulled from the queue? Trying to figure out why your server is lagged. 🧐

**Comment by ob-stripe** [comment]
Fixed in 17.0.0.
