### ISSUE TITLE
Source missing in StripeCustomerCreateOptions

### ISSUE THREAD

**Issue by programmersommer** [stripe/stripe-dotnet#1185]
Hi!
I am using ASP.NET Core 2.0 and latest Stripe.net package (16.1.0)

Here is page with a little bit outdated sample:
[Create a customer](https://stripe.com/docs/billing/quickstart#create-customer)

Currently Source is missing in StripeCustomerCreateOptions.
There is only SourceToken and if to set it to source on customer creation request I am receiving error:

> Invalid request (check your POST parameters): unable to determine value for parameter: source

**Comment by remi-stripe** [comment]
@programmersommer It's not missing, it just has a different name. It's called `SourceToken` as you can see [here](https://github.com/stripe/stripe-dotnet/blob/0bbcf99d35f844e638339aaba177a754d21930e8/src/Stripe.net/Services/Customers/StripeCustomerCreateOptions.cs#L41)

**Comment by programmersommer** [comment]
Thank you for quick answer!
You mean that setting source to SourceToken was right idea. Have no idea in this case what could be wrong.

**Comment by remi-stripe** [comment]
The docs you linked currently assume the parameter is named `Source` when it is named `SourceToken` so I am working with our docs team to fix the Docs example to match what the library does today.
