### ISSUE TITLE
StripePlan.Created field not restored after serialization and deserialization

### ISSUE THREAD

**Issue by slimCODE** [stripe/stripe-dotnet#1186]
(I know about the `should_roundtrip_datetimes` unit test, but somehow I'm seeing equivalent code fail).

I'm implementing caching (via Redis) on our calls to the Stripe API, and I noticed that my `StripePlan` entities came back with a different `Created` value (not tested with others yet). The code to reproduce is very simple:

```
    Console.WriteLine($"{serverPlan.Created}");
    var json = Newtonsoft.Json.JsonConvert.SerializeObject(serverPlan);
    var restored = Newtonsoft.Json.JsonConvert.DeserializeObject<StripePlan>(json);
    Console.WriteLine($"{restored.Created}");
```

The output:
> 2018-04-05 17:16:15
1970-01-18 15:02:28

I'm confused. I'm still with 13.3.1, but did not see anything related in the changelogs.

**Comment by remi-stripe** [comment]
@slimCODE I can confirm that this does not work in 13.3.1 but when I tested the latest version, 16.1.0, it works as expected.

I'd recommend upgrading to the latest!
