### ISSUE TITLE
Can StripeCustomerService be treated as a singleton?

### ISSUE THREAD

**Issue by sgwatgit** [stripe/stripe-dotnet#1187]
Environment: ASP.NET, .NET 4.6.1

I have a wrapper service for `stripe-dotnet` that I use in my application. It sets up the api key in its constructor

```
public class StripeWrapper
{
    public StripeWrapper(StripeConfiguration config)
    {
         StripeConfiguration.SetApiKey(config.ApiPrivateKey);
    }

    public Customer DoSomethingWithACustomer(string customerId)
    {
        var customerService = new StripeCustomerService();
        ...
    }
}
```

The `StripeWrapper` class has methods that wrap and validate requests to `stripe-dotnet`. In a lot of these wrapper methods I am calling `var customerService = new StripeCustomerService();` because they all deal with interacting with the Customer.

Can i save my `new StripeCustomerService();` and use it as a singleton, either via DI from the composition root or within my `StripeWrapper` during construction?

Are there any issues with thread safety I should be aware of?

Thanks!

**Comment by anelder-stripe** [comment]
@sgwatgit - I think you're probably safe to do that provided that your request options don't change from request-to-request.  Personally, I'd like to see the idea of these being instantiated at all removed from the library.  These should really be functions/class-methods.  Hopefully we'll make a strong push to get that out there one day.

**Comment by sgwatgit** [comment]
@anelder-stripe Just so I'm clear - I'm doing something like this in my wrapper methods

```
            var customerOptions = new StripeCustomerCreateOptions
            {
                Email = request.Email,
                SourceToken = request.Token,
                Description = request.Description
            };

            var customer = await customerService.CreateAsync(customerOptions);
```

and the request could be populated with different users's data.

As long as I'm generating new `StripeCustomerCreateOptions` for each request/user I should be ok reusing the `StripeCustomerService`, correct?

**Comment by anelder-stripe** [comment]
Yep!  That's totally fine!  👍
