### ISSUE TITLE
Idempotentcy_key not supported by StripeChargeCreateOptions

### ISSUE THREAD

**Issue by remoorejr** [stripe/stripe-dotnet#1193]
The Idempotent Request example;

`var chargeService = new StripeChargeService();
chargeService.Get("tok_mastercard", new StripeRequestOptions() { IdempotencyKey = "3sCO5c44TpzgfuCp" })`

is a bit ridiculous since Get and Delete requests are idempotent by definition, Note that all of the other code samples show an example of creating a Stripe charge, where it most certainly makes sense.

The idempotency_key does not seem to be supported as a charge option.

**Comment by brandur-stripe** [comment]
Hi @remoorejr,

Regarding `GET` requests: they are indeed idempotent, and you can choose to not include an idmpotency key with them. The server will ignore a key if one is included, but it won't produce an error about it.

Regarding charge options: idempotency keys are considered part of the general shared options that can go in any request. If you take a look at the service method for creating a charge:

``` c#
        public virtual StripeCharge Create(StripeChargeCreateOptions createOptions, StripeRequestOptions requestOptions = null)
```

You'll see that it takes both a `StripeChargeCreateOptions` and `StripeRequestOptions`. You want to include the particulars about the charge in the former, while including any request "meta" information like the idempotency key in the latter.

Hope that helps! I'm going to close this out for now, but let us know if you're experiencing any other trouble.

**Comment by remoorejr** [comment]
Go it. I think it would be worthwhile to modify the example code to be consistent with the other examples.

Thanks,

Robert E. Moore Jr.
(617) 365-3231 | skype: remoorejr | @remoorejr <https://twitter.com/remoorejr> 
 
Please treat all of my email correspondence  as PRIVILEGED AND CONFIDENTIAL.
