### ISSUE TITLE
Subscription options: Plan is required but also obsolete?

### ISSUE THREAD

**Issue by SeanKilleen** [stripe/stripe-dotnet#1194]
Hi all, I think I've come across what appears to be a disagreement between Stripe.NET and the Stripe REST API that's a blocker for us. I go into my goal below, but only to provide context -- I get that you're not the support group. (by the way, I absolutely love Stripe's dev team -- it's a best-in-class product for sure). 

## Background / Goal
Business Goal: My customer has multiple product keys that we'd like to associate with subscription items under one subscription. This is because each subscription item might be associated with a different plan.

For more context: my customer sells a plugin for a piece of software, and to purchase a subscription for the plugin, the users are required to associate it with a product key. There are monthly & yearly plans, and in one session users might purchase 1 yearly subscription & 2 monthly subscriptions to apply to 3 distinct product keys. (the product is such that independently licensed products are often used in a team setting).

Technical Goal: Save the each product key as metadata along with a subscription item, and have that roll up under one subscription that's associated with their customer ID. 

## How I'm attempting to go about this
In case my understanding is flawed.

* I obtain or create the customer as necessary using a `StripeCustomerService`
* I create a subscription using `StripeSubscriptionCreateOptions` and a `StripeSubscriptionService`.
* Once I have the Subscription ID as a result, for each item I want to create, I create a `StripeSubscriptionItemCreateOptions` with the metadata, newly created subscription ID, Plan ID, etc.
* I  use the `StripeSubscriptionItemService`

## The Problem
I receive an error upon attempting to create the subscription: `Missing required param: plan.`

It's true, I use no plan on my `SubscriptionCreateOptions` because I don't want a plan associated with the subscription, but rather with the underlying subscription items.

Furthermore, I see in the options object that `PlanId` **is marked as obsolete**, with a suggestion to use `Items` instead. However, if I was to use `Items`, it is not a full `SubscriptionItem` object. It's a list of `StripeSubscriptionItemOption`, which means I can't associate metadata; only a plan ID.

Also, in the [docs for creating a subscription](https://stripe.com/docs/api#create_subscription), it seems that `plan` isn't listed as a parameter, though it is used in the example.

## What I've tried so far

* Don't include `PlanId` field: receive error about required parameter 
* Use a null `PlanId` string: receive error about required parameter
* Use an empty `PlanId` string: Receive an error that I should pass a plan or remove the plan field from the request. (ironic since it appears to be required)
* Use a made-up `PlanId` string: Receive an error that no plan is found by that name
* Use no `PlanId` string and an empty list of `Items`: receive error about required parameter

## Questions

* Is my overall goal achievable? Or do I need to do a separate subscription for each product key, so that I can associate metadata and a plan in a painless way? 
* Am I taking the correct approach here? 
* Would the correct solution be to add metadata to `StripeSubscriptionItemOption`? If it was possible to add a metadata dictionary there, I would have everything I needed I think. 
* Do I need to do something to ensure that the Stripe.NET and REST API are in agreement? 
]* If I was to use the `Items` field of the `SubscriptionCreateOptions`, is there anyway I could somehow add the metadata later? One item might be a monthly plan & one might be a yearly plan, so it's important that I associate the right metadata. I can't see a way I'd be able to link the two.

## Some Code to Demonstrate the issue

```csharp
            var subscriptionCreateOptions = new StripeSubscriptionCreateOptions
            {
               // here is where Stripe appears to expect a PlanId
               // the Items field here is a list of objects that only have PlanId and Quantity, not the ability to also add Metadata
                CustomerId = customer.Id
            };

            var newSubscription = _subscriptionService.Create(customer.Id, subscriptionCreateOptions);

            foreach (var requestItem in subscriptionRequestItems)
            {
                var options = new StripeSubscriptionItemCreateOptions
                {
                    PlanId = requestItem.PlanId,
                    SubscriptionId = newSubscription.Id,

                    // This is what I need to do, so that the key can be associated with the subscription item
                    Metadata = new Dictionary<string, string>
                    {
                        {"VWKey", requestItem.VWKey}
                    }
                };

                _subscriptionItemService.Create(options);
            }

            return _subscriptionService.Get(newSubscription.Id);
```

## My system Info

* Win 10 
* App targeting .NET Framework 4.6
* Stripe.NET nuget package v16.3.0 (latest stable available)

Thanks for any help you can give!

**Comment by remi-stripe** [comment]
@SeanKilleen You can't create a Subscription that is "empty". The idea instead is to create a Subscription with the list of Subscription Items directly. So if you want to subscribe someone to plan_A, plan_B and plan_F you would create one subscription with three subscription items. You can read more about this in the documentation [here](https://stripe.com/docs/billing/subscriptions/multiplan#creating)

The code would look like this:

```
var items = new List<StripeSubscriptionItemOption> {
    new StripeSubscriptionItemOption {
        PlanId = "plan_A"
    },
    new StripeSubscriptionItemOption {
        PlanId = "plan_B"
    },
    new StripeSubscriptionItemOption {
        PlanId = "plan_F",
    },
};
var options = new StripeSubscriptionCreateOptions {
    Items = items,
};
var service = new StripeSubscriptionService();
StripeSubscription subscription = service.Create("cus_4fdAW5ftNQow1a", options);
```

The `plan` parameter is the old approach which has been deprecated for a while now. At the time, Subscriptions could only support one plan at a time so you would created the Subscription with just a plan id in the `plan` parameter. This is not true anymore since a Subscription can have between 1 and 20 plans, so you use Subscription Items now.

We don't support adding metadata on subscription items creation but you can update each subscription item after the fact if needed to set the metadata you want on it.

The code would look like this:

```
var updateOptions = new StripeSubscriptionUpdateOptions
{
    Items = new List<StripeSubscriptionItemUpdateOption>
    {
        new StripeSubscriptionItemUpdateOption
        {
            Id = subscription.Items.Data[0].Id,
            Metadata = new Dictionary<string, string>{ {"key", "value1"} }
        },
        new StripeSubscriptionItemUpdateOption
        {
            Id = subscription.Items.Data[1].Id,
            Metadata = new Dictionary<string, string>{ {"key", "value2"} }
        },
        new StripeSubscriptionItemUpdateOption
        {
            Id = subscription.Items.Data[2].Id,
            Metadata = new Dictionary<string, string>{ {"key", "value3"} }
        }
    }
};

StripeSubscription subscriptionUpdated = subService.Update(subscription.Id, updateOptions);
```

**Comment by SeanKilleen** [comment]
@remi-stripe thanks for the quick response!

Here's the piece I'm not sure of. If I have a yearly subscription item associated with "key1", and a monthly subscription item associated with "key2", and I create the subscription with the two items without metadata -- how would I know which item to assign the metadata to after it's been created? Will they always be returned in the order they were created so that I can safely assume the first subscription item prior to creation is still the first subscription item to update? 

My concern is that if I create the items without metadata, the metadata could be applied in the wrong order, because I can't be sure which keys `Data[0]` and `Data[1]` correspond to.

**Comment by remi-stripe** [comment]
Unfortunately you can not create a subscription with multiple items for different billing cycles. The requirement is that all plans have the same billing cycle instead.

If you want to charge someone yearly for $100 and also monthly for $20 you would need 2 separate subscriptions instead, one with each plan.

As for the metadata part, you would be able to recognize the right plan based on its id. The subscription object also contains all the details about each subscription item and the associated plan so you would know for each one what they represent.

**Comment by SeanKilleen** [comment]
@remi-stripe awesome, thank you, this clears up my misunderstanding of the requirements for me.

It sounds like for our scenario, the best default is to create a subscription per product key and store the product key as metadata on the subscription. 

Thanks again for the quick responses & thorough explanation.
