### ISSUE TITLE
Update plan with product

### ISSUE THREAD

**Issue by SimonChris** [stripe/stripe-dotnet#1202]
I am trying to migrate from the old non-product API, in which I updated a Plan from a plan ID. In the new API, the "Name" and "StatementDescriptor" fields are now on the Product instead of the Plan.

According to the Stripe docs, the plan update settings should be able to accept an optional Product argument, but this does not appear to be present on the Stripe.NET StripePlanUpdateOptions class.

How can I update the plan and the corresponding product from the plan ID?

**Comment by remi-stripe** [comment]
Thanks for the report! I had no idea we supported this feature but I just pushed a PR for the next version to support this!

**Comment by SimonChris** [comment]
Thanks for the quick reply :). 

I took a look at your PR, and it seems like I will still only be able to update the Product Id on the plan. What I am looking for is a way to update the properties of the existing while updating the plan.

Is there any way to update the plan product properties without having to update the plan and product separately?

**Comment by remi-stripe** [comment]
@SimonChris I tested to be safe before pushing my PR and that is not possible. At the moment the `product` parameter on the Update Plan API only supports a product id to move the plan from one product to another.

If you want to update a product's properties, you would need to use the Update Product API instead.
