### ISSUE TITLE
StripeListOptionsWithCreated is in the wrong namespace

### ISSUE THREAD

**Issue by Jehoel** [stripe/stripe-dotnet#1206]
**Package version:** 16.10.0

**Problem:**

Most of the library's public types are in the root `Stripe` namespace, however in recent releases (since at least 16.4.0) the class `StripeListOptionsWithCreated` is in the `Stripe.net` namespace and it's the only type in that namespace too. I see it's only used by the `Stripe.StripeOrderListOptions` so it looks like a bug.

Another clue it's a bug is that namespaces in .NET should be in `PascalCase`, but `Stripe.net` isn't.

![image](https://user-images.githubusercontent.com/1693078/41381054-4e83d160-6f1b-11e8-9080-04a40feff34e.png)

**Comment by remi-stripe** [comment]
@Jehoel Thanks for the report! I pushed a fix in https://github.com/stripe/stripe-dotnet/pull/1208 which we likely can merge tomorrow!

**Comment by ob-stripe** [comment]
Released in 16.11.0.
