### ISSUE TITLE
Nested Expansions?

### ISSUE THREAD

**Issue by BrianVallelunga** [stripe/stripe-dotnet#1209]
Is it possible to use the nested expand feature? For example, if I pull back Charges, I want both the Invoice and the Subscription to come with it. Thanks!

**Comment by remi-stripe** [comment]
@BrianVallelunga You definitely can! You would do something like this:

```
var options = new StripeChargeListOptions() {};
options.AddExpand("invoice.subscription");

var chargeService = new StripeChargeService();
StripeList<StripeCharge> chargeItems = chargeService.List(options);
```

This would return charges and they would have an Invoice and a Subscription object back if those are present.

**Comment by BrianVallelunga** [comment]
Perfect. Thanks a lot. This will save us a lot of API calls.
