### ISSUE TITLE
Order property is missing from StripeChargeCreateOptions

### ISSUE THREAD

**Issue by joshberry** [stripe/stripe-dotnet#1212]
An order property is missing from the StripeChargeCreateOptions class so order id cannot be set when creating a charge.

![image](https://user-images.githubusercontent.com/1396816/41661184-bb5b9622-7463-11e8-8e5b-58770290e8a3.png)

I'd be happy to submit a PR for this if the change would be acceptable.

**Comment by remi-stripe** [comment]
@joshberry This documentation is for the Charge object. It means that when you retrieve a charge associated with an Order, we will return the id of the order in the `order` property. It also says it can be [expanded](https://stripe.com/docs/api#expanding_objects) to get the full Order object. You can see this is already supported in the library here: https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Entities/StripeCharge.cs#L221-L238

The Create Charge [API](https://stripe.com/docs/api#create_charge) though does _not_ take an `order` parameter. If you want to charge for an order you would instead use the Pay Order [API](https://stripe.com/docs/api#pay_order)

**Comment by joshberry** [comment]
My misunderstanding. Thanks for the explanation!
