### ISSUE TITLE
UpcomingAsync and ListUpcomingLineItems throws an exception when no items are available

### ISSUE THREAD

**Issue by pschmitz-survey** [stripe/stripe-dotnet#1246]
(Identical to: https://github.com/stripe/stripe-node/issues/301)

As part of our implementation, we're attempting to validate that no "upcoming" items exist for a customer before we build and create an invoice. However, simply polling for upcoming items results in a StripeException (and unnecessarily floods our stripe logs with 404 errors).

Expected behavior:

These API calls are successful and return an empty invoice/line items

Actual behavior:

A StripeException is thrown "Error: No upcoming invoices for customer: cus_xxxxxxxxxxx"

Summary:

`
Method: GET
URL: /v1/invoices/upcoming/lines
Status: 404
Source: Stripe/v1 .NetBindings/16.14.0
`

Response:

`
{
  "error": {
    "code": "invoice_upcoming_none",
    "doc_url": "https://stripe.com/docs/error-codes/invoice-upcoming-none",
    "message": "No upcoming invoices for customer: cus_xxxxxxxxxxx",
    "type": "invalid_request_error"
  }
}
`

**Comment by remi-stripe** [comment]
@pschmitz-survey This is the ay our API was designed. If you try to simulate an upcoming invoice and there's none, we will return an exception. This is the same logic as trying to retrieve a customer that does not exist.

In this case, we expect you to know whether a customer has pending invoice items or an ongoing subscription and only call the upcoming method if so. That's why we return a 404 in that case.

**Comment by pschmitz-survey** [comment]
@remi-stripe Thanks for the fast follow-up. I certainly don't expect API changes to cater towards our needs, but to provide reasoning/use-case on this particular request (future consideration or others run into similar challenges):

During our original (poor) implementation, the invoice-creation request could fail and upcoming items would sit in limbo, then later swept in as duplicates/undesired items in a subsequent successful invoice. 

We're conducting item-queue/creation in proper atomic-fashion now, but a simple sanity check against an upcoming preview, regardless of its existence, would be nice to have.

**Comment by remi-stripe** [comment]
@pschmitz-survey The issue is that, if we did not return an error, we would have to return an empty invoice with no line items which is not a concept that exists in the API today. That's the reasoning behind the error we return so that you can easily handle it in your code instead.
