### ISSUE TITLE
Bug StripeInvoiceService Pay() & PayAsync().

### ISSUE THREAD

**Issue by Klynk** [stripe/stripe-dotnet#1256]
Hello,

I found some missing settings for the Pay() & PayAsync() methods.

https://stripe.com/docs/api/dotnet#pay_invoice

There are two input parameters 'forgive' and 'source'.

I tried to make some changes, which seemed to work.

I made a new class Stripe.net/src/Services/Invoices/StripeInvoicePayOptions.cs

```C#
namespace Stripe.net.Services.Invoices
{
    using Newtonsoft.Json;

    public class StripeInvoicePayOptions : StripeBaseOptions
    {
        /// <summary>
        /// Gets or sets if invoice should be forgiven if source has insufficient funds to fully pay the invoice.
        /// </summary>
        [JsonProperty("forgive")]
         public bool? Forgive { get; set; }

        /// <summary>
        /// Gets or sets a payment source to be charged. The source must be the ID of a source belonging to the customer associated with the invoice being paid.
        /// </summary>
        [JsonProperty("source")]
        public string Source { get; set; }
    }
}
```

I also had to make two changes in Stripe.net/src/Services/Invoice/StripeInvoiceService.cs

```C#
        public virtual StripeInvoice Pay(string invoiceId, StripeInvoicePayOptions payOptions = null, StripeRequestOptions requestOptions = null)
        {
            return Mapper<StripeInvoice>.MapFromJson(
                Requestor.PostString(
                    this.ApplyAllParameters(payOptions, $"{Urls.Invoices}/{invoiceId}/pay", false),
                    this.SetupRequestOptions(requestOptions)));
        }

        public virtual async Task<StripeInvoice> PayAsync(string invoiceId, StripeInvoicePayOptions payOptions = null, StripeRequestOptions requestOptions = null, CancellationToken cancellationToken = default(CancellationToken))
        {
            return Mapper<StripeInvoice>.MapFromJson(
                await Requestor.PostStringAsync(
                    this.ApplyAllParameters(payOptions, $"{Urls.Invoices}/{invoiceId}/pay", false),
                    this.SetupRequestOptions(requestOptions),
                    cancellationToken).ConfigureAwait(false));
        }
```

I did a test for Source, and it seemed to work.
I have not tested Forgive,

I am fairly new to git, and I have no idea how to branch.

I don't know your coding/comment guidelines either.
I just wanted to make invoice payment work,
where the customer is able to select which card to charge.

OS: Windows 10 (17134.228)
.NET Version: Microsoft.AspNetCore.All (v2.1.2)
Library Version: Stripe.net (v17.11.0)

**Comment by remi-stripe** [comment]
@Klynk Thanks a lot for reporting this and providing example code. I will work on this later today and we should have a version for you by tomorrow!

**Comment by remi-stripe** [comment]
Fix in progress in https://github.com/stripe/stripe-dotnet/pull/1257

**Comment by ob-stripe** [comment]
Fixed in #1257 and released as 18.0.0.

Note that this is a breaking change, as the signatures of the `StripeInvoiceService.Pay` and `PayAsync` methods changed: they now take an additional `StripeInvoicePayOptions` argument.

**Comment by Klynk** [comment]
Thank you, tested SourceId now and it works.

**Comment by voidmonk** [comment]
@ob-stripe
> Note that this is a breaking change, as the signatures of the StripeInvoiceService.Pay and PayAsync methods changed: they now take an additional StripeInvoicePayOptions argument.

Curious to know why is `StripeInvoicePayOptions` a required argument (not optional), even though the related Stripe API method arguments are optional?

**Comment by remi-stripe** [comment]
@voidmonk That's the way we built the services. The options are not optional though you can pass `null` if you want I think.

**Comment by ob-stripe** [comment]
The library is not very consistent in this regard right now: some methods do have their options argument as optional (e.g. `List` methods) while others require an options argument even if all arguments are optional on the backend (e.g. `StripeChargeService.Capture` or `StripeInvoiceService.Pay`).

I'd personally be in favor of making the options argument required everywhere. As @remi-stripe pointed out, users can simply pass `null` if they don't want to pass any parameters in the request.
