### ISSUE TITLE
StripeSubscriptionService.Cancel() requires StripeSubscriptionCancelOptions param

### ISSUE THREAD

**Issue by kawaicheung** [stripe/stripe-dotnet#1264]
With the 19.0.0 release, it looks like the `StripeSubscriptionService.Cancel()` method requires a `StripeSubscriptionCancelOptions`object passed into it, even though it appears there isn't anything you can set that's unique to the cancellation options.

Can this be an optional param in a future release? Or, is there something I'm missing with cancel-specific options, especially since the `cancel_at_period_end` option has been moved to `Update()`?

-KC

**Comment by remi-stripe** [comment]
@kawaicheung There will be new parameters added in the near future. To avoid a second breaking change I started the logic to take a parameter. If you don't need to pass anything right now, the easiest solution is to pass `null` instead!

**Comment by kawaicheung** [comment]
Gotcha. Thanks for the quick response @remi-stripe!
