### ISSUE TITLE
Error on customer get with subscription coupon

### ISSUE THREAD

**Issue by kawaicheung** [stripe/stripe-dotnet#1265]
I'm receiving this error when calling `StripeCustomerService.Get()`:
```
JsonReaderException: Input string '40.0' is not a valid integer. Path 'subscriptions.data[0].discount.coupon.percent_off', line 108, position 31.
```
I am using v19.1.0 and .net 4.5 framework and using the latest API version (2018-08-23)

In my customer's subscription, they have a 40% discount coupon associated to their subscription. I know there was a recent int -> decimal upgrade for coupons in this version, but looks like the .NET API needs the type update from `int?` to `decimal?` in `Stripe.StripeCoupon`.

Thanks!
-KC

**Comment by remi-stripe** [comment]
@kawaicheung thanks a lot for the detailed report and sorry about the bug on that one, that's my bad. I just opened a PR to fix this and we'll try to release it shortly.
