### ISSUE TITLE
typo in stripeEvent for 

### ISSUE THREAD

**Issue by satuday** [stripe/stripe-dotnet#1281]
there is a typo for the event "source.transaction.created", its named SourceTransactionCanceled in
https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Constants/StripeEvents.cs#L455

**Comment by remi-stripe** [comment]
@satuday Thanks a lot for the report! I wanted to ack this as we have not forgotten. We're planning a major revision soon and we'll make that change at the same time to avoid releasing a major version with such a specific change.

You can follow along in https://github.com/stripe/stripe-dotnet/pull/1277

**Comment by ob-stripe** [comment]
Fixed in 20.0.0.
