### ISSUE TITLE
StripeAccountCreateOptions missing account_token parameter

### ISSUE THREAD

**Issue by evandespault** [stripe/stripe-dotnet#1289]
Using the Stripe.net v19.6.0 from nuget, I'm trying to create a new Custom Account as described in https://stripe.com/docs/api/dotnet#create_account

However, rather than passing the account details (e.g. legal entity) directly to our backend, I am using Stripe.js to securely acquire these details and generate an account token, and pass that token to the backend, as described in https://stripe.com/docs/connect/account-tokens

Unfortunately, it seems that the StripeAccountCreateOptions class is missing the "account_token" parameter, which would be used for this purpose. Unless I'm missing something, it seems like it's not possible with this library to create a custom account using an account token.

**Comment by remi-stripe** [comment]
@evandespault Thanks for the report and sorry about the trouble. I just opened a PR to fix this and we will try to release a version tomorrow.

**Comment by ob-stripe** [comment]
Fixed in 19.7.0. The version should be available on NuGet within a few minutes.

**Comment by evandespault** [comment]
Amazing. Thank you very much for the quick update! :)
