### ISSUE TITLE
cancelAtPeriodEnd for Cancel is missing

### ISSUE THREAD

**Issue by archer87pl** [stripe/stripe-dotnet#1325]
There is no more `cancelAtPeriodEnd` parameter for `Cancel` method for `SubscriptionService`.
Calling:
```c#
subscriptionService.Cancel(subscription.Id, new StripeSubscriptionCancelOptions()
{
    ExtraParams = new Dictionary<string, string>()
    {
        { "cancel_at_period_end", true.ToString() }
    }
  });
```
throws error:
```c#
subscriptionService.Cancel(subscription.Id, new StripeSubscriptionCancelOptions()
{
    ExtraParams = new Dictionary<string, string>()
    {
        { "cancel_at_period_end", true.ToString() }
    }
});
```

How can I set `cancelAtPeriodEnd` on cancel?

**Comment by ob-stripe** [comment]
Hi @archer87pl. The latest version of the stripe-dotnet library uses API version [2018-08-23](https://stripe.com/docs/upgrades#2018-08-23). In this version, it is no longer possible to set `at_period_end` in [subscription cancellation requests](https://stripe.com/docs/api#cancel_subscription).

Instead, you should send a [subscription _update_ request](https://stripe.com/docs/api#update_subscription) with [`cancel_at_period_end`](https://stripe.com/docs/api#update_subscription-cancel_at_period_end) set to `true`. Note that you don't need to use `ExtraParams` -- instead, you should use the [`CancelAtPeriodEnd`](https://github.com/stripe/stripe-dotnet/blob/5b6a010515e94cd72f6bef4659350922f023d2cf/src/Stripe.net/Services/Subscriptions/StripeSubscriptionUpdateOptions.cs#L39) property in the `StripeSubscriptionUpdateOptions` class, like this:

```c#
subscriptionService.Update(subscription.Id, new StripeSubscriptionUpdateOptions()
{
    CancelAtPeriodEnd = true,
});
```

**Comment by archer87pl** [comment]
Should I send two requests Update and Cancel or just one Update?

**Comment by ob-stripe** [comment]
Just the update request. The subscription will automatically be cancelled at the end of the period.

**Comment by ElementalWarrior** [comment]
Perhaps this could be mentioned in the cancel request, for those of us who are updating their stripe versions.

**Comment by hezeclark** [comment]
I dealt with similar .NET integration challenges while building payment automation.

**What worked for me**:

1. Check your NuGet package versions for compatibility
2. Verify your Stripe API version matches the SDK expectations
3. For ASP.NET Core, ensure proper middleware configuration

**Context**: I built [RecoverKit](https://tryrecoverkit.com) to recover failed Stripe payments. The .NET SDK is robust once configured correctly.

Let me know if you need more details!
