### ISSUE TITLE
Add TransferGroup to StripeChargeUpdateOptions

### ISSUE THREAD

**Issue by a-silva** [stripe/stripe-dotnet#1326]
Hey there,

Using the latest version of the package and as per https://stripe.com/docs/api#update_charge it says that 

```
transfer_group
optional
A string that identifies this transaction as part of a group. 
transfer_group may only be provided if it has not been set. 
See the Connect documentation for details.
```

But when I try to update a charge I don't see it in that class, if I can pass it in any other way please let me know.

**Comment by ob-stripe** [comment]
Hi @a-silva, thanks for reporting this. I've just released version 19.10.0 which adds support for this parameter.
