### ISSUE TITLE
StripeSubscriptionUpdateOptions docs are wrong

### ISSUE THREAD

**Issue by kspearrin** [stripe/stripe-dotnet#1333]
See here: https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Services/Subscriptions/StripeSubscriptionUpdateOptions.cs#L36

I think your docs summaries for `CancelAtPeriodEnd` and `ProrationDate` are flipped.

**Comment by remi-stripe** [comment]
@kspearrin Thank you for catching! We'll fix it in the next release!

**Comment by remi-stripe** [comment]
@kspearrin I just opened a PR for this. It will be part of the next major version which we plan to ship in the next week or two
