### ISSUE TITLE
Add auto_advance to StripeInvoiceCreateOptions

### ISSUE THREAD

**Issue by zerobounce** [stripe/stripe-dotnet#1338]
I believe a few days ago, the default to this was "true" but as of Oct 15th, it's now false, causing all invoices to be generated in "draft" mode. 

It should be added as an option so it can be set with the create options. 

Thanks.

**Comment by zerobounce** [comment]
This was a glitch I guess that was going on for 2 days at Stripe, it appears to be corrected. But this option should still be added.

**Comment by remi-stripe** [comment]
This option will be added when we release the next API version!

**Comment by ob-stripe** [comment]
Implemented in 20.0.0.
