### ISSUE TITLE
Sample for Connect in .Net Core

### ISSUE THREAD

**Issue by Ponant** [stripe/stripe-dotnet#1341]
Hi there,
That is not about an issue but rather a request for some quick template in .Net (possibly .Net Core) that showcase the Stripe Connect flow?

**Comment by remi-stripe** [comment]
@Ponant It's not really something we have available today though most of the flow is browser-based and not really specific to .NET Core itself as described [here](https://stripe.com/docs/connect/standard-accounts):
1/ Redirect to Stripe
2/ User fills out the form
3/ User is redirected to your server
4/ You use the authorization code (ac_XXXX) to finish the connection.

I'd recommend talking to our support team if you have any follow up questions about this though: https://support.stripe.com/email
