### ISSUE TITLE
Add migration steps concerning ConstructEvent

### ISSUE THREAD

**Issue by DavidRouyer** [stripe/stripe-dotnet#1354]
I've updated the lib from v19.10.0 to v20.1.0 and I had to change my code from:

```csharp
var stripeEvent = EventUtility.ConstructEvent(json, stripeSignature, webhookSigningSecret);
Source source = Mapper<Source>.MapFromJson(stripeEvent.Data.Object.ToString());
```
to:
```csharp
var stripeEvent = EventUtility.ConstructEvent(json, stripeSignature, webhookSigningSecret);
Source source = (Source)stripeEvent.Data.Object;
```

But it's not specified in the migration guide, can you add it?

**Comment by ob-stripe** [comment]
Hi @DavidRouyer, thanks for the suggestion! Indeed, as you noted, `Event.Data.Object` is now declared as an `IHasObject` interface and can be directly cast to a concrete class. We'll update the migration guide to clarify this.

**Comment by ob-stripe** [comment]
Bit of a late reply, sorry! I've moved the migration guide for v20 to the repository's wiki: https://github.com/stripe/stripe-dotnet/wiki/Migration-guide-for-v20. The guide has been updated to include some code samples showing how to cast the interfaces for polymorphic resources into concrete types.
