### ISSUE TITLE
Issue with post of decimal data when decimal separator is not dot (again)

### ISSUE THREAD

**Issue by Maetiz** [stripe/stripe-dotnet#1357]
I see this has been fixed before in #801 but it has re-appeared. Probably in #1276. This occurs in v20.1.0 and v20.0.0 but not in v19.10.0.

I'd make a pull request of this but I'm having some issues with the solution so here's just my guess at the fix in `RequestStringBuilder` in `private static List<Parameter> FlattenParamsValue(object value, string keyPrefix)`:
```
else if (value is decimal dec)
{
    flatParams = new List<Parameter>();
    flatParams.Add(new Parameter(keyPrefix, dec.ToString(CultureInfo.InvariantCulture)));
}
```

**Comment by ob-stripe** [comment]
Fixed in 20.2.0.

Thanks for the report @Maetiz!
