### ISSUE TITLE
SourceType - where is BankAccount const property ?

### ISSUE THREAD

**Issue by pmahend1** [stripe/stripe-dotnet#1359]
- >IPaymentSource represents all resources that can be used to create a Charge. This can be a Card, BankAccount, Source or Account.

- >StripeSource is now named Source as the other Source class was removed in favour of IPaymentSource. We have also added support for all existing source types and related properties or parameters.

After recent major upgrade where you folks changed `IPaymentSource` and `Source`  I am using `SourceType` class for type of IPaymentSource object's type by 

```c#
var list = customerService.GetAllSources(customerId);
 foreach (var item in list){

if(item.Object == SourceType.Card){
...
}
else if(item.Object == "bank_account"){// here
}
```

SourceType class does not have property for bank account, it however has for `AchCreditTransfer` `AchDebit` and `Bancontact` (??) 

Is this intentional?

Earlier I just used to iterate through this list which was Source type and has either Card and BankAccount set.

using hard_coded `"bank_account"` seems dumb to me. 

I searched for `"bank_account"` in this repo, couldnt find it in any Enum or class other than Json converters or Test classes.

Rationale behind this? I think `SourceType` should have constant property.

```c#
public const string BankAccount= "bank_account";
```

**Comment by ob-stripe** [comment]
To add to Remi's answer, with C# 7.0 you can use [pattern matching](https://docs.microsoft.com/en-us/dotnet/csharp/pattern-matching). You could update your code like this:

```c#
var list = customerService.GetAllSources(customerId);

foreach (var item in list)
{
  switch (item)
  {
    case Account account:
      // do something with account
      break;
    case BankAccount bankAccount:
      // do something with bankAccount
      break;
    case Card card:
      // do something with card
      break;
    case Source source:
      // do something with source
      break;
  }
}
```

Closing the issue, but feel free to reply if you have more questions.
