### ISSUE TITLE
Question about 3d secure resource creation migrating from 19.10.00 to 20.+

### ISSUE THREAD

**Issue by goldenass** [stripe/stripe-dotnet#1362]
How does the following code translates, given that `ThreeDSecureCardOrSourceId` and `RedirectReturnUrl` do  not exists anymore?

```c#
var sourceOptions = new StripeSourceCreateOptions()
{
    Amount = (int)(payment.Amount * 100),
    Currency = "EUR",
    Type = "three_d_secure",
    ThreeDSecureCardOrSourceId = requestSource.Id,
    RedirectReturnUrl = returnUrl
};
```

And the following, given that `SourceTokenOrExistingSourceId` does not exists anymore?
```c#
var options = new StripeChargeCreateOptions
{
    Amount = (int)(payment.Amount * 100),
    Currency = "EUR",
    SourceTokenOrExistingSourceId = requestSource.Id,
    ReceiptEmail = email
};
```

**Comment by remi-stripe** [comment]
Hey @goldenass! When you create a 3DS Source from an existing Source, the original card source id should go in `three_d_secure[card]` as documented [here](https://stripe.com/docs/sources/three-d-secure#server-side-source-creation) and the redirect URL should go under `redirect[return_url]`. 

On 20.* you end up having to do it this way:

```
var sourceOptions = new StripeSourceCreateOptions()
{
    Amount = (int)(payment.Amount * 100),
    Currency = "EUR",
    Type = "three_d_secure",
    ThreeDSecure = new SourceThreeDSecureCreateOptions
    {
        CardId = requestSource.Id,
    },
    Redirect = new SourceRedirectOptions
    {
        ReturnUrl = returnUrl,
    }
};
```

For `SourceTokenOrExistingSourceId` you just want to use `SourceId` instead as defined [here](https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Services/Charges/ChargeCreateOptions.cs#L91-L92).

```
var options = new StripeChargeCreateOptions
{
    Amount = (int)(payment.Amount * 100),
    Currency = "EUR",
    SourceId = requestSource.Id,
    ReceiptEmail = email
};
```
