### ISSUE TITLE
Get balance Transaction no longer reflected in api reference 

### ISSUE THREAD

**Issue by astadtla** [stripe/stripe-dotnet#1371]
https://stripe.com/docs/api/balance/balance_transaction?lang=dotnet 
no longer reflects how to obtain a balance transaction. 

please let me know how this functions now, as there is no documentation, and the forced update now has crippled previous code preventing us from importing orders for versions before 20.

**Comment by astadtla** [comment]
in 20.*the class names have changed removing the "Stripe" prefix from many classes, from the reference you mentioned and I have update them as shown below to the following:

 StripeConfiguration.SetApiKey(Strings.StripeAuthenticationKey);
            var balanceService = new BalanceService();
            BalanceTransaction transaction = balanceService.Get(id);

yesterday this call functioned, on version 16.* 

today I now get the fowling error and this error persists in every version from 16.* through version 20.4.0

Unrecognized request URL (GET: /v1/balance/history/). If you are trying to list objects, remove the trailing slash. If you are trying to retrieve an object, make sure you passed a valid (non-empty) identifier in your code. Please see https://stripe.com/docs or we can help at https://support.stripe.com/.'


I have tried the previous versions but the API reference does not reflect functioning code, is there perhaps another way to obtain the balencetransaction in 20.* that i can attempt?

**Comment by ob-stripe** [comment]
Going to close this issue since this is likely a user error (as @remi-stripe said above, the `id` variable is probably `null` or an empty string).

Feel free to reply if you're still having trouble.
