### ISSUE TITLE
Feature Request: Fractional quantity support on invoice items

### ISSUE THREAD

**Issue by pschmitz-survey** [stripe/stripe-dotnet#1391]
I apologize in advance if this is the incorrect area to post this request - It's likely more related to the core functionality of the Stripe API and less about the dotnet implementation:

Our company has a use-case for "fractional quantities" at an invoice-item-level. Ex: 

Name: Service Hours
Unit Price: $20
Quantity: 1.5
Amount: $30

Our initial expectation was that this item would be accepted by Stripe's system, however we receive an error (against API 2018-02-06) and Stripe support has informed us that this is an unsupported use-case.

While this may seem like a negligible shortcoming to work around on our end (invoice an additional line item for the "remainder", simply invoice the total amount, etc), none have gained full-approval within our system/clientele:

- Our sales team uses hourly rates in our contracts. It's necessary for us to match that unit type and rate in the invoice.

- Some of our clients are less forgiving when the itemization isn't transparent (quantity: 1) or exact (we'll round down, absorb the loss, however clients see this as an inaccuracy on our part).

**Request:** Allow fractional precision for the Invoice Item's "quantity" field. If the amount results in an invalid denomination (fractional cent value), throw an error.

**Comment by remi-stripe** [comment]
@pschmitz-survey Thanks for the feature request. Github issues should be limited to bugs and issues with the dotnet library though and this is currently a limitation of our API.

I'm going to close this one out but I've shared your feedback with the engineering team and it's something we hope to support in the future!
