### ISSUE TITLE
Add Type to ProductListOptions

### ISSUE THREAD

**Issue by jamrocktech** [stripe/stripe-dotnet#1392]
.NET version: Assembly Stripe.net, Version=20.2.0.0

I've searched to see if there are any outstanding requests for this feature and did not find any matches. 

Hence this feature request to add the Type attribute to the [ProductListOptions](https://github.com/stripe/stripe-dotnet/blob/19f0758c09471392fc51a8d3b19a8d6bde852e29/src/Stripe.net/Services/Products/ProductListOptions.cs) class.

This would eliminate the initial call of all Products initially, followed by a filter to selected the desired Type (good or service).

Additionally, Stripe's documentation does indicate that they have an optional attribute in their Product List Options.

Thanks for the consideration.

**Comment by jamrocktech** [comment]
I am closing as I have learnt that you can accomplish this by way of ExtraParms.

**Comment by remi-stripe** [comment]
@jamrocktech We just released 21.4.0 that has support for this option!
