### ISSUE TITLE
Why is there no .net examples on the main pages?

### ISSUE THREAD

**Issue by gnphild** [stripe/stripe-dotnet#1397]
Hey folks, 

Why is .NET omitted from the main pages on your website yet you have languages with a much smaller user base. Seems petty.

**Comment by remi-stripe** [comment]
@gnphild Sorry about that, this is definitely something we would like to improve in the near future. We have .NET examples in a lot of our docs and the API reference has an example for every API method. Would you be able to show me some of the ones where it's missing and you'd like to see it added?
