### ISSUE TITLE
No source property in CardCreateOptions?

### ISSUE THREAD

**Issue by lbrevity** [stripe/stripe-dotnet#1398]
Hello,

Stripe.net : 19.6.0.0

I'm trying to use 3d secure card for my subscription based payment in my site. When user back to my website after authentication, he has source of 3d secured card. using that source I created customer using **StripeCustomerCreateOptions**. then for 3d secured card I have to create charge, right? so I created that using customer and source. But after before I attach customer to subscription for future auto payment, I have to create card. I'm trying this using **CardCreateOptions**, but in that no source property is there- so I can create card and save to customer for future auto payment??

**Comment by ob-stripe** [comment]
Hi @lbrevity. If I understand correctly, you want to add a source to an existing customer. With Stripe.net 19.6.0, the property you need to use is [`StripeCardCreateOptions.SourceToken`](https://github.com/stripe/stripe-dotnet/blob/v19.6.0/src/Stripe.net/Services/Cards/StripeCardCreateOptions.cs#L9-L10).

Note that GitHub issues are specifically for bugs or feature requests in the library. If you have followup questions regarding how to use the library, please reach out to support at https://support.stripe.com/email.
