### ISSUE TITLE
Question: How to Charge Customer at the time of Subscription Seat-Quantity Update?

### ISSUE THREAD

**Issue by a-patel** [stripe/stripe-dotnet#1399]
Question: How to Charge Customer at the time of Subscription Quantity Update?

e.g. I as a customer subscribed for a yearly plan ($100) with quantity 1, So Stripe charge $100 at time of subscription creation.

When I update the quantity to 2 after 6-month Stripe will charge for 2nd seat of current cycle usage in next payment cycle (100+100+50-from last year).

I want to charge $50 at time of subscription quantity update?
What  should I do?

**Comment by remi-stripe** [comment]
@a-patel Github issues should only be used to report bugs with the library itself! For API questions or how to use our products, the best solution would be to contact our support team instead which you can do here: https://support.stripe.com/email

What you can do though is create an invoice via the [API](https://stripe.com/docs/api#create_invoice) after the upgrade to charge the pending invoice items that were created. This is covered at the end of the documentation [here](https://stripe.com/docs/billing/subscriptions/upgrading-downgrading).
