### ISSUE TITLE
Unrecognized request URL (POST: /v1/customers//subscription)

### ISSUE THREAD

**Issue by jfrueh** [stripe/stripe-dotnet#140]
Hi - I'm running into an issue when trying to update the customers subscription (see attached screenshot).  I doubt this is a bug because it's such a common task, but I'm at a loss for what would be causing this.  Any feedback would be greatly appreciated.  Thanks for the awesome library!

![stripe](https://f.cloud.github.com/assets/1854052/2122776/870eaa38-921a-11e3-887c-ce6d2c4cf5c3.JPG)

**Comment by fdwillis** [comment]
How did you get the customerid to return something?
