### ISSUE TITLE
InvoicePayOptions required

### ISSUE THREAD

**Issue by twilly86** [stripe/stripe-dotnet#1409]
I'm trying to setup manual invoice payments and using invoiceService.Pay is requiring InvoicePayOptions.

Looking here..
https://stripe.com/docs/api/invoices/pay

The only required field is the invoice id.

Is it possible to make this the only required field? 

It's failing when I try and submit the pay request saying the source is invalid, but the api should pick up the default source on file with the customer.

**Comment by remi-stripe** [comment]
@twilly86 You should be able to simply pass `null` when calling the function or an empty `InvoicePayOptions`! This ensures that in the future, when we add more parameters, we don't have to release a breaking change!

**Comment by twilly86** [comment]
I tried passing in Null, and got the same error even though the customer
has a valid payment source on file.

**Comment by remi-stripe** [comment]
what does "the same error" mean exactly in this context? Can you share your exact code and the error returned?
