### ISSUE TITLE
Subscription service get by id not working

### ISSUE THREAD

**Issue by superheri** [stripe/stripe-dotnet#1410]
While calling the SubscriptionService and trying to get the subscription by it's like :

```c#
var subscriptionService = new SubscriptionService();
var subscription = subscriptionService.Get(subscriptionId);
```

I get the following error :

```Stripe.StripeException: 'Unrecognized request URL (GET: /v1/subscriptions/). If you are trying to list objects, remove the trailing slash. If you are trying to retrieve an object, make sure you passed a valid (non-empty) identifier in your code. Please see https://stripe.com/docs or we can help at https://support.stripe.com/.'```

And since I have too many subscriptions, using the `List` method is not an option.

Please fix this bug since I really need to use it in my web app.

OS : Win 10 1809
.NET version : 4.5.2
Stripe.NET version : 21.7.0

**Comment by superheri** [comment]
After debugging my block of code, it seems that since I'm using an object from my database to in which I'm setting the subscriptionId, sometimes it is not initialising correctly for somewhat reason. So I'll see to correct the instanciation of my objects.

Thank you very much for your REALLY FAST answer 🥇 and sorry for the inconvenience.

**Comment by remi-stripe** [comment]
Glad you were able to fix the issue :)
