### ISSUE TITLE
Error converting value {null} to type 'System.Int64'.

### ISSUE THREAD

**Issue by rsnj** [stripe/stripe-dotnet#1442]
Stripe.net SDK v21.7.0

Simply trying to get a list of Issuing Cards for a user.
```
var cardService = new Issuing.CardService();
var cards = await cardService.ListAsync(new CardListOptions
{
    CardholderId = stripeCardholderId,
});
```
Getting this Exception:
> Newtonsoft.Json.JsonSerializationException: Error converting value {null} to type 'System.Int64'. Path 'authorization_controls.max_amount', line 8, position 22. ---> System.InvalidCastException: Null object cannot be converted to a value type.

Looks like the values in [AuthorizationControls.cs](https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Entities/Issuing/Authorizations/AuthorizationControls.cs) should be nullable?

**Comment by remi-stripe** [comment]
@rsnj Thanks for the report and sorry about the troubles! I've opened a PR for a fix here: https://github.com/stripe/stripe-dotnet/pull/1443

**Comment by rsnj** [comment]
@remi-stripe thanks for the quick turnaround.
Any ideas when v22 will be released?
Is there a way around this issue in the meantime? Or will I have to clone your branch and build locally?

**Comment by rsnj** [comment]
Thanks for the quick turnaround!

**Comment by remi-stripe** [comment]
Sure! Let us know if that does not solve the issue!
