### ISSUE TITLE
Cancel subscription using prorate

### ISSUE THREAD

**Issue by ismcagdas** [stripe/stripe-dotnet#1448]
Hi,

Thank you for this great library :). According to stripe docs, https://stripe.com/docs/api/subscriptions/cancel, we can use a prorate parameter to credit remaining unused time to customer. However, SubscriptionCancelOptions doesn't contain such a field.

Is this the expected behavior ?

Thanks.

**Comment by remi-stripe** [comment]
@ismcagdas Thanks for reporting the issue! I just opened a PR in https://github.com/stripe/stripe-dotnet/pull/1449 which we will release early next year!

**Comment by remi-stripe** [comment]
@ismcagdas This was released as 21.8.0 which should be available in a bit!

**Comment by ismcagdas** [comment]
You are awesome 👍
