### ISSUE TITLE
Stripe Transfer API

### ISSUE THREAD

**Issue by jmawebtech** [stripe/stripe-dotnet#1454]
Hi,

I am trying to pull a list of credit card charges, based on a Stripe transfer. I can pull a list of transfers, but I cannot pull their associated credit card charges. What am I doing wrong? Here is my code:

```c#
        public List<BalanceTransaction> SearchBalances(DateTime beginTime, DateTime endTime)
        {
            List<BalanceTransaction> balanceTransactions = new List<BalanceTransaction>();
            BalanceTransactionService service = new BalanceTransactionService(userName);
            service.ExpandSource = true;

            while(true)
            {
                BalanceTransactionListOptions listOptions = new BalanceTransactionListOptions()
                {
                    Limit = 100,
                    AvailableOnRange = new DateRangeOptions()
                    {
                        GreaterThanOrEqual = beginTime,
                        LessThanOrEqual = endTime
                    }
                };

                if (balanceTransactions.Count() > 0)
                    listOptions.StartingAfter = balanceTransactions.LastOrDefault().Id;

                StripeList<BalanceTransaction> newBalanceTransactions = service.List(listOptions);

                balanceTransactions.AddRange(newBalanceTransactions.Data);

                if (!newBalanceTransactions.HasMore)
                    break;

            }

            return balanceTransactions;
        }
```

![2019-01-03_12-00-33](https://user-images.githubusercontent.com/1679993/50650714-42428700-0f4f-11e9-918d-ed3a5464e081.jpg)

**Comment by remi-stripe** [comment]
@jmawebtech To list transactions bundled in a Payout, you have to explicit set the `PayoutId` [property](https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Services/BalanceTransactions/BalanceTransactionListOptions.cs#L18) to the corresponding Payout id `po_123`. Your code would look like this:

```
BalanceTransactionListOptions listOptions = new BalanceTransactionListOptions
{
    Limit = 100,
    PayoutId = "po_123",
};

if (balanceTransactions.Count() > 0)
    listOptions.StartingAfter = balanceTransactions.LastOrDefault().Id;

StripeList<BalanceTransaction> newBalanceTransactions = service.List(listOptions);
```

**Comment by jmawebtech** [comment]
How do I obtain the payout ID?

**Comment by remi-stripe** [comment]
@jmawebtech This is just the id of the Payout, representing the movement of funds to from your Stripe account to your own bank account. This is the `po_123` that you see in your screenshot in the Dashboard: `po_1DBXyRH...`.

There are multiple ways to get those such as listing all Payouts via https://stripe.com/docs/api#list_payouts or receiving one of the `payout.*` events on your webhook endpoint for example.

**Comment by jmawebtech** [comment]
Hi,

Prior to using your integration, this was my old code:

        public List<Balance> SearchBalance(DateTime beginTime, DateTime endTime, string type, string transfer)
        {
            List<Balance> balances = new List<Balance>();

            for (int i = 0; i < 10; i++)
            {
                string url = String.Format("{0}/v1/balance/history?created%5Bgte%5D={1}&created%5Blte%5D={2}&limit=100&offset={3}&expand[]=data.source", m_BaseUrl, ConvertToTimestamp(beginTime), ConvertToTimestamp(endTime), i * 100);

                if (!String.IsNullOrEmpty(type))
                    url += "&type=" + type;

                if (!String.IsNullOrEmpty(transfer))
                    url = String.Format("{0}/v1/balance/history?transfer={1}&limit=100&offset={2}&expand[]=data.source", m_BaseUrl, transfer, i * 100);

                List<Balance> cList = JObject.Parse(GetJson(url))["data"].ToObject<List<Balance>>();

                if (cList.Count() == 0)
                    break;

                balances.AddRange(cList);

                if (cList.Count() < 100)
                    break;
            }

            return balances;
        }

Is this correct?

        public List<BalanceTransaction> SearchBalances(DateTime beginTime, DateTime endTime, string payoutId)
        {
            List<BalanceTransaction> balanceTransactions = new List<BalanceTransaction>();
            BalanceTransactionService service = new BalanceTransactionService(userName);
            service.ExpandSource = true;

            while(true)
            {
                BalanceTransactionListOptions listOptions = new BalanceTransactionListOptions()
                {
                    Limit = 100,
                };

                if (String.IsNullOrEmpty(payoutId))
                {
                    listOptions.CreatedRange = new DateRangeOptions()
                    {
                        GreaterThanOrEqual = beginTime,
                        LessThanOrEqual = endTime
                    };
                }
                else
                {
                    listOptions.PayoutId = payoutId;
                }

                if (balanceTransactions.Count() > 0)
                    listOptions.StartingAfter = balanceTransactions.LastOrDefault().Id;

                StripeList<BalanceTransaction> newBalanceTransactions = service.List(listOptions);

                balanceTransactions.AddRange(newBalanceTransactions.Data);

                if (!newBalanceTransactions.HasMore)
                    break;

            }

            return balanceTransactions;
        }

**Comment by remi-stripe** [comment]
@jmawebtech The latter code should work yes. Can you clarify what's not working? Having concrete examples of what's returned, how you loop over the list of transactions, what you print, etc. would be helpful

**Comment by jmawebtech** [comment]
Hi,

How do I send you a request and response? I tried Fiddler, but I get an SSL error. If you would like, I can send you a private message with my client's info. When I add type = "transfer", I get no results. This use to work with my previous code.

I used to be able to search for balance histories of type transfer, get the details using the source ID, then enumerate through the list if charges.

**Comment by remi-stripe** [comment]
I would recommend reaching out to our support team in that case for help since this is not really a bug with the library. You can contact them here: https://support.stripe.com/email and they can help you debug this!
