### ISSUE TITLE
InvoicePayOptions missing PaidOutOfBand property

### ISSUE THREAD

**Issue by DanieleBelfiore** [stripe/stripe-dotnet#1474]
The API reference [https://stripe.com/docs/api/invoices/pay](https://stripe.com/docs/api/invoices/pay) provide the **paid_out_of_band** option, but in the **/src/Stripe.net/Services/Invoices/InvoicePayOptions.cs** file, the property PaidOutOfBand is missing.

    public class InvoicePayOptions : BaseOptions
    {
        [JsonProperty("forgive")]
        public bool? Forgive { get; set; }

        [JsonProperty("source")]
        public string SourceId { get; set; }
    }

In this moment, I don't know how to set an invoice as paid.
Thanks a lot in advance.

**Comment by remi-stripe** [comment]
@DanieleBelfiore Thanks for the report! I'll work on a fix today!

**Comment by paulasjes-stripe** [comment]
Fixed in v22.6.0!

**Comment by DanieleBelfiore** [comment]
Thanks a lot for your support!
