### ISSUE TITLE
Better StripeException Message?

### ISSUE THREAD

**Issue by winzig** [stripe/stripe-dotnet#1497]
Right now when a StripeException is thrown, the Message property is:

`Exception of type 'Stripe.StripeException' was thrown.`

And then there's a StripeError property that has more info. We use Sentry for logging exceptions, and so the only thing we're seeing is the stack trace and the top level message, which is not very useful. (We already know StripeException was thrown, since we're looking at it. :trollface:)

Would it be possible for you to copy the StripeException.StripeError.ErrorDescription and Error into the top level .Message property? 

For the record, this is what I'm seeing now for an example exception in our debugger:

<img width="579" alt="screen shot 2019-02-01 at 11 02 22 am" src="https://user-images.githubusercontent.com/127062/52143806-52fb2100-2611-11e9-8ce5-0057e133906e.png">

So in this scenario, perhaps the top level .Message would be:

`Authorization code expired (invalid_grant).`

**Comment by winzig** [comment]
BTW, I'm also going to open a request with Sentry that they might expose the entire exception object in their interface somewhere, in case the above request is not feasible for some reason.

**Comment by ob-stripe** [comment]
Hi @winzig. This sounds very reasonable! TBH I thought we were already copying the message from Stripe's API, but that doesn't seem to be the case. Tagging this as `future`, but this should be very straightforward.

**Comment by ob-stripe** [comment]
Fixed in 22.8.1.
