### ISSUE TITLE
Need a way to set Product.Shippable

### ISSUE THREAD

**Issue by winzig** [stripe/stripe-dotnet#1503]
Product exposes a `Shippable` attribute, but neither the Product Create nor Update API (nor this SDK) exposes a way to set it, as far as I can tell. This property:

https://github.com/stripe/stripe-dotnet/blob/9a8a933d0796bad9e8a199894b66b7d98392641a/src/Stripe.net/Entities/Products/Product.cs#L93

It appears those APIs do accept a `shippable` boolean parameter, but it's undocumented. The dashboard also does not seem to provide a way to adjust this property.

**Comment by ob-stripe** [comment]
Hi @winzig, thanks for the report. We'll add this to both product creation and update parameters soon. In the meantime, you can use the `AddExtraParam` method to send arbitrary parameters:

```c#
var options = new ProductCreateOptions
{
  Type = "good",
  ...
};
options.AddExtraParam("shippable", "true");
```

**Comment by winzig** [comment]
@ob-stripe Thanks for the fast response, and apologies but it looks like I'm mistaken/confused. When logged in, Stripe's API docs were showing me an older version of the API, apparently before that parameter was documented for the API. I then went to Stripe.net repo and searched for Shippable to see how I might set it with the SDK, and was only noticing it in the Product.cs class, but now I see it in the ProductSharedOptions class, so I think all is well. I'm going to close this issue.

**Comment by ob-stripe** [comment]
Haha, I didn't even check 🤦‍♂️ Thanks!
