### ISSUE TITLE
Cannot set days_until_due parameter in Invoice

### ISSUE THREAD

**Issue by DanieleBelfiore** [stripe/stripe-dotnet#1521]
In the **InvoiceCreateOptions** and **SubscriptionCreateOptions** I cannot set the parameters **days_until_due**.

The parameter is present, I use it with a value, but after the call, in the **logs** on the Stripe dashboard, the value is always set to **15** and the expiration date of the Invoice is always in **15 days**.

It seems that 15 is the default value and the passed value is not read.

Do you could to check if the passed value to parameter is used? 
Or am I wrong in anything else?

Thanks a lot in advance

**Comment by ob-stripe** [comment]
Hi @DanieleBelfiore. This value doesn't come from the Stripe.net library: `DaysUntilDue` is declared as a `long?` and defaults to `null`. `null` values in options classes are not sent in API requests.

Can you share your code for creating e.g. `InvoiceCreateOptions`, and also tell us which version of Stripe.net you're using?

**Comment by DanieleBelfiore** [comment]
`var invoiceOptions = new InvoiceCreateOptions()
{
               Billing = Billing.ChargeAutomatically,
               CustomerId = "10",
               TaxPercent = 0,
               DaysUntilDue = 1
            };`

**Comment by ob-stripe** [comment]
`DaysUntilDue` is only valid when `Billing` is set to `Billing.SendInvoice`: https://stripe.com/docs/api/invoices/create#create_invoice-days_until_due. Can you try changing `Billing` from `Billing.ChargeAutomatically` to `Billing.SendInvoice`?

**Comment by DanieleBelfiore** [comment]
Ok, it works with the `Billing.SendInvoice` value.
Thank you so much.
