### ISSUE TITLE
Source "card_present" entity

### ISSUE THREAD

**Issue by DanWM** [stripe/stripe-dotnet#1525]
Captured Payment Intents that were collected by the Terminal API from a card reader include charges data  which has a source entity that contains a card_present entity.  However, card_present is not available in Stripe .NET so I'm not able to access it after casting the charge source to a source.   Instead, I have to parse the intent ResponseJson to get to it.
For instance: (string)jso["charges"]["data"][0]["source"]["card_present"]["last4"]
Will this be available in the future, or am I missing it in the API ?

**Comment by ob-stripe** [comment]
Hi @DanWM, thanks for reporting this. I've prepared a fix in #1526 and we'll release an updated version of the library shortly.

**Comment by ob-stripe** [comment]
@DanWM This is fixed in Stripe.net 23.2.0, which should appear on Nuget in a few minutes. `Source` objects now have a `CardPresent` property.
