### ISSUE TITLE
Stripe.net API version inconsistency

### ISSUE THREAD

**Issue by vktr** [stripe/stripe-dotnet#1529]
I've updated to the latest Stripe.net version (v24.0.0) which mentions being compatible with API version 2019-02-19 - however I can see that the StripeConfiguration.ApiVersion still defaults to 2019-02-11, and my webhooks throws errors because of it.

Is this the intended behaviour (to manually set the StripeApiVersion on StripeConfiguration) or did you miss updating it before release?

Workaround for now:

```
StripeConfiguration.StripeApiVersion = "2019-02-19";
```

**Comment by ob-stripe** [comment]
Oops! Thanks @vktr, it looks like you're entirely correct. I've unlisted v24.0.0 from Nuget and will release a fixed version shortly. Thanks for the report and apologies for this mistake.

**Comment by ob-stripe** [comment]
Alright, this is fixed in v24.0.1 which will appear on Nuget in a few minutes. Thanks again!
