### ISSUE TITLE
PaymentIntentService.Confirm - ClientSecret is missing

### ISSUE THREAD

**Issue by bnserig** [stripe/stripe-dotnet#1532]
Hi,
I'm using Stripe.NET in a Xamarin Forms application.
I try to confirm a PaymentIntent with the publishable key but the property ClientSecret is missing in PaymentIntentConfirmOptions.
Can you add this property to this object ?

Thank you.

**Comment by remi-stripe** [comment]
@bnserig Thanks for the report! I'll work on a fix!

**Comment by remi-stripe** [comment]
@bnserig This fix was released as 24.1.0. Really sorry about the delay on that one, I forgot to release last week.

**Comment by bnserig** [comment]
Thanks for the release.
