### ISSUE TITLE
assert_capabilities missing from OAuthTokenCreateOptions

### ISSUE THREAD

**Issue by winzig** [stripe/stripe-dotnet#1543]
The OAuth API supports asserting that certain requested capabilities have been applied to the relationship, but the SDK doesn't currently accept those parameters. Detailed here: 

https://stripe.com/docs/connect/express-accounts#verify-the-accounts-capability

In the meantime, I'm using `AddExtraParam` to work around the issue. Thanks!

**Comment by remi-stripe** [comment]
@winzig Thanks for reporting! Assigning to @ob-stripe who has been working on some of this in https://github.com/stripe/stripe-dotnet/pull/1542 to see if he can fix at the same time.

**Comment by ob-stripe** [comment]
As of version 27.0.0, the library now supports this parameter natively: https://github.com/stripe/stripe-dotnet/blob/67a6bc4a8b833e1a5a6ddb92f6f9dd7f31a2d58b/src/Stripe.net/Services/OAuth/OAuthAuthorizeUrlOptions.cs#L77-L86

**Comment by winzig** [comment]
@ob-stripe Is there a reason `assert_capabilities` wasn't also added?

**Comment by ob-stripe** [comment]
@winzig Sorry I wasn't clear!

- `suggested_capabilities` was added as a parameter to the `/authorize` request: https://github.com/stripe/stripe-dotnet/blob/67a6bc4a8b833e1a5a6ddb92f6f9dd7f31a2d58b/src/Stripe.net/Services/OAuth/OAuthAuthorizeUrlOptions.cs#L77-L86
- `assert_capabilities` was added as a parameter to the `/token` request: https://github.com/stripe/stripe-dotnet/blob/67a6bc4a8b833e1a5a6ddb92f6f9dd7f31a2d58b/src/Stripe.net/Services/OAuth/OAuthTokenCreateOptions.cs#L8-L19

**Comment by winzig** [comment]
Ok great, thank you!
