### ISSUE TITLE
Is there a way to have the subscription.Create  add metadata on to the Charge Object?

### ISSUE THREAD

**Issue by zerobounce** [stripe/stripe-dotnet#1544]
We pass metadata into the charge object on instant payments and we use that metadata to help reduce fraud with radar and put some payments into review. When you create a subscription through this Library, I don't see a way to pass that metadata into the charge object, I can add it to metadata on the subscription, but not have it pass through on the charge object. Therefore, it doesn't apply to radar.

**Comment by remi-stripe** [comment]
@zerobounce Unfortunately, this is not something the API supports today. I'd recommend reaching out to our support team to raise this (though I'll also raise internally): https://support.stripe.com/contact
