### ISSUE TITLE
Issuing transaction does not contain amount property

### ISSUE THREAD

**Issue by albernhagen** [stripe/stripe-dotnet#1549]
According to stripe documentation for the issuing transaction object, there should be an `amount` field available - https://stripe.com/docs/api/issuing/transactions/object#issuing_transaction_object-amount

This is not currently available on the `Stripe.Issuing.Transaction` entity in the API.  I tried to create a branch and submit a PR, but I get a 403 when adding the branch.  Let me know if I can help in anyway as this is a high priority item for me.

Thanks!

**Comment by remi-stripe** [comment]
@albernhagen Thanks for the report. I just opened a [PR](https://github.com/stripe/stripe-dotnet/pull/1550) to fix this!

**Comment by ob-stripe** [comment]
Fixed in 24.4.1.
