### ISSUE TITLE
Job Title

### ISSUE THREAD

**Issue by lucasisola** [stripe/stripe-dotnet#1553]
For the purpose of sending **Owners** and **Beneficial Owners**, support is needed to send `relationship.title` to fulfill the requirements for Custom Connect accounts to send Job Title.

**Comment by ob-stripe** [comment]
Hi @lucasisola. You can set this property via [`PersonRelationshipOptions.Title`](https://github.com/stripe/stripe-dotnet/blob/ee3a44e27dd7926117c2ec7e803298213737e33c/src/Stripe.net/Services/Persons/PersonRelationshipOptions.cs#L19-L20), and retrieve it via [`PersonRelationship.Title`](https://github.com/stripe/stripe-dotnet/blob/ee3a44e27dd7926117c2ec7e803298213737e33c/src/Stripe.net/Entities/Persons/PersonRelationship.cs#L32-L36).

Closing, but feel free to reply if needed.

**Comment by lucasisola** [comment]
Phew. Super-fast reply. Cheer @ob-stripe!

**Comment by ob-stripe** [comment]
Glad I could help :)

**Comment by bgecawichBAO** [comment]
I am creating a person via token.  It appears that I cannot set the relationship in the token request.  It also appears that when you create a person you cannot set relationship options when you create a person using a token, even after the person is created.  How do I set the title, account opener, and owner if I am using a token for the person and the account?

**Comment by remi-stripe** [comment]
@bgecawichBAO Can you clarify what prevents you from setting the relationship when creating a token? The more details you can provide about your existing code, the easier it will be to help

**Comment by bgecawichBAO** [comment]
I was getting an exception that the relationship could not be set.  Let me try it again and I'll post what I'm getting.  Thx.

**Comment by bgecawichBAO** [comment]
This is what I'm getting.....Stripe.StripeException: 'Parameter 'relationship' cannot be used in conjunction with a person token.'  Here's the code.  Am I doing something wrong?
var pro = new PersonRelationshipOptions
            {
                AccountOpener = accountOpener,
                Owner = accountOwner,
                Title = string.IsNullOrEmpty(title) ? null : title
            };
            var poptions = new PersonCreateOptions
            {
                PersonToken=personToken,
                Relationship=pro
            };

            var pservice = new PersonService();
            Person person = pservice.Create(accountID, poptions);

**Comment by remi-stripe** [comment]
But you can not do this so that's expected. Can you explain how you are creating the Person Token in your code?

**Comment by bgecawichBAO** [comment]
I have a form that shows the fields required either for a new account or as a result of additional requirements needed.  Initially it has all the account and person information on it.  I create an account token, person token for account opener and owner (if they are not the same person), and external account token.  I then pass the tokens back to the server and create the account and associate the persons to it.  

My Javascript builds the person object dynamically based on the information needed which is everything.  When I was sending the relationship information in the person token it was not being set so I pass the title, and settings for account opener and account owner back to the server.  I'm guessing that there is another way to do this based on your response.

**Comment by bgecawichBAO** [comment]
I think I may have just found the issue.  Thank you for your quick response.  I will post back if I don't get it fixed.

**Comment by bgecawichBAO** [comment]
I'm all set....there was a bug in my JS code that was preventing the relationship from being properly sent in the token.

**Comment by remi-stripe** [comment]
@bgecawichBAO yay! Glad you were able to figure this one out!
