### ISSUE TITLE
ARM64 Support for UWP

### ISSUE THREAD

**Issue by liliyashka** [stripe/stripe-dotnet#1555]
I can not build project for the store on ARM64. Does Stripe not support ARM64?

**Comment by ob-stripe** [comment]
Hi @liliyashka. Stripe.net is generally meant to be used as a backend library. While it can technically be used to tokenize payment information in Xamarin apps, this has dubious [PCI implications](https://stripe.com/docs/security#validating-pci-compliance) and is not officially supported. The library is not tested with Xamarin or non-x86 architectures.

Stripe recommends that you use a webview and [Stripe.js](https://stripe.com/docs/stripe.js) or [Checkout](https://stripe.com/docs/checkout) to tokenize payment information. If you have more questions, please follow up with Stripe's support at https://support.stripe.com/email.
