### ISSUE TITLE
Keys property from V.24.0.0

### ISSUE THREAD

**Issue by dpellizza** [stripe/stripe-dotnet#1558]
From Stripe-dotnet v.24.0.0 the keys property on Account has been removed. How can I get the account's publishable key? I have to store the account's publishableKey to be used with Stripe.js to get cards source token on front-end.
Stripe API docs said that creating a new Custom Account it returns the Account object, **with an additional keys Dictionary containing secret and publishable keys for that account**.
When I use your Stripe.AccountService.Create(NewAccount) I'm not able to get additional keys.
What I'm wrong? Can you help me please?

**Comment by remi-stripe** [comment]
@dpellizza The version 24.0.0 is pinned to API version `2019-02-19` which removes those keys. You can read more about this on our upgrades page: https://stripe.com/docs/upgrades#2019-02-19

You should not need those keys for your integration. You should instead use your own platform's Publishable API key and pass the connected account's id (acct_123) in the `stripeAccount` property as documented here: https://stripe.com/docs/sources/connect#creating-direct-charges

**Comment by dpellizza** [comment]
We support the ability to upload files to Stripe directly from the browser. Simply use JavaScript to hit the endpoint ( https://stripe.com/docs/file-upload ) providing account's publishable API key. 
How can I use it without publishableKey?

**Comment by remi-stripe** [comment]
@dpellizza You can upload the file with your Publishable API key and then it should just work on the connected account as needed. You can also make the same request but pass the account's id in the `Stripe-Account` header as documented here for the curl call: https://stripe.com/docs/connect/authentication#authentication-via-the-stripe-account-header
