### ISSUE TITLE
DisputeEvidenceOptions - inconsistent field names

### ISSUE THREAD

**Issue by ydenega** [stripe/stripe-dotnet#1561]
DisputeEvidenceOptions class fields that hold ID of uploaded file are consistently named with 'FileId' at the end, for example, ServiceDocumentationFileId.

duplicate_charge_documentation, according to Stripe API documentation, holds ID of file upload.
However DuplicateChargeDocumentation field does not follow this naming pattern,

**Comment by remi-stripe** [comment]
Thanks for the report. Since this is a breaking change, we'll release this with our next major version.

**Comment by ob-stripe** [comment]
As of version 27.0.0, the parameter is named `DuplicateChargeDocumentationFileId ` to be consistent with other parameters: https://github.com/stripe/stripe-dotnet/blob/67a6bc4a8b833e1a5a6ddb92f6f9dd7f31a2d58b/src/Stripe.net/Services/Disputes/DisputeEvidenceOptions.cs#L38-L39
