### ISSUE TITLE
Response of card expired even though it shouldn't be?

### ISSUE THREAD

**Issue by Thorium** [stripe/stripe-dotnet#1566]
Hi,

It seems that sometimes the `POST /v1/customers/cus_.../sources` API responses

```json
{
  "error": {
    "code": "expired_card",
    "doc_url": "https://stripe.com/docs/error-codes/expired-card",
    "message": "Your card has expired.",
    "param": "exp_month",
    "type": "card_error"
  }
}
```

even though the card is still very valid for years. I'm trying to trace why this happens.

Environment details:
Windows and .NET Framework full.
Stripe.net version 19.10
UK machines (DD/MM/YYYY)

Can it be some date conversion?
Or maybe because the expiration month and year properties have been renamed between `ExpirationYear` and `ExpirationMonth` (my Stripe.NET) vs `exp_month` and `exp_year` (Stripe.com dashboard JSON)? Can Stirpe.NET convert these back and forth if the versions are mismatching?

**Comment by remi-stripe** [comment]
@Thorium If we return "card expired" it means that it is what the bank is telling us. It's possible the customer has renewed that card for example after losing it.

I'm going to close this out as this is unlikely to be related to the code of the library but feel free to reach out to our support team if you need more help: https://support.stripe.com/contact
