### ISSUE TITLE
NullRef in ParseEventDataItem

### ISSUE THREAD

**Issue by ithielnor** [stripe/stripe-dotnet#1584]
OS: Windows Server 2016
.Net: Framework 4.7.2
Stripe: 22.8.1

After upgrading to 22.8.1 from 15.x we're getting a null reference error within the ParseEventDataItem method on the following code:

```
Event stripeEvent = EventUtility.ConstructEvent(body, Request.Headers["Stripe-Signature"], secret);
if (stripeEvent.Type == "payout.created")
{
    Payout payout = EventUtility.ParseEventDataItem<Payout>(stripeEvent.Data.Object);
}
```

> System.NullReferenceException: Object reference not set to an instance of an object.
> at Stripe.EventUtility.ParseEventDataItem[T](Object dataItem)

I have verified that the default API version in my dashboard is set to 2018-11-08. Also, the `ConstructEvent` executes successfully.

Looking at the payload I see the event has:

```
"data": {
    "object": {
      "id": ...
      ...etc
    }
}
```

I can upgrade to 22.9 if you think that will help, but I really don't want to go further than that.

**Comment by ithielnor** [comment]
I'm curious if this could be some problem with the Newtonsoft.Json reference. We're running version 11. Does Stripe need a different version?

**Comment by remi-stripe** [comment]
@ithielnor Would you be able to provide a bit more details here such as the type of event that you are receiving and the event id `evt_123`?

**Comment by ithielnor** [comment]
@remi-stripe We discovered that the stripeEvent.Data.Object is already the parsed object. So we modified the code above to:

```
Payout payout = (Payout)stripeEvent.Data.Object;
```

I don't know when this changed as I can find no record of it in the release notes or the migration documents. The old code definitely worked in 15.x.

If you still want to look at one of the events, you can checkout id: evt_1EPJNKDAXyBcDxExrPZudpfz.

**Comment by remi-stripe** [comment]
@ithielnor We had large breaking changes in versions 20.0.0 and 22.0.0. We wrote detailed migration guides in the wiki (and linked to those from the changelog). I think https://github.com/stripe/stripe-dotnet/wiki/Migration-guide-for-v22#event-deserialization-with-eventutilityconstructevent--eventutilityparseevent is what you were looking for

**Comment by ithielnor** [comment]
@remi-stripe , I read through that a few times. However it makes no mention of the Data object or that `ParseEventDataItem` is no longer required. It only mentions `ConstructEvent` and `ParseEvent` and specifically the changes relating to API versioning.

I actually think v20 is more relevant but somewhat buried: https://github.com/stripe/stripe-dotnet/wiki/Migration-guide-for-v20#interfaces-for-polymorphic-resources. I recommend calling it out more clearly, and removing or deprecating `ParseEventDataItem` entirely.

**Comment by remi-stripe** [comment]
Thanks for the feedback. We'll investigate how to make that clearer in our docs too

**Comment by ob-stripe** [comment]
@ithielnor Thanks for the feedback! We're already planning on removing `ParseEventDataItem` in a future major version, but you're right that we should have called this out more explicitly.
