### ISSUE TITLE
Session Callbacks arent RestFul?

### ISSUE THREAD

**Issue by AdrianFinnegan** [stripe/stripe-dotnet#1585]
In the latest version 25.8.0.0 whereby you are required to create a session before making a charge and set the SuccesUrl and CancelUrl respectively:

```
 SessionCreateOptions createOPtions = new SessionCreateOptions
            {
                SuccessUrl = "http://localhost:62364/Basket/Success",
                CancelUrl = "http://localhost:62364/Basket/Cancel",
                //Line Items and Intent fields ommitted
            };

 SessionService stripeSesssionService = new SessionService("myKey");
            var session = stripeSesssionService.Create(createOPtions);
```
When the customer returns from Payment, how do I link their transaction to the session on my end?
So up front you need to do something like:
SuccessUrl = "http://localhost:62364/Basket/Success/"+session.Id;
But you don't know the session Id until after you have created it...

There is a property called ClientReferenceId but I dont see a way to query the Session/Charge with that field to get the status of the transaction either.

So the question is, if the customer makes a successful payment, how do I find the status of it, RestFully?

**Comment by remi-stripe** [comment]
@AdrianFinnegan Github issues should be limited to issues with the library itself. This is more a product question so I would recommend reaching out to our [support team|https://support.stripe.com/contact] instead if you have follow up questions.

In your example today though, we recommend using the webhook event to do fulfillment instead as documented here: https://stripe.com/docs/payments/checkout/fulfillment#webhooks
