### ISSUE TITLE
Is there are reason that you are using a static class for the events?

### ISSUE THREAD

**Issue by Franklin89** [stripe/stripe-dotnet#1590]
Is there are reason that you are using a static class for the events? (`stripe-dotnet/src/Stripe.net/Constants/Events.cs`)

Could they be changed to `const strings`? Then it would be possible to use a `switch`-statement when processing the events. I created a pull request (#1589) for this incase you would like to take this into consideration

**Comment by ob-stripe** [comment]
Hi @Franklin89. It's generally considered better practice to define constant values in libraries as readonly static properties. You can find some additional context and discussion in the PR where we switched from constants to static strings: #1423.

Unfortunately, this does prevent the values from being usable in `switch` statements, which is particularly annoying for webhook handlers where you would typically do something like `switch (event.Type) { ... }`. We're currently considering reverting that change in a future major version, but for now the best solution is to replace the `switch` statement with a series of `if / else if`.

I'll leave this issue open and tag it as future, and will update once we reach a decision on whether to switch back to actual constants or not.

**Comment by Franklin89** [comment]
@ob-stripe Thanks for the clarification. That does make sense for a library I fully agree. So I will go ahead with the `if / else if`.

**Comment by anth12** [comment]
+1 for reverting to `const`. 

Personally I'm opting to maintain a local version of `Events` with constants. I agree there may be some scenarios that benefit from properties, but I don't see any benefits here regarding event types.

**Comment by ob-stripe** [comment]
As of version 27.0.0, we've reverted to using `const` for string values. This makes them usable with `switch` statements again.
