### ISSUE TITLE
Support for new enable_incomplete_payments flag

### ISSUE THREAD

**Issue by kcoderhere** [stripe/stripe-dotnet#1597]
Can support be added for the new `enable_incomplete_payments` flag to `SubscriptionCreateOptions` and `SubscriptionUpdateOptions` [introduced in 2019-03-14](https://stripe.com/docs/billing/lifecycle#incomplete-opt-in)? 

I'm currently using this as my workaround:
`options.AddExtraParam("enable_incomplete_payments", "false");`

**Comment by remi-stripe** [comment]
@kcoderhere stripe-dotnet is always pinned to the most recent API version so the latest major version, 25.* is pinned to the API version [2019-03-14](https://stripe.com/docs/upgrades#2019-03-14). This means that, by default, the library automatically support incompletes Subscriptions already.

If you use the latest major version you should never have to pass `enable_incomplete_payments` and automatically get that behaviour out of the box.

**Comment by kcoderhere** [comment]
Except I don't _want_ that behavior, hence why I have to pass a "false" via `AddExtraParam` to prevent it from happening.

**Comment by remi-stripe** [comment]
@kcoderhere Thanks for clarifying. My understand of this parameter was that it was only added to enable the new behavior on old API versions and was not supposed to be settable as `false. I'm clarifying this internally and will follow up once I get more details about the behavior.

Flagging that doing this prevents you from handling cards requiring 3DS for example as documented here: https://stripe.com/docs/billing/migration/strong-customer-authentication

**Comment by remi-stripe** [comment]
@kcoderhere Really sorry for the delay on that one. I wanted to flag that we have shipped a new parameter, `payment_behavior` that replaces `enable_incomplete_payments` and it's now supported on the library. You can read more about it here: https://stripe.com/docs/api/subscriptions/create#create_subscription-payment_behavior

**Comment by nbnminds** [comment]
hi @remi-stripe  if we set 'payment_behavior' => 'allow_incomplete', the api throws error This customer has no attached payment source, 

It should allow the subscription be created so we can get last invoice payment intent and process. let me know what wrong ?

**Comment by remi-stripe** [comment]
@nbnminds This is expected behaviour today and the incomplete status only happens if the payment failed with an active source and not with a customer that has no source. You have to attach one first.

**Comment by nbnminds** [comment]
@remi-stripe if that is case then how is payment intent going to be used with create subscription

**Comment by remi-stripe** [comment]
I'm not sure what you mean exactly here. You need to collect payment method details client-side, create a `PaymentMethod` and attach it to a `Customer` before you create your `Subscription`.
