### ISSUE TITLE
Is this JSON key correct for Multibanco?

### ISSUE THREAD

**Issue by Andrewangeta** [stripe/stripe-dotnet#1604]
I'm just browsing the library and noticed that the Json property of the multibanco is uppercased is this a typo?
https://github.com/stripe/stripe-dotnet/blob/b1c7480ae5ecfb91910e7819ab1140f1b6c9f683/src/Stripe.net/Entities/Sources/SourceMultibanco.cs#L10

**Comment by Andrewangeta** [comment]
Same with P24 
https://github.com/stripe/stripe-dotnet/blob/b1c7480ae5ecfb91910e7819ab1140f1b6c9f683/src/Stripe.net/Entities/Sources/SourceP24.cs#L7

**Comment by remi-stripe** [comment]
@Andrewangeta Thanks for the report, this is definitely not correct. I'll work on fixing those later today but I'll wait a bit in case you find any other!

**Comment by Andrewangeta** [comment]
Also for EPS
https://github.com/stripe/stripe-dotnet/blob/b1c7480ae5ecfb91910e7819ab1140f1b6c9f683/src/Stripe.net/Entities/Sources/SourceEps.cs#L7

This has at least one property mentioned [here](https://stripe.com/docs/api/charges/object#charge_object-payment_method_details-eps-verified_name)

**Comment by Andrewangeta** [comment]
@remi-stripe I'm seeing a pattern where the payment method details are [looking a lot like sources](https://stripe.com/docs/api/charges/object#charge_object-payment_method_details).
but they're mismatched with some having properties and some missing. And some might be outdated according to the details of hashes returned on [this page](https://stripe.com/docs/sources). It's confusing to say the least lol.

**Comment by remi-stripe** [comment]
That part is a bit different. The Source object is separate from what is put on `payment_method_details` today.

Sources are being replaced by PaymentMethods which will make maintaining this a lot easier so for now we are not directly added all fields to the type-specific sub-classes.

I opened a PR to fix the properties names: https://github.com/stripe/stripe-dotnet/pull/1605

**Comment by Andrewangeta** [comment]
@remi-stripe Ah nice! I'm building a [Swift NIO](https://github.com/apple/swift-nio) based library and just making sure to get most of it right. But thanks for the heads up on sources being replaced in the future.

**Comment by remi-stripe** [comment]
@Andrewangeta Oh wow that's neat. I would recommend relying on [stripe-mock](https://github.com/stripe/stripe-mock) for the test suite like we do!

**Comment by Andrewangeta** [comment]
that sounds good! Before I was only making sure the models would encode/decode correctly. But I'll try to base my new test suite on .Nets testing pattern using mock.
