### ISSUE TITLE
Unrecognized request URL (POST: /v1/payment_intents//capture)

### ISSUE THREAD

**Issue by jinek** [stripe/stripe-dotnet#1614]
For code
```
var service = new PaymentIntentService();
            PaymentIntent _ =
                service.Capture(LockedPayment.MethodSpecificData, new PaymentIntentCaptureOptions());
```
stripe returns error:

```
{
  "error": {
    "message": "Unrecognized request URL (POST: /v1/payment_intents//capture). If you are trying to list objects, remove the trailing slash. If you are trying to retrieve an object, make sure you passed a valid (non-empty) identifier in your code. Please see https://stripe.com/docs or we can help at https://support.stripe.com/.",
    "type": "invalid_request_error"
  }
}
```

**Comment by remi-stripe** [comment]
@jinek This error indicates that you're passing an empty string as the PaymentIntent id. You need to double check your `LockedPayment.MethodSpecificData` as it's likely null instead of containing the `pi_12345` id.

**Comment by jinek** [comment]
OK, thanks, shouldn't it tell parameter is null? Because it's impossible to understand from exception text

**Comment by ob-stripe** [comment]
@jinek I agree that the API error is difficult to understand, and this issue can be caught before the request is sent to the API. I've added a check that will raise an `ArgumentException` if the provided ID is `null`, an empty string, or contains only whitespace. It will be released with the next major version.
