### ISSUE TITLE
dependency error

### ISSUE THREAD

**Issue by ramyat1711** [stripe/stripe-dotnet#1619]
PM> Install-Package Stripe.net
Attempting to resolve dependency 'Newtonsoft.Json (≥ 9.0.1)'.
Install-Package : 'Stripe.net' already has a dependency defined for 'Newtonsoft.Json'.
At line:1 char:1
+ Install-Package Stripe.net
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQua

i have already installed newtonsoft 9.0.1

**Comment by ob-stripe** [comment]
Hi @ramyat1711. I haven't run into this particular issue before, but a quick Google search suggests it's an issue with the NuGet Package Manager that can be resolved by upgrading it to the latest version: https://stackoverflow.com/a/25844391/5307473. Can you give that a try and report back?

**Comment by ob-stripe** [comment]
Closing this, but feel free to reply if you're still having trouble.
