### ISSUE TITLE
Yellow triangle on Stripe.net dependency

### ISSUE THREAD

**Issue by xnetdude** [stripe/stripe-dotnet#1621]
I'll delete this if user error but can't seem to install 25.19.0 on Visual Studio .net core 2.0 razor pages application.  Just get a yellow exclamation mark with no tooltip help on the stripe.net dependency.

Consequently, the library can't be referenced in the "using" statement. Is this a dependency issue perhaps, but I don't get any error either installing it via nuget.

Thanks.

**Comment by ob-stripe** [comment]
Hi @xnetdude. Can you try running `dotnet restore` manually in your project? That should either fix the issue or at least provide an error message that provides a little more information.

**Comment by ob-stripe** [comment]
Closing this, but feel free to reply if you're still having issues.
