### ISSUE TITLE
PayoutCreateOptions does not contain the Description property.

### ISSUE THREAD

**Issue by AKomyshan** [stripe/stripe-dotnet#1627]
Currently i was unable to create Payout object with Description property. Cuz https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Services/Payouts/PayoutCreateOptions.cs doesnt contains Description property.

I find some workaround `options.AddExtraParam("description", "test description");` But I'm not sure that's a good solution.

**Comment by ob-stripe** [comment]
Sorry, forgot to reply earlier, but this was fixed in version 25.20.0.
