### ISSUE TITLE
StartDate always null

### ISSUE THREAD

**Issue by BrianVallelunga** [stripe/stripe-dotnet#1636]
Using the latest SDK (26.0) the Subscription's `StartDate` is always null, despite the SDK having deprecated `Start`. Looking at the JSON I'm getting back, I don't see `start_date` being returned at all, just `start`. I'm using SDK version 2019-05-16 and the docs say it should return `start_date`.

Here's the source link that shows the mapping from JSON to .NET:
https://github.com/stripe/stripe-dotnet/pull/1613/files/fddeb15dbb087babe309aca17c274f26069bbd81

**Comment by remi-stripe** [comment]
@BrianVallelunga Thanks for the report. It looks to be an issue with the API as the field is just not returned yet. We're investigating and I'll update you once it's fixed!

**Comment by remi-stripe** [comment]
@BrianVallelunga I'm really sorry about the delay on that one, we fixed the API server-side but I forgot to update you. I just confirmed that this field is set as expected on the latest version of stripe-dotnet so you should be all set!
