### ISSUE TITLE
Extra "verification_method" parameter on SourceBankAccount

### ISSUE THREAD

**Issue by ithielnor** [stripe/stripe-dotnet#1645]
I'm using version 22.8.1.

I was directed by my Stripe rep to use an additional `verification_method` parameter on the Bank Account when we create new BankAccount records for our customers (due to specific agreement with have in place). I cannot figure out how to do this. My code looks something like this:

(EDITED)

**Comment by remi-stripe** [comment]
@ithielnor This is not really an issue with the library here and more a misunderstanding. I'm going to close this out, and I edited your previous response to hide some of the hidden parameters to avoid confusion.

I've clarified this internally though so your contact at Stripe should be able to clarify with you separately
