### ISSUE TITLE
SourceToken seems to be removed from CustomerCreateOptions in v27.0

### ISSUE THREAD

**Issue by imsam67** [stripe/stripe-dotnet#1649]
I've just updated the NuGet package for Stripe.net in my ASP.NET Core app from v26.0.0 to v27.0.0 and the `CustomerCreateOptions` seems to no longer have `SourceToken` property.

I was using the following code to create a customer in my Stripe account. How do I now create a customer without the token?

Here's my current code that requires a token:
```
public async Task<string> CreateCustomer(string name, string email, string token)
{
     var customerOptions = new CustomerCreateOptions()
     {
         Email = email,
         Description = name,
         SourceToken = token
      };
        
      try
      {
           var customer = await _customerService.CreateAsync(customerOptions);
           return customer.Id;
      }
      catch(Exception e)
      {
           throw new Exception(e.Message);
      }
}
```

**Comment by ob-stripe** [comment]
The property is now simply called `Source` and can be either a `string` or a `CardCreateNestedOptions`: https://github.com/stripe/stripe-dotnet/blob/67a6bc4a8b833e1a5a6ddb92f6f9dd7f31a2d58b/src/Stripe.net/Services/Customers/CustomerCreateOptions.cs#L78-L94

This is described in the migration guide: https://github.com/stripe/stripe-dotnet/wiki/Migration-guide-for-v27#polymorphic-parameters.
