### ISSUE TITLE
Source id is not been there in charge Create options -Version 27

### ISSUE THREAD

**Issue by JagadeeshwaranG** [stripe/stripe-dotnet#1652]
![image](https://user-images.githubusercontent.com/48272788/59196977-bee82a00-8bad-11e9-880d-d09462f7338a.png)

can you guys update the documentation how we can charge card payment?

**Comment by TheNowyn** [comment]
It was renamed to 'Source'. Lookup v27 migration guide for mode details.

**Comment by JagadeeshwaranG** [comment]
@TheNowyn Yes I saw the migration guide but I did not get coding samples to create customer, source, charge. can you guys update that info in current doc portal?

**Comment by UweKeim** [comment]
For anyone interested, here is the link to the [Migration guide for v27](https://github.com/stripe/stripe-dotnet/wiki/Migration-guide-for-v27).

**Comment by ob-stripe** [comment]
We've updated examples on Stripe's site to use `Source` instead of `SourceId`.

I'm closing the issue, but feel free to reply if you notice any other examples that are not working with the latest version!
