### ISSUE TITLE
Docs issue on Remove Discount from subscription.

### ISSUE THREAD

**Issue by OscarCR88** [stripe/stripe-dotnet#1666]
Hi to the maintainers!

I was reviewing the docs [here ](https://stripe.com/docs/api/discounts/subscription_delete?lang=dotnet) related to remove discount from subscription. 
Turns out that the method the docs said needs to be called is: 
`DeleteCustomerDiscount`
however, the method we really need to remove Discount from subscription is:
`DeleteSubscriptionDiscount`
Hope you guys can solve it, and save some time to other folks.

Cheers!

**Comment by ob-stripe** [comment]
Oops! Thanks for reporting this @OscarCR88. We'll fix this promptly.

**Comment by ob-stripe** [comment]
Docs are fixed. Thanks again!
