### ISSUE TITLE
Custom Newtonsoft JSON Options cause header error from telemetry

### ISSUE THREAD

**Issue by richardlawley** [stripe/stripe-dotnet#1670]
NET Framework 4.7.1, Stripe.Net 27.3.1, JSON.NET 12.0.2

If you make multiple requests using the same StripeClient, the second request adds a telemetry header containing the last request's latency.  The value of this header is a JSON value, serialised using `JsonConvert.SerializeValue`.

If the calling application has specified custom default options for JsonConvert (specifically referring to the Formatting Option), this value can contain newlines and causes every request after the initial one to fail:

> System.FormatException: 'New-line characters in header values must be followed by a white-space character.'

This was thrown from System.Net.Http.Headers.HttpHeaders.ParseAndAddValue with name = "X-Stripe-Client-Telemetry" and value as below (newlines left encoded to make it obvious):

> "{\r\n  \"last_request_metrics\": {\r\n    \"request_id\": \"req_iXuBVBUsCQUDdF\",\r\n    \"request_duration_ms\": 485\r\n  }\r\n}"

To resolve this, you should create your own JsonConverter instance with your own fixed options, rather than relying on the defaults which a calling application may have changed.

**Comment by ob-stripe** [comment]
Thanks a lot for the detailed report and the fix @richardlawley! Much appreciated.
