### ISSUE TITLE
Missing a Property which named Set_up_future in SessionPaymentIntentDataOptions.cs 

### ISSUE THREAD

**Issue by tobecon** [stripe/stripe-dotnet#1690]
I was using the Session api to Collect my Customer' s information. But when I  followed the Document [here](https://stripe.com/docs/api/checkout/sessions/create#create_checkout_session-payment_intent_data-setup_future_usage) , I found there is no property set_up_future in that Class

**Comment by remi-stripe** [comment]
This was released in 27.9.0
