### ISSUE TITLE
Strong Customer Authentication support

### ISSUE THREAD

**Issue by toxsedyshev** [stripe/stripe-dotnet#1691]
Hi! Is SCA support implemented in the library?

https://stripe.com/docs/strong-customer-authentication

I use TokenService (client side) and ChargeService (server side) to make charges from bank cards, but can't find any new functionality like URL of 3D secure page in the API response, etc.

**Comment by remi-stripe** [comment]
@toxsedyshev Yes the library supports everything that this guide mentions. To handle SCA you have to move off of using Tokens and Charges onto PaymentIntent and PaymentMethod. If you upgrade to the latest version of stripe-dotnet you should find everything you need. If you have any follow-up questions, don't hesitate to reach out to our support team: https://support.stripe.com/contact
