### ISSUE TITLE
SessionPaymentIntentDataOptions.SetupeFutureUsage

### ISSUE THREAD

**Issue by eutrading** [stripe/stripe-dotnet#1692]
Hello,
i'm doing something wrong or in the 27.8.1 a property of the SessionPaymentIntentDataOptions class is missing?

In particular i'm referring to SessionPaymentIntentDataOptions.SetupeFutureUsage

it seems that it should be present as reported here from the stripe API:
https://stripe.com/docs/api/checkout/sessions/create#create_checkout_session-payment_intent_data-setup_future_usage

But i'm not able to find it in the library, am i doing something wrong?

Thank you very much for you help

**Comment by remi-stripe** [comment]
@eutrading Thanks for the report! I'll work on a fix!

**Comment by remi-stripe** [comment]
This was released in 27.9.0
