### ISSUE TITLE
Stripe.StripeException: 'You cannot specify an `on_behalf_of` value that is different from the `transfer_data[destination]` value when using `card`

### ISSUE THREAD

**Issue by granthoff1107** [stripe/stripe-dotnet#1709]
I'm attempting to have users pay each other directly.  I've created a function which creates destination charges from one user to another.  I've created a function which will transfer money from a customer to the seller while collecting a fee:

    var paymentIntentService = new PaymentIntentService();
    var paymentIntentTransferDataOptions = new PaymentIntentTransferDataOptions();

    paymentIntentTransferDataOptions.Destination = sellerAccountId ?? this.GetPlatformAccount();

    var options = new PaymentIntentCreateOptions
    {
        Amount = amountInCents,
        Currency = currency,
        ApplicationFeeAmount = applicationFeeInCents,
        PaymentMethodTypes = new List<string> { "card" },
        OnBehalfOf = customerAccountId,
        TransferData = paymentIntentTransferDataOptions
    };

    var requestOptions = new RequestOptions { IdempotencyKey = idem };
    return await paymentIntentService.CreateAsync(options, requestOptions);
    
When I try to send money from one user to another I get an error:

>Stripe.StripeException: 'You cannot specify an `on_behalf_of` value that is different from the `transfer_data[destination]` value when using `card` or `card_present` in `payment_method_types`. This is because when you are using destination charging, Stripe must settle charges in the country of the destination account. You can learn more about charges and transfers here: https://stripe.com/docs/connect/charges-transfers#on-behalf-of'

This error message is very misleading, How would you be able to take in a charge if you cannot have the values of OnBehalfOf differ from destination.  E.g Even if you were to send it directly to the platform, the OnBehalfOf would still differ from the destination.

I'm aware I can transfer money to my platform and then to the seller, However, that opens me up to a risk, where the Customer disputes a charge, and I cannot recoup the cost from the seller.  So I would perfer the users pay eachother directly, Whether that is in a single transaction, or 2 (e.g customer creates a transaction to the platform for use of services, and then creates another transaction directly to the seller).

According to the documentation overview: 
>"businesses like Shopify can use the card_payments capability to enable sellers to accept payments directly from their customers ... Connected accounts with the card_payments capability have their statement descriptor displayed on the customer’s bank statement, not the platform’s." 

However there is not many examples to support this claim.

How can I have two users pay eachother?

**Comment by remi-stripe** [comment]
@granthoff1107 `on_behalf_of` is used to indicate which account you're creating the charge on behalf of. This means that your Customer John Does pays your recipient CookieStore with the account acct_123 through your platform. So you put `on_behalf_of: "acct_123"` when you create the Charge to indicate this.

The `transfer_data` hash lets you control where you want to send the funds. In your case the funds go to the same account that you created the charge on behalf of. So you would pass `transfer_data[destination]: "acct_123"`

The values **have to match**. The reason we have two parameters is that they control different behaviors. One decides how we settle the charge with regards to the card network and the other one where to send funds, and there are cases where you send funds to another account but settle as the platform.

Ultimately, your code, in your case, should always have the same value set in both, to the id of the account receiving the funds.

**Comment by remi-stripe** [comment]
Also to add a bit more details. If you are worried about liability and disputes, you likely should use Standard accounts and Direct charges instead. I would recommend reading https://stripe.com/docs/connect/accounts carefully and following up with our support team if you have any questions: https://support.stripe.com/contact

**Comment by granthoff1107** [comment]
Thanks for your response but this is still a bit unclear.

Who does Acct123 belong to the customer?  If so why would the destination
be the same account?

If the account belongs to the platform, what field is the one which
specifies which customer is sending the data.

I've discussed with the support team but they're unclear on the issue and
keep elevating it to the specialists but I haven't gotten a response

**Comment by remi-stripe** [comment]
In Stripe a Customer object represent someone *paying* for a service. An Account object represents someone delivering a service and receiving funds.

So acct_123 is owned by the person who will receive the funds in your example and cus_ABCDE the person who will pay funds.

I'll leave the rest to the support team as it's about your business itself and less about the integration so they are better equipped to discuss this with you more actively.

**Comment by MaeseppTarvo** [comment]
@remi-stripe So the on_behalf_of in the @granthoff1107 case would be the `cus_ABCDE` or the on_behalf_of can only be `acct_123`?

**Comment by vonjourn8519** [comment]
but how could I specify the source account Id, i.e. cus_ABCDE  who will pay the fund?

**Comment by remi-stripe** [comment]
@vonjourn8519 this is a 5 years old issue, please work with our support team for 1:1 support help instead: https://support.stripe.com/contact
