### ISSUE TITLE
SessionSubscriptionDataItemOptions does not have TrialPeriodDays

### ISSUE THREAD

**Issue by markprins81** [stripe/stripe-dotnet#1720]
The SessionSubscriptionDataItemOptions object, for creating a session to do checkout on a subscription does not have the property TrailPeriodInDays.

https://stripe.com/docs/payments/checkout/migration#api-subscriptions states it is in the API

**Comment by remi-stripe** [comment]
@markprins81 Thanks for the report! The docs are incorrect, the parameter is not inside the `items` hash, it's at the same level as items: https://stripe.com/docs/api/checkout/sessions/create#create_checkout_session-subscription_data-trial_period_days

It's supported in the library here: https://github.com/stripe/stripe-dotnet/blob/3cda6c1374e0197f7bb4ccc575e714abdf1f493d/src/Stripe.net/Services/Checkout/SessionSubscriptionDataOptions.cs#L35

I'll get the docs fixed!
