### ISSUE TITLE
Feature Request - SubscriptionItemOption to include Metadata property

### ISSUE THREAD

**Issue by adrianofo** [stripe/stripe-dotnet#1721]
Hello,

I need to create a Subscription with Subscription Items containing Metadata.
However, the SubscriptionItemOption class is missing the property Metadata.
https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Services/Subscriptions/SubscriptionItemOption.cs

Thanks,

Adriano

**Comment by remi-stripe** [comment]
@adrianofo Thanks for the report and sorry about the troubles! I opened a PR and it should be merged soon!

**Comment by remi-stripe** [comment]
@adrianofo I just release 27.18.0 which should have the fix!

**Comment by adrianofo** [comment]
Thank you very much!
Much appreciated!

**Comment by Simonl9l** [comment]
would be good to have the metadata also appear in the dashboard as it does for other entities.
