### ISSUE TITLE
Support for Connect Direct Charges

### ISSUE THREAD

**Issue by damiensawyer** [stripe/stripe-dotnet#1730]
Hi, 

It would be great to get .net library support for Direct Charges. 

https://stripe.com/docs/connect/direct-charges

Thanks :-)

**Comment by ob-stripe** [comment]
Hi @damiensawyer, the library does support this, though it looks like we don't have a .NET example on that page.

```c#
var service = new Stripe.ChargeService();
var charge = service.Create(
  new Stripe.ChargeCreateOptions
  {
    Amount = 123,
    Currency = "usd",
    Source = "tok_visa",
  },
  new Stripe.RequestOptions
  {
    StripeAccount = "{{CONNECTED_STRIPE_ACCOUNT_ID}}",
  }
);
```

**Comment by damiensawyer** [comment]
Thanks for that :-)

I wish I'd checked my email this morning. I got up at 2am and wrote a
custom handler. Lol.
