### ISSUE TITLE
Create InvoiceStatuses and InvoiceBillingReasons classes

### ISSUE THREAD

**Issue by adrianofo** [stripe/stripe-dotnet#1731]
Hello,

I am implementing a solution that we are needing to get the Status and BillingReason properties of an Invoice.
It would be more elegant to use constants instead of strings.
Currently, they support only string values.
If possible, could you please create two static classes with constant values (for example):
- [InvoiceStatuses](https://stripe.com/docs/api/invoices/object#invoice_object-status);
- [InvoiceBillingReasons](https://stripe.com/docs/api/invoices/object#invoice_object-billing_reason);

Similar to the [SubscriptionStatuses](https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Constants/SubscriptionStatuses.cs) class.

These two classes will be used in the [Invoice](https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Entities/Invoices/Invoice.cs) class.

Thanks,

Adriano

**Comment by remi-stripe** [comment]
@adrianofo At the moment, we don't want to add enum classes in the library and we recommend that you rely on the strings directly. There's another issue discussing adding Enums in the future potentially but it's not something we're ready to build in the short term. You can follow along in https://github.com/stripe/stripe-dotnet/issues/1673.

I'm going to close this out, I hope it's okay!

**Comment by adrianofo** [comment]
Thank you!
I understand. No worries.
