### ISSUE TITLE
Not getting Invoice Items list by Invoice ID

### ISSUE THREAD

**Issue by adrianofo** [stripe/stripe-dotnet#1737]
Hello,

I am using the Invoice Items API to get the list of Invoice Items for a specific Invoice in Draft Status.
But the list is coming empty.

```csharp
var requestOptions = new RequestOptions
{
    ApiKey = "apiSecretKey"
};

var invoiceItemService = new InvoiceItemService();

var invoiceItemListOptions = new InvoiceItemListOptions
{
    InvoiceId = "invoiceId"
};

var invoiceItems = await invoiceItemService.ListAsync(invoiceItemListOptions, requestOptions);
```
Is there anything else I should be doing?

Thanks,

Adriano

**Comment by remi-stripe** [comment]
@adrianofo This should work as long as this Invoice has Invoice Items on it. Invoice Items and Invoice Line Items are different:
https://stripe.com/docs/api/invoiceitems/object
https://stripe.com/docs/api/invoices/line_item

Are you sure your invoice has invoice items on it?

**Comment by adrianofo** [comment]
When I retrieve the Line Items for the specific invoice, I get two items, what is I am expecting.
Using the Dashboard, I can see the invoice created (in Draft status) has two items.
Does the invoice create two Invoice Items as well?

**Comment by remi-stripe** [comment]
@adrianofo Invoice Items are entirely separate and created via the API: https://stripe.com/docs/api/invoiceitems/create

It looks like you are not using Invoice Items at all so it's expected that this API request returns nothing. You should make sure to use the other API to list line items which is `ListLineItems` on the `InvoiceService`: https://github.com/stripe/stripe-dotnet/blob/2137391a57a66e767ac110dd6c2f6636af9ad69b/src/Stripe.net/Services/Invoices/InvoiceService.cs#L94

**Comment by adrianofo** [comment]
@remi-stripe What I am trying to do is update the quantity and/or delete the existing line items of an invoice.
But they seem to be read-only.
For example, how can I delete one specific invoice line item (or invoice item?) from an invoice (in draft status)?

Thanks,

Adriano

**Comment by remi-stripe** [comment]
This is not possible today in the API with line items. Only in the Dashboard I think since you can't create Draft invoices via the API today. I would recommend discussing this with our support team instead: https://support.stripe.com/contact?email=true

**Comment by adrianofo** [comment]
@remi-stripe The documentation says:
> When the invoice is created, you’ll receive (via configured webhooks) an invoice.created event. This time, the invoice’s status attribute will be draft, which means that its invoice items are open for modification.

https://stripe.com/docs/billing/invoices/subscription#subscription-renewal

We are trying to update the quantity/delete existing items of an invoice.
What is it allowed to do to a draft invoice?

Thanks,

Adriano

**Comment by remi-stripe** [comment]
@adrianofo I'm sorry but github issues should be limited to bugs with the libraries itself. Your ask is more a product question on how to use the API. You should contact our support team instead: https://support.stripe.com/contact

But the short answer is that you can **not** modify the line items on an invoice that are due to a Subscription. You can only modify the `InvoiceItem` resources which you had created before that were pending on the customer. So what you are trying to do is just not possible.
