### ISSUE TITLE
Is there a way to CC a person when sending an Invoice?

### ISSUE THREAD

**Issue by zerobounce** [stripe/stripe-dotnet#1740]
I didn't see a way to add a CC to sending in invoice via the API, I was wondering if this functionality exists. I can do it manually when I send an invoice in the admin.

**Comment by remi-stripe** [comment]
@zerobounce This is not possible in the API today, only in the Dashboard. I'm closing this issue as it's not a bug with the library itself but you can report this to our support team: https://support.stripe.com/contact
