### ISSUE TITLE
BankAccountCreateOptions missing metadata property

### ISSUE THREAD

**Issue by thomasdonaldclark** [stripe/stripe-dotnet#1741]
According to the documentation for [creating a bank account](https://stripe.com/docs/api/customer_bank_accounts/create), I believe the `BankAccountCreateOptions` class is missing a `metadata` property.

I think the modifications that need to be made specifically to this class would be inheriting the `IHasMetadata` interface and adding the property:

`[JsonProperty("metadata")]`
`public Dictionary<string, string> Metadata { get; set; }`

I'm unsure if any additional changes need to be made.

**Comment by remi-stripe** [comment]
@thomasdonaldclark Thanks for the report! I opened a PR and this will be fixed in the next release

**Comment by remi-stripe** [comment]
This was fixed in v27.25.0
