### ISSUE TITLE
Webhook fails to parse

### ISSUE THREAD

**Issue by thephoton** [stripe/stripe-dotnet#1749]
Webhook handlers fail to parse Stripe's JSON on the latest version of the API 2019-08-14, using the latest library release, 28.1.0 with MOTO payments enabled the account (but not for a paymentintent).

Relevant line: 
`var stripeEvent = EventUtility.ParseEvent(json);`
Results in "Null object cannot be converted to a value type."

Stripe is sending the following JSON object:
`{
  "id": "evt_1F81WK2qCSJQtwts85FlXXXX",
  "object": "event",
  "api_version": "2019-08-14",
  "created": 1565946891,
  "data": {
    "object": {
      ...
      "charges": {
        "object": "list",
        "data": [
          {
            ...
            "payment_method_details": {
              "card": {
                "brand": "visa",
                "checks": {
                  "address_line1_check": null,
                  "address_postal_code_check": "pass",
                  "cvc_check": "pass"
                },
                "country": "DE",
                "exp_month": 1,
                "exp_year": 2020,
                "fingerprint": "31JHm5b54H4vdCL9",
                "funding": "credit",
                "last4": "3184",
                "moto": null,
                "three_d_secure": {
                  "authenticated": true,
                  "succeeded": true,
                  "version": "1.0"
                },
                "wallet": null
              },
              "type": "card"
            },
            ...
          }
        ],
        ...
      },
      ...
    }
  },
  ...
  "type": "payment_intent.succeeded"
}`

Workaround appears to be to remove the invalid line before parsing:
`json = json.Replace("\"moto\": null,", "");`

Cards taken with MOTO enabled yield "moto: true" in the JSON and do not trigger the error.

**Comment by ob-stripe** [comment]
Hi @thephoton, thanks for the report and sorry for the inconvenience. We'll release a fix soon.

**Comment by ob-stripe** [comment]
@thephoton This should be fixed in version 28.2.0 which will be available on Nuget in a few minutes.
