### ISSUE TITLE
Missing StartDate in SubscriptionSchedulePhaseOptions

### ISSUE THREAD

**Issue by CZ-DannyK** [stripe/stripe-dotnet#1754]
Hello,

we are now trying to get subscription schedule working in our system, during investigation we have found there is missing property StartDate in SubscriptionSchedulePhaseOptions object (in api documentation is presented). Without this parameter we get this message during update:

> The subscription schedule update is missing at least one phase with a `start_date` to anchor end dates to.

This bug occurs in latest version 28.2.0 on .NET Core 2.2.x project.

Thanks in advance for help/fix

**Comment by remi-stripe** [comment]
@CZ-DannyK This was fixed in 28.3.0, thanks a lot for the report!
