### ISSUE TITLE
Missing Schedule (and ScheduleId) in Subscription object

### ISSUE THREAD

**Issue by CZ-DannyK** [stripe/stripe-dotnet#1757]
Hello again,

thank you very much for fixing of missing StartDate property in SubscriptionSchedulePhaseItem so fast, but i am affraid i have found another one missing.

This time it is property Schedule and probably ScheduleId in Subscription object (in documentation is this property presented). Fortunately it can be bypassed via listing of subscription schedules, but would be better to have it directly on object.

Again, thanks in advance for help/fix :)

**Comment by remi-stripe** [comment]
@CZ-DannyK Thanks for the report! I opened a PR for this and we will release this soon!

**Comment by CZ-DannyK** [comment]
I see it in 28.4.0 version, thanks you for fast fix!
