### ISSUE TITLE
Feature request: get `redirectToCheckout`-equivalent URL on server.

### ISSUE THREAD

**Issue by vegardlarsen** [stripe/stripe-dotnet#1759]
It would be helpful for implementations where a payment form is POSTed to a server, that the server could create the redirect URL to checkout. So instead of having to serve up a view that only loads the Stripe JavaScript code to then call:

```js
var stripe = Stripe('pk_test_....');
stripe.redirectToCheckout({ sessionId: '@ViewData['SessionId']' }).then(function(result) {
    alert(result.error.message);
});
```

We could instead do this on the server:

```cs
// boring part of creating SessionCreateOptions cut
var service = new SessionService();
var session = await service.CreateAsync(options);

// this is the new part, assuming we are in a controller:
return this.Redirect(session.GetCheckoutUri());
```

Does this make sense to anyone else but me? The advantage is that it would cut a full page load (download, render and Javascript execution) from at least my workflow.

**Comment by remi-stripe** [comment]
@vegardlarsen At the moment, this is not something supported by Checkout. The redirect has to happen client-side and this is a requirement on our end. If we end up adding a server-side redirect it will definitely be added to stripe-dotnet.

I'm closing this here but feel free to report the feature request to our support team: https://support.stripe.com/contact

**Comment by melvinmt** [comment]
I was wondering the same exact thing but thanks for the client-side requirement clarification, I will now stop looking for a way to do it on the server.

**Comment by remi-stripe** [comment]
@melvinmt Thanks for providing the feedback, this is helpful signal for us. We're definitely investigating what it would take to build this on our end but for now the redirect is client-side only.

**Comment by GeraldWodni** [comment]
@remi-stripe, I fell for the same issue as @melvinmt mentioned: I was looking for a couple of hours to find a way to do it server-side. May I recommend stating [somewhere prominently (maybe at point 2)](https://stripe.com/docs/payments/accept-a-payment) to developers that client-side is a requirement? Other payment providers I implemented had such an option, so it felt natural to keep digging for it ;)

**Comment by TrueNorthTrent** [comment]
@remi-stripe I agree.. I'm working with python, and still had to scour through the internet and find this post before I realized this isn't a feature you guys support.

**Comment by marcostaff** [comment]
I am integrating my site with stripe and i was really disappointed. I don't understand why to complicate your life with a javascript library when everything could be done on the server side.

**Comment by master-of-null** [comment]
My usecase is one in which, I want a user to hit a link from email and redirect them right to the stripe Checkout. I don't want to have to build a page, just to serve the redirect. Is this still not possible?

**Comment by remi-stripe** [comment]
@master-of-null It's something we have in beta at the moment and we hope to ship it publicly later this year but for now you need to redirect to a page on your website.

**Comment by isapir** [comment]
My use case is to open a Modal dialog with the checkout collection inside it without a redirect.  @remi-stripe would the new feature allow that?

**Comment by remi-stripe** [comment]
For everyone watching this thread/issue, I wanted to mention that we just shipped this ability today. The `Session` resource now has a `url` [property](https://stripe.com/docs/api/checkout/sessions/object#checkout_session_object-url) that you can use to do a server-side redirect. We just shipped this in stripe-dotnet version 39.54.0. You can now access the `Url` property on `Session` [here](https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Entities/Checkout/Sessions/Session.cs#L326).

Over the next few weeks, we're going to update our docs to reflect this but I wanted to circle back quickly!

**Comment by go2ready** [comment]
Amazing @remi-stripe ! I was just looking at this solution today, I assume python would also be supported right?

**Comment by remi-stripe** [comment]
@go2ready  yes all libraries support this. Python/PHP/Ruby/Node are "dynamically typed" so it will work on all versions of those libraries automatically since it's a new property being returned!

**Comment by frankjosephbarbato** [comment]
Was searching for same, server side redirect from Node JS/Express. Good news

**Comment by isapir** [comment]
And I am planning to use it with HTTP calls so I'd love to see a cURL example :)

**Comment by remi-stripe** [comment]
@isapir https://stripe.com/docs/api/checkout/sessions/create has examples for curl too and `url` is returned all the time so there shouldn't be anything curl specific

**Comment by isapir** [comment]
Thanks @remi-stripe!  It works great - I thought that I need to pass a special param hence the confusion

**Comment by Abdulali97** [comment]
@remi-stripe  
wow i was thinking about redierct from server  
couple days  ago  now i see this 🤩
