### ISSUE TITLE
SubscriptionSchedule and Renew forever?

### ISSUE THREAD

**Issue by CZ-DannyK** [stripe/stripe-dotnet#1762]
Hello,

as you might have noticed in recent days, i am working with subscription schedules. Thank you again for fast response and fixes. Now i have stuck with another problem. 

I am able to create new subscription schedule by migrating of current subscription, add phases, but cant figure out, how to set properties of SubscriptionScheduleUpdateOptions that will set last planned phase to **renew forever**. Currently every properties configuration i have tried results in scheduled phase to end at the end of plan interval (for example in a month since startin date). I see in Subscription Dashboard UI to be possible set Renew forever, but cant figure out any way, how to set it via this library.

Here is example of code i am using now:

```
var subscriptionScheduleUpdateOptions = new Stripe.SubscriptionScheduleUpdateOptions()
 {
       Phases = new List<SubscriptionSchedulePhaseOptions>()
       {
            new SubscriptionSchedulePhaseOptions()
            {
                  StartDate = subscriptionSchedule.CurrentPhase.StartDate,
                  EndDate = subscriptionSchedule.CurrentPhase.EndDate,
                  Plans = new List<SubscriptionSchedulePhaseItemOptions>()
                  {
                       new SubscriptionSchedulePhaseItemOptions()
                       {
                             PlanId = subscription.Plan.Id,
                             Quantity = 1,
                        },
                   },
               },
               new SubscriptionSchedulePhaseOptions()
                {
                     Plans = new List<SubscriptionSchedulePhaseItemOptions>()
                     {
                          new SubscriptionSchedulePhaseItemOptions()
                          {
                               PlanId = planId,
                               Quantity = 1,
                          },
                      },
                 },
       },
       RenewalBehavior = "renew",
       RenewalInterval = new SubscriptionScheduleRenewalIntervalOptions()
       {
              Interval = newPlan.Interval,
              Length = newPlan.IntervalLength,
        },
};

subscriptionSchedule = subscriptionScheduleService.Update(subscriptionSchedule.Id, subscriptionScheduleUpdateOptions);
```

Is it even possible with current API to set Renew forever on phase?

Thanks for help,
Daniel

**Comment by remi-stripe** [comment]
@CZ-DannyK Github issues should be limited to bugs with the library itself and not questions about our API. Moving forward, I would recommend that you contact our support team as they can help with any API questions.

Here, you are passing `RenewalBehavior = "renew"` as expected which should work though this possibility is going away soon so talking to our support team would be best.

You can contact them here: https://support.stripe.com/contact

**Comment by CZ-DannyK** [comment]
@remi-stripe No problem, i will contact support. I have placed it here just to be sure nothing wrong is with library.

Thanks again
