### ISSUE TITLE
I have recently upgraded my Api and trying to fix all the breaking changes and everything is gone well except that I can't figure out this issue. TokenService used to accept an access token of a customer but now it doesn't. How do I pass accesstoken to TokenService now to create a charge for a connected customer?

### ISSUE THREAD

**Issue by dbonabhealth** [stripe/stripe-dotnet#1765]
Please only file issues here that you believe represent actual bugs or feature requests for the Stripe.net library.

If you're having general trouble with your Stripe integration, please reach out to Stripe support using the form at https://support.stripe.com/ (preferred) or via email to support@stripe.com.

If you are reporting a bug, please include your OS version, .NET version and the version of the Stripe.net library you're using, as well as any other details that may be helpful in reproducing the problem.

**Comment by paulasjes-stripe** [comment]
I'm not sure if your message here was a copy paste error, but to answer your title question you'd pass in the Stripe-Account header in your request: https://stripe.com/docs/connect/authentication#stripe-account-header
