### ISSUE TITLE
Get customer by Id is throwing incorrect info

### ISSUE THREAD

**Issue by OscarCR88** [stripe/stripe-dotnet#1772]
OS: Windows 10 x64
Net Framework: 4.6.1
Stripe.net: 27.3.2

using this method:
`var customer = await customerService.GetAsync(customerId);`
returns "No such customer: cus_**********"

however, when calling Stripe's API via Postman with the following:
`https://api.stripe.com/v1/customers/cus_**********`
returns the actual customer, which drives me thinking it's a library's problem.

Any help would be greatly appreciated.

PS: this error only happens for a set of customers, not for all of them.

**Comment by ob-stripe** [comment]
@OscarCR88 Are you using the same API key in your .NET integration and in Postman?

**Comment by OscarCR88** [comment]
Well, this is embarrasing. Turns out the customer Id I was using had a starting space, that's why it said No such customer. 
Sorry for making you guys waste your time.

Closing...

**Comment by ob-stripe** [comment]
Haha, no worries at all, glad you figured it out!
