### ISSUE TITLE
Unable to use PII token with PersonUpdateOptions.IdNumber

### ISSUE THREAD

**Issue by danroot** [stripe/stripe-dotnet#1773]
According to stripe api docs, when updating an account update.individual.id_number can be either the ID Number (ie SSN in US), OR a PII token generated by Stripe.js:
https://stripe.com/docs/api/accounts/update#update_account-individual-id_number

However, if one attempts to set IdNumber to a full PII token (ie by POSTing an AccountUpdateOptions with IdNumber set to the JSON output of Stripe.js createToken), then JSON deserialization fails because it expects string, not token.

If one posts just the token id from Stripe.js (ie by POSTing an AccountUpdateOptions with IdNumber set to the token id from createToken), then Stripe rejects it as an invalid Id (ie SSN numbers must be 9 numbers), presumably because it is treating the token id as a SSN.

In other areas of the Stripe.NET SDK, this is handled with a separate token property, but I don't see any IdNumberToken option.  Is this missing in the .NET SDK, or am I missing something in how this works?

**Comment by remi-stripe** [comment]
@danroot Would you be able to share a bit more code to reproduce the issue? I just tried and our API supports passing a PII token id (pii_1234567) when updating an account's `individual` and it's not rejected.

**Comment by ob-stripe** [comment]
Closing, but feel free to reply if you're still having trouble and we'll reopen.
