### ISSUE TITLE
Setting customer source fails

### ISSUE THREAD

**Issue by brian-kane521** [stripe/stripe-dotnet#1776]
I'm running a .net core 2.2 application (debugging on Windows) and running the following code:
```

    var options = new SourceAttachOptions
    {
        Source = sourceId,
    };
    var service = new SourceService();
    var source = service.Attach(customerId, options);

```
Results in a StripeException:
`Unrecognized request URL (POST: /v1/customers//sources). If you are trying to list objects, remove the trailing slash. If you are trying to retrieve an object, make sure you passed a valid (non-empty) identifier in your code. Please see https://stripe.com/docs or we can help at https://support.stripe.com/.`

It appears perhaps that the Service object isn't building the target URL properly?

**Comment by ob-stripe** [comment]
@brian-kane521 It's likely the case that `customerId` is null or an empty string. Can you double-check that this is not the case?

**Comment by brian-kane521** [comment]
Apologies, that was the case

**Comment by ob-stripe** [comment]
No worries at all!
