### ISSUE TITLE
Implement subscription_data.payment_behavior=allow_incomplete for session/checkout creation

### ISSUE THREAD

**Issue by timstokman** [stripe/stripe-dotnet#1777]
This option is already implemented for subscription creation, but not for the session API (SessionSubscriptionDataOptions). This options allows you to create subscriptions for existing customers (and thus avoiding duplicate customer records).

Documentation for this API call is here: https://stripe.com/docs/payments/checkout/incomplete-subscriptions .

If it would help, I could create a pull request for this.

**Comment by remi-stripe** [comment]
@timstokman Thanks for the report! This parameter was added specifically for older integrations that need to migrate so we don't want to add it to the library as most integrations would never need it and it would be confusing for them.

If you need to pass this parameter, you should use `AddExtraParam` which lets you pass undocumented parameters. It would look like this:

```
var options = new SessionCreateOptions {
    PaymentMethodTypes = new List<string> {
        "card",
    },
    SubscriptionData = new SessionSubscriptionDataOptions {
        Items = new List<SessionSubscriptionDataItemOptions> {
            new SessionSubscriptionDataItemOptions {
                PlanId = "plan_123",
            },
        },
    },
    SuccessUrl = "https://example.com/success",
    CancelUrl = "https://example.com/cancel",
};
options.AddExtraParam("subscription_data[payment_behavior", "allow_incomplete");

var service = new SessionService();
Session session = service.Create(options);
```
