### ISSUE TITLE
Error when using 3D secure test cards

### ISSUE THREAD

**Issue by AversaConsulting** [stripe/stripe-dotnet#1779]
I've been trying to move to PaymentIntents using the latest .NET library. This was working ok but has now started getting errors. Anyone seen anything similar? I'm trying to have a manually confirmed payment after the 3D secure has happened as I have a risk in my checkout (holiday booking) that the order can't be processed as someone else has taken the booking while you're in the checkout. I'm using the .net examples pretty much unchanged albeit in VB.NET.

This all works ok with a non 3D secure card - but if a 3D secure test card is used, the .NET code (correctly?) sends a requires_action to the web page - but it then comes up with an error in the console of 

```
Uncaught (in promise) IntegrationError: handleCardAction: The PaymentIntent supplied does not require manual server-side confirmation. Please use handleCardPayment instead to complete the payment.
    at new t (https://js.stripe.com/v3/:1:10518)
    at https://js.stripe.com/v3/:1:122921
```
I initiate the payment as per the docs:

```
                If Not Request2.payment_method_id Is Nothing Then

                    ' Create the PaymentIntent
                    Dim createOptions = New PaymentIntentCreateOptions With {
                        .PaymentMethodId = Request2.payment_method_id,
                        .Amount = CLng(Basket.IncSellTotal * 100),
                        .Currency = "gbp",
                        .CaptureMethod = "manual",
                        .Confirm = True
                    }

                    PaymentIntent = PaymentIntentService.Create(createOptions)
                End If
```

and JS code again pretty much unchanged with extra debugging...

```
 else if (response.requires_action) {
            // Use Stripe.js to handle required card action
            alert('requires_action');
            stripe.handleCardAction(
                response.payment_intent_client_secret
            ).then(function (result) {
                if (result.error) {
                    // Show error in payment form
                    displayError.textContent = result.error.message;
                    alert('error');
                }
            });

  }
```

it doesn't actually hit the error section at all - just logs the message in the console on Chrome - MS Edge shows nothing - and nothing happens client side

Any help greatly appreciated! 

Nick

**Comment by ob-stripe** [comment]
Hi @AversaConsulting. This doesn't seem to be an issue with the Stripe.net client library, but rather an issue with your own integration.

GitHub issues on this repository are specifically for bugs or feature requests for the Stripe.net client library. I recommend you reach out to Stripe's support at https://support.stripe.com/email with the details you provided here -- they should be able to help you debug your integration and fix the issue.
