### ISSUE TITLE
PlanTier UnitAmountDecimal is spelled UnitAmountDecinal version 28.6.0.0

### ISSUE THREAD

**Issue by RiedigerD2** [stripe/stripe-dotnet#1781]
The property **UnitAmountDecinal** should be spelled **UnitAmountDecimal**. The JsonProperty attribute value correctly spells unit_amount_decimal so the property will still be filled in regardless of spelling. This is a minor bug.

**Comment by remi-stripe** [comment]
This is fixed in 29.1.0
