### ISSUE TITLE
BankAccountCreateOptions missing DefaultForCurrencyProperty

### ISSUE THREAD

**Issue by jjspierx** [stripe/stripe-dotnet#1787]
Using v29.1.0

The `BankAccountCreateOptions` class does not contain the `DefaultForCurrency` property.  According to the API documentation it should exist, and it exists in the `CardCreateOptions` class.

**Comment by remi-stripe** [comment]
@jjspierx This is defined top-level on `ExternalAccountCreateOptions` [here](https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Services/ExternalAccounts/ExternalAccountCreateOptions.cs#L24). Does that solve your issue?

**Comment by jjspierx** [comment]
My understanding is that ExternalAccounts are to be used as transfer destinations for Customer (Connected) accounts.  I am not using Connected accounts, so I am using BankAccount and Card objects as Sources for Customers.  Even if I can use ExternalAccount Service and Options instead, shouldn't one be able to set the default payment option on BankAccount and Card objects directly?

**Comment by remi-stripe** [comment]
@jjspierx `default_for_currency` only makes sense for External Accounts though. It does not exist, not work on Customers.

If you're trying to debit a customer via ACH then you would use BankAccounts but you would ignore `default_for_currency` entirely

**Comment by jjspierx** [comment]
You are absolutely correct.  I was confusing this property for the customers DefaultSource property. Thanks you so much.  Issue closed.

**Comment by remi-stripe** [comment]
Glad I was able to clear things up! The fact that we "share" the resource between External Accounts and Customers has been a real point of confusion for a while.

We're deprecating this and rebuilding everything on `PaymentMethod` moving forward which will make it a lot clearer hopefully :)
