### ISSUE TITLE
Code Replacement

### ISSUE THREAD

**Issue by IvanMykhayliv** [stripe/stripe-dotnet#1790]
Hello, how are you doing today?

I'm inquiring about the most recent Stripe package. Our code related to Stripe was working fine, but after the recent update, we've adapted our code to follow suit, barring a few lines.

What's the best way to substitute the code lines found in the attached image?

Please get back to us as soon as you can. Thank you, and have a good day.
![tr](https://user-images.githubusercontent.com/12425521/65344039-92787c80-dba4-11e9-9d5c-d6df048146f2.jpg)

**Comment by remi-stripe** [comment]
@IvanMykhayliv We recommend that you use `TaxRate` instead. This is documented in details here: https://stripe.com/docs/billing/taxes/tax-rates

Hope this helps!
