### ISSUE TITLE
Error to find dependencies

### ISSUE THREAD

**Issue by garucin27** [stripe/stripe-dotnet#1793]
Hi have implemented the new version of stripe but when I had publish my system implementation Stripe looks for the newtonsoft version 9.0.0 as a dependency, mi project have the 12.0.0 version, I tried a newtonsoft downgrade to 9.0.0 version but it did’t works, do yo know this issue?

**Comment by ob-stripe** [comment]
HI @garucin27. The Stripe.net library specifies its dependency on Newtonsoft.Json like this: https://github.com/stripe/stripe-dotnet/blob/f58498d41f64fa474d8f2dbdc557f4a66e60acf0/src/Stripe.net/Stripe.net.csproj#L45

According to [NuGet's documentation](https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#version-ranges-and-wildcards), this means that we're requiring a _minimum_ version of 9.0. We're not setting any maximum version, so more recent versions of Newtonsoft.Json like 12.0 should work as well.

Can you share more information about the issue? What are the exact errors you're seeing?

**Comment by ob-stripe** [comment]
Closing, but feel free to reply with more information if you think this is really an issue with the Stripe.net library and we'll investigate.
