### ISSUE TITLE
Error with the capture intent method

### ISSUE THREAD

**Issue by garucin27** [stripe/stripe-dotnet#1795]
I am trying to do a payment with split payment using the ApplicationFeeAmount in the PaymentIntentCaptureOptions, when I send in this way I receive the error: 

Can only apply an application_fee_amount when the PaymentIntent was made on behalf of another account (using an OAuth key or the Stripe-Account header), or when using the transfer_data[destination] parameter.

And when I use the transfer_data[destination] parameter I am getting the error: 

Received unknown parameter: transfer_data[destination]

There's a thing that I am missing?

`var options = new PaymentIntentCaptureOptions()
            {
                AmountToCapture = PriceAsSmallestUnit(order.Totals.AmoundDue, order.CurrencyCode),
            };
            if(order.AutoFulfill)
            {
                options.ApplicationFeeAmount = applicationFee;
                options.TransferData = new PaymentIntentTransferDataOptions
                {
                    Destination = sourcePayment.ConnectAccountId
                };
            }
            return service.Capture(sourcePayment.SourceId, options);`

**Comment by remi-stripe** [comment]
@garucin27 Usually, the problem here is that your account is connected to itself and you're passing your own main account id instead of a real connected account one. I'd recommend double checking the id of the account you're sending and that it does not match your own. If you have any follow-up questions, you should reach out to our support team: https://support.stripe.com/contact

**Comment by garucin27** [comment]
Thank you!

I´ve checked and I am not using the same account, I am using a real connected account.

There is another reason?

**Comment by remi-stripe** [comment]
It is almost always the real reason. I'd recommend asking our support team instead as this isn't a bug with the library and we're need real details of your account(s) that you should not share here.
