### ISSUE TITLE
Missing Status enum in ReaderListOptions

### ISSUE THREAD

**Issue by desaiankur** [stripe/stripe-dotnet#1796]
ReaderListOptions.cs is missing the "status" enum that is used to filter readers list to only offline or online readers.

**Comment by remi-stripe** [comment]
@desaiankur Thanks a lot for the report! I've opened a PR to fix this and it will be released in the next version!

**Comment by remi-stripe** [comment]
This has been released in 29.5.0. Thanks again for the report :)
