### ISSUE TITLE
"Invalid response object from API" exception when creating a Report Run

### ISSUE THREAD

**Issue by JohnNevilleEF** [stripe/stripe-dotnet#1823]
When using this SDK to trigger report runs(specifically a payouts.itemized.2 report) I am receiving an error that says the API is returning an invalid response object despite the API returning an OK response code. 

The response I received is as follows:

> "{
>   "id": "**Redacted**",
>   "object": "reporting.report_run",
>   "created": 1572280196,
>   "error": null,
>   "livemode": true,
>   "parameters": {
>     "interval_end": 1569988800,
>     "interval_start": 1569902400
>   },
>   "report_type": "payouts.itemized.2",
>   "result": null,
>   "status": "pending",
>   "succeeded_at": null
> }

I suspect that this has to do with succeeded_at being null in the response but not in the class.

**Comment by ob-stripe** [comment]
Hi @JohnNevilleEF, thanks for the report. I think you're right, `SucceededAt` should be nullable. We'll release a fix soon.

**Comment by ob-stripe** [comment]
Fixed in 32.1.3.
