### ISSUE TITLE
empty values are sent as null and stripe refuses them

### ISSUE THREAD

**Issue by softlion** [stripe/stripe-dotnet#1828]
I receive this exception message when using this code

```c#
                var sessions = new SessionService();
                var order = await sessions.CreateAsync(orderOptions);
```

> You passed an empty string for 'line_items[0][images]'. We assume empty values are an attempt to unset a parameter; however 'line_items[0][images]' cannot be unset. You should remove 'line_items[0][images]' from your request or supply a non-empty value.

```json
 "code": "parameter_invalid_empty",
  "decline_code": null,
  "doc_url": "https://stripe.com/docs/error-codes/parameter-invalid-empty"
```

The orderOptions contains a SessionCreateOptions object, with one item in the LineItems property.
The SessionLineItemOptions item initialize all fields, including the Images field but with an empty list.

A workaround is to use a non empty list containing a non empty string (a space) (" ").

```c#
                var items = new List<SessionLineItemOptions>
                {
                    new SessionLineItemOptions
                    {
                        Name = "Test", Amount = 1, Currency = "usd", Quantity = 1,
                        Images = new List<string>() { " " } //TODO Remove when the stripe lib is bug fixed
                    },
                };
```

Nuget version 32.1.3

**Comment by remi-stripe** [comment]
@softlion Would you be able to provide the exact code that triggers the bug? You showed the bug that "fixes the bug" I think. Ultimately `images` is supposed to be optional and this code works fine for me:

```
var options = new SessionCreateOptions {
  SuccessUrl = "https://example.com/success",
  CancelUrl = "https://example.com/cancel",
  PaymentMethodTypes = new List<string> {
    "card",
  },
  LineItems = new List<SessionLineItemOptions> {
      new SessionLineItemOptions {
        Name = "T-shirt",
        Description = "Comfortable cotton t-shirt",
        Amount = 1500,
        Currency = "usd",
        Quantity = 2,
    },
  },
};

var service = new SessionService();
Session session = service.Create(options);
Console.WriteLine(session.Id);
```

**Comment by ob-stripe** [comment]
Closing due to age, but feel free to reply if you believe this is a bug that needs to be fixed in the Stripe.net library.
