### ISSUE TITLE
Handling errors

### ISSUE THREAD

**Issue by clement911** [stripe/stripe-dotnet#1839]
What is the recommended way to catch errors and get error messages?

For example, I am looking at `OAuthTokenService().CreateAsync`.
The [documentation](https://stripe.com/docs/connect/oauth-reference#post-token-errors) includes an error and error_description but these are not in the OAuthToken entity.

Am I supposed to catch an exception? If so, what is the type?
Or am I supposed to look at the entity's StripeResponse and check the status code?

**Comment by ob-stripe** [comment]
Hi @clement911. Whenever the API returns an error (whether for "normal" API requests or OAuth requests), the Stripe.net library will throw a [`StripeException`](https://github.com/stripe/stripe-dotnet/blob/b993b33246607c0a3c14e4e31c5a446bfc0aa524/src/Stripe.net/Infrastructure/Public/StripeException.cs). The `StripeException` class has a [`StripeError`](https://github.com/stripe/stripe-dotnet/blob/b993b33246607c0a3c14e4e31c5a446bfc0aa524/src/Stripe.net/Infrastructure/Public/StripeException.cs#L31) property that contains the values of the error object returned by the API. For OAuth errors, the [`Error`](https://github.com/stripe/stripe-dotnet/blob/b993b33246607c0a3c14e4e31c5a446bfc0aa524/src/Stripe.net/Entities/StripeError.cs#L93) and [`ErrorDescription`](https://github.com/stripe/stripe-dotnet/blob/b993b33246607c0a3c14e4e31c5a446bfc0aa524/src/Stripe.net/Entities/StripeError.cs#L96) properties would be filled.

**Comment by clement911** [comment]
Got it.
Thank you for the fast response. Might be worth adding this info to the wiki.
