### ISSUE TITLE
Why is Event.Created nullable?

### ISSUE THREAD

**Issue by clement911** [stripe/stripe-dotnet#1840]
Why is Event.Created nullable?

Also, is this in UTC or the machine timezone?

**Comment by remi-stripe** [comment]
@clement911 `created` can be optional on some resources at the moment and I think it was optional on `Event` for a while a long time ago. It's not nullable today though so I'll push a fix and in the next major version it won't be nullable anymore.

As for the timestamps, our API always returns a unix timestamp so it would be UTC-based!

**Comment by remi-stripe** [comment]
Okay the next major version (34.0.0) will have this fix. You can follow along in this PR: https://github.com/stripe/stripe-dotnet/pull/1838

**Comment by clement911** [comment]
Thank you @remi-stripe !
I'll leave it to up to you to close this issue.

**Comment by remi-stripe** [comment]
Yes, I'll close the issue when the major version is released!
