### ISSUE TITLE
Update customer with Default Source does not seem to work

### ISSUE THREAD

**Issue by CarlosTorrecillas** [stripe/stripe-dotnet#1843]
Hi there,

Whenever I create a card related to a customer, once I attach it and try to update the customer to have it as a Default Source it does not seem to work as the dashboard is not showing it when I navigate to the customers tab.

My code:

```
public async Task<PaymentMethod> CreateAsync(string token, string customerId)
        {
            PaymentMethod paymentMethod = null;

            try
            {
                var options = new PaymentMethodCreateOptions
                {
                    Type = "card",
                    Card = new PaymentMethodCardCreateOptions
                    {
                        Token = token
                    }
                };

                var createdPaymentMethod = await _paymentMethodService.CreateAsync(options);

                if (createdPaymentMethod != null)
                {
                    var paymentMethodAttachOptions = new PaymentMethodAttachOptions
                    {
                        Customer = customerId
                    };

                    var attachedPaymentMethod = await _paymentMethodService.AttachAsync(createdPaymentMethod.Id, paymentMethodAttachOptions);

                    if(attachedPaymentMethod != null)
                    {
                        var customerUpdateOptions = new CustomerUpdateOptions
                        {
                            DefaultSource = token
                        };

                        var customerUpdated = await _customerService.UpdateAsync(customerId, customerUpdateOptions);

                        if(customerUpdated != null)
                        {
                            paymentMethod = attachedPaymentMethod;
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                Logger.Error(ex, $"Error creating payment method for {customerId}");
            }
            
            return paymentMethod;
        }
```
The method itself works however the action of setting the default source doesn't. I have tried both the token and the Id of the new payment method attached but none of them did the trick. If however I go to the dashboard and open a customer, go to the card that has been created and attached to it and click on "set as default" it then shows as default source.

Am I doing something wrong - is there any other method I need to call to make that happen?

I'm using Windows 10, .NET Core 2.2, Stripe 30.1.0 nuget package.

Thanks in advance

**Comment by remi-stripe** [comment]
@CarlosTorrecillas You are creating PaymentMethod objects. Those are entirely separate from legacy Card or Source objects. You can not pass a `pm_123456` in `DefaultSource`, that won't work (and that request should fail).

The `DefaultSource` property is deprecated. Instead, you can use `InvoiceSettings.DefaultPaymentMethod`. That will only set the default payment method for Subscriptions and Invoices though.

This isn't really a bug with the library itself which works as expected. Since it's more a question about the API, I'd recommend following up with our support team in you have any other questions: https://support.stripe.com/contact

**Comment by CarlosTorrecillas** [comment]
Thanks for the feedback @remi-stripe , that would make sense. In fact what I'm trying to achieve is to get a subscription schedule to collect the money from the set up card - which isn't really working. Checking the dashboard and according to support, when you have just one payment method set up that would be your default payment method. The subscription schedules I'm creating don't have the default payment method associated in the request because I thought that would be taken from the customer. Anyhow, I've changed the code to get updated the InvoiceSettings.DefaultPaymentMethod for the subscriptions as follows:

```
var customerUpdateOptions = new CustomerUpdateOptions
                        {
                            InvoiceSettings = new CustomerInvoiceSettingsOptions
                            {
                                DefaultPaymentMethod = attachedPaymentMethod.Id
                            }
                        };

                        var customerUpdated = await _customerService.UpdateAsync(customerId, customerUpdateOptions); 
```
Just to note, the previous code was working as in not failing on any of the requests so I'm not sure if there is anything that may be letting that go through in the code in the API side. Last but not least, I'm happy to get this through support but they redirect me to the API docs which sometimes aren't up to date or complete "clear" and that's why I find quite useful reporting the behavior here.

Thanks,
Carlos.

**Comment by remi-stripe** [comment]
Thanks for clarifying and glad you were able to fix the issue. Github issues really should be limited to bugs with the library itself though so it's not the best place to get help.

Developers are on IRC on Freenode in the #stripe channel. If you have technical questions like that one, you should join the channel and they can help you :)

**Comment by CarlosTorrecillas** [comment]
I'll sure will use that for the future. Many thanks again!
