### ISSUE TITLE
Inconsistency when trying to calculate the cost of proration

### ISSUE THREAD

**Issue by demirmusa** [stripe/stripe-dotnet#1846]
Stripe Version: 33.4.0
.Net Version: .Net Core 3.0

I am trying to calculate the cost of proration before I upgrade the subscription of the customer.
I am following that document: https://stripe.com/docs/billing/subscriptions/prorations. 

Here is my method to get proration 
```
public async Task<decimal> GetCostOfProration(string subscriptionId, string newPlanId)
{
    try
    {
        //https://stripe.com/docs/billing/subscriptions/prorations
        // Set the proration date to this moment:
        DateTimeOffset prorationDate = DateTimeOffset.UtcNow;

        var subService = new SubscriptionService();
        Subscription subscription = await subService.GetAsync(subscriptionId);

        // See what the next invoice would look like with a plan switch
        // and proration set:
        var items = new List<InvoiceSubscriptionItemOptions>
        {
            new InvoiceSubscriptionItemOptions
            {
                Id = subscription.Items.Data[0].Id,
                Plan = newPlanId, // Switch to new plan
            },
        };

        var options = new UpcomingInvoiceOptions
        {
            Customer = subscription.CustomerId,
            Subscription = subscriptionId,//(1)
            SubscriptionItems = items,
            SubscriptionProrationDate = prorationDate.UtcDateTime,
        };

        var invService = new InvoiceService();
        Invoice invoice = await invService.UpcomingAsync(options);

        // Calculate the proration cost:
        long cost = 0;
        foreach (var invoiceLineItem in invoice.Lines.ToList())
        {
            DateTimeOffset periodStart = new DateTimeOffset(invoiceLineItem.Period.Start.Value);
            if (periodStart.ToUnixTimeSeconds() == prorationDate.ToUnixTimeSeconds())
            {
                cost += invoiceLineItem.Amount;
            }
        }

        return ConvertFromStripePrice(cost);
    }
    catch (Exception e)
    {
        Logger.Error($"Could not calculate proration: {subscriptionId}, {newPlanId}", e);
        throw;
    }
}
```
 

1. The documentation is not contain the row
 `Subscription = subscriptionId,//(1)`. 
But if I don't add subscriptionId, it is throwing an exception
`You cannot update a subscription item without a subscription.`
Stack Trace:
```
   at Stripe.StripeClient.ProcessResponse[T](StripeResponse response)
   at Stripe.StripeClient.<RequestAsync>d__25`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Stripe.Service`1.<RequestAsync>d__23`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at (MyProjectName).Payments.Stripe.StripeGatewayManager.<GetCostOfProration>d__9.MoveNext() in (MyProjectName)\Payments\Stripe\StripeGatewayManager.cs:line 122
```

2. If I add subscription id it mostly works as expected but there is inconsistency in the result. It sometimes returns a different value.

![Screenshot_5](https://user-images.githubusercontent.com/48536631/69414624-25a86c80-0d24-11ea-82bd-251db0c723b5.png)
or
![Screenshot_2](https://user-images.githubusercontent.com/48536631/69414627-293bf380-0d24-11ea-85ba-141833db8fdb.png)

I expect a little bit difference because it works a couple of seconds/milliseconds delayed than the previous one. But it returns 0(zero).
Am I doing something wrong or is there a problem?

**Comment by remi-stripe** [comment]
@demirmusa Github issues should be limited to bugs or feature requests in the library.

This would be really specific to your account, the plans you're passing and the state of your subscription ahead of time. Since this won't be a bug in the library and is more an API question about proration, I would recommend talking to our support team instead directly https://support.stripe.com/contact

Just in case, the most common cause of this is this line 
```
if (periodStart.ToUnixTimeSeconds() == prorationDate.ToUnixTimeSeconds())
```

Because sometimes the proration item is created a second after you sent your request and so that if sometimes skip the proration items. What you can do is add some jitter to the logic and find proration items that were created a few seconds around that date instead.

**Comment by demirmusa** [comment]
Alright, I'll contact support.
Thanks a lot for your suggestion and interest.
