### ISSUE TITLE
Misleading error message

### ISSUE THREAD

**Issue by TomGullen** [stripe/stripe-dotnet#1857]
If you have a subscription with status `incomplete_expired` and attempt to delete an invoice item from this subscription, it returns the error:

    Customer cus_GFco6EKctYcU6n does not have a subscription with ID sub_GFx11KyK7FUx8F

This is a misleading error, as the subscription *does* belong to that customer ID.  I believe the actual issue here is that you cannot modify `incomplete_expired` subscriptions.

Possibly the Stripe documentation here needs clarification on when an invoice item can and cannot be deleted from a subscription also.

I know this isn't a Stripe.net specific issue as it's an error returned from the Stripe API but hoping this can be fixed.

**Comment by remi-stripe** [comment]
@TomGullen Thanks for the report. As you mentioned, this is not a stripe-dotnet bug here so it's not something that could be fixed and github issues should be limited to bugs or feature requests with the library itself.

I would recommend talking to our support team directly and providing relevant failed requests https://support.stripe.com/contact though I will report internally too.
