### ISSUE TITLE
Can't create payment source from a token

### ISSUE THREAD

**Issue by AhmedMKamal** [stripe/stripe-dotnet#1862]
Please, only file issues here that you believe represent actual bugs or feature requests for the Stripe.net library.

If you're having general trouble with your Stripe integration, please reach out to Stripe support using the form at https://support.stripe.com/ (preferred) or via email to support@stripe.com.

If you are reporting a bug, please include your OS version, .NET version and the version of the Stripe.net library you're using, as well as any other details that may help reproduce the problem.

Versions:
OS: Windows 10 (local) and Ubuntu server 18 (host)
.NET: dotnet core 3.0.100
Stripe.net: 33.9.0

I'm trying to create a payment source from a payment source token using the snippet below

**_Simplefied_**
```c#
public async Task AddPaymentSourceAsync(string userId, string paymentSource)
        {
            var user = await GetUserAsync(userId)
                .ConfigureAwait(false);

            var options = new Stripe.SourceCreateOptions
            {
                Token = paymentSource, // assume that paymentSource == "tok_visa"
                Customer = user.StripeId // assume that StripeId == "cus_GIEfTfTR8xyT9C"
            };

            await _stripeSourceService.CreateAsync(options)
                .ConfigureAwait(false);
        }
```
for some reason the `CreateAsync` function throws an error `"Received unknown parameter: token"`, why?

**Comment by cjavilla-stripe** [comment]
can you show where you've defined _stripeSourceService?

Also, in case it's helpful, there are Stripe engineers available to chat during most business hours in the #stripe channel on Freenode (https://webchat.freenode.net/?channel=#stripe).

**Comment by AhmedMKamal** [comment]
here's the definition of `_stripeSourceService`

`Startup.cs`
```c#
public void ConfigureServices(IServiceCollection services)
{
    services.AddTransient<Stripe.SourceService>();
}
```

`PaymentsServiceImpl.cs`
```c#
public class PaymentsServiceImpl : IPaymentsService
{
    private readonly Stripe.SourceService _stripeSourceService;

    public PaymentsServiceImpl(Stripe.SourceService stripeSourceService)
    {
        _stripeSourceService = stripeSourceService;
    }

    // and then the AddPaymentSourceAsync that I've mentioned before
}
```

in short, you can consider it `var _stripeSourceService = new Stripe.SourceService();`

and, thanks for the reference, should I move this issue there?

**Comment by cjavilla-stripe** [comment]
ok, sorry for any confusion. The `token` cannot be passed at the same time as `customer`. The `customer` argument during source creation is purely for cloning a source with Connect. 

Please reach out to support.stripe.com/contact for more info :)
