### ISSUE TITLE
Typo in v30 Migration Guide

### ISSUE THREAD

**Issue by winzig** [stripe/stripe-dotnet#1864]
https://github.com/stripe/stripe-dotnet/wiki/Migration-guide-for-v30

In the section on renaming, it shows `SubscriptionCreateOptions.CouponId` being renamed to the (identically named) `SubscriptionCreateOptions.CouponId`. I think the second column should say `SubscriptionCreateOptions.Coupon`, right?

**Comment by remi-stripe** [comment]
@winzig Nice catch, thanks for reporting the issue. I just fixed it which should hopefully be clearer!

**Comment by winzig** [comment]
@remi-stripe Another minor typo, this one in the changelog `SubscritionSchedule` instead of `SubscriptionSchedule`. Yes, I'm playing catch-up on our SDK use tonight. ;)

**Comment by remi-stripe** [comment]
Nice catch, I just fixed it! Let me know if you see anything else!
