### ISSUE TITLE
Id property removed from SuscriptionItemUpdateOptions?

### ISSUE THREAD

**Issue by winzig** [stripe/stripe-dotnet#1867]
I'm migrating from 33.9.0 to 34.1.0 and running into an error indicating `Id` is not part of `SubscriptionItemUpdateOptions`. I don't see this in the last 2 release notes, yet my code was compiling previously with 33.9.0?

```c#
new Stripe.SubscriptionItemUpdateOptions {
    Id = existingSubscription.Items.Data[0].Id,
    Plan = planId
}
```

**Comment by winzig** [comment]
Actually, I think I'm running into something strange while trying to address the change of some classes from `...Option` to `...Options`. I'll update in a minute once I figure this out. ;)

**Comment by winzig** [comment]
Ahh, never mind I misread this changelog entry:

`SubscriptionItemUpdateOption is now merged into SubscriptionItemOptions.`

**Comment by winzig** [comment]
I think one thing that confused me is that there is still a `SubscriptionItemUpdateOptions` class. So after quickly reading it, I first changed `SubscriptionItemUpdateOption` to `SubscriptionItemUpdateOptions` instead of changing my references to `SubscriptionItemOptions` as the changelog indicated.

**Comment by remi-stripe** [comment]
@winzig Glad you figured it out, sorry that one was confusing. The naming of the fields also tripped me up when doing the rename as they are so close to each other. 

Let us know if you have any feedback on the changes (or the library) :)
