### ISSUE TITLE
How to handle webhooks/events with different API versions?

### ISSUE THREAD

**Issue by clement911** [stripe/stripe-dotnet#1874]
Stripe.net is pinned to a particular version but if we upgrade our account's version, we'll start receiving events in a new version, while not all events generated with the previous version may have been processed yet.

So, I'm wondering what is a good way to handle the transition period, where we have to process events that may be in either version N or version N+1.

As far as I know, it's not possible to reference two different versions Stripe.net, so that means that the application could only handle a single version at a time.

Any good practices out there that you could recommend?

I see that `EventUtility.ParseEvent` has a `throwOnApiVersionMismatch` parameter.
That brings another question to mind.
What will happen if we parse an event with a version that doesn't match the library's version?
Will some properties being ignored and not populated?
Can it throw an exception?

For example, if a property was renamed, I guess it would be dangerous, because the deserialized object might have a null value even though there was a value (just under a different name).
I suppose that more important changes might even cause the deserilization to even fail and throw an exception?

**Comment by remi-stripe** [comment]
> So, I'm wondering what is a good way to handle the transition period, where we have to process events that may be in either version N or version N+1.

What I recommend in this case is to add a second webhook endpoint to your account with the new API version explicitly set to the API version of the new version of stripe-dotnet: https://stripe.com/docs/api/webhook_endpoints/create#create_webhook_endpoint-api_version

Doing this means that for a while, we will generate events for both API versions your integration might be using. You could throw the event payload in a queue for each version and then based on which version of stripe-dotnet your background job is running you can choose to parse the right version that matches.

Once your deploy is stable you can then delete the webhook endpoint for the old API version and stick to the new one moving forward.


>What will happen if we parse an event with a version that doesn't match the library's version?
> Will some properties being ignored and not populated?
> Can it throw an exception?

Many of the API versions changes only touch a really small part of our API. If you don't use that product at all, then none of the changes would affect your webhook handler. For that reason, we built this option to let you easily deserialize events from a different API version as needed.

This means that if we rename a field on say Coupon and you never use Coupon then deserializing a Charge event with the new API version wouldn't cause any problem. 

On the other hand, if we change the shape of a field on `Charge` from a string to a dictionary for example, when you attempt to deserialize, the JSON parser would encounter an error and could crash.

I recommend using this option only in test mode and not in production.

**Comment by clement911** [comment]
Two webhooks!

I was thinking of querying back the API in case of version mismatch but I hadn't thought about creating another webhook!

Thank you.
