### ISSUE TITLE
WebhookEndpoint.Connect is always false

### ISSUE THREAD

**Issue by clement911** [stripe/stripe-dotnet#1876]
As far as I can tell, the `Connect` property is never returned by the API and should therefore be removed from the `WebhookEndpoint` class.

Unless I'm missing something?

Is it enough to check that `ApplicationId` is non null to determine that the endpoint is a connect endpoint?

**Comment by remi-stripe** [comment]
@clement911 Thanks a lot for catching that one. It definitely should be present and this is a bug in the API. I'll report this internally and get this fixed soon!

**Comment by clement911** [comment]
Sure thing.

**Comment by remi-stripe** [comment]
@clement911 After discussing this internally, I confirmed that `Connect` should not be here. I've opened a PR to mark it as obsolete and also took the opportunity to rename `ApplicationId` to `Application` for consistency! It'll go in the next version.

**Comment by clement911** [comment]
Ok.
So just to confirm, we can identify if the webhook endpoint is a connect endpoint by checking applicationid != null?

**Comment by remi-stripe** [comment]
Fixed in 34.5.0
