### ISSUE TITLE
SessionLineItemOptions uses wrong data type

### ISSUE THREAD

**Issue by dansiegel** [stripe/stripe-dotnet#1879]
# Description

In looking at the Stripe.Net API to create a [new Session for a checkout](https://stripe.com/docs/payments/checkout/one-time#one-time-payments-with-checkout) I would need to add a list of Line Item Options which seems to be the only place to place a price. The Amount property however is using a `long?`. This seems to make no logical sense as a long is an integral numeric type and not a floating point numeric type as you would expect when working with a charge amount.

This should be changed to either a double or decimal

**Comment by clement911** [comment]
See https://stripe.com/docs/currencies#zero-decimal

**Comment by dansiegel** [comment]
@clement911 thank you for the clarification. If that's the case that's not very discoverable when you're just trying to get started with checkouts. I might suggest a couple of changes:

- Have the docs team add that link in the checkout docs I posted initially.
- Update the xml docs on the SessionLineItemOptions

right now you just have:

```cs
/// <summary>
/// The amount to be collected per unit of the line item.
/// </summary>
[JsonProperty("amount")]
public long? Amount { get; set; }
```

where I believe simply adding some remarks with that link would be hugely beneficial.

```cs
/// <summary>
/// The amount to be collected per unit of the line item.
/// </summary>
/// <remarks>
/// See https://stripe.com/docs/currencies#zero-decimal
/// </remarks>
[JsonProperty("amount")]
public long? Amount { get; set; }
```

**Comment by remi-stripe** [comment]
@dansiegel Thanks for the feedback! I can see how it's not something easily discoverable when you're just starting with our API. I'll flag internally to see how we could make it easier to understand how this field works as it's definitely a common question! Glad you were unblocked so quickly so thank you @clement911 for the help :)
