### ISSUE TITLE
Stripe.net and Newtonsoft.Json 11.0.2

### ISSUE THREAD

**Issue by sanamend** [stripe/stripe-dotnet#1883]
ASP.NET Application .NET version 4.5 with Newtonsoft.Json 11.0.2 needed for other external library. 
I rebuilded stripe.net solution changing the nuget package: I updated exist Newtonsoft.Json version (9.0.1) with new nuget package Newtonsoft.Json 11.0.2. I got new stripe.net.dll and used it. 
All, seems, work fine.
Someone know if it is ok?

Thanks
Regards

**Comment by ob-stripe** [comment]
Hi @sanamend. 9.0.1 is the minimum version of Newtonsoft.Json that is required to use Stripe.net, but more recent versions should work fine too.

Closing this, but feel free to reply!
