### ISSUE TITLE
Provide Stripe.Abstractions as nuget package

### ISSUE THREAD

**Issue by Bchir** [stripe/stripe-dotnet#1889]
* As a developer, I want to have abstraction overall stripe services, so that I can easily mock them using a third party ( like Moq)  on my unit tests
example : 
``` CSharp
_sourceServiceMock = new Mock<ISourceService>();
_sourceService.Setup(s => s.GetAsync(something)).Returns(somethingElse);
_myService = new MyService(_soureServiceMock.Object);
```
Also
* As a developer, I want abstraction as different NuGet, so that I only reference the stripe NuGet on my gateway project and reference only the abstraction on my class libraries, So that as long as the abstraction doesn't change, I only need to update the nuget on my gateway project.

**Comment by ob-stripe** [comment]
I'm not convinced this is needed -- it's already fairly easy to use Stripe services in unit tests by mocking the underlying `StripeClient`, e.g.:

```c#
var stripeClientMock = new Mock<IStripeClient>();
stripeClientMock.Setup(c => c.RequestAsync<Source>(
  It.IsAny<HttpMethod>(),
  It.IsAny<string>(),
  It.IsAny<BaseOptions>(),
  It.IsAny<RequestOptions>(),
  It.IsAny<CancellationToken>()
).Returns(source);
var sourceService = new SourceService(stripeClientMock.Object);
```

Also, realistically, we would not be able to maintain a separate package at this time. We may revisit this once we're able to generate the code for the library from the OpenAPI spec (which we expect to be the case sometimes in 2020), but for the time being we'll have to decline this request.

Closing, but feel free to reply.
