### ISSUE TITLE
Missing fields on SubscriptionItemUpdateOptions

### ISSUE THREAD

**Issue by danrub** [stripe/stripe-dotnet#1898]
Stripe documentation states:

For each item we optionally can add **id** as subscription item to update or specify **deleted =true** if we require to remove item from subscription items.

In the latest release: 34.15.0 those fields are missing inside `SubscriptionItemUpdateOptions` which is a Breaking change. 

![image](https://user-images.githubusercontent.com/417622/72510618-7040f380-3852-11ea-9d00-f78f3d5a660f.png)

**Comment by Allezk** [comment]
I also ran into this issue Stripe haven't updated their documentation yet. So if any one else finds this issue before they update their documentation. The new class is SubscriptionItemOptions. Not SubscriptionItemUpdateOption or SubscriptionItemUpdateOptions

**Comment by cjavilla-stripe** [comment]
Thanks for reporting. I'll take a look and update these docs. Sorry for the confusion!
