### ISSUE TITLE
Request: create combined interface for Services

### ISSUE THREAD

**Issue by RonSijm** [stripe/stripe-dotnet#1900]
Hello! At the moment all the services seem to derivative of 5 interfaces. (this pattern seems generated) - I was wondering if you could create an overlaying interface instead.

For example, the current implementation is as following:

```
    public class CustomerService : Service<Customer>,
        ICreatable<Customer, CustomerCreateOptions>,
        IDeletable<Customer>,
        IListable<Customer, CustomerListOptions>,
        IRetrievable<Customer, CustomerGetOptions>,
        IUpdatable<Customer, CustomerUpdateOptions>
    {
```
I'd like to request if that could be changed into the following:

```
    public interface ICustomerService : 
        ICreatable<Customer, CustomerCreateOptions>,
        IDeletable<Customer>,
        IListable<Customer, CustomerListOptions>,
        IRetrievable<Customer, CustomerGetOptions>,
        IUpdatable<Customer, CustomerUpdateOptions>
    {
    }


    public class CustomerService : Service<Customer>, ICustomerService
    {
```

This should be a non-breaking change because the CustomerService still requires all interfaces, but it will make it much easier to mock or substitute the entire ICustomerService. Interface Segregation wise, classes that only use a specific method can still implement any of the specific ones

**Comment by ob-stripe** [comment]
Hi @RonSijm, thanks for the feature request!

At the moment the library is manually written, and maintaining it is already a non-trivial burden on the team, so I would rather not introduce this change right away.

That said, we are in the process of generating the code of our client libraries directly from the OpenAPI specification file for Stripe's API. Once we update stripe-dotnet to be generated, then this change should be easy enough to make.

I'm tagging this as `future` for now. I don't have an ETA for when stripe-dotnet will be generated, but it's on our roadmap. I'll post an update here once I have some concrete news to share. Thanks for your patience!

**Comment by jonocairns** [comment]
I also think this is a great idea. Specifically when you need to bind services on at dotnetcore API. We're currently having to get around this by creating our own StripeService (with an interface) which wraps the lower level services so we can mock them out in test land.

**Comment by nathanchere** [comment]
I came here to request the same thing myself since unit testing things with a dependency on Stripe is impractical in its current state. Given how old this ticket is and having looked at the actual work involved, I'd be happy to implement this if it's not treading on any toes.

**Comment by ctrudeau-stripe** [comment]
Hi @nathanchere, stripe-dotnet is generated right now, so definitely don't do the work of implementing this interface everywhere. However if you would like implement this for a couple resources of how you would like this to work, that'd would be a valuable contribution and first step.

**Comment by ghandmann** [comment]
+1

That's indeed something that the StripeClient lacks badly. UnitTesting could be a breeze. Instead it's a pain.

Beside that: We use it in the context of a .net Core ServiceWorker with dependency injection in place, injecting concrete instances (and depending on concrete instances) is just a big no-no in this case.

**Comment by johncyril** [comment]
@nathanchere -- would you still find these implemented interfaces for a couple of resources helpful?
I'm currently encountering the same issue as lots of others in terms of testing and am happy to contribute to this in order to avoid multiple developers having to write exactly the same facades for unit testing.

What would you find useful or helpful from us here?

**Comment by pakrym-stripe** [comment]
Hello friends! 

Can you help me with an example of a unit-test you are trying to write?

All methods on service types are `virtual` and they have a public parameterless constructor that should make service types equivalent to interfaces from the unit-testing perspective.

To illustrate using Moq and XUnit:

``` C#
        [Fact]
        public void MockingServiceWorks()
        {
            Mock<CustomerService> mock = new Mock<CustomerService>();
            mock.Setup(m => m.Get("cus_1", null, null)).Returns(new Customer() { Name = "My customer" });

            CustomerService service = mock.Object;

            Assert.Equal("My customer", service.Get("cus_1").Name);
        }
```

**Comment by pakrym-stripe** [comment]
Closing as it seems that CustomerService classes can be mocked as easily as interfaces. Please reopen if you find a scenario that's not covered and still requires an extra interface.
