### ISSUE TITLE
CreditNote out_of_band_amount should be nullable

### ISSUE THREAD

**Issue by caitchison** [stripe/stripe-dotnet#1901]
Trying to retrieve a list of credit notes through the CreditNoteService.ListAsync method I am receiving an error. The initial exception only says there was an 'Invalid response object from API'
 but upon further investigation I can see that I am trying to retrieve a credit note with a null out_of_band_amount. `"out_of_band_amount": null`

The OutOfBandAmount is set as `long` on the [entity,](https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Entities/CreditNotes/CreditNote.cs#L155) so the Json deserialisation is failing.

Could you please allow a null value on the OutOfBandAmount so that this list of Credit Notes can be retrieved? Or is this an error on the API side and that null should actually be a zero?

**Comment by cjavilla-stripe** [comment]
Hey caitchison sorry about that. Working on a quick patch.

**Comment by ob-stripe** [comment]
Fixed in 34.16.1 which will be available on NuGet in a moment.

**Comment by caitchison** [comment]
Thank you for such a fast turnaround!
