### ISSUE TITLE
Error on all API Requests: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by jjspierx** [stripe/stripe-dotnet#1922]
After a recent upgrade of stripe.net library and target API on Stripe I started receiving errors on all API requests.  The error and fix is essentially the same as: https://github.com/stripe/stripe-dotnet/issues/1667

This issue was fixed in PR# https://github.com/stripe/stripe-dotnet/issues/1668 However, I am seeing the same issue with v34.22.0. The same fix works by setting the security protocol to TLS12 (`ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12`).  Here are some details about the issue.

- Issue started occuring after upgrading Stripe.net from v13.x => v34.22.0

- Also upgraded Stripe API from 2018-02-28 => 2019-12-03 (rolled back to 2018-02-28 after the error started occuring to verify it was not the API upgrade causing the issue and the issue still occured when rolling back).

- My code targets .NET Framework 4.5

- The error seems to occur with any API call.  All of my API calls are via the service classes, and I do NOT use any custom client in place of `Stripe.SystemNetHttpClient` .

- The error does not occur on my Windows 10 development machine, it only occurs with identical code on my AWS EC2 instance running Windows Server 2012 R2

- Adding `ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12` before my API calls seems to have resolved the issue, but it is odd that I should need to do this.  It looks like the code in `/src/Stripe.net/Infrastructure/Public/SystenNetHttpClient.cs` should be doing this for me.  Maybe it is a permissions issue with Windows Server 2012 or something strange like that?

Here is an example of a request that fails:

```
var myCharge = new ChargeCreateOptions()
{
    ...                    
};

var chargeService = new ChargeService();
stripeCharge = chargeService.Create(myCharge);
```

The code sample above fails with the below Stack Trace. 
I think the most pertinent facts are:
  

1.  Passes on Windows 10 development machine, but fails on AWS EC2 Windows Server 2012 R2
2. Passes when manually setting SecurityProtocol to TLS12

```
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at Stripe.SystemNetHttpClient.<MakeRequestAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stripe.StripeClient.<RequestAsync>d__25`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stripe.Service`1.<RequestAsync>d__24`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stripe.Service`1.Request[T](HttpMethod method, String path, BaseOptions options, RequestOptions requestOptions)
   at Stripe.ChargeService.Create(ChargeCreateOptions options, RequestOptions requestOptions)
```

**Comment by ob-stripe** [comment]
The fix to enable TLS 1.2 with .NET Framework 4.5 is still present in the library as of v34.22.0: https://github.com/stripe/stripe-dotnet/blob/0b2f64aa66afe577fc98c12e4325a01329abfd68/src/Stripe.net/Infrastructure/Public/SystemNetHttpClient.cs#L69-L73

Since you're reporting that manually setting `ServicePointManager.SecurityProtocol` fixes the issue for you, then that means that the code I linked to is not being executed. I can think of two reasons:

1. The target framework is not `net45` (but then TLS 1.2 should be enabled out of the box)

2. `SystemNetHttpClient`'s constructor is never executed.

The former doesn't really make sense. The latter should only happen if you're using custom clients, but you're reporting that that's not the case. So this is quite strange 🤔

Can you try removing the manual fix (i.e. not setting `ServicePointManager.SecurityProtocol` yourself) and creating a dummy `SystemNetHttpClient` instance, e.g. like so:

```
var dummyClient = new Stripe.SystemNetHttpClient();
```

and see if that fixes the issue? This way we can narrow the problem down to `SystemNetHttpClient`'s constructor not being executed.

**Comment by ob-stripe** [comment]
Closing this, but feel free to reply if you're still observing the issue and we'll reopen.

**Comment by solidcloudio** [comment]
I'm seeing this same error and fix in Stripe.net 36.0.0.0.  All API Calls fail with Socket forcibly closed...              ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;  Fixes it..

I'm using .NET 4.6.2
