### ISSUE TITLE
Add iin and issuer to 

### ISSUE THREAD

**Issue by ipicitdept** [stripe/stripe-dotnet#1943]
Card.cs  (stripe-dotnet/blob/master/src/Stripe.net/Entities/Cards/Card.cs) has properties for iin and issuer, we need it coded in:

/stripe-dotnet/blob/master/src/Stripe.net/Entities/Charges/ChargePaymentMethodDetails/ChargePaymentMethodDetailsCard.cs

Can we get that in place?

**Comment by remi-stripe** [comment]
@ipicitdept Thanks a lot for the report! This is now fixed and we released 35.3.0 with those changes
