### ISSUE TITLE
Setting a field to null?

### ISSUE THREAD

**Issue by clement911** [stripe/stripe-dotnet#1954]
If I understand correctly, setting an option's property to `null` will cause the field to not be sent over the wire.

If that is the case, how I can actually set a field to a null value (i.e clearing the value).

For example, if I want to clear the customer's phone number.

I can set `CustomerUpdateOptions.Phone` to `null`. But it won't be serialized at all right?

Unless I'm missing something obvious here...

**Comment by remi-stripe** [comment]
@clement911 In the API, if you pass an empty string it will unset the string field.

```
var options2 = new CustomerUpdateOptions {
  Email = "",
  Phone = "",
};
Customer customer2 = service.Update(customer.Id, options2);
```

This would return `email: null` and `phone: null` in the API.

**Comment by clement911** [comment]
What if I want to set an empty string?
What about other types such as numerics and dates and bools?

**Comment by remi-stripe** [comment]
You can't set an empty string in that case, it will just set the field to null already. This is how the API itself works, so it's not really specific to stripe-dotnet.

You can not unset number of booleans with stripe-dotnet though our API rarely supports this in the first place.

**Comment by clement911** [comment]
hmm ok.
Seems like quite a limitation...

**Comment by clement911** [comment]
Although I'm not sure if it's a big deal in practice...

**Comment by remi-stripe** [comment]
In my experience, it's not. Most booleans are set to true or false, we rarely have a null "state". We're also moving more to enums instead to represent the "true/false/unset" state where it matters.

**Comment by clement911** [comment]
Ok, thanks for the quick response.
