### ISSUE TITLE
`Stripe.Capability.RequestedAt` is nullable

### ISSUE THREAD

**Issue by willock-stripe** [stripe/stripe-dotnet#1962]
[Per the OpenAPI spec](https://raw.githubusercontent.com/stripe/openapi/master/openapi/spec3.json), `requested_at` is nullable. However, `stripe-dotnet` [assumes that it's never null](https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Entities/Capabilities/Capability.cs#L52-L57).

This is causing issues for users who are deserialising "un-request capability" events with the SDK:

```
Newtonsoft.Json.JsonSerializationException: Error setting value to 'RequestedAt' on 'Stripe.Capability'. ---> System.NullReferenceException: Object reference not set to an instance of an object.
```

**Comment by remi-stripe** [comment]
Fixed in 35.7.1, thanks for the report @willock-stripe
