### ISSUE TITLE
Invalid Source Type

### ISSUE THREAD

**Issue by bghanchi** [stripe/stripe-dotnet#1967]
Hi, I am trying to create a source of bitcoin type then I got this  "The type `bitcoin` is not a valid source type." not only for bitcoin but also not working for sepa_debit type.

![image](https://user-images.githubusercontent.com/30151850/77645078-21b58100-6f88-11ea-8de1-6b8b74802b93.png)

I am using stripe.net version:- 36.9.0

**Comment by remi-stripe** [comment]
@bghanchi Thanks for reaching out. We do not support bitcoin anymore on Stripe. This was announced in January 2018: https://stripe.com/blog/ending-bitcoin-support

Don't hesitate to reach out to our support team if you have more questions: https://support.stripe.com/contact
