### ISSUE TITLE
Feature request: Get account current API version

### ISSUE THREAD

**Issue by clement911** [stripe/stripe-dotnet#1971]
We need to be programmatically retrieve our account current version.

Why?
What we really want to do is retrieve the version of webhook endpoints that are not pinned to particular version, and which therefore use the account version.
Unfortunately, when we load webhook endpoints, any endpoints that is not pinned to a specific version will have a version set to empty string.

If we could somehow retrieve the account version, we would know that this is the version used by unpinned webhooks.

As far as I know there is no API to get the account version, however, it should be possible for Stripe.Net to make a dummy API call (such as `AccountService.GetSelf`) WITHOUT a `Stripe-Version` header in the request, and then inspect the `Stripe-Version` returned in the response, which should contain the current account version.

Any chance you could add a `Task<string> AccountService.GetVersionAsync()` to the account service that does just that?

**Comment by clement911** [comment]
I'm a bit confused though.
In live mode our unpinned hook returns an empty string version and the version field is blank in the dashboard:

![image](https://user-images.githubusercontent.com/3426504/77921411-0d32fa80-72a0-11ea-8925-d11de5ed5330.png)


But I just tried again in test mode and passed a null version when creating the webhook, but this time the API and the dashboard actually return a version.

![image](https://user-images.githubusercontent.com/3426504/77921530-2c318c80-72a0-11ea-89e0-6a7bbe689821.png)

I know it's unpinned as well because the version changed when I upgraded the account version.

Does the version pinning behaviour differ in Live vs Test mode?

**Comment by remi-stripe** [comment]
@clement911 I don't think we would implement something like this though I will definitely raise this internally. I see what you're describing, but the main reason you're doing this is to understand the API version of your webhook endpoint that are not pinned. The better solution here is to fix the webhook endpoint to instead be pinned by adding a new one with the right version (the same as stripe-dotnet) and deleting the old one.

As for the second question, that's just a quirk of Test mode in that case. We actively discourage anyone using stripe-dotnet (or stripe-java and stripe-go) from using webhook endpoints that are not pinned to the same API version as the library is.

**Comment by clement911** [comment]
We did consider using pinned webhook versions but let me explain why we ended up deciding to use unpinned versions.

First, let me tell you of our very high level architecture. I think it's a pretty standard architecture for wehbook handling. We have 2 components.

1.  The **webhook receiver**.
All it does is listen for the HTTP POST requests coming from Stripe, validates the signature with the configured secret key, persist the event JSON to datastore/queue and return HTTP 200.
We like to keep it extremely simple and we hardly ever update it. It's ok if it has an old-ish version of Stripe.Net because we don't make any API calls and just use Stripe.Net to verify the signature. We want to minimize the down time as much as possible of this component because when webhook delivery fails, Stripe will wait some time (about 30 minutes I believe) before retrying, which can cause a significant lag between the time an event occurs and when it will get processed. We use cloud auto scale capabilities to handle elastic volume (a popular option this days is using serverless function as a service)

2. The **webhook processor**
This component reads from the persisted event queues and processes them. It is a lot more complicated and has a lot of business logic. We deploy / restart this component on a regular basis, which can cause downtime, but this is acceptable because the component will restart quickly and resume event processing from the queue.

Now, I want to contrast the impact of using pinned version webhook VS unpinned/rolling version webhook when we upgrade to a new version of the Stripe API (i.e. we are upgrading our Stripe.Net dependency)

1. Using unpinned version webhooks:
All we have to do is log into our stripe dashboard and upgrade the account's API to match the Stripe.Net version.
That's it.

2. Using pinned version webhooks:
First of all, a new webhook with the new version must be created (since Stripe doesn't let us update the pinned version, more on this below). That's problematic already.
We definitely don't want to go into the Stripe dashboard and add the new webhook manually, because we handle dozens of event types and it's way too manual and error prone to check all the event types manually. You could easily check the wrong type and forgot some types or even make a typo in the webhook url.
That leaves us with the other option, which is to create the webhook with the API. This way the list of events and endpoint url is correct every time and it's automated. It's not trivial though because we must have some protection against creating that new webhook endpoint multiple times (what if the process crashed as it was creating it?), maybe with a global lock, or with a reconciliation process that checks that only a single webhook exist for any given version.
Once it's created, we must also delete the old webhook using the API reliably.
Regardless of how we create the new webhook, the new webhook created gets a generated secret key which is different to the existing webhook endpoint. That's a problem. As soon as we create this new endpoint, our webhook receiver starts receiving events with a signature that it cannot validate. Indeed, we must somehow implement a way to configure the generated secret key into our webhook receiver. We always create the new webhook before deleting the old one so we don't miss any events but this means that some events could be duplicated (one for each version). That's ok but that also means that the webhook receiver need to actually be aware of multiple private keys and verify the signature with the correct key.
That's A LOT more complicated right?

Ideal solution:
The ideal solution would be simple if only the Webhook API let us update the pinned version of our webhook.
All we would need is some code that updates the version of the single webhook that we have. There would be no duplicate events but more importantly the secret key would stay the same.
It's even better than using unpinned version because we wouldn't even need to log into the Stripe dashboard to upgrade the account's API version.
So consider this a feature request. I know it's not related to Stripe.Net specifically, but could you please raise it internally to allow us to update the pinned version via the API?
Neither the API nor the dashboard seem to allow it, which I find strange because it's pretty much what happens already to unpinned hooks when we upgrade the account version.

Sorry for the long response, but I hope it makes sense.
Hopefully you can tell me I'm over complicating this, but we are after a bullet proof solution that can scale.

Any thoughts?

> As for the second question, that's just a quirk of Test mode in that case.

By the way, that kind of quirk is annoying. One of the main benefit of having a Test mode is that we can test our code before pushing to prod. But if Test mode doesn't behave like Prod mode then it pretty much defeats the purpose. I understand that Test mode cannot be exactly like production all the time but in this case I don't see why the pinned version behavior should be any different.

**Comment by remi-stripe** [comment]
Thanks a lot for the long writeup. I definitely understand where you are coming from and we have also discussed this internally extensively in the past. I'm going to reply to specific quotes from your answer hoping it will help clarify why we believe using the API is the best options in this situation.

> All we have to do is log into our stripe dashboard and upgrade the account's API to match the Stripe.Net version.

Let's say we release 2 API versions in quick succession for example over a week. Let's say the first one is a small change in the API you care about and the second one is a bigger one. For example, the second API version could be a large scale change such as [2019-02-19](https://stripe.com/docs/upgrades#2019-02-19) where we redesigned the entire Account API and changed the behaviour of the way statement descriptors work.

In that world, you can't use the Dashboard as we don't let you choose a specific version to upgrade to, it's always the latest. You would be "stuck" in this situation and would have to use the API to create the endpoint.

> First of all, a new webhook with the new version must be created (since Stripe doesn't let us update the pinned version, more on this below). That's problematic already.

We made that decision consciously because of the way statically typed client libraries work. Updating the endpoint is usually the wrong approach for companies that do staged rollouts of their changes.

The idea here is that you have the same endpoint twice, one for each API version associated with both versions of stripe-dotnet you're deploying. This means we send each event twice (one per API version). And then whichever of your client is pulling the event from your queue you can make sure you look at the API version you do actively support.

This ensures that if anything goes wrong with your rollout, you can easily rollback without losing any event over that period. Your database would still be able to retrieve or fetch the event with the correct API version you expect without any downtime.

> It's not trivial though because we must have some protection against creating that new webhook endpoint multiple times (what if the process crashed as it was creating it?), maybe with a global lock, or with a reconciliation process that checks that only a single webhook exist for any given version.

You shouldn't need any of this complexity. You can just use [Idempotent Requests](https://stripe.com/docs/api/idempotent_requests). The idea is that when you create the webhook endpoint, you generate a unique idempotency key, for example URL + API version + stripe-dotnet version (just an example) and then you can always retry the request with the same key and make sure that it won't create a duplicate endpoint again.

> Regardless of how we create the new webhook, the new webhook created gets a generated secret key which is different to the existing webhook endpoint. That's a problem. As soon as we create this new endpoint, our webhook receiver starts receiving events with a signature that it cannot validate.
> We always create the new webhook before deleting the old one so we don't miss any events but this means that some events could be duplicated (one for each version). That's ok but that also means that the webhook receiver need to actually be aware of multiple private keys and verify the signature with the correct key.

That's one of the advantages of our approach. You would have 2 endpoint, one per API version, and your backend should know the webhook secret for each one. That should be something you can automate and don't need to hardcode in your own code.

> The ideal solution would be simple if only the Webhook API let us update the pinned version of our webhook.

Hopefully, some of what I explained above convinced you this is not safe and likely would not work. That's why we block this to discourage developers from trying this approach that we don't think scales safely.

**Comment by clement911** [comment]
Thank you for your quick response as usual.

It does address some of the issues (idempotent request 👍) but unfortunately not the main one, which is the fact that creating a new endpoint generates a new secret key.

I do see where you're coming from, but maybe you made your design choices based on a specific architecture and deployment model that you had in mind, which doesn't match ours. 

It sounds like you might be assuming that the receiving and processing of webhook events lives in a single service deployed as a single unit? Maybe that's why it wasn't possible to validate an event signature without parsing until this [recent PR](https://github.com/stripe/stripe-dotnet/pull/1869).

It seems to me that if you would allow us updating a webhook's pinned version, you would still be able to achieve your deployment model (just don't ever update the pinned version), but it would still allow alternative architectures like ours to actually update the pinned version.

I worked a lot with Shopify webhooks in the past, which was somewhat easier because there is a single secret key for the entire account (as opposed to one per webhook).

Based on the current limitation, I'm thinking that any time we create a new webhook, we'll have to persist the secret key (as opposed to storing it in a config file), and the webhook receiver will have to fetch the relevant secret key whenever it received an event with a version it doesn't have the secret key for yet. A bit more complex, but I think that will work and be fully automated. There is the possibility that our service crashes after creating the webhook but before persisting the secret key though...

**Comment by remi-stripe** [comment]
> It does address some of the issues (idempotent request 👍) but unfortunately not the main one, which is the fact that creating a new endpoint generates a new secret key.

That's fair. I still don't fully grasp why the webhook secret has to be the same. It seems to me that if you create 2 endpoints, then you would get the event twice, one per endpoint (each with its own secret). While you deploy your code for the new version and start sharing the second webhook secret with all your relevant servers, you still know the old one and can keep verifying that version of the event.
Can you clarify what specifically in your architecture requires this? Why can you handle one webhook secret on your servers but not two? 

> Based on the current limitation, I'm thinking that any time we create a new webhook, we'll have to persist the secret key (as opposed to storing it in a config file), and the webhook receiver will have to fetch the relevant secret key whenever it received an event with a version it doesn't have the secret key for yet. A bit more complex, but I think that will work and be fully automated. There is the possibility that our service crashes after creating the webhook but before persisting the secret key though...

This might be the explanation to what I was asking above. If your secret is "hardcoded" in a config file it's definitely going to cause problems. Having it in your database or stored as an environment variable for your server as you spin them up and down based on the version of stripe-dotnet you deploy could work too.

> I worked a lot with Shopify webhooks in the past, which was somewhat easier because there is a single secret key for the entire account (as opposed to one per webhook).

It is something we discussed extensively when designing webhook endpoints and their secrets. It has some downsides though such as making it harder to roll if you think the secret leaked. Our approach allows you to add a new endpoint with a new secret, confirm everything works and then delete the old one for example. We had also discussed the ability to set your secret yourself when you create it via the API. I'll definitely bring this up again internally so thanks a lot for all the feedback and details as usual!

**Comment by clement911** [comment]
> Can you clarify what specifically in your architecture requires this? Why can you handle one webhook secret on your servers but not two?

It's because we like our webhook receiver to be:
- Super simple (just verify and store the event)
- Not needing to ever be updated or restarted (since all it uses Stripe.Net for is the signature check and we expect this logic to hardly ever change, it doesn't need to ever uprade Stripe.Net). This is important so that downtime is very low (because events are postponed for 30 minutes by Stripe when it doesn't get a HTTP 200 response).

Now, we'll have to make it smarter so that it can somehow fetch generated secrets from some datastore. (This receiver is not the one creating the webhook because it never gets updated. It only receives the webhooks.)
It will need to be enhanced so that it is ready to fetch a new secret very quickly as well, because events signed with the new secret will start coming in as soon as the new endpoint is created (by the webhook processor).

> It is something we discussed extensively when designing webhook endpoints and their secrets. It has some downsides though such as making it harder to roll if you think the secret leaked. Our approach allows you to add a new endpoint with a new secret, confirm everything works and then delete the old one for example.

I believe you can achieve that with a global secret as well.
You could allow 2 active global secrets at a time and include a signature for both secrets in the webhook header. Once the code is updated, the user could disable the old secret and Stripe would stop including the signature for that one.



It should be fine, we'll be able to make things work with the current API so feel free to close this ticket. I still wish we could update the pinned version but I understand you cannot accommodate everyone's wishes.

**Comment by remi-stripe** [comment]
> It will need to be enhanced so that it is ready to fetch a new secret very quickly as well, because events signed with the new secret will start coming in as soon as the new endpoint is created (by the webhook processor).

I see your point but that's not exactly true. In a way there is no urgency since you will keep getting the event for the old API version with the old signature and continue processing them as is. So in a way it doesn't affect you immediately. I do agree that it makes that part of your infrastructure more complex though.

> I believe you can achieve that with a global secret as well.
> You could allow 2 active global secrets at a time and include a signature for both secrets in the webhook header. Once the code is updated, the user could disable the old secret and Stripe would stop including the signature for that one.

For sure and we definitely considered this. Webhook signatures have also been live for almost 3 years and having a global secret has rarely been raised but we're definitely looking into alternatives now!

> It should be fine, we'll be able to make things work with the current API so feel free to close this ticket. I still wish we could update the pinned version but I understand you cannot accommodate everyone's wishes.

We definitely appreciate the feedback, especially when it comes with clear context and evidence like you did! We're discussing alternatives internally, both supporting updating the API version and the webhook secret.

I'm going to close this out, but I'll circle back here if we end up making changes to the API to support some of those feature requests!

**Comment by ob-stripe** [comment]
Just wanted to say thank you for taking the time to share such good feedback @clement911, we definitely appreciate it!

**Comment by clement911** [comment]
Avec plaisir 😉
