### ISSUE TITLE
The call is ambiguous between the following methods or properties: 'System.Linq.Queryable.Where(System.Linq.IQueryable, System.Linq.Expressions.Expression<System.Func<TSource, bool>>)' and 'System.Linq.AsyncEnumerable.Where(System.Collections.Generic.IAsyncEnumerable, System.Func<TSource, bool>)'

### ISSUE THREAD

**Issue by pauldbentley** [stripe/stripe-dotnet#1974]
Related to the new release of 35.11.0.

I use Stripe.Net and EntityFrameworkCore in the same project.

Now that Stripe.Net references System.Linq.Async I am getting the following errors when trying to query an EF Core DbSet (which implements IAsyncEnumerable):

The call is ambiguous between the following methods or properties: 'System.Linq.Queryable.Where(System.Linq.IQueryable, System.Linq.Expressions.Expression<System.Func<TSource, bool>>)' and 'System.Linq.AsyncEnumerable.Where(System.Collections.Generic.IAsyncEnumerable, System.Func<TSource, bool>)'

This is because AsyncEnumerable also includes a Where() function.

I have created a Gist here: https://gist.github.com/pauldbentley/7d5e60cd47509a4011d240b55d72b2e8

Is there a way I can tell the compiler not to "see" the reference to System.Linq.Async which is coming from Stripe.Net?

**Comment by Greatsamps** [comment]
I have had this exact issue also. Spent most the morning trying to work out where this had suddenly come from!

**Comment by pauldbentley** [comment]
> I have had this exact issue also. Spent most the morning trying to work out where this had suddenly come from!

I've just rolled back to 35.10.0 for now.

**Comment by Greatsamps** [comment]
> > I have had this exact issue also. Spent most the morning trying to work out where this had suddenly come from!
> 
> I've just rolled back to 35.10.0 for now.

same here, i was like, oh, so it was coming from Stripe.. really did not expect that!

**Comment by ob-stripe** [comment]
Hi everyone, thanks for the report and sorry for the inconvenience. Could you let me know the exact version of EF Core you're using in your projects?

**Comment by pauldbentley** [comment]
> Hi everyone, thanks for the report and sorry for the inconvenience. Could you let me know the exact version of EF Core you're using in your projects?

3.1.3

**Comment by Greatsamps** [comment]
> Hi everyone, thanks for the report and sorry for the inconvenience. Could you let me know the exact version of EF Core you're using in your projects?

3.13

**Comment by ob-stripe** [comment]
Thanks both. We should have a fix incoming shortly.

**Comment by ob-stripe** [comment]
We just released 35.11.1 which should fix this issue (the dependency on `System.Linq.Async` was removed entirely). It will be visible on NuGet shortly.

Please feel free to reply here to report if it works for you or if you're still observing the issue after upgrading.

**Comment by pauldbentley** [comment]
That has resolved the issue - many thanks for the quick turn around on this.

**Comment by ob-stripe** [comment]
No problem, thanks for letting us know that the issue is fixed!
