### ISSUE TITLE
Access to the "Has More" flag when paging

### ISSUE THREAD

**Issue by ghost** [stripe/stripe-dotnet#198]
Can you add the ability to access the "HasMore" flag when retrieving paged data?

**Comment by bounav** [comment]
Hello, hopefully I've just be looking the wrong places but I can't find the `HasMore` info when I'm listing Stripe plans.

Right now I'm doing the following to get all my plans but this will do a extra call that returns nothing to work out that all the plans have been retrieved.

```csharp
var allPlans = new List<StripePlan>();
            
var plans = new StripePlan[0];

do
{
    plans = StripePlanService.List(new StripeListOptions {Limit = 25, StartingAfter = plans.Last()?.Id}).ToArray();

    allPlans.AddRange(plans);
} while (plans.Any());
```

Why not make all the `List` action on the services return `IHasMoreEnumerable` that inherit `IEnumerable` and extends it with an `HasMore` boolean property?

Then the first example would still work, but you could also implement it like this (and it wouldn't do that one extra API call that returns no results)

```csharp
var allPlans = new List<StripePlan>();
            
IHasMoreEnumerable<StripePlan> plans;

do
{
    plans = StripePlanService.List(new StripeListOptions {Limit = 25, StartingAfter = plans?.Last()?.Id});

    allPlans.AddRange(plans);
} while (plans.HasMore);
```
