### ISSUE TITLE
Missing field payment_method.card.generated_from

### ISSUE THREAD

**Issue by clement911** [stripe/stripe-dotnet#1980]
It appears that `payment_method.card.generated_from` is missing although it is documented:

https://stripe.com/docs/api/payment_methods/object#payment_method_object-card-generated_from

Oversight or by design?

**Comment by remi-stripe** [comment]
@clement911 That one is one purpose. It shouldn't be documented publicly and it looks like an oversight, I've flagged internally but you should ignore that field!
