### ISSUE TITLE
[Feature Request] Provide official Xamarin Bindings for iOS/Android

### ISSUE THREAD

**Issue by dansiegel** [stripe/stripe-dotnet#1984]
It's very disappointing as a .NET Developer that this SDK ultimately tries to guide you down the path of providing a web view. Please provide an official Bindings library for Stripe iOS / Android for Xamarin developers

**Comment by remi-stripe** [comment]
@dansiegel Thanks a lot for reaching out. It's definitely something we would like to offer in the future. Both to support Xamarin but also other solutions such as React Native or Flutter. We don't have short term plans to support this right now but we are looking into it! 

Going to tag this one as a future improvement but close for now, I hope it's okay
