### ISSUE TITLE
AmbiguousMatchException from RuntimeInformation.FrameworkDescription

### ISSUE THREAD

**Issue by richardlawley** [stripe/stripe-dotnet#1986]
Since upgrading to v35, I'm getting an error from the StripeClient constructor when running on Windows 2012 R2 Server (under IIS).  This is related to the changes in v35 to enhance the user agent string being reported back to the Stripe servers.

> System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> System.Reflection.AmbiguousMatchException: Multiple custom attributes of the same type found.
>    at System.Attribute.GetCustomAttribute(Assembly element, Type attributeType, Boolean inherit)
>    at System.Runtime.InteropServices.RuntimeInformation.get_FrameworkDescription()
>    at Stripe.Infrastructure.RuntimeInformation.get_IsFullFramework()
>    at Stripe.Infrastructure.RuntimeInformation.GetRuntimeVersion()
>    at Stripe.SystemNetHttpClient.BuildStripeClientUserAgentString()
>    at Stripe.SystemNetHttpClient..ctor(HttpClient httpClient, Int32 maxNetworkRetries, AppInfo appInfo, Boolean enableTelemetry)
>    at Stripe.StripeClient..ctor(String apiKey, String clientId, IHttpClient httpClient, String apiBase, String connectBase, String filesBase)
> .... (my code)

This did not happen from my development machine (Windows 10) nor from a Console app on the same Windows Server 2012.  I eventually tracked this down to https://github.com/microsoft/ApplicationInsights-dotnet-server/issues/241 - I had Application Insights Monitor installed on the server (though was no longer using it).  Removing this prevented the problem.

I appreciate that this problem isn't technically caused by Stripe, but it might be better to trap exceptions when you're building your user agent string for cases where this bug is causing problems.  If you choose not to change anything, at least the explanation & workaround is here for other people.

**Comment by ob-stripe** [comment]
Thanks for the detailed report @richardlawley. I agree that gathering runtime information for the user agent string should not surface exceptions if it fails. We'll fix this in the next version.
