### ISSUE TITLE
Incorrect json mapping for ScheduledQueryRun.Error

### ISSUE THREAD

**Issue by clement911** [stripe/stripe-dotnet#1990]
`ScheduledQueryRun.Error` is mapped to 'error' but is documented as a hash that contains an `message` field.

https://stripe.com/docs/api/sigma/scheduled_queries/object#scheduled_query_run_object-error

**Comment by remi-stripe** [comment]
Oh nice catch. I'm surprised we never saw reports for that one since deserialization would fail whenever you get an error. I'll get it fixed in the branch for the next major version!

**Comment by clement911** [comment]
It might be a good idea to have unit tests that check that JSON deserialization and serialization can round trip to the same JSON string.
