### ISSUE TITLE
ApplicationFee.OriginatingTransaction

### ISSUE THREAD

**Issue by clement911** [stripe/stripe-dotnet#1991]
I'm not sure if it's a problem with the docs or with Stripe.dotnet but the [docs for `ApplicatonFee.OriginatingTransaction`](https://stripe.com/docs/api/application_fees/object#application_fee_object-originating_transaction) says it can expand in either a `Charge` or a `Transfer` but in Stripe.dotnet it can only be expanded into a `Charge`?

**Comment by remi-stripe** [comment]
The docs are not completely wrong, but it's here for legacy reasons. It will stay as just a `Charge` in stripe-dotnet and you can confirm this in stripe-java too [here](https://github.com/stripe/stripe-java/blob/master/src/main/java/com/stripe/model/ApplicationFee.java#L95) as the library is generated automatically from our openapi spec and should always be complete and correct.
