### ISSUE TITLE
Several events missing from Stripe.Events

### ISSUE THREAD

**Issue by clement911** [stripe/stripe-dotnet#1995]
I found the following missing events in `Stripe.Events`.
capability.updated
customer.tax_id.created
customer.tax_id.deleted
customer.tax_id.updated
issuing_settlement.created
issuing_settlement.updated
transfer.failed
transfer.paid

**Comment by clement911** [comment]
And shouldn't these be removed?

`bitcoin.receiver.*`

**Comment by remi-stripe** [comment]
Thanks for the heads up, I'll make sure to add the following one
```
capability.updated
customer.tax_id.created
customer.tax_id.deleted
customer.tax_id.updated
```

`issuing_settlement.created`, `issuing_settlement.updated` are not really missing they just shouldn't be in the openapi spec and we're cleaning this up.

`transfer.failed`, `transfer.paid` those are deprecated and only available on old API versions so they won't be added to stripe-dotnet.

`bitcoin.receiver.*` those are deprecated but still in the public openapi spec so for now they stay in the spec. Removing them is on our list!

**Comment by clement911** [comment]
Got it. Thanks!
