### ISSUE TITLE
Consider an ability to use System.Text.Json instead of Newtonsoft.Json

### ISSUE THREAD

**Issue by ivanstus** [stripe/stripe-dotnet#2008]
I think there should be an ability to use System.Text.Json instead of Newtonsoft.Json. According to MS tests it is faster than Newtonsoft.Json and is a default Json serializer/deserializer for .NET Core apps.

**Comment by remi-stripe** [comment]
@ivanstus thanks for the report! We're tracking this potential improvement in another issue https://github.com/stripe/stripe-dotnet/issues/1979 so I'd recommend following along on that one!
