### ISSUE TITLE
Disposal of resources

### ISSUE THREAD

**Issue by pietersap** [stripe/stripe-dotnet#2009]
Is there a reason why none of the classes are disposable? It looks like StripeClient and SystemNetHttpClient should be disposable, since they contain a member HttpClient (which is disposable). This HttpClient is not disposed, causing a possible memory leak.

If I would use this in ASP.NET dependency injection as a scoped resource, a small amount of memory will be leaked in every request that uses the StripeClient. I would probably inject it as a singleton which will mostly eliminate the memory leakage since the object is only created once, but still...

**Comment by ob-stripe** [comment]
Despite `HttpClient` implementing `IDisposable`, the general consensus is that instances of `HttpClient` should not be disposed. There are many blog posts and StackOverflow answers on this issue, e.g. https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/

The stripe-dotnet library lazily initializes a `StripeClient` the first time a request it's sent, but the instance is kept around as a singleton ([here](https://github.com/stripe/stripe-dotnet/blob/49a813b1a415be6e52bd66d48e86a322a64ab494/src/Stripe.net/Infrastructure/Public/StripeConfiguration.cs#L25)), so you don't need to manage this yourself.

Does this answer your question? Happy to discuss this further if you still have concerns.
