### ISSUE TITLE
Sample for Stripe Checkout with .NET Core

### ISSUE THREAD

**Issue by thinkcodellc** [stripe/stripe-dotnet#2015]
Is there a sample project for Stripe Checkout with .NET core ? 
Thanks in advance.

**Comment by cjavilla-stripe** [comment]
@thinkcodellc we don't have a ton of Stripe Samples with .Net core, but this one is for setting up a Subscription: https://github.com/stripe-samples/set-up-subscriptions/tree/master/server 

We have a starter episode of developer office hours here: https://www.youtube.com/watch?v=2-mMOB8MhmE&list=PLy1nL-pvL2M4N3kfPoZ0igtbMj3K3Jdr_&index=16&t=0s

We'll work on adding more samples, but for now I'm hopeful these will unblock you :)

**Comment by cjavilla-stripe** [comment]
Going to close this for now. Feel free to reach out to support.stripe.com/contact if you run into any issues.
