### ISSUE TITLE
CreditNoteLineOptions Metadata

### ISSUE THREAD

**Issue by clement911** [stripe/stripe-dotnet#2023]
I don't understand why `CreditNoteLineOptions.Metadata` exists given that `CreditNoteLineItem.Metadata` doesn't exist (and is not documented either).

**Comment by clement911** [comment]
I just tested it out and this will actually result in a error if populated:

`Stripe.StripeException: 'Received unknown parameter: lines[0][metadata]'`

**Comment by remi-stripe** [comment]
Thanks for the report. I'll flag the field as deprecated.

**Comment by clement911** [comment]
Sure thing.
