### ISSUE TITLE
Klarna source payments - lack of property: "product"

### ISSUE THREAD

**Issue by Bartosz97** [stripe/stripe-dotnet#2029]
Hi everyone,
I am implementing Klarna source by .NET SDK ver. 36.6.0.0 and I didn't find property: "product" on "SourceKlarnaCreateOptions" class
![image](https://user-images.githubusercontent.com/32617190/81410081-7714ae80-9140-11ea-8e10-187e3abc434d.png).
On documentation: https://stripe.com/docs/sources/klarna
Source was created with property: "product": "payment".
And unfortunately, I can't receive response properties like:  "pay_later_redirect_url".

Thanks for help.

**Comment by remi-stripe** [comment]
Thanks for the report and sorry for the issue here. I've prepared a PR and we will release the fix next week! 

In the meantime you can pass it like this:
```
options.AddExtraParam("klarna[product]", "payment");
```

**Comment by remi-stripe** [comment]
@Bartosz97 This was fixed in 36.10.0
