### ISSUE TITLE
Self Service Portal - Language Support for non-English customers

### ISSUE THREAD

**Issue by deekoulos** [stripe/stripe-dotnet#2034]
Hey Guys,

it would be awesome to have an option for creating a Self Service Portal Session in other languages. Currently the self serve portal is only available in English and therefore is this awesome portal useless for all non-english speaking customers, in our case all german customers.

Is the multi lingual support for the self serve portal already planned in your product roadmap? If yes, until when could we expect this?

Thanks in advance!
Armin

**Comment by remi-stripe** [comment]
@deekoulos Thanks for reaching out! Github issues should be limited to bugs or feature requests with the stripe-dotnet library itself. Since this is a question about the API. I'll flag internally but I'd recommend reaching out to our support team directly to register your interest too: https://support.stripe.com/contact

**Comment by remi-stripe** [comment]
Small update: we just shipped support for a few locales based on your browser and we're working on adding more!

**Comment by deekoulos** [comment]
@remi-stripe thanks for the update! could you please be more specific, what locales and how I can consume the new support? 

thanks!

**Comment by deekoulos** [comment]
Ah great, now I can see that it is also available in German!!!

**Comment by cjavilla-stripe** [comment]
Hey @deekoulos! Just to close the loop here. As of this comment, we support the following locales based on the browser's language preference:

English
German
Spanish
French
Italian
Japanese
Chinese (simplified)

Thanks again!
