### ISSUE TITLE
NuGet 36.12.1 PriceCreateOptions missing Product or PriceProductOptions properties

### ISSUE THREAD

**Issue by chrisofthecoffee** [stripe/stripe-dotnet#2042]
I have just added Stripe.net vsn 36.12.1 from NuGet and was trying to code up adding a price to a product and found the properties Product or PriceProductOptions, as shown in the documentation.

I've checked the code here and they are both there, added 23 days ago with tag v36.12.1 so I'm puzzled why they're not in the 36.12.1 I just got from NuGet (and re-got a couple of times).

I previously tried 36.10.1 and same story but fair enough, they were only just added, so I updated to 36.12.1.

Both properties are shown in code examples in the docs (https://stripe.com/docs/billing/subscriptions/products-and-prices) so I'm not sure if the problem is that the documentation is a bit ahead of the released code, but then again I have 36.12.1 and that's tagged as where they were added... or if I'm just being immensely dim somehow, which is entirely possible.

I asked a in support chat to see if I was missing something obvious but he pointed me at the docs and said the properties should be there.

I can see TiersMode and UnitAmountDecimal and other properties which went in with the same change, so all in all it's a bit puzzling, surely the Product property can't have been somehow mysteriously excluded from the 36.12.1 build or lots of folk's existing code would have screamed about it.

![image](https://user-images.githubusercontent.com/17450109/81883405-bb340300-95c7-11ea-8785-c7aeaa55474e.png)

**Comment by remi-stripe** [comment]
@chrisofthecoffee Thanks for reaching out. It looks like those are marked as internal instead of public for some reason. I'll push a fix soon.

**Comment by chrisofthecoffee** [comment]
Oh gosh yes, you're right, public, public, public... internal.. internal, public... I'm miffed I didn't spot that myself so my post could have been more helpful than plaintive :) 

Thanks !

**Comment by remi-stripe** [comment]
All good I'm really glad you caught this and I'm sorry for the churn. The good thing is that we're working internally on generating stripe-dotnet automatically from our openapi spec so that mistakes like this can't happen in the future :)

**Comment by chrisofthecoffee** [comment]
Glad to have helped, nice easy fix ! - I'll get a coffee and keep an eye out for the change, will this plonk a 36.12.2 on NuGet ? Ta again, I'm over in Indonesia so wasn't sure if anyone there would be awake, wherever 'there' might be.

**Comment by remi-stripe** [comment]
I just released this as 36.12.2 so you should now be all set once it's available on NuGet

**Comment by chrisofthecoffee** [comment]
Great thanks, I cloned your update and linked from there for now but will Nuget the update later today, super fast response, cheers again

**Comment by chrisofthecoffee** [comment]
Just to confirm, I gotted 36.12.2 from NuGet and all good.
