### ISSUE TITLE
Business case

### ISSUE THREAD

**Issue by bobingham** [stripe/stripe-dotnet#2059]
This repository seems to float along of its own accord.  Is it possible to group some of these releases into business cases?  Thus:
#37.5.0 - _Add support for ProductData on SessionLineItemPriceDataOptions_
#37.6.0 - _Add support for BACS Debit as a PaymentMethod_
These appear to be critical issues for me but I have no idea how to use them or what the implications are.
I mean, if I include 'BACS' as a payment method where do the input for sort code and account number go?  Just how do I implement this?
I now have _ProductData on SessionLineItemPriceDataOptions_ - great.  But what does that actually do?
What are the business reasons and where are the instructions for use?
As it is we just have a whole series of releases the reasons for which are entirely unclear and we have no idea where to pick up the business reasons for inclusion or the documentation to support implementation.
These changes may be great in the developers head but without knowing what is in the developer's head they're a bit pointless for the rest of us....

**Comment by remi-stripe** [comment]
@bobingham Thanks a lot for the feedback and I do see how this could be confusing. The changelog is really seen as a way to see what new features are added. This makes it easier to know where to upgrade when you want one of those features or what changes happened in past major versions.

Usually, we recommend using our Docs directly instead to understand the features you want to work with. 

For example, the first one is the addition of `product_data` in the API for Checkout Session's line items. This is in the API reference here: https://stripe.com/docs/api/checkout/sessions/create#create_checkout_session-line_items-price_data-product_data and this feature lets you create Price and Product inline when creating a Checkout Session.

As for the second one, this is a new feature that is going be be released publicly next week. It will let you accept BACS Debit payment which is bank account direct debit in the UK. The docs are not public yet but we always try to get our client libraries to support new features ahead of time.

Does that make sense?

**Comment by bobingham** [comment]
@remi-stripe  - thanks,.  That makes perfect sense.  I have been struggling for a while with creating subscriptions through `CheckoutSession`, with a setup cost and then a tiered plan the quantity for which will only be known at the end of the period end.  The addition of `product_data`  may go someway towards this.
As for BACS, that is a welcome arrival and I will wait for the announcement of functionality.  How do I go about subscribing to documentation change for this functionality and will I be able to implement it through a checkout session?
And whilst I have your attention, there is no way for a customer to modify customer data (billing address, email, legal name etc) through the self-service portal.  I thought this would have been one of the first items to be added?  Or should I add a new issue - where would I do that?

**Comment by remi-stripe** [comment]
> As for BACS, that is a welcome arrival and I will wait for the announcement of functionality. How do I go about subscribing to documentation change for this functionality and will I be able to implement it through a checkout session?

We don't really have a good mechanism for this today unfortunately though we're working on improving the situation. And yes that will work on Checkout too!

> And whilst I have your attention, there is no way for a customer to modify customer data (billing address, email, legal name etc) through the self-service portal. I thought this would have been one of the first items to be added? Or should I add a new issue - where would I do that? Will the customer be able to change payment method from card to BACS through the self-serve portal?

The Self-serve portal is brand new and only shipped recently. We focused on two core features that were requested constantly which was the ability to change your subscription's prices and the ability to view past invoices. More features will happen over time. I'd recommend talking to our support team directly for things like this as Github should be limited to bugs with the library itself. Our support team can collect feature requests and surface those to the right product teams internally and you can contact them here: https://support.stripe.com/contact

Going to close this out but I'll talk to my team about maybe make the changelog a bit clearer around why features are added instead of just what is being added.
