### ISSUE TITLE
Accept payments on client dotnet applications using payment intent

### ISSUE THREAD

**Issue by DamienDoumer** [stripe/stripe-dotnet#2067]
This is kind of a feature request and a question at the same time. And, I don't have an extensive knowledge of how payment processes occur so I might be requesting something which has not been implemented cause it might cause security issues.

Integrating stripe on mobile apps using Xamarin requires mobile bindings to the stripe android and iOS SDKs. The native versions handle 3Dsecure and accepting cards. But Most of the existing binding packages for Xamarin are outdated. Building native Xamarin bindings for each new versions of Stripe is not easy at all, I've tried it. 
So, could this package help in the processes of accepting payments using payment intent 3dsecure ?  This will make it easier to integrate  native applications too.  This is what I mean by accepting payments: https://stripe.com/docs/payments/accept-a-payment

**Comment by remi-stripe** [comment]
@DamienDoumer Thanks for reaching out! At the moment we do not support Xamarin unfortunately. I know some developers have been able to use stripe-dotnet and have it build for Xamarin but I don't think it was really straightforward. Also, the library is built for the server-side parts of your code and doesn't offer specific UIs for 3DS like the mobile SDKS do.

Our advice in your case is to use a Webview instead. In your mobile app, open a Webview and load your website view instead based on Elements. This will ensure that you handle 3D Secure and payments properly without any added complexity. You could also simply default to Checkout to make things a lot easier and let us handle the payment part: https://stripe.com/docs/payments/checkout

**Comment by dalton5** [comment]
Hi Damien. I created a medium article which provides a solution. It works great for me: https://alexismeilland.medium.com/how-to-manage-stripe-payments-between-a-connected-account-and-a-customer-with-xamarin-forms-470f04e1be7
