### ISSUE TITLE
BalanceService.Get() does not contain Issuing Pending an Available Balances

### ISSUE THREAD

**Issue by sobelito** [stripe/stripe-dotnet#2071]
I am consuming the issuing (still beta?) and the web console and CLI return properties that are not represented in the .NET SDK, ie "issuing.available, and issuing.pendng". These values are not rolled into aggregate balance available and pending.

Example:
```
C:\Users\admin>curl https://api.stripe.com/v1/balance -u sk_live_XXXXXXXX:
{
  "object": "balance",
  "available": [
    {
      "amount": 0,
      "currency": "usd",
      "source_types": {
        "card": 0
      }
    }
  ],
  "issuing": {
    "available": [
      {
        "amount": 123456,
        "currency": "usd"
      }
    ],
    "pending": [
      {
        "amount": 0,
        "currency": "usd"
      }
    ]
  },
  "livemode": true,
  "pending": [
    {
      "amount": 0,
      "currency": "usd",
      "source_types": {
        "card": 0
      }
    }
  ]
}
```

Running .NET Core 3.1.
```
#region Assembly Stripe.net, Version=34.17.0.0, Culture=neutral, PublicKeyToken=null
// C:\Users\admin\.nuget\packages\stripe.net\34.17.0\lib\netstandard2.0\Stripe.net.dll
#endregion

using Newtonsoft.Json;
using Stripe;
using System.Collections.Generic;

namespace Stripe {
  public class Balance : StripeEntity<Balance>, IHasObject {
    public Balance();

    [JsonProperty("object")]
    public string Object { get; set; }
    [JsonProperty("available")]
    public List<BalanceAmount> Available { get; set; }
    [JsonProperty("connect_reserved")]
    public List<BalanceAmount> ConnectReserved { get; set; }
    [JsonProperty("livemode")]
    public bool Livemode { get; set; }
    [JsonProperty("pending")]
    public List<BalanceAmount> Pending { get; set; }
  }
}
```

**Comment by remi-stripe** [comment]
@sobelito The Issuing balance was added in stripe-dotnet 36.8.0 as you can see on the [changelog](https://github.com/stripe/stripe-dotnet/blob/master/CHANGELOG.md#3680---2020-05-01). You're on an older version which is why you don't see it. You need to upgrade your version of stripe-dotnet.

**Comment by sobelito** [comment]
Thank you for the quick feedback and reference to the change log @remi-stripe - my bad on not updating the package.  Was just looking at the BalanceDetails in the commit and I see it has the issuing.available property (the one of more pressing interest for me) but am I correct that it doesn't at the moment support the issuing.pending property? Will have another look.

**Comment by remi-stripe** [comment]
There should not be pending balance for Issuing today. There's only `available` as you can see in the docs: https://stripe.com/docs/api/balance/balance_object#balance_object-issuing-available

I think you have `pending` in the response for legacy reasons, likely because you were part of the Issuing beta but you can just ignore it it will always be 0.
