### ISSUE TITLE
Incorrect field description

### ISSUE THREAD

**Issue by NoahStahl** [stripe/stripe-dotnet#2089]
Minor: I noticed an incorrect description for the InvoiceItem field here:

https://github.com/stripe/stripe-dotnet/blob/b39f51a5167ded6c094c5dff9f2a6a3d219aa77c/src/Stripe.net/Services/Invoices/InvoiceUpcomingInvoiceItemOptions.cs#L37

I believe it should correspond to:

https://stripe.com/docs/api/invoices/upcoming_invoice_lines#upcoming_invoice_lines-invoice_items-invoiceitem

**Comment by remi-stripe** [comment]
@NoahStahl Thanks for the report! Would you be interested in doing the PR to fix this and potentially other issues you find? If not, just let me know and I'll get this fixed tomorrow!

**Comment by NoahStahl** [comment]
Hi @remi-stripe, I'm devoting all time to my current project (with Stripe integration :)). Thanks for fixing, no rush!

**Comment by remi-stripe** [comment]
@NoahStahl I just pushed a fix to master. It will go in our next release!
