### ISSUE TITLE
Stripe .NET documentation missing

### ISSUE THREAD

**Issue by dletozeun** [stripe/stripe-dotnet#2093]
Hello,

The documentation link in the README is broken https://stripe.com/docs/api?lang=dotnet

Where is the .NET API documentation ?

Many thanks.

**Comment by paulasjes-stripe** [comment]
HI there, I'm not sure what you mean by "broken" as that link works correctly for me. You should see .NET examples on the right in the api reference, for example: https://stripe.com/docs/api/payment_intents/create?lang=dotnet

This is for bugs and issues with the stripe-dotnet repo specifically, so if you are still having problems seeing the .NET API reference please reach out to Stripe support: https://support.stripe.com/contact

**Comment by dletozeun** [comment]
Hello,

My bad, I did not scroll enough to see the C# examples and with the url redirect I too quickly thought I was back on the REST API. Thanks!
