### ISSUE TITLE
BalanceTransactionCreateOptions is missing

### ISSUE THREAD

**Issue by ozonni** [stripe/stripe-dotnet#2122]
https://stripe.com/docs/api/customer_balance_transactions/create?lang=dotnet

![image](https://user-images.githubusercontent.com/25206121/87958123-6faf4100-cab1-11ea-9025-c4cc18fd6aa4.png)

But there is no `BalanceTransactionCreateOptions` type as well as `BalanceTransactionService` doesn't have `Create` method

**Comment by remi-stripe** [comment]
@ozonni The API reference is incorrect in that case unfortunately but I'll make sure to get it fixed. You want the `CustomerBalanceTransactionService` instead.
