### ISSUE TITLE
validate=false?

### ISSUE THREAD

**Issue by winzig** [stripe/stripe-dotnet#213]
We are migrating customers over to Stripe and are running into issues where Stripe won't allow us to add the customer if the card is currently being declined. We would prefer they allow all customers in, and then the normal Stripe billing routines will proceed the next time the person is due to be billed (at trial_end), and THEN if the card is declined, it will generate the web hooks our system is designed to deal with, handling the declines at that point.

After talking to Stripe support, I got a response that this is possible, I just need to pass "validate=false". The response was pretty vague, but it sounds like either on the customer options or maybe the card options, there should be a way to turn off validation. I didn't see anything like this available in Stripe.net, so I'm guessing it's not implemented? Is there any mechanism available to pass additional parameters with a request, or would I need to add this functionality into Stripe.net as a proper property?

So far I have not even been able to find this validate property mentioned in Stripe's docs, so it may be a hidden feature?

**Comment by jgoodale** [comment]
I had the same issue and forking the code worked perfectly, thank you.
