### ISSUE TITLE
You did not provide an API key. You need to provide your API key in the Authorization header, using Bearer auth

### ISSUE THREAD

**Issue by mexner** [stripe/stripe-dotnet#214]
Deleting a Plan, using my secret key, this works great.

However, using the same code base, when attempting to delete a plan, using an access_token from Stripe Connect, I receive this error.

You did not provide an API key. You need to provide your API key in the Authorization header, using Bearer auth (e.g. 'Authorization: Bearer YOUR_SECRET_KEY'). See https://stripe.com/docs/api#authentication for details, or we can help at https://support.stripe.com/.

Any thoughts on what could be wrong?

var planSrvc = new StripePlanService(_apiKey);  //access_token for StripeConnect
planSrvc.Delete("Plan A");  //ID of plan @stripe

**Comment by Ayan-Ali** [comment]
if you are using an environment variable or something to put your secret stripe key in your server,  Try adding it directly in the code as a string or something 

`const stripe = new Stripe(YOUR_SECRET_KEY);`

**Comment by higherstates** [comment]
> 
@Ayan-Ali This doesn't work without `process.env`. It says `STRIPE_KEY is not defined`

**Comment by codmitu** [comment]
ty Ayan-Ali, make sure to call dotenv first 😅
```
require('dotenv').config({ path: './.env' })
const stripe = require('stripe')(process.env.STRIPE_SECRET_KEY)
```

**Comment by anupvrj** [comment]
> if you are using an environment variable or something to put your secret stripe key in your server, Try adding it directly in the code as a string or something
> 
> `const stripe = new Stripe(YOUR_SECRET_KEY);`

It worked for me.

**Comment by andreisucman** [comment]
> 

Jus switch the places of dotenv and stripe lines and you can use env variables.

Like so: 

```
require("dotenv").config();
const stripe = require("stripe")(process.env.STRIPE_SECRET_KEY);
```
