### ISSUE TITLE
No customer ID on ChargeCreateOptions

### ISSUE THREAD

**Issue by comtsamsmith** [stripe/stripe-dotnet#2147]
Hi,

So I'm trying to create, or update an existing customer, and then pass that info to the:
**stripeCharge = chargeService.Create(chargeOption, RequestOptions)**

So I can do a charge at a later date.But the:

 Dim chargeOption = New ChargeCreateOptions With {
        .Amount = 100,
        .Currency = "USD",
        .Description = "Buying " & Now(),
        .ReceiptEmail = "samsmith@coxxxmtxuxxxxnts.cxxxom",
        .Metadata = Metadata    

**.customer=MyCustomerID**   Missing????
    
      } '     

Does not seem to have a Property for Customer, to pass the customer ID which it should do according to the Stripe documentation.  Surly this object should reflect the same properties?  Or am I missing something?

**Comment by cjavilla-stripe** [comment]
Should be capital C Customer. Try:

```
Dim chargeOption = New ChargeCreateOptions With {
  .Amount = 100,
  .Currency = "USD",
  .Description = "Buying " & Now(),
  .ReceiptEmail = "samsmith@coxxxmtxuxxxxnts.cxxxom",
  .Metadata = Metadata,
  .Customer=MyCustomerID,
}
```

**Comment by comtsamsmith** [comment]
Christ, I must be losing the plot.  Thanks.
