### ISSUE TITLE
stripe 'Public member 'Delete' on type 'SubscriptionService' not found.'

### ISSUE THREAD

**Issue by Jacobus75** [stripe/stripe-dotnet#2161]
Hi There

Please check when I try and Delete subscription I get this error. "stripe 'Public member 'Delete' on type 'SubscriptionService' not found.'"

I double checked and my code seems correct as per stripe api cancel subscription example

Thanks
Cobus

**Comment by remi-stripe** [comment]
@Jacobus75 Thanks for reaching out! The method is called `Cancel` and not `Delete`. The API Reference is incorrect so I'll get that fixed but if you call the Cancel method you should be unblocked

**Comment by Jacobus75** [comment]
Thanks for your quick response. 
I changed to the following as per your recommendation:
  var service = new Stripe.SubscriptionService();
    service.Cancel(subscriptionId);

It gets blocked

Please let me know

Thanks

**Comment by Jacobus75** [comment]
Hi There

 

Thanks for your quick response. I see the request is closed so I mail rather.
I changed to the following as per your recommendation:
var service = new Stripe.SubscriptionService();
service.Cancel(subscriptionId);

It gets blocked

Please let me know

Thanks

Cobus

**Comment by remi-stripe** [comment]
@Jacobus75 I'm sorry but I need more information than "it gets blocked". What is the problem you are encountering exactly, what is the error you get back?

**Comment by Jacobus75** [comment]
Hi Remi

 

Herewith the Exception:

 

System.MissingMemberException: 'Overload resolution failed because no accessible 'Cancel' accepts this number of arguments.'

 

 

Hope this helps

 

Thanks

**Comment by remi-stripe** [comment]
@Jacobus75 The error indicates that there's a cancel method but it expects another argument, you just need to do `server.Cancel('sub_123', null);` if you don't want to pass an argument to the method.

I'd recommend chatting with our support team directly if you have any follow up questions about this as it's not really an issue with the library. You can contact them here: https://support.stripe.com/contact
