### ISSUE TITLE
CustomerCreateOptions missing TrialFromPlan option for creating an initial subscription

### ISSUE THREAD

**Issue by bronthulke** [stripe/stripe-dotnet#2180]
When creating a new customer and immediately putting them on a subscription, I have always called it like this:

```
var customer = await _stripeCustomerService.CreateAsync(new Stripe.CustomerCreateOptions
{
    Email = email,
    Description = description,
    Source = stripeToken,
    Plan = selectedPackagePlan.PaymentGatewayPlanId,
    Quantity = newQuantity,
    TaxPercent = selectedPackagePlan.TaxPercent
});
```

I now have Stripe subscription products with trials on them in Stripe, so want to add the TrialFromPlan flag to the options the same way as I can for `SubscriptionCreateOptions`, but that appears to be missing.

### WORKAROUND:
I have worked around it for now by doing the CustomerCreate without any subscription info, and then doing a SubscriptionCreate after.

### DESIRED OUTCOME:
It would be nice to be able to just pass through the TrialFromPlan flag via the Customer Create calll, to avoid having to two this in two parts.

### INFO:
OS Version: Windows 10
.NET Version: 4.7.2
Stripe.net Library Version: 37.20.0

**Comment by cjavilla-stripe** [comment]
Hey @bronthulke!

Thanks for the feedback :) Creating the customer with a plan is actually a legacy pattern that we recommend against using. Instead, the path you've taken is the correct and recommended route by creating a Customer then separately creating a Subscription. 

Cheers!

**Comment by bronthulke** [comment]
Fantastic thanks!
