### ISSUE TITLE
Update ApiVersion to 2020-08-27

### ISSUE THREAD

**Issue by TCBroad** [stripe/stripe-dotnet#2188]
The API version still refers to 2020-03-02 in the most recent release. You cannot create webhooks with this version anymore so the library throws errors until this is rectified, or you ignore versions.

**Comment by remi-stripe** [comment]
@TCBroad thanks for reaching out and sorry about the delay! We're working on the change for stripe-dotnet but it is bundled with a lot of cleanup and other breaking changes so it's a bit delayed. We're planning to release it today hopefully!

In the meantime, we recommend that you always create Webhook Endpoints by explicitly setting `api_version` to the same version that the library is pinned to. So if you are on the latest stripe-dotnet you would create an endpoint with `ApiVersion = '2020-03-02'` and then you could deserialize them. 

Once 38.0.0 is released you will be able to upgrade and create a new endpoint with the API version `2020-08-27`.

I'll update this issue once 38.0.0 is available!

**Comment by remi-stripe** [comment]
@TCBroad So we aligned and the version is ready but we will defer the merge to next Monday. It's a pretty substantial rewrite, leading to a major version and we think it's a lot safer for all users if the version goes out on Monday instead.

**Comment by TCBroad** [comment]
Hi, thanks for updating this issue - it's understandable there's no release if it's a big change. I figured they'd both be out together as it was released on the date of the API version change so assumed it had just been missed out.

I feel it might be good to allow users to create webhooks (via the web UI) that target the latest +1 versions just for when there's a mismatch in versioning again. I appreciate you can create webhooks via the API but it's a bit more messing around if you're prototyping something, or didn't know about it.

I'll check back in the week for a new dll, and work on the older API version in the meantime.

Cheers!

**Comment by ptyang** [comment]
Is this still expected to be updated today?

**Comment by remi-stripe** [comment]
@ptyang Yes it should go out in a few hours!

**Comment by remi-stripe** [comment]
Hello everyone! We just released v39.1.0 which should have all the changes required for the latest API version. Since v38.0.0 introduced a lot of breaking changes, we wrote a detailed migration guide here: https://github.com/stripe/stripe-dotnet/wiki/Migration-guide-for-the-upcoming-v38

We had to do a quick fast follow with v39.0.0 because we missed some other breaking changes that were introduced so if you use the latest (39.1.0) you should now be all set!

**Comment by ptyang** [comment]
Great work on the updated release and getting it out quickly. How long to expect before the updated NuGet package goes up?

**Comment by remi-stripe** [comment]
It can take a few hours for Nuget to reflect those builds. I'll keep monitoring!

**Comment by remi-stripe** [comment]
Hey everyone! We encountered some issues due to a change in dotnet version on Appveyor causing one of the release steps to fail. We'll work on the correct release tomorrow morning, sorry for the extra delay here.

**Comment by remi-stripe** [comment]
We just fixed the release issue and we now have 39.1.2 that is merged and available on NuGet. I've been able to install and test that version across a few endpoints so it seems that we are now all set.

Really sorry about the extra unexpected delay on that one but you should all be able to upgrade to 39.1.2 and get the new API version and new features.
