### ISSUE TITLE
Why do you specify userAgent in request?

### ISSUE THREAD

**Issue by MSIH** [stripe/stripe-dotnet#219]
I noticed that the following UserAgent info is being passed on all request to Stripe.

request.UserAgent = "Stripe.net (https://github.com/jaymedavis/stripe.net)";

Is this required?
Should this be customizable?

**Comment by AlfieDarko** [comment]
Just wondering, is this still the default UserAgent string?

**Comment by jaymedavis** [comment]
No - it now contains the version information, and some metadata about your environment. See the Client.cs source to review everything.
