### ISSUE TITLE
Code breaking after upgrading to latest nuget package. Missing type or namespace

### ISSUE THREAD

**Issue by davitgr** [stripe/stripe-dotnet#2196]
After upgrading to 39.1.2, I am unable to create credit card and bank account tokens because CreditCardOptions and BankAccountOptions are not found. The error says type or namespace name 'CreditCardOptions' cannot be found. These are samples of what I am trying to do:

```
var options = new TokenCreateOptions
            {
                Card = new CreditCardOptions
                {
                    Number = "*****",
                    ExpYear = 2025,
                    ExpMonth = 12,
                    Cvc = 123,
                    AddressCity = "#####",
                    AddressState = "MA",
                    AddressCountry = "US",
                    AddressLine1 = "####",
                    AddressZip = "02478"
                }
            };
```

```
 var options = new TokenCreateOptions
            {
                BankAccount = new BankAccountOptions
                {
                    Country = "US",
                    Currency = "USD",
                    AccountHolderName = "name",
                    AccountHolderType = "",
                    RoutingNumber = "*****",
                    AccountNumber = "*****"
                }
            };
```

Is there a change that needs to be made for this to work or is something broken?

**Comment by remi-stripe** [comment]
@davitgr Thanks for writing in. 38.0.0 and 39.0.0 were large major versions with a lot of breaking changes. We've documented each one of them in the wiki here: https://github.com/stripe/stripe-dotnet/wiki/Migration-guide-for-v38-and-v39

You want do use `BankAccountOptions` and `CreditCardOptions` instead.

We're also working on updating our API Reference for this, cc @cjavilla-stripe

**Comment by davitgr** [comment]
That's what I am using now as I mentioned in my original post. Should I be
using TokenCardOptions and TokenBankAccountOptions?

**Comment by remi-stripe** [comment]
@davitgr I saw you closed the issue, did you figure out the problem in the end?

**Comment by davitgr** [comment]
I did. The document you sent was very helpful.
