### ISSUE TITLE
Missing required param: interval. 

### ISSUE THREAD

**Issue by AEDesigns** [stripe/stripe-dotnet#2200]
I have been getting this error all day and I can't figure out why. I'm using the latest versions of wordpress and learndash and I've gone through setting up webhooks.

**Comment by cjavilla-stripe** [comment]
Hey @AEDesigns is this with stripe-php for wordpress? This repository is for stripe-dotnet which I don't believe runs on wordpress. Your best bet is likely to reach out to support: support.stripe.com/contact or chat with us on IRC in the freenode network in the #stripe channel.
