### ISSUE TITLE
Missing required param: charge when trying to create refund

### ISSUE THREAD

**Issue by xllx1** [stripe/stripe-dotnet#2202]
Hi, I am trying to create a refund using the payment intent id according to the [document](https://stripe.com/docs/refunds#api), following the example given:
```cshtml
var refunds = new RefundService();
var refundOptions = new RefundCreateOptions {
  PaymentIntent = "pi_xxxxxxxxxxxx"
};
var refund = refunds.Create(refundOptions);
```

But I got an error saying `Missing required param: charge.`

I have tried to create a refund using `Charge`, it works as expected. From my understanding from the document, we can use create a refund from either payment intent or charge. However I have been using the payment intent api all along, and I believe using payment intent to create a refund is right way to do so.

**Comment by remi-stripe** [comment]
@xllx1 This code should just work. Are you sure you're hardcoding a payment intent id in that variable? My guess is that the variable you use might be null or empty and causing the API to not receive anything.
Unfortunately it's tricky to debug without more details such as an example request. You should be able to look at the logs in your Dashboard (under Developers) and find that failed request to confirm the parameters you are sending.

**Comment by xllx1** [comment]
Yes you are right, the variable that holds the payment intent id is empty, I messed up the post request and am confused on the error message when creating a refund. Thanks for your help!
