### ISSUE TITLE
InvoiceItemPeriod.Start and InvoiceItemPeriod.End should be DateTime

### ISSUE THREAD

**Issue by clement911** [stripe/stripe-dotnet#2218]
Why were InvoiceItemPeriod.Start/End turned into long?

**Comment by clement911** [comment]
And InvoiceLine.Start/End as well

**Comment by dgvives** [comment]
Just ran into the same, had to use a workaround. Would be nice to have them as DateTime
```
DateTimeOffset.FromUnixTimeSeconds(invoiceLineItem.Period.End).DateTime
```

**Comment by remi-stripe** [comment]
Changing the type is a breaking change so we've cued it up for the next major to avoid making a breaking change for just this small change since it's been like this for a while already. We haven't forgotten though and hopefully one will go out in the next few weeks.

**Comment by winzig** [comment]
@remi-stripe Is there any more info on this change? I'm trying to "catch up" our use of the SDK to the latest, and running into a lot of instances where nullable DateTime's are now long. I've found this PR that I think caused this, but I don't see any comments in the PR or in the release notes that explain the logic: https://github.com/stripe/stripe-dotnet/pull/2165/files

**Comment by winzig** [comment]
Also noticed a lot of nullable DateTime's turning into non-nullable DateTimes, and was having trouble tracking down the reason for that change, or what happens in scenarios where in the past it would have been null, but is no longer possible?

**Comment by remi-stripe** [comment]
@winzig no update just yet. We haven't done a major version in over a year and we try to avoid "cosmetic" major versions as much as we can, especially after having done some serious rework of the infrastructure/naming scheme in 2019 and 2020. It's still slotted and we would try to bundle this change in the next major as it happens, which is often tied to Stripe releasing a new API version as that requires a major version on stripe-dotnet. Sorry for the delay!

**Comment by winzig** [comment]
@remi-stripe It's fine that there's not an update, but is there any information about these changes that I could use to answer the above queries? 😬

**Comment by remi-stripe** [comment]
Sorry I didn't realize you had a question there. Yes, since the property is not nullable anymore in the library, it means it can't be null and should always be set.

**Comment by kerams** [comment]
Is there a reason all of these fields are `DateTime` and not `DateTimeOffset`? Is it something that could be changed in the next major version?

I feel more comfortable using the latter since I don't have to care what kind of `DateTime` the underlying library is giving me (UTC or local). Moreover, plenty of APIs seem to not take `Kind` into account, which is a potential source of bugs and headaches. With `DateTimeOffset` and the baked-in offset these pitfalls go away.

**Comment by remi-stripe** [comment]
@kerams I don't think we use `DateTimeOffset` anywhere in the library right now for properties or params and all the dates are Unix timestamps and always UTC based. I don't think we'd change this any time soon as I don't remember anyone preferring this before. @clement911 I'm curious what your take is on that one as core user of stripe-dotnet for a while now?

**Comment by winzig** [comment]
On a green field project 4 years ago we chose to go solely with DateTimeOffset and never regretted it. It would be a natural fit for Stripe's library given that you are 100% UTC-based. 

From [Microsoft's page on date formats](https://docs.microsoft.com/en-us/dotnet/standard/datetime/choosing-between-datetime):

![image](https://user-images.githubusercontent.com/127062/184505305-7a719098-3d75-4718-85fd-475f7c2452b3.jpeg)

**Comment by clement911** [comment]
I don't feel very strongly either way. 

I'm OK with using DateTime because the API uses UTC everywhere.
Using DateTimeOffset might give the impression that the Stripe API can use different time zones, but in reality the API only deals with UTC both on the read side and write side (AFAIK).

For example, imagine that you want to update an invoice's DueDate.
Even if you pass a non UTC value, Stripe.NET would convert to UTC, and the API would return a UTC value. Is that ok or is that unintuitive?
