### ISSUE TITLE
ReportTypeService List fails if given parameters

### ISSUE THREAD

**Issue by clement911** [stripe/stripe-dotnet#2227]
When using `ReportTypeService.ListAsync`, passing a `Limit` parameter fails.
Indeed, the docs documents 0 parameter.

**Comment by clement911** [comment]
I see.
I'd much from that you keep generic objects such as `IListable` and `ListOptions` because we use them heavily to write generic code that works with multiple services.
It's not really a big deal to be honest that the `ReportTypeService` fails there. I'll close.

**Comment by remi-stripe** [comment]
I think we could still do this and just have `ListOptions` be empty really but keep it as an interface if that makes sense. Or I could push internally so that every List API supports pagination (which I thought it did so I think this one is special and should be fixed :p)

**Comment by clement911** [comment]
An empty interface wouldn't work for us as we actually use the members of the interface...
So, personally, I'd prefer the second option to push every List API to support pagination.
But again, we can live with the current state of things...

**Comment by mbroshi-stripe** [comment]
👋 Hi @clement911! This was a very old issue, but I just wanted to point out that we at last put in a permanent fix where `ReportTypeService` no longer extends `ListOptions` in the [v48.0.0 release](https://github.com/stripe/stripe-dotnet/releases/tag/v48.0.0).
