### ISSUE TITLE
When I using Stripe.net in my plugin I face this exception

### ISSUE THREAD

**Issue by BalsamIbrahim** [stripe/stripe-dotnet#2234]
Could not load file or assembly 'Stripe.net, Version=39.19.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
can you please help me in this problem
I use stripe.net in class library project to create my plugin c#

**Comment by remi-stripe** [comment]
@BalsamIbrahim At the moment, the stripe-dotnet library does not support this feature unfortunately and we don't use a "strongly-named assembly". You likely would have to sign the library yourself if your pipeline requires it following something like this guide: https://brutaldev.com/post/net-assembly-strong-name-signer
