### ISSUE TITLE
Could not load file or assembly 

### ISSUE THREAD

**Issue by BalsamIbrahim** [stripe/stripe-dotnet#2235]
can you help me in this problem 
![Screenshot (111)](https://user-images.githubusercontent.com/34779906/97501661-548a8200-197a-11eb-86ff-51a1b63a9ee6.png)

System.IO.FileLoadException: 'Could not load file or assembly 'Stripe.net, Version=35.3.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)'

**Comment by remi-stripe** [comment]
@BalsamIbrahim this seems like the same question you opened before which I've answered here: https://github.com/stripe/stripe-dotnet/issues/2234

I'm going to close this out again, I hope it's okay. It's unfortunately something we just do not support at the moment.
