### ISSUE TITLE
ACH Payments

### ISSUE THREAD

**Issue by jmawebtech** [stripe/stripe-dotnet#2242]
Hi,

I have an ACH payment that was made on 10/4, but my query fails to return it. Does this SDK support ACH payments? I emailed Stripe support and they were unsure how to resolve the issue. Do I need a parameter? Am I using the wrong endpoint?

https://api.stripe.com/v1/charges?created[gte]=1601784000&created[lte]=1601870340&limit=100&expand[0]=data.invoice&expand[1]=data.customer&expand[2]=data.source 

![ach](https://user-images.githubusercontent.com/1679993/98114780-c465a480-1e73-11eb-8f1d-786ea0165d7c.png)

**Comment by remi-stripe** [comment]
@jmawebtech Yes stripe-dotnet supports ACH payments and has for multiple years. This is unlikely to be a bug with the library itself and more likely to be due to the way you filter charges. Would you be able to share more specific code that you are using exactly and exact information is missing?

**Comment by jmawebtech** [comment]
`        public List<Order> SearchOrders(DateTime beginTime, DateTime endTime)
        {
            List<Order> invoices = new List<Order>();
            OrderService service = new OrderService();

            while (true)
            {
                OrderListOptions listOptions = new OrderListOptions()
                {
                    Limit = 100,
                    Created = new DateRangeOptions()
                    {
                        GreaterThanOrEqual = beginTime,
                        LessThanOrEqual = endTime
                    },
                };

                listOptions.AddExpand("data.charge");
                listOptions.AddExpand("data.customer");

                if (invoices.Count() > 0)
                    listOptions.StartingAfter = invoices.LastOrDefault().Id;

                StripeList<Order> newInvoices = service.List(listOptions);

                invoices.AddRange(newInvoices.Data);

                if (!newInvoices.HasMore)
                    break;
            }

            return invoices;
        }
`

**Comment by jmawebtech** [comment]
Hi,

Is there another endpoint for ACH? I found the invoice on 9/28. How about SourceAchDebit?

**Comment by remi-stripe** [comment]
@jmawebtech Sorry for the delay. I'm having troubles following what you're describing I'm sorry. The type of source associated with the Charge should not matter here and the code you shared should mostly work though I don't fully grasp the `sourceStatus` part in your method.

What I would recommend here is to explicitly write simple code that just loops over the charges in that timeframe and outputs the id for each one just to be 100% sure this is not a problem with your code. Also, I'd recommend trying to fetch that Charge directly via the Retrieve Charge API to confirm it's retrieved successfully: https://stripe.com/docs/api/charges/retrieve

I'm fairly confident this can't be a bug with the library itself but I need a lot more explicit details to help you debug this. I'd recommend contacting our support team with all the extra information you have: https://support.stripe.com/contact
