### ISSUE TITLE
New version numbering scheme?

### ISSUE THREAD

**Issue by winzig** [stripe/stripe-dotnet#2251]
I noticed we've gone from v39.23.0 to v7.63.0. Assuming this kind of jump was on purpose, is there a document that talks about this jump backward in version numbers? Thanks!

**Comment by richardm-stripe** [comment]
Hello @winzig, thanks for the report. This version number was a mistake, v7.63.0 was published in error and should not be used. We've marked that package as unlisted on nuget, and have published 39.24.0.
