### ISSUE TITLE
Nuget page shows .NET 4.5+, but actually 4.6.1 is required.

### ISSUE THREAD

**Issue by joshnoe** [stripe/stripe-dotnet#2259]
https://www.nuget.org/packages/Stripe.net/

![image](https://user-images.githubusercontent.com/734801/101067593-95af1c80-354c-11eb-907e-634890139a21.png)

**Comment by remi-stripe** [comment]
@joshnoe Nice catch and thanks for the heads up! We'll get it fixed!
