### ISSUE TITLE
Element gives problems in firefox

### ISSUE THREAD

**Issue by JesperPetersenDk** [stripe/stripe-dotnet#2264]
It is such that I experience problems with stripe element in relation to the fact that it is not displayed on Firefox but that in google and microsoft browser it is displayed without problems.

Here are some pictures I took.
![WBHgOwG](https://user-images.githubusercontent.com/9692664/102910541-088c2300-447b-11eb-936a-5210e3cd9874.png)

![3kOT8jq](https://user-images.githubusercontent.com/9692664/102910550-0c1faa00-447b-11eb-8393-90af262ed80b.png)

![qZ4mzRW](https://user-images.githubusercontent.com/9692664/102910558-0e820400-447b-11eb-8c22-8cb3ba88f323.png)

For example, if I click ctrl + f5 I get 200 but I run it again. then I get 304, but basically nothing appears on the screen around stripe payment. But it's funny that Firefox is the only browser that does not show it on.

I've also deleted everything cached and removed everything, but it still gives problems that I can not access the strip element on the page.

After i delete tihs, can i see this here.

![sGMyQnS](https://user-images.githubusercontent.com/9692664/102913381-f7451580-447e-11eb-8485-f844473ec40a.png)

**Comment by remi-stripe** [comment]
@JesperPetersenDk Github issues should be limited to bugs with the stripe-dotnet library. Your question is more an integration question about Elements in your browser.

I'd recommend reaching out to our support team directly for help https://support.stripe.com/contact
Make sure to share your exact code, for example in a gist and a URL where  to reproduce
