### ISSUE TITLE
Proper use of CancellationToken

### ISSUE THREAD

**Issue by Cellus250** [stripe/stripe-dotnet#2267]
Hello, I think there may be an issue with the CancellationToken on the async requests. However, I have only tested this on the PaymentMethodService.ListAsync request and I may be doing something wrong. Please check it out.

```
try 
{
  var cancellationTokenSource = new CancellationTokenSource(delay: TimeSpan.FromMilliseconds(3000));
  var paymentMethodService = new PaymentMethodService();
  var paymentMethodOptions = new PaymentMethodListOptions()
  {
      Customer = "CustomerID",
      Type = "card"
  };

   var paymentMethods = await paymentMethodService.ListAsync(paymentMethodOptions, cancellationToken:cancellationTokenSource.Token);
}
catch (TaskCanceledException)
{
    // Handle timeout
}
```

Conditions: Stripe Ephemeral key, no internet connection
Expected Result: Request times out after 3000 milliseconds
Actual Result: Request runs indefinitely

Update: 
I think this can be closed. I found the actual issue, a change in the code upstream causes an exception to be raised during this call and I was not catching the appropriate exception. However, this does raise a new question though, why would the request await indefinitely if an appropriate catch is not used?

**Comment by remi-stripe** [comment]
Thanks for the detailed report and the quick update! Glad you found out what the issue was!
