### ISSUE TITLE
API/SDK to test a Checkout Session end to end

### ISSUE THREAD

**Issue by sam-wheat** [stripe/stripe-dotnet#2270]
Hello, in the email shown below I ask Stripe support how to create an integration test for a Checkout Session.  Their response is that it cannot be done.  I requested that they create APIs to make it possible and I am requesting supporting SDK from you.

Thank you.

### Email to stripe support:

From: me
Sent: Monday, January 4, 2021 11:23 AM
To: Stripe <support@stripe.com>
Subject: How to simulate submitting a payment in an integration test using stripe.net?
 
Hello,

In my code I create a session representing the users subscription order:

    SessionCreateOptions options = new SessionCreateOptions
    {
        PaymentMethodTypes = new List<string> { "card" },
        LineItems = new List<SessionLineItemOptions>
        {
            new SessionLineItemOptions { Price = order.PaymentProviderPlanID, Quantity = 1 }
        },
    Customer = order.CustomerID,
    CustomerEmail = string.IsNullOrEmpty(order.CustomerID) ? order.UserEmail : null,
    Mode = "subscription",
    SuccessUrl = hostURL + "/Subscription/ConfirmSubscription?session_id={CHECKOUT_SESSION_ID}",    
    CancelUrl = hostURL + "/SubActivationFailure"
    };

I then redirect the user to the Checkout portal where they can submit payment.

I want to create an integration test that exorcises this code. However I need a way to simulate the events that occur when the customer
submits payment. 

If at all possible I do not want to change or omit the code shown above as it works fine for what it is supposed to do. 

How do I do that?

Thank you.

### Response from Stripe

From: Stripe Support <support@stripe.com>
Sent: Wednesday, January 6, 2021 12:48 AM
To: me
Subject: Re: How to simulate submitting a payment in an integration test using stripe.net?
 
Hi Sam,

Hope this email finds you well.

Coming straight to the point here, it's not possible to complete a Checkout Session payment with only code. You need to actively visit the Checkout page in a browser to complete the payment. If you want to automate a test payment with the code only to activate a subscription then you need to look into using PaymentIntents instead of Checkout Sessions. You can learn more about using PaymentIntents for your subscriptions at the link provided below:

https://support.stripe.com/questions/stripe-billing-integration-with-payment-intents-api

I hope this helps and if you have any further questions, please feel free to reply to this email. I'm always happy to help.

Best regards,
Mike B

**Comment by remi-stripe** [comment]
@sam-wheat Thanks for the feedback and the detailed context. At the moment this is not something we directly support and we don't have plans in the short term to add this feature. What we recommend instead is to mock this situation and corresponding response in the API instead.

Otherwise a more direct alternative is to use the Stripe CLI tool: https://stripe.com/docs/stripe-cli Doing so will let you trigger a `checkout.session.completed` event directly from the command-line (or your own code) to simulate a real Session being completed on your account.

I'm going to close this issue because it's not really a feature request for stripe-dotnet itself and more an API feature request. It's something we've heard before and are tracking internally. If we were to add support for this in the future, it'd be immediately available in all client libraries, including stripe-dotnet, though it's unlikely to happen for now.

**Comment by sam-wheat** [comment]
@remi-stripe Thanks for your response.  As far as I know there is no way to mock this or complete a checkout session in code.  I actually requested assistance on this from Stripe and this is their response: 

> Coming straight to the point here, it's not possible to complete a Checkout Session payment with only code. You need to actively visit the Checkout page in a browser to complete the payment.

I checked the session completed event however because the payment can not be submitted it doesn't offer a true way to test the activated subscription.

It really would be great to have a way to test this end-to-end in code.  

Thanks again.

**Comment by remi-stripe** [comment]
@sam-wheat There are alternatives though such as real mocking on the API (just returning a fake JSON that mirrors what the API would return) or using the Stripe CLI to explicitly trigger a `checkout.session.completed` event (which in turn **will** cause a real Session to be created and completed).

We don't have plans to add a way to complete a session with just code for now other than this.
