### ISSUE TITLE
Badly formatted payment_method_types sent from PaymentIntentService

### ISSUE THREAD

**Issue by magnusvw** [stripe/stripe-dotnet#2273]
I am using the PaymentIntentService like this:

```
[AllowAnonymous]
[HttpPost("capture")]
[Consumes("application/json")]
[Produces("application/json")]
public ActionResult Capture(StripeCaptureRequest chargeRequest)
{
    var requestOptions = new RequestOptions
    {
        ApiKey = _stripeSettings.ApiKey
    };

    var metadata = new Dictionary<string, string>();
    metadata.Add("CustomerUserId", chargeRequest.CustomerUserId.ToString());
    metadata.Add("ExpertUserId", chargeRequest.ExpertUserId.ToString());

    var chargeOptions = new PaymentIntentCreateOptions
    {
        Metadata = metadata,
        Currency = chargeRequest.Currency,
        Amount = chargeRequest.Amount,
        ReceiptEmail = chargeRequest.Email,
        Description = chargeRequest.Description,
        PaymentMethodTypes = new List<string>() { "card" }
    };

    var service = new PaymentIntentService();
    var charge = service.Create(chargeOptions, requestOptions);

    return Ok(charge);
}
```

I get "status": "requires_payment_method" included in the response.

When I check the logs in the Stripe dashboard, the dotnet api library apparently generates the following POST:

```
{
  "amount": "1000",
  "currency": "sek",
  "description": "Grejer",
  "metadata": {
    "CustomerUserId": "1",
    "ExpertUserId": "2"
  },
  "payment_method_types": {
    "0": "card"
  },
  "receipt_email": "xxx@xxx.se"
}
```

However, payment_method_types should be formatted like this according to the docs:

```
"payment_method_types": [ 
  "card" 
]
```

Using dotnet 5.0.200-preview.20601.7 with System.Text.Json, Windows 10 Home 18363.1256 and Stripe.net 39.32.0.

**Comment by remi-stripe** [comment]
@magnusvw This is not a bug with the library. Both versions work in our API but our client libraries like stripe-dotnet prefer the integer-indexed version for arrays like this. It doesn't matter on an array of enum values like this one, but the order matters for other array of hashes such as `items` in a Subscription update where order must be preserved.

Your code works fine and the reason you have `requires_payment_method` is simply to indicate that you need to collect card details to confirm that PaymentIntent. The next step is to confirm that PaymentIntent client-side with Elements as documented here https://stripe.com/docs/payments/accept-a-payment?integration=elements#web-collect-card-details
