### ISSUE TITLE
AccountService.Get requires account ID but API supports being called without one

### ISSUE THREAD

**Issue by jimboreilly** [stripe/stripe-dotnet#2281]
Was following an example with the `AccountService` found in the documentation on [Transferring from a connected account](https://stripe.com/docs/connect/account-debits#transferring-from-a-connected-account) using the below snippet:

```csharp
StripeConfiguration.ApiKey = "sk_my_secret_key";

var accountService = new AccountService();
Account account = accountService.Get();
```

It doesn't look like the `AccountService` supports calling `Get` without providing an id (might be deprecated according to an issue linked below?) , I'm using the same example in F# in a project referencing Stripe.net release 39.33.0

```fsharp
let stripeClient = StripeClient(apiKey = "sk_my_secret_key")
let accountService = AccountService(stripeClient)
let account = accountService.Get(); // Doesn't compile
```

And providing `null` or `""` throws 

```
  Error Message:
   System.ArgumentException : The resource ID cannot be null or whitespace. (Parameter 'id')
```

Using the curl request provided in the documentation, I get the expected result of my platform account associated with the API key.

Might be the same issue as a very old https://github.com/stripe/stripe-dotnet/issues/540

**Comment by jimboreilly** [comment]
The curl request I'm using for reference although its exactly from the documentation:

```
curl https://api.stripe.com/v1/account \
  -u sk_my_secret_key
```

**Comment by remi-stripe** [comment]
@jimboreilly thanks for reaching out! The issue is with the docs right now. The method is called `GetSelf` in stripe-dotnet and defined [here](https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Services/Accounts/AccountService.cs#L98-L106) so the code example should be

```
let stripeClient = StripeClient(apiKey = "sk_my_secret_key")
let accountService = AccountService(stripeClient)
let account = accountService.GetSelf();
```

I'll get the docs fixed!
