### ISSUE TITLE
3D Secure test cards - no redirect url

### ISSUE THREAD

**Issue by IamSonOfTenny** [stripe/stripe-dotnet#2283]
No redirect url in the paymentIntent, however it is present in the response JSON, just not mapping correctly to the response model (PaymentIntent)
![image](https://user-images.githubusercontent.com/30115849/107392013-29730b00-6af1-11eb-88f8-c6f0246215ee.png)
![image](https://user-images.githubusercontent.com/30115849/107392625-c9c92f80-6af1-11eb-8f66-0be8ec6c510b.png)

.net version: 
![image](https://user-images.githubusercontent.com/30115849/107394024-53c5c800-6af3-11eb-9ae9-8df434f16f2d.png)

![image](https://user-images.githubusercontent.com/30115849/107393889-2da02800-6af3-11eb-924a-b0f5c8a5412b.png)

**Comment by remi-stripe** [comment]
@IamSonOfTenny Thanks for reaching out. The `use_stripe_sdk` property in the API is something specific for the Stripe.js library. It's not something that you're supposed to access or look into today. When a PaymentIntent is in that state, the next step is to go client-side and use Stripe.js to confirm the PaymentIntent and let it do the 3DS flow automatically for you.

**Comment by IamSonOfTenny** [comment]
@remi-stripe thanks for your speedy reply! Hopefully, I understand you correctly, if the payment intent is in the "requires action" state, it should be returned to the client and handled by the front end library e.g. react-stripe-elements or react-stripe-js?

**Comment by remi-stripe** [comment]
That's correct! It would be this step: https://stripe.com/docs/payments/accept-a-payment#web-submit-payment
