### ISSUE TITLE
Api Changes 37 -> 39 - missing Card option for token supply during PaymentIntent Creation

### ISSUE THREAD

**Issue by DavidSekula** [stripe/stripe-dotnet#2285]
Just updated our Api as our customer requires 3d Secure checks during the checkout process, and in the middle of one of our Sagas, we create a payment intent using a card token that was generated elsewhere

The state of the payment is set to manual verification, and is only taken later in the Saga once a set of other checks return back that it's ok to take it.

How would we supply a token in the case of above?
Previously this was done like this: 

```csharp
            var charge = new PaymentIntentCreateOptions()
            {
                Customer = customer.Id,
                Amount = Convert.ToInt64(payment.OrderTotal * CURRENCY_FACTOR_LOWEST_DENOMINATOR),
                Currency = CURRENCY,
                Description = PAYMENT_DESCRIPTION,
                ReceiptEmail = customer.Email,
                StatementDescriptor = PAYMENT_DESCRIPTION,
                ErrorOnRequiresAction = false,
                ConfirmationMethod = "manual",
                PaymentMethodData = new PaymentIntentPaymentMethodDataOptions()
                {
                    Card = new PaymentMethodCardCreateOptions()
                    {
                        Token = payment.StripeToken, // this is CreditCardOptions created as TokenCreateOptions, as a token
                    },
                    Type = SourceType.Card,
                }
            };
```

Is it along the lines of:
`options.AddExtraParam("payment_method_data[card][token]", payment.StripeToken);`

Also - How do we enable 3d secure on this?
Is it a case of adding

```csharp
                PaymentMethodOptions = new PaymentIntentPaymentMethodOptionsOptions()
                {
                    Card = new PaymentIntentPaymentMethodOptionsCardOptions()
                    {
                        RequestThreeDSecure = "any",
                    }
                },
```

Thanks in advance

**Comment by remi-stripe** [comment]
@DavidSekula If you use PaymentIntent you shouldn't be using Tokens client-side for this. Instead create a PaymentMethod and pass it in the `PaymentMethod` parameter on PaymentIntent creation. If you don't want to do this then `AddExtraParam` should work (but is discouraged).
As for enabling 3D Secure, you usually do this within Radar instead. I'd recommend reaching out to our support team directly for help on this: https://support.stripe.com/contact
