### ISSUE TITLE
.net 5 Blazor Server checkout implementation without Javascript

### ISSUE THREAD

**Issue by jonrmorgan99** [stripe/stripe-dotnet#2291]
I've spent several days trying to implement a simple one-time payment checkout using Blazor server and Stripe. I was hoping this would be possible in stripe-dotnet without resorting to Javascript/JSInterop. 

There are a lot of hoops to jump through and I'm increasingly coming to the conclusion that, since Blazor is meant to do away with the need to code in Javascript, I've got too far ahead of the game.

Are there any plans to introduce checkout methods into stripe-dotnet, specifically the equivalent of the Jscript method stripe.redirectToCheckout ?

**Comment by remi-stripe** [comment]
@jonrmorgan99 We're working on this feature right now and the idea is that we will add a `url` property on the Session that you can use to redirect from the server. We don't have a firm timeline for shipping this just yet unfortunately but you can reach out to our support team to register your interest for the feature: https://support.stripe.com/contact

**Comment by jonrmorgan99** [comment]
Hello,

 

Did you complete the Blazor implementation ?

 

I couldn’t find anything in the Developers section of Stripe.com or GitHub.

 

Apologies if I’ve overlooked it !

 

Best

 

Jon
