### ISSUE TITLE
PaymentIntentPaymentMethodDataOptions card option not found

### ISSUE THREAD

**Issue by dalton5** [stripe/stripe-dotnet#2292]
Hi,

I try to setup my confirm payment intent and I can't find the card option. Is it normal?

What is the workarround?

I have also investigated and it seems that it exists as you can see here: https://github.com/duckpage/stripe-card-payment-xamarin/blob/master/client/XamStripe/Payment/Methods.cs line 46

But as you can see I don't have it in the last version.

![image](https://user-images.githubusercontent.com/8339768/109533723-d5898f80-7aba-11eb-99d9-aa8c1fa448de.png)

How can I confirm details of card then?

Thanks,

**Comment by remi-stripe** [comment]
@dalton5 Passing `payment_method_data` in the API does work but it puts you in a higher PCI scope as you have to pass raw card details server-side too. To meet PCI requirements it's recommended to instead do this client-side with Elements in a browser for example as documented [here](https://stripe.com/docs/security/guide#validating-pci-compliance).

Passing billing details is already supported in the library using `PaymentIntentPaymentMethodDataOptions` and `PaymentIntentPaymentMethodDataBillingDetailsOptions` in the code [here](https://github.com/stripe/stripe-dotnet/blob/a516eedf0325bd56b8363c9f5787b8adb1530f13/src/Stripe.net/Services/PaymentIntents/PaymentIntentPaymentMethodDataOptions.cs#L49). You can't just pass billing details without also passing the raw card details which is what puts you in a higher PCI scope.

If you want to send the raw card details yourself it is still possible with stripe-dotnet, for example if you build your own mobile app in .NET client-side. The idea is to use `AddExtraParam` instead like this:

```
var options =new PaymentIntentConfirmOptions
{
  ...
};
options.AddExtraParam("payment_method_data[card][number]", "4242424242424242");
options.AddExtraParam("payment_method_data[card][exp_month]", "01");
// etc.
```

**Comment by dalton5** [comment]
So the best practice to enter credit card details is to embed it withb elements in a webview? Is there an example? Is it the correct approach pci compliant?

**Comment by remi-stripe** [comment]
Yes using Elements in a Webview is what you should be doing for PCI compliance: https://stripe.com/docs/security/guide#validating-pci-compliance covers this in more details. There are many examples in our  documentation such as https://stripe.com/docs/payments/accept-a-payment

I'm going to close this out as it's not an issue with the library. If you need further help though you can talk to our support team here: https://support.stripe.com/contact. You can also talk to Stripe engineers on IRC, they are in #stripe on Freenode and can help with questions about your code!

**Comment by dalton5** [comment]
thanks a lot. It helped me alot! Yes close it.
