### ISSUE TITLE
Newtonsoft.Json dependency version

### ISSUE THREAD

**Issue by wimpyprogrammer** [stripe/stripe-dotnet#230]
I'm confused by the version of the Newtonsoft.Json dependency for the Stripe.net NuGet package.

I just installed version 2.3.3 via Nuget, where [the Newtonsoft.Json dependency is listed as ≥ 5.0.8](https://www.nuget.org/packages/Stripe.net/2.3.3).  However, when I try to run some simple code:

``` C#
StripeAccountService accountService = new StripeAccountService("sk_test_xxx");
StripeAccount account = accountService.Get();
```

I get an error: `Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

Is the dependency listed on the NuGet package accurate?  It looks like the Newtonsoft.Json version was increased to 6 [back in May](https://github.com/jaymedavis/stripe.net/commit/fac9ad8b065b4b195e65912bc0fb1ff7990b2726).

The problem is that I'm trying to install stripe.net alongside openstack.net, whose [NuGet dependencies require Newtonsoft.Json ≥ 5.0.8 && < 6.0](https://www.nuget.org/packages/openstack.net/).  And all my attempts at binding redirection:

``` xml
<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
    <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="5.0.8.16617" />
    </dependentAssembly>
</assemblyBinding>
```

have been unsuccessful.  Does stripe.net actually need version 6 of Newtonsoft.Json?  It seems like the upgrade was unintentional.

I'm no expert with these intricate dependency trees, so if I'm overlooking something obvious please let me know.  Thank you!

**Comment by hasmukhsavaliya** [comment]
Acutally, you need to get version 7.0.0.0 for Newtonsoft.Json.dll file.
