### ISSUE TITLE
ConfigurationFeaturesOptions add Subscription Pause

### ISSUE THREAD

**Issue by jmawebtech** [stripe/stripe-dotnet#2300]
Hi,

I am using 39.40.0. I am creating custom customer portal for my users. I want to enable subscription pause, but the code is missing. The docs said the setting is in preview mode. Do you have a release date for this feature?

https://stripe.com/docs/api/customer_portal/configuration

**Comment by remi-stripe** [comment]
@jmawebtech At the moment this feature is still in beta, though it does work. We don't have a specific release data for it yet but once it's public for everyone it will be in client libraries. I'm flagging to the team but I'd recommend reaching out to our support team directly to register your interest: https://support.stripe.com/contact
