### ISSUE TITLE
Latest API updates causing issues with accessing api.stripe.com

### ISSUE THREAD

**Issue by b3hdad** [stripe/stripe-dotnet#2301]
Hi,

After upgrading to the latest Stripe release v39.42.0, I am getting random issues getting to stripe API. I am using this client on my home page to get the plans (i.e. await _stripPlanService.ListAsync()) from stripe. However, now I am seeing the following error intermittently:

`
An error occurred while sending the request. and inner exception is: The remote name could not be resolved: 'api.stripe.com' : at Stripe.SystemNetHttpClient.<MakeRequestAsync>d__29.MoveNext() in /_/src/Stripe.net/Infrastructure/Public/SystemNetHttpClient.cs:line 204 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Stripe.StripeClient.<RequestAsync>d__25`1.MoveNext() in /_/src/Stripe.net/Infrastructure/Public/StripeClient.cs:line 114 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Stripe.Service`1.<RequestAsync>d__25`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) a
`

One thing to note is that I upgraded this on 27th of March but started seeing these errors a few hours ago. So I am not 100% sure if it is because of the updates or not.

What I have done for now is that I have downgraded Stripe client, to v39.39.0, which is just before any API updates went in.
The problem seems to have gone away with this downgraded version. 

I thought I ping you guys about it. 

Thanks.

**Comment by remi-stripe** [comment]
@b3hdad Thanks for reaching out. There wasn't any substantial change between the latest version (39.42.0) and the one you're on (39.39.0) so it's unlikely to be a bug with the library itself. Based on the error, this looks to be more a network issue with your host that is unable to reach our servers' and leading to timeouts/errors. My guess is that there was a blip on your server/host and it resolved itself after you rolled back the change and restarted your services. I'd recommend reaching out to your host provider to discuss this first. Additionally you could try to rollout the latest version in Test mode first to see if you can reproduce.

**Comment by b3hdad** [comment]
@remi-stripe thank you for quick feedback. Yes, it might be. My app is on Azure and I have noticed that Microsoft have been doing some upgrades recently with the underlying platform. I am currently putting some safeguards around this and will upgrade to the latest version again and see if I can reproduce it locally. Please feel free to close it and if I can reproduce it, I will re-open. Thanks again.
