### ISSUE TITLE
DisplayItems collection property vanished from Session class

### ISSUE THREAD

**Issue by lukepuplett** [stripe/stripe-dotnet#2306]
I've just updated my Stripe NuGet package from 36 to 39 and tried to run my app. I get a compiler error because `DisplayItems` is not a member of the `Session` object I'm referencing in a webhook event handler.

It's supposed to contain `SessionDisplayItem` instances, which the intellisense help says:

> The line items, plans or SKUs that were purchased by the customer.

I've googled for it and searched the change log here and there's no mention of it. It's like it never existed at all.

Google search shows no mention of the deprecation/removal (or even existence) of this property? I asked my wife to pinch me and I'm neither asleep, in an alternative universe or dead, I don't think.

https://www.google.com/search?q=stripe+c%23+Session+DisplayItems&source=lmns&bih=969&biw=1920&rlz=1C1CHBD_en-GBGB837GB837&hl=en-GB&sa=X&ved=2ahUKEwiq1sfHjf7vAhXa0-AKHYjXAl0Q_AUoAHoECAEQAA

I'm lost. What should I be using instead? Why isn't this breaking change mentioned anywhere? Thanks.

**Comment by remi-stripe** [comment]
@lukepuplett The `DisplayItems` collection was removed in the most recent API version: [2020-08-27](https://stripe.com/docs/upgrades#2020-08-27)
> Checkout Sessions no longer include the display_items property. Use the includable line_items property instead.

The stripe-dotnet library is always pinned to the most recent API version. Whenever a new API version, we release a new major version of stripe-dotnet with all the breaking API changes included. This is what happened for the 39.X version release where we moved the library to that API version and removed deprecated properties and parameters [changelog](https://github.com/stripe/stripe-dotnet/blob/master/CHANGELOG.md#3912---2020-09-01)

The `DisplayItems` collection was legacy for a while as we added direct line items support for all modes. Your code needs to look at the `LineItems` collection instead which is includable: https://stripe.com/docs/expand#includable-properties

**Comment by lukepuplett** [comment]
Thanks Remi. There's a communication problem here. I should be able to do a CTRL+F find in Chrome while on the changelog and see the property that was removed. It's a big change. It's not mentioned. I should be able to search for the property name `DisplayItems` and not `display-items`.

I've raised a call with support because I seem to be using the `SessionDisplayItem.Plan` object to get at the plan ID and interval. I can't find a way to do this with the latest `Session` class design/API.

I'm also not clear on what happens when a webhook sends me objects that have "includable" properties, since I didn't make the request in the first place. I assume you include everything in a webhook.

Thanks

**Comment by lukepuplett** [comment]
Looking at my code, it appears that the `Plan` object could potentially be `null` and my code will handle it, so maybe you guys never populated that object anyway. We'll never know.

**Comment by lukepuplett** [comment]
Actually, I do need it and you must have sent it since this was all tested and working, and my code logs an error and only extends a 1 day grace window in the absence of a `Plan` object.

**Comment by lukepuplett** [comment]
Thank you Remi. I think this might help me.

https://stripe.com/docs/payments/checkout/migrating-prices

**Comment by remi-stripe** [comment]
Oh yeah that doc is great if you were using the old way of passing amount directly on Session creation. Nice find, sorry I didn't think to link you to it! I hope you're unblocked and this conversation was great feedback for us to improve how we write our changelog and our official migration guides for stripe-dotnet!

**Comment by lukepuplett** [comment]
Also for other people hitting the same issue:

> You can’t receive webhook events with properties auto-expanded. Objects sent in events are always in their minimal form. To access nested values in expandable properties, you must retrieve the object in a separate call within your webhook handler.

https://stripe.com/docs/expand

Though that contradicts this:

> The line_items field does not render by default as display_items did, but you can include it using expand when creating a Checkout Session

https://stripe.com/docs/payments/checkout/migrating-prices

And presumably this mean this will work in my `CreateStripeCheckoutSession` method.

            var options = new SessionCreateOptions
            {
                Expand = new List<string>()
                {
                    "line_items"
                },
                ...

**Comment by remi-stripe** [comment]
@lukepuplett what this means is that the `LineItems` property is only present when explicitly included/expanded via the API. When you code makes the API request to create/retrieve the Session you can expand (what you showed) automatically. With webhooks, you don't control this so the event will not have the LineItems property set and you will need to retrieve the Session separately to expand the line items!

**Comment by lukepuplett** [comment]
Cheers. But it reads as if I can set the Expand property when making the session and the webhook will return it. So I shouldn't need a call back to your API in my handler.

> but you can include it using expand when creating a Checkout Session

I'll find out. I've left a comment in my code as I won't be testing this for weeks, This is all Yak Shaving; I'm just trying to get my code to compile so I can get on with whatever I was supposed to be doing. I can't even remember now! It'll come to me in the morning.

Thanks for your help. Sweet dreams.

**Comment by remi-stripe** [comment]
> But it reads as if I can set the Expand property when making the session and the webhook will return it. So I shouldn't need a call back to your API in my handler.

That's not how it works today. The Expand will only apply to this specific API Request and the response returned and not future events being sent to your endpoint for that Session as those are completely separate!

**Comment by lukepuplett** [comment]
Okay thanks. It looks like the new API is a backward step. It's a shame. Stripe was conceived and built to lessen the pain. Each improvement should only make life easier, require less code, fewer interactions, fewer points of failure, less testing, less money. This absolutely does not. It's not your fault and I appreciate your help.

The wider problem that the Stripe product team must understand is that if their product begins to stand out as a thorn, we'll see an opportunity to build the next paracetamol and replace Stripe's entire value proposition and business. I'm not kidding. It's already got me thinking of what exactly I use Stripe for and I have an idea of how to build something that has just 5% of the integration surface.

If Stripe doesn't become easier at the same rate as everything else about building apps, what wasn't seen as the painful work a few years ago can become the hot potato that coders don't want to touch.

**Comment by remi-stripe** [comment]
@lukepuplett I understand that having a breaking change happens when you upgrade the library is painful especially when your code just worked but I don't think the changes made the API a lot more complex. It's the opposite and we've received detailed feedback about how much easier LineItems and Prices are as an API than the previous solution. It was also not possible to support future new features that we're planning on the old `DisplayItems` option on Checkout and it wouldn't have scaled.

As for the expansion itself, which I assume is what is putting you off, it's something we're actively monitoring. It's a balance between easy of use (getting all items at once in an event) and latency (getting the API to take 3 or 4 seconds to respond end to end because it needs to render potential thousands of line items in the future).

**Comment by lukepuplett** [comment]
I understand that you sometimes have to change an API to accommodate new features. But as you say, not including the data is a more significant change that just a re-org (also I was upset by the difficult finding this breaking change).

a) it adds a chance of a failure for my app to reach yours to get the missing information; I have to cater for that possibility. What if your push microservices are up but your get API is down for a few seconds?
b) it adds latency, so you think you're speeding it up, but you're not because I've got to fetch the missing data, and I'd suggest that not many customers will have 1,000s of line items, so I'm being impacted by a hypothetical problem that other customers may have.
c) I now have to rework my app to get an HTTP client down into that corner of my code with retry logic.

Remember, you have an API for me to ask for this stuff to be included via your `Expand` property, but you haven't enabled it for webhooks/asynchronous calls.

It sounds like you need to propagate my `Expand` setting around your internal events so that when your backend eventually pushes its webhook payload back out to me, your service knows what to include.

And I'm not even sure it matters that it takes a while for the webhook to come back since its async, my customers aren't blocked while this all takes place.

Thank you.
