### ISSUE TITLE
StripeList Add Lines

### ISSUE THREAD

**Issue by jmawebtech** [stripe/stripe-dotnet#2310]
Hi,

I am using 39.40.0.

I am trying to write a unit test. 

            StripeList<InvoiceLineItem> items = new StripeList<InvoiceLineItem>();
            items.Append(new InvoiceLineItem()
            { 
                Price = new Price()
                {
                    ProductId = "1"
                }
            });

When I call the code, I get a null reference here:

![image](https://user-images.githubusercontent.com/1679993/115722430-fe0c6800-a34c-11eb-841a-8cddc866b549.png)

How do I add line items to an invoice?

**Comment by remi-stripe** [comment]
@jmawebtech The steps would be to first create an Invoice Item [API](https://stripe.com/docs/api/invoiceitems/create) and then after that you create an Invoice [API](https://stripe.com/docs/api/invoices/create) which will automatically pull in the pending invoice item as a line on the invoice.

I'm going to close this out as this is more a support question and github issues are limited to bugs with the library itself. Please reach out to our support team if you need more help: https://support.stripe.com/contact
