### ISSUE TITLE
As per Indian regulations, export transactions require a customer name and address.

### ISSUE THREAD

**Issue by SourabhDhiman77** [stripe/stripe-dotnet#2311]
I have implement strip payment but I have face issue.
As per Indian regulations, export transactions require a customer name and address..

**Comment by remi-stripe** [comment]
@SourabhDhiman77 Github issues should be limited to bugs with the library and this is more a support question. I'd recommend reading this doc https://stripe.com/docs/india-accept-international-payments but otherwise please reach out to our support team for help: https://support.stripe.com/contact
