### ISSUE TITLE
3DS Redirect url is not being returned on payment intent creation

### ISSUE THREAD

**Issue by yasinkultur** [stripe/stripe-dotnet#2321]
Hello I could not find the property to get the 3D secure return url when the status is "requires_action", I was only able to access the property using the raw JObject.

Here is the code.

```
var servicePaymentIntent = new PaymentIntentService();
var options = new PaymentIntentCreateOptions
                        {
                            Amount = stripeAmount,
                            Currency = "gbp",
                            Customer = getStripeCustomerId,
                            PaymentMethod = model.token,
                            Confirm = true,
                            OffSession = false,
                            Metadata = new Dictionary<string, string>() {
                                        { "where", "buynow" },
                                        { "basketid", basketId.ToString() }
                                },
                            UseStripeSdk = true,
                            SetupFutureUsage = "on_session",
                            ReturnUrl = Url.ActionLink("HandleThreeDS", "Basket", new { basketId = basketId })
                        };
var res = await servicePaymentIntent.CreateAsync(options);

if (res.Status == "requires_action")
{
  var getRedirectUrl = res.RawJObject["next_action"]["use_stripe_sdk"]["stripe_js"].ToString();

}
```

**Comment by remi-stripe** [comment]
@yasinkultur Github issues should be limited to bugs with the library and your question seems more like a question about the API/product. I'd recommend talking to our support team instead: https://support.stripe.com/contact/email

To unblock you though, you are not supposed to read off of `use_stripe_sdk` at all in your integration. Instead, this indicates we want you to confirm client-side with Stripe.js directly to let us handle the next steps. If you don't want to use Stripe.js you should be using `UseStripeSdk = false` as defined [here](https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Services/PaymentIntents/PaymentIntentCreateOptions.cs#L246) to reflect that though it is highly discouraged. At least if you did this you should either get an error back or a next action set to `redirect_to_url`. The `use_stripe_sdk` is considered fully opaque on our end and not something we guarantee a stable format for.
