### ISSUE TITLE
Properties in the sdk not in the documentation

### ISSUE THREAD

**Issue by zgirod** [stripe/stripe-dotnet#2322]
Hello,

I was using the sdk and I noticed that for some classes there are discrepancies between the properties available on the documentation vs the properties in the sdk. Looking at the commit history it looks like there is a process where openapi is being used to add properties to the classes (very cool!). However it doesn't appear to work in reverse and remove properties if a property was removed. Here is what I found.

Create a customer
https://stripe.com/docs/api/customers/create
https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Services/Customers/CustomerCreateOptions.cs

The sdk has the following properties but those properties don't exist on the documentation:
- plan
- quantity
- trial_end
- validate

Retrieve an invoice's line items
https://stripe.com/docs/api/invoices/invoice_lines
https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Services/Invoices/InvoiceListLineItemsOptions.cs

The sdk has the following properties but those properties don't exist on the documentation:
- coupon
- customer
- subscription
- subscription_items
- subscription_plan

We are not using too many Stripe endpoints so I didn't check a whole bunch of *Options.cs classes. If you do have the openapi comparison going maybe you can also have it check for properties in the sdk but not in openapi as well.

Thanks,
Zach

**Comment by remi-stripe** [comment]
@zgirod This is done on purpose on our end to decrease the amount of breaking changes we force users to go through when they upgrade their library for new features. 
We decrease adoption of legacy features by undocumenting those explicitly from our docs, but we keep them for a while in client libraries if they were widely used which is true of a few examples you have here (though not all).

Does that make sense?

**Comment by zgirod** [comment]
Hi @remi-stripe 

Yeah, that makes complete sense. The Stripe api has a wide footprint and many users on many different versions so I can understand it is a challenging problem set. I think you guys do a great job with it too.

I wonder if there is middle ground somewhere; because the problem now is it is confusing for new users. Because you see a property and try and look up what the property is? How or why should you use it? And you can't get any information.

My first thought was you could hit the properties with a

`[Obsolete("This attribute is being sunset.", false)]`

But I see that you guys have TreatWarningsAsErrors = true so that won't work.

Do you think there is a way to keep the properties around to lower upgrade friction but clearly communicate to new users that those properties shouldn't be used anymore?

**Comment by jonorossi** [comment]
> Do you think there is a way to keep the properties around to lower upgrade friction but clearly communicate to new users that those properties shouldn't be used anymore?

Stripe.net could use `[EditorBrowsable(EditorBrowsableState.Never)]` to hide them from IntelliSense so developers don't write new code using them.

**Comment by remi-stripe** [comment]
We do use `Obsolete` regularly though there are no concreate examples in the lib as we removed most of those in the latest major version. We'll have a look to see if we can improve some of the ones currently in the library that we know are widely used though discouraged to make it easier for developers who use their IDE/auto-completion like you are!

**Comment by zgirod** [comment]
That's cool. Is there a reason a property that isn't in the documentation shouldn't be marked `Obsolete` or at the very least have a have a comment added to it like:

```
/// <summary>
/// This property is being sunset. You won't find this property in the documentation.
/// </summary>
```

**Comment by remi-stripe** [comment]
Mostly that we need to build some more complex logic for this since the library is automatically generated from a custom version of our openapi spec. Definitely on our radar but it's been lower priority than a lot of core improvements or new features!

**Comment by zgirod** [comment]
Understood! Thanks for talking through this with me. Keep up the great work with the api.

Please go ahead and close the ticket.
