### ISSUE TITLE
Install-Package : “Microsoft.Bcl.AsyncInterfaces”已拥有为“System.Threading.Tasks.Extensions”定义的依赖项。

### ISSUE THREAD

**Issue by dream-lmc** [stripe/stripe-dotnet#2334]
正在尝试解析依赖项“Microsoft.Bcl.AsyncInterfaces (≥ 1.1.0)”。
Install-Package : “Microsoft.Bcl.AsyncInterfaces”已拥有为“System.Threading.Tasks.Extensions”定义的依赖项。

**Comment by richardm-stripe** [comment]
Hello @dream-lmc, I'm closing this as I don't think this represents an issue with `stripe-dotnet` directly, it seems like there is some problem with nuget on your system.
