### ISSUE TITLE
This C# Stripe SDK not use ThreadPool ?

### ISSUE THREAD

**Issue by dream-lmc** [stripe/stripe-dotnet#2335]
This C# Stripe SDK not use ThreadPool ?

**Comment by richardm-stripe** [comment]
Every Stripe method has an "Async" option (e.g. [CustomerService.CreateAsync](https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Services/Customers/CustomerService.cs#L32)) that returns a [Task](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task?view=net-5.0) which are [queued to the ThreadPool](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/task-based-asynchronous-programming).

Closing the issue, feel free to re-open with more details if there's some specific multi-threading use case you're concerned about.
