### ISSUE TITLE
Request: Customer Portal language API

### ISSUE THREAD

**Issue by alexuaua** [stripe/stripe-dotnet#2337]
Hi,

I've upgraded legacy code to newest Stripe API and switched from manual charges to Checkout and Portal products. I'm really happy with cleaner code, better security and improved UX, but found that the Portal API does not allow to pass language when one creates portal session. 
For us it's a real issue, because one of our products that uses Stripe runs in embedded browser and unfortunately it always reports locale as "en-US". We pass language option during Checkout session creation and I hope Portal session API can be upgraded to select a language/locale and match Checkout experience.

**Comment by remi-stripe** [comment]
@alexuaua Thanks for reaching out! We don't support this yet but we're working on it just this week as the API change got approved internally. We don't have a firm date for releasing this just yet but I'll flag to the engineering team for visibility and we'll update this thread once it ships!
