### ISSUE TITLE
Standard account issue in india

### ISSUE THREAD

**Issue by sanjeetkum** [stripe/stripe-dotnet#2344]
Hi Everyone,
I am trying to create one time login link but  getting below error :- 
**Cannot create an edit link for the account acct_1J5yEkSFsoSm2lGI, which is not an Express account.**
How did you resolve this issue , given the fact in india we are using account type: "standard".

Thanks and Regards,
Sanjeet Kumar

**Comment by remi-stripe** [comment]
@sanjeetkum Github issues should be limited to bugs with the stripe-dotnet library. You asked an integration question which you should discuss with the support team instead on https://support.stripe.com/contact/email or developers on https://stripe.com/go/developer-chat

To unblock you though, you can not use LoginLink with Standard accounts. Those only work with Express accounts. Standard accounts have full Dashboard access with an email/password and you can just redirect them to https://dashboard.stripe.com
