### ISSUE TITLE
Recurring payments

### ISSUE THREAD

**Issue by Shriyanshmit** [stripe/stripe-dotnet#2360]
Please let me know how it is possible to make recurring payment using .net core library.

Every month I want to make a transaction. Please suggest which code should I use?

**Comment by remi-stripe** [comment]
@Shriyanshmit Github issues should be limited to issues with the library. You have an integration question that would be answered by our [support team](https://support.stripe.com/contact/email).

**Comment by Shriyanshmit** [comment]
From the same library I want to do the recurring payment.
