### ISSUE TITLE
Unable to use client from Azure Functions project

### ISSUE THREAD

**Issue by joaocolombo** [stripe/stripe-dotnet#2381]
There is currently an error in Azure Functions when they require System.Configuration.ConfigurationManager v5.0.0: [dotnet/runtime#54642
](https://github.com/dotnet/runtime/issues/54642)
I cloned the repo and took the version down to 4.7 and it compiles, and works fine. Is it possible to make a version with 4.7 or something like that?

**Comment by remi-stripe** [comment]
@joaocolombo Thanks for the submission! I can't promise it's something we'd be able to implement soon unfortunately but we're looking into it internally

**Comment by sequarell** [comment]
i might have the same problem or at least something related.
I have a azure functions project setup on net6 and functions runtime v4. Somewen in the last few days it stopped working(assuming to some kind of update, maybe new VS2022 preview)
I get 

"Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. 

when accessing database with entitfy framework core (from within SqlAuthenticationProviderManager)
However, I was not able to resolve the issue with downgrading packages.. tried to downgrade configruarion manager and entity framework packages, no success.

Doing the exact same operations from a net6 console app with the same package versions, everything runs fine. Really seems to depend on the azure function runtime.

**Comment by joaocolombo** [comment]
@sequarell yes,  I went through this problem too, so i decided remove System.Configuration.ConfigurationManager of Stripe code, and finily works well.

below the fork without System.Configuration.ConfigurationManager

[Stripe without ConfigurationManager](https://github.com/joaocolombo/stripe-dotnet/tree/master)

**Comment by pakrym-stripe** [comment]
Hello friends! Can you, please, try the latest version of Stripe.net and the latest Azure Functions runtime to see if the issue with ConfigurationManager still reproduces?

The latest Stripe.NET references System.Configuration.ConfigurationManager 4.7.0 which aligns with what Azure Functions 3.35.0 runtime requires.
