### ISSUE TITLE
Unable to create customer portal session

### ISSUE THREAD

**Issue by siuhleung7** [stripe/stripe-dotnet#2392]
Hello, I followed this article:
https://stripe.com/docs/billing/subscriptions/integrating-customer-portal

<img width="866" alt="Screenshot 2021-11-04 at 5 34 59 PM" src="https://user-images.githubusercontent.com/7855085/140290916-6644bee1-645b-41cb-bf55-7d9ab5fdac1e.png">

But I cannot set return_url in my code
![Screenshot 2021-11-04 at 5 36 59 PM](https://user-images.githubusercontent.com/7855085/140291062-3717a61a-5a8f-4cae-93f1-8357f1a82821.png)

Using the latest version of SDK:  39.75.0

Thank you

**Comment by kerams** [comment]
My guess is that you're using `Stripe.Checkout`. The `Stripe.BillingPortal` namespace contains `SessionCreateOptions` and `SessionService` as well. You need to use the latter to create a customer portal session.

**Comment by gabrielhildebrandt** [comment]
You need to use `Stripe.Checkout` instead `Stripe.BillingPortal`

**Comment by gabrielhildebrandt** [comment]
I had the exact same issue and figured out I was using `Stripe.BillingPortal`, changing to `Stripe.Checkout` worked fine

**Comment by gabrielhildebrandt** [comment]
Cuzão

**Comment by remi-stripe** [comment]
Thanks @kerams @gabrielhildebrandt for chiming in and helping! This is not really a bug with the library and is instead and integration question so I'm going to close, but if their response isn't what you were looking for, please talk to our support team for help @siuhleung7: https://support.stripe.com/contact
