### ISSUE TITLE
Feature Request: Subscription Quantity Restrictions For Customer Portal Configuration Not Exposed via API

### ISSUE THREAD

**Issue by ajkimberley** [stripe/stripe-dotnet#2400]
The Stripe billing documentation states that, when configuring the Customer Portal, it is possible to set quantity restrictions for products when enabling the quantity update feature: https://stripe.com/docs/billing/subscriptions/integrating-customer-portal

However, this only appears to be possible when configuring the portal via the dashboard, as this setting does not appear to be exposed by the .NET implementation of the API.

Would it be possible to implement this? It would be very useful to be able to configure those quantity restrictions dynamically in code.

Note, seems like it would be a good way allowing developers to disable downgrades for their subscriptions and only allow users to upgrade - a feature that is not currently supported.

**Comment by remi-stripe** [comment]
@ajkimberley Github issues should be limited to bugs with the library itself and this is a feature request which should go to our support team instead: https://support.stripe.com/contact

At the moment, this feature is Dashboard only. We will add it in the future to the API if we get this feature request from enough users but I'll flag your request too.

**Comment by ajkimberley** [comment]
Apologies for posting in the wrong place. I checked the default text when I first selected "New Issue" and it does say it's okay to post feature requests for the library. But I'll make sure to send them to support team in the future.

**Comment by remi-stripe** [comment]
Totally fine, it's a tricky line. Feature requests for the library mean things specific to stripe-dotnet. For example something like supporting a new .NET version or similar. But for the API parameters and features, stripe-dotnet will support it automatically as soon as the API does support this!

I mostly remind this when I close to avoid confusion for future askers and to make it clear why I am closing and that it's not that I am ignoring your request (I already filed an ask internally to surface this request :)

**Comment by ajkimberley** [comment]
Ah right, I see. That makes sense. Thanks for forwarding my request on. Much appreciated. :)
