### ISSUE TITLE
Allow overriding the StripeVersion to support future features (i.e.: beta program)

### ISSUE THREAD

**Issue by mauriciojsola** [stripe/stripe-dotnet#2407]
We are using the Stripe ACH feature which is in Beta as of now. We applied for the beta program and we are trying to test it by using the Stripe.Net library.

From this doc: [https://stripe.com/docs/payments/us-bank-account/accept-a-payment#web-create-payment-intent] (https://stripe.com/docs/payments/us-bank-account/accept-a-payment#web-create-payment-intent) in order to let the Stripe API know we are under the beta program, it needs to be indicated in the headers:

`
"Stripe-Version:2019-05-16;us_bank_account_beta=v2"`

What would be the best way to override the **Stripe-Version** header (if any at all) in order to include extra params?

**Comment by richardm-stripe** [comment]
Hello @mauriciojsola. Betas aren't currently supported by `Stripe.Net`, as betas can introduce conflicts with the static type definitions in this library which can cause surprising behavior and crashing deserialization failures. Unfortunately, for the time being if you need to send a beta header with your request you will need to bypass Stripe.Net and make the HTTP request manually.

**Comment by mauriciojsola** [comment]
Thanks @richardm-stripe. Sounds good. I understand. I will make the HTTP request manually and include the required beta header. Not a big deal.

**Comment by johncyril** [comment]
@richardm-stripe would you consider betas living in a separate branch in the repo, with perhaps a `-prerelease` nuget package published?

**Comment by tim-schmidt** [comment]
This issue answers my question, but I would also be interested in a official StripeVersion override feature. I totally understand why you don't allow it. Thanks for all the good work @richardm-stripe!

**Comment by marcelocamargosjr** [comment]
I have the same problem using the version 2022-08-01;pix_beta=v2

**Comment by pakrym-stripe** [comment]
This is now possible in beta versions of the library. More details in [readme](https://github.com/stripe/stripe-dotnet#beta-sdks).

**Comment by mjsola** [comment]
Awesome! thank you for implementing this.
