### ISSUE TITLE
AccountCardOptions not included in ExternalAccountCreateOptions.ExternalAccount

### ISSUE THREAD

**Issue by viDanno** [stripe/stripe-dotnet#2409]
It appears AccountCreateOptions.ExternalAccount and AccountUpdateOptions,ExternalAccount  support AccountCardOptions , however ExternalAccountCreateOptions.ExternalAccount  does not.   I am able to use the Token API endpoint to generate a token for the debit card and then create an external account with the token, but it's an extra step.  I don't need to do this for bank accounts as I can create them without a token as an external account.

**Comment by richardm-stripe** [comment]
Hello @viDanno. Sorry for the extremely delayed response.

We deliberately omit the SDK definitions that allow passing raw card details here. If you pass raw details here, it drastically increases your PCI requirements, and using the Token API on the client side and doing the "extra step" is the correct approach that we want to encourage. There is quite a bit of discussion about this issue on https://github.com/stripe/stripe-node/issues/761 (in another library).
