### ISSUE TITLE
Add targets for net6.0 and netcoreapp3.1

### ISSUE THREAD

**Issue by jon-armen** [stripe/stripe-dotnet#2410]
Feature Request:

- Add target for net6.0, keeping up with the latest frameworks.
- Add target for netcoreapp3.1, avoiding fallback to netstandard2.0 reference, which requires Bcl references

**Comment by kerams** [comment]
What's the point of the net6,0 (and existing net5.0) TFM?

**Comment by pakrym-stripe** [comment]
Work outlined in this issue is done.
