### ISSUE TITLE
StripeClient instance per controller vs. singleton

### ISSUE THREAD

**Issue by HappyNomad** [stripe/stripe-dotnet#2417]
I'm starting my first Stripe integration and need to know which of the following mutually exclusive alternatives, for Asp.Net Core, is the preferred approach.

# Option A
Controller constructors have `new StripeClient(`...

# Option B
`ConfigureServices` in `Startup.cs` has:

    services.AddSingleton<IStripeClient, StripeClient>(s => new StripeClient(

I've thoroughly searched but can't find the answer to this basic question.  I hope I get one here.

**Comment by pakrym-stripe** [comment]
Hey, have you seen some ASP.NET Core-specific samples that do that? Or do you mean the general-purpose samples?

**Comment by HappyNomad** [comment]
I only follow Asp.Net Core samples since that's what I use on the backend.

**Comment by pakrym-stripe** [comment]
Can you link to the sample you are following? I'll try to see if we can make it better.

**Comment by HappyNomad** [comment]
Thanks for your interest in improving the samples.  I followed along with the [Stripe.net playlist on Youtube](https://www.youtube.com/playlist?list=PLy1nL-pvL2M4cNNoUtjWevYSci4ubsbhC).  In particular, I watched and rewatched the episodes on [setting up an Asp.Net Core project](https://youtu.be/2-mMOB8MhmE) and [accepting a payment](https://youtu.be/mqEjRgoZWdo).

**Comment by bobbyangers** [comment]
Although the `HttpClient` should be a Singleton as per recommendent;  however the `IStripeClient` does not need to be.  
In fact each request should have it's own instance.

**Comment by cecilphillip-stripe** [comment]
@pakrym-stripe what do you think about using something like this using the httpclient factory

```csharp
   services.AddHttpClient("Stripe");
   services.AddTransient<IStripeClient, StripeClient>(s =>
   {
       var clientFactory = s.GetRequiredService<IHttpClientFactory>();
       var httpClient = new SystemNetHttpClient(
          httpClient: clientFactory.CreateClient("Stripe"),
          maxNetworkRetries: StripeConfiguration.MaxNetworkRetries,
          appInfo: appInfo,
          enableTelemetry: StripeConfiguration.EnableTelemetry);

        return new StripeClient(apiKey: StripeConfiguration.ApiKey, httpClient: httpClient);
   });
```

**Comment by cecilphillip-stripe** [comment]
@HappyNomad Is this resolved for you?

**Comment by pakrym-stripe** [comment]
Closing as the original question is answered. The general DI support can be discussed in #1882
