### ISSUE TITLE
Runtime failures on netcoreapp3.1 target after v39.90.0

### ISSUE THREAD

**Issue by lukejoshuapark** [stripe/stripe-dotnet#2420]
Hi there - I've noticed a runtime issue in an existing netcoreapp3.1 project that I believe was initiated by the changes in #2411.

On v39.89.0 - the application runs fine and without error.  On v39.90.0, it produces the following runtime error at startup:

```
An assembly specified in the application dependencies manifest (Some.Redacted.Project.Name.deps.json) was not found:
package: 'System.Drawing.Common', version: '4.7.0'
path: 'runtimes/unix/lib/netcoreapp3.0/System.Drawing.Common.dll'
```

I can reliably tweak the version number of `Stripe.net` to produce/prevent this error.  Is there some project-local setup that might be affecting this for me?  Any advice appreciated.

Thanks

**Comment by pakrym-stripe** [comment]
Hey @lukejoshuapark, what version of of .NET SDK are you using? This issue looks related to https://github.com/dotnet/sdk/issues/11489 . 

What's interesting is that Stripe doesn't have a transitive dependency on `System.Drawing.Common`. Do you have some other dependencies that can bring it into restore graph?

**Comment by lukejoshuapark** [comment]
Hey @pakrym-stripe - thanks for linking that issue, I didn't find that in my initial search. 👍  It certainly does seem related - although, like you say, there are no transitive dependencies on `System.Drawing.Common`.

Further, the following

```
dotnet list package --include-transitive | grep "System.Drawing.Common"
```

Gives no results. 😢 I'm using the 3.1 SDK - interesting that the runtime path is looking up `netcoreapp3.0`.

**Comment by pakrym-stripe** [comment]
Can you take a look at the deps.json and try to find what package declares `System.Drawing.Common` as a dependency?

**Comment by pakrym-stripe** [comment]
Is there a chance you can try .NET 6 SDK to see if the issue still reproes?

**Comment by lukejoshuapark** [comment]
Hey @pakrym-stripe - I think I've made some progress.  The `deps.json` file showed the following chain of dependencies:

```
Stripe.net/39.90.0
-> System.Configuration.ConfigurationManager/4.7.0
-> -> System.Security.Permissions/4.7.0
-> -> -> System.Windows.Extensions/4.7.0
-> -> -> -> System.Drawing.Common/4.7.0
```

It looks like the version 4.5.0 of `System.Security.Permissions` (the one used indirectly by `Stripe.net/39.89.0`) did not rely on `System.Windows.Extensions`, but version 4.7.0 does, hence the dependency.

**Comment by lukejoshuapark** [comment]
I created #2423 to downgrade the version - not sure if that is the best route forward or what.  Will do some testing with newer SDKs.

**Comment by pakrym-stripe** [comment]
Is it possible to share more details from you csproj? 

I tried to repro your problem using the following project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Stripe.net" Version="39.90.0" />
  </ItemGroup>

</Project>
```

and 

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.416
 Commit:    8d3765c609

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.17
 OS Platform: Darwin
 RID:         osx-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.416/

Host (useful for support):
  Version: 3.1.22
  Commit:  35fa579a30

.NET Core SDKs installed:
  3.1.416 [/usr/local/share/dotnet/sdk]
```

But the build produces an expected folder structure and the app runs successfully.

**Comment by lukejoshuapark** [comment]
@pakrym-stripe Sure, the project that actually depends on Stripe looks like this:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Stripe.net" Version="39.89.0" />
  </ItemGroup>

</Project>
```

The project that depends on the one above, and is the one that is run, looks like this:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Stripe.Project.Shown.Above\Stripe.Project.Shown.Above.csproj" />
  </ItemGroup>

</Project>

```

I've removed some other project references.  Also potentially worth noting is that the runtime env for this is Linux in AWS Lambda.

**Comment by pakrym-stripe** [comment]
Is it possible that you don't include the `runtimes` directory from the output path in the container image?

**Comment by lukejoshuapark** [comment]
@pakrym-stripe Ahhhh yep you're bang on - my build step wasn't recursively copying sub-directories into the container, just the `publish` top-level.  Didn't even think to check that.  Thanks for all your help, much appreciated.  I'll close this issue and the PR I opened.
