### ISSUE TITLE
ChargeService, CreateAsync is throwing exception but return type is Charge model

### ISSUE THREAD

**Issue by goors** [stripe/stripe-dotnet#2451]
So, it is really simple:

```
var service = new ChargeService();
var charge = await service.CreateAsync(options); -> this should return Charge and not throwing exception.
```

This will throw exception when transaction requires authentication.

There is no difference if I use `service.Create(options)`. I got same thing.

Nuget version is: 39.104.0

**Comment by goors** [comment]
I do not see the reason why this response does not have payment intent?
I mean in your docs it says:

**Required for businesses that accept multiple payment methods and cards requiring authentication (for example, due to [Strong Customer Authentication](https://stripe.com/docs/strong-customer-authentication) in Europe).**


I really do not want to create customer or attach/create customer card on your system. Payment intents only work if you:

1. create customer
2. add/attach car to the customer

And you keep their credit cards on your system. I don't see any reason for that.

**Comment by goors** [comment]
if you do try / catch you can get charge request by id in exception but again if error is of `authentication_required` you should really try to do payment intent return so i can redirect customer to bank website or app or what ever page is used for authorising payment.

**Comment by remi-stripe** [comment]
Hey @goors Github issues are limited to bugs with the library itself. Here you're more asking integration questions better directed at our support team which you can contact here: https://support.stripe.com/contact
