### ISSUE TITLE
What is the purpose of the SourceType class?

### ISSUE THREAD

**Issue by IanKemp** [stripe/stripe-dotnet#2456]
https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Constants/SourceType.cs

It _appears_ to enumerate the available payment methods available, but is incomplete, e.g. missing `bacs_debit` and `us_bank_account` among others. It also seems that the Stripe code doesn't use this class at all, e.g. `JsonPropertyAttribute("sepa_debit")` instead of `JsonPropertyAttribute(SourceType.SepaDebit)`.

What is this class intended to represent and can/should I rely on its existence going forward?

**Comment by kamil-stripe** [comment]
Hi @IanKemp! `SourceType` class exists to provide some convenience for users integrating with Stripe. It is safe to rely on this class and we apologize it got outdated. It's being updated in https://github.com/stripe/stripe-dotnet/pull/2458. Thank you for bringing this to our attention.
