### ISSUE TITLE
Alternative way to specify API key

### ISSUE THREAD

**Issue by asmith3006** [stripe/stripe-dotnet#2464]
### Is your feature request related to a problem? Please describe.

Currently ApiKey is a static attribute of StripeConfiguration. This means that running a system with multiple Strip accounts on it is impossible as you can't use different API keys for different calls. 

### Describe the solution you'd like

Either instantiate a new Stripe() object and pass in API key as the constructor, then all subsequent methods (Session Create etc.) are called on this object, or allow SessionService to take in API keys or a Config object when making it.

**Comment by yejia-stripe** [comment]
Hi @asmith3006, thank you for the suggestion! You're right, we don't support multiple StripeClients at once. As a work-around, does [per-request configuration](https://github.com/stripe/stripe-dotnet#per-request-configuration) work for your use cases?

**Comment by cecilphillip-stripe** [comment]
@yejia-stripe's solution is probably the easiest way to achieve what you're looking for.
 
@asmith3006  What type of app are you build (web/desktop)? Are you on .NET Framework or one of the newer runtimes?
 
 If you're using a DI container, you might also be able to control the creation of a new [IStripeClient](https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Infrastructure/Public/IStripeClient.cs) as shown [here](https://github.com/stripe/stripe-dotnet/issues/2417#issuecomment-1098564265).

**Comment by pakrym-stripe** [comment]
The `StripeClient` constructor takes an `apiKey` as a parameter. You can then use the `StripeClient` to create service instances:

```C#
var service = new CustomerService(new StripeClient(apiKey: "....."));
```

**Comment by asmith3006** [comment]
I think it would work, thanks @yejia-stripe  and @pakrym-stripe , really helpful.
