### ISSUE TITLE
.NET library remove property from request body if it is null

### ISSUE THREAD

**Issue by Avi-0510** [stripe/stripe-dotnet#2466]
### Describe the bug

It seems like the .NET library will remove the data in the request body if any property is set to null.

### To Reproduce

1. create a customer along with a shipping address.
2. Try to update the Customer's Shipping address with null.
        var options = new CustomerUpdateOptions
        {
          Shipping = null
        };
3. API response with 200 but Shipping address doesn't get updated.

### Expected behavior

It should remove the Shipping address from the customer.

### OS

Windows

### .NET version

3.0

### Library version

39.48.0

### API version

2020-08-27

**Comment by pakrym-stripe** [comment]
Hi @Avi-0510, 

Unfortunately `null` as a property value in update properties can mean two things:
1. Don't perform an update.
2. Set the property to null.

Stripe.NET uses the first as the default behavior so having a property set to null is treated as "don't do anything".

You can force the library to send `null` by using `ExtraParams`:

```C#
 await service.UpdateAsync(customer.Id, new CustomerUpdateOptions()
                {
                    ExtraParams =
                    {
                        {"shipping", null}
                    }
                });
```
