### ISSUE TITLE
Stripe.Events static class is missing event definitions declared in Webhook API documentation

### ISSUE THREAD

**Issue by mark-allott** [stripe/stripe-dotnet#2469]
### Describe the bug

The dotnet project is missing definitions from the webhook events that are present in other implementations for the following:

- payment_link.created
- payment_link.updated
- transfer.failed
- transfer.paid

(example: see https://github.com/stripe/stripe-php/blob/8275e7a8ee4aa8890baf581bde12a1fe5b201ebd/lib/Event.php#L171 and https://github.com/stripe/stripe-php/blob/8275e7a8ee4aa8890baf581bde12a1fe5b201ebd/lib/Event.php#L251 )

Another webhook event appears in the code, but has no documentation for it, as defined in page https://stripe.com/docs/api/webhook_endpoints/create :
payment.created (see https://github.com/stripe/stripe-dotnet/blob/8b1725b48c5ea3142f0fbe2e32661d62734b9324/src/Stripe.net/Constants/Events.cs#L520 )

### To Reproduce

Within an existing project dotnet project:

1. install latest stripe-dotnet package from package manager console / NuGet UI  - i.e. v39.107.0 released 21-Apr-2022
2. using the example code, as shown here: https://stripe.com/docs/webhooks , include an additional "if" clause, or convert to a switch statement and try to use the following events using the pre-defined constants:

```c#
switch (stripeEvent.Type)
  {
    case Events.PaymentLinkCreated:
      break;
    case Events.PaymentLinkUpdated:
      break;
    case Events.TransferFailed:
      break;
    case Events.TransferPaid:
      break;
    ...
  }
```

### Expected behavior

Intellisense should be able to locate definitions for the events, but cannot locate them as they are not defined in the stripe-dotnet/src/stripe.net/constants/events.cs file (see https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Constants/Events.cs )

### OS

N/A

### .NET version

net6.0

### Library version

stripe-dotnet 39.107.0

### API version

2020-08-27

**Comment by remi-stripe** [comment]
@mark-allott Thanks for the report. I opened a PR to fix this https://github.com/stripe/stripe-dotnet/pull/2470

`transfer.failed` and `transfer.paid` are legacy events that can't happen on a recent API version so you'd never receive them. They should be hidden from our API Reference, but can't be hidden for internal reasons unfortunately but you can ignore them.

**Comment by mark-allott** [comment]
@remi-stripe - thanks for the quick turnaround on the additions.
Might I suggest adding the `Obsolete` decorator to the `transfer.failed` and `transfer.paid` events - as has been done with the declaration for `InvoicePaymentSucceeded`. That would have the added benefit for other developers in immediately notifying them that the code they are trying to use has been deprecated by showing it as a CS0618 compiler warning 😉

**Comment by remi-stripe** [comment]
@mark-allott That's quite different though. `invoice.payment_succeeded` still exists and can be received on the latest API version. It's just considered deprecated in favour of `invoice.paid`. The other events `transfer.failed` and `transfer.paid` can't be received on the latest API version. They have been deprecated and removed in 2017, they are just in the API reference for legacy reasons that is hard to fix in the docs, but they are not in the library as they can't happen.

**Comment by mark-allott** [comment]
@remi-stripe - I understand. Documentation tells us it "exists", but in reality, those events can never happen because they have been removed from the codebase. It's a shame the documentation isn't as easy to update with obsolete/deprecated tags as the code is!

**Comment by mark-allott** [comment]
@remi-stripe - I understand. Documentation tells us it "exists", but in reality, those events can never happen because they have been removed from the codebase. It's a shame the documentation isn't as easy to update with obsolete/deprecated tags as the code is!

**Comment by mark-allott** [comment]
Thanks @remi-stripe - I now see that we have the missing events declared in the 39.109.0 package published 05-May-2022 😁
