### ISSUE TITLE
inApp Checkout

### ISSUE THREAD

**Issue by jrahma** [stripe/stripe-dotnet#2471]
### Describe the solution you'd like

Hi,

It will be great if you add an SDK to use with mobile apps and websites as well.

For example, if we will use the stripe in Xamarin or MAUI app and we want to have an inApp check out that will have the credit card processing and we can enable or disable any feature.

**Comment by pakrym-stripe** [comment]
Hi @jrahma, can you please clarify what feature are you looking for in a library?

**Comment by jrahma** [comment]
@pakrym-stripe  what I mean is an SDK where you just pass few parameters and it will take care of the rest by showing inApp payment popup similar to the attached images.

for example, I will pass the currency and amount to:

```
StripeInAppOptions inAppoption = new StripeInAppOptions();
inAppoption.GooglePay = true;
inAppoption.SamsungPay = true;
inAppoption.ApplePay = true;
inAppoption.Visa = true;
inAppoption.MasterCard = true;

Stripe.ShowInApp(string currency, decimal amount)

```

and then it will show the inApp payment where the user pay using the selected payment methods.

Once done, the StripeInApp will return the callback details including:

- Completed
- Declined
- Cancelled
- etc...
-
