### ISSUE TITLE
PaymentIntent.PaymentMethod.Card.RawJObject

### ISSUE THREAD

**Issue by prashant-samisen** [stripe/stripe-dotnet#2476]
### Describe the bug

I depend on PaymentIntent.PaymentMethod.Card.RawJObject to access brand_product value for card payment. However, the RawObject is sometimes present and sometimes null. Should this always work?

### To Reproduce

Create a PaymentIntent Service and do a Get using a payment intent id for a card payment.

### Expected behavior

The RawJObject is not null.

### Code snippets

```csharp
private CardProduct? GetProductCode(PaymentIntent paymentIntent)
  {
    CardProduct? cardProductCode = null;

    if (paymentIntent?.PaymentMethod?.Card?.RawJObject?["brand_product"] != null)
    {
      string? productCode = (string?)(paymentIntent.PaymentMethod.Card?.RawJObject["brand_product"]);

      cardProductCode = _dataAccessService.GetCardProductCode(productCode);
    }

    return cardProductCode;
  }
```

### OS

Windows

### .NET version

.NET 6

### Library version

Stripe.net (39.110.0)

### API version

2020-08-27

**Comment by clement911** [comment]
Also see https://github.com/stripe/stripe-dotnet/pull/2258

**Comment by pakrym-stripe** [comment]
Fixed in https://github.com/stripe/stripe-dotnet/pull/2258
