### ISSUE TITLE
SourceType class is still missing some members

### ISSUE THREAD

**Issue by IanKemp** [stripe/stripe-dotnet#2477]
### Is your feature request related to a problem? Please describe.

Missing members in [`SourceType`](https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Constants/SourceType.cs) that are currently present on [`PaymentMethod`](https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Entities/PaymentMethods/PaymentMethod.cs):

* AfterpayClearpay 
* BacsDebit
* Boleto
* Fpx
* Grabpay
* InteracPresent
* Oxxo
* UsBankAccount
* WechatPay (there is `Wechat` but that should probably be renamed)

### Describe the solution you'd like

Add the missing members.

### Describe alternatives you've considered

Maintain the list myself, which is painful.

**Comment by remi-stripe** [comment]
@IanKemp the `SourceType` class maps to the enum values that `type` on `Source` can take. The `Source` API is legacy and has been deprecated for multiple years. It's been replaced by the `PaymentMethod` API. All the examples you mentioned do **not** exist on the legacy Source API and have only been built on the newer PaymentMethod API. You should completely ignore the `Source` and `SourceType` classes really and focus on the `PaymentMethod` class.

**Comment by IanKemp** [comment]
@remi-stripe then where can I find constants for the [available payment method types](https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Services/PaymentMethods/PaymentMethodCreateOptions.cs#L187) when I am creating a payment method? For example, if I want to create a BACS debit payment, I have to do something like:

```cs
var paymentMethod = new PaymentMethodCreateOptions
{
    Type = "bacs_debit",
    ....
};
```

Note the string literal `"bacs_debit"` - which I now have to maintain in my code, along with the string literals for every other payment method type I need to support.

If `SourceType` is not the correct place for these constants, could you please create a `PaymentMethodType` (or similar) class enumerating them?

**Comment by remi-stripe** [comment]
@IanKemp We don't have plans for now to create an equivalent class. Our stripe-dotnet library doesn't really have enum support today and the `SourceType` one was a legacy exception that we haven't really maintained. This means you'll have to hardcode the string instead, which is similar to how all our other APIs work in the library.

**Comment by IanKemp** [comment]
> @IanKemp This means you'll have to hardcode the string instead, which is similar to how all our other APIs work in the library.

The whole point of a library is to encapsulate domain-specific concepts so that consumers don't have to do that. Forcing consumers to define and maintain these constants that you, Stripe, are responsible for creating and maintaining is both nonsensical and inconvenient. Please reconsider.

**Comment by remi-stripe** [comment]
@IanKemp We won't reconsider this decision for now unfortunately. We do agree that having a way to support all enum values in the future would be a great addition and it's something we want to offer, but we won't add a one-off constant like this for `PaymentMethod` until we have a scalable solution for all enums.
