### ISSUE TITLE
Missing property subscription.on_behalf_of

### ISSUE THREAD

**Issue by clement911** [stripe/stripe-dotnet#2493]
### Is your feature request related to a problem? Please describe.

Yes, I cannot see the field on_behalf_of on the subscription object

### Describe the solution you'd like

Added the property on_behalf_of to the subscription object

### Additional context

See https://stripe.com/docs/api/subscriptions/object#subscription_object-on_behalf_of

**Comment by clement911** [comment]
@remi-stripe I see.

I didn't raise a bug, I raised a feature request.

But what is the point of even releasing preview features if we can't even use them?

We'd use _StripeEntity.RawJObject_ but it's broken. I've submitted a [PR](https://github.com/stripe/stripe-dotnet/pull/2258) to fix it, was told that someone would look at it within a week, and it's been a year and a half and the PR is still open...

p.s: Stripe support is telling me that this feature is reliable and I can start using it. Not sure how though...

**Comment by remi-stripe** [comment]
@clement911 I know you did submit a feature request, but it's not really an improvement to the library. It's asking for something that is automatically generated and will be in the library once the feature get publicly released. We would have dozens of issues open on things that are mostly expected to be out of the library. We also avoid discussing/leaking secret features in the library, they are private and in beta for usually good reasons.

The Preview feature can be used in most cases too, both via `AddExtraParam` and `RawJObject`. I know it's not perfect but it does mostly work for a lot of beta features like this one.

I'm sorry for the delay on your PR, some things did fall through the cracks on our end as some features are less high priority than others. I'll flag internally again.

**Comment by clement911** [comment]
> @clement911 I know you did submit a feature request, but it's not really an improvement to the library. It's asking for something that is automatically generated and will be in the library once the feature get publicly released. We would have dozens of issues open on things that are mostly expected to be out of the library. We also avoid discussing/leaking secret features in the library, they are private and in beta for usually good reasons.

That's fair and I understand, though I had no idea that I was behind a private flag and in a beta. Stripe support didn't mention that to me and just told me that I should be able to use this new field starting right now.

> I'm sorry for the delay on your PR, some things did fall through the cracks on our end as some features are less high priority than others. I'll flag internally again.

Thanks, I appreciate it. I honestly don't believe that `StripeEntity.RawJObject` is usable as it is.
