### ISSUE TITLE
CouponCreateOptions.AmountOff to be decimal

### ISSUE THREAD

**Issue by VesselinVassilev** [stripe/stripe-dotnet#2504]
### Is your feature request related to a problem? Please describe.

Why is AmountOff property of the CouponCreateOptions class long? and not decimal? ?

On our checkout page, the user may see that the discount is $100.40, but when they go to Stripe checkout the discount is shown as $100 which is confusing.

Why not use decimal for AmountOff? 

### Describe the solution you'd like

change CouponCreateOptions.AmountOff to decimal?

**Comment by remi-stripe** [comment]
@VesselinVassilev All amounts are in the smallest currency unit for that currency. If you have `currency: 'usd'` and `amount: 
 100` then it means 100 _cents_ or $1.00 off, not $100. This mirrors how most of the amounts properties and parameters work in our API. 

If you have any followup questions, please don't hesitate to chat with our support team directly for help: https://support.stripe.com/contact
