### ISSUE TITLE
PaymentMethodWechatPayOptions has no properties

### ISSUE THREAD

**Issue by TomGullen** [stripe/stripe-dotnet#2552]
### Describe the bug

As per: 
https://stripe.com/docs/api/payment_intents/create

payment_method_options.wechat_pay.client is a required property when creating a payment intent with a Wechat payment method.

When attempting to create a new payment intent with WeChat, it returns:
Missing required param: payment_method_options[wechat_pay][client].

Please add in the documented properties for the PaymentMethodWechatPayOptions object

### To Reproduce

1. Create Wechat payment method
2. Create new Payment Method using created payment method
3. Attempt payment

### Expected behavior

Payment should proceed

### Code snippets

```csharp
case PaymentMethod.WeChat:
    {
        newPaymentMethodOptions.WechatPay = new PaymentMethodWechatPayOptions
        {
            Client = "web"
        };
        break;
    }
```

### OS

N/a

### .NET version

4.8

### Library version

40.0.0

### API version

2020-08-27

**Comment by TomGullen** [comment]
Work around:
paymentIntentOptions.AddExtraParam("payment_method_options[wechat_pay][client]", "web");

**Comment by yejia-stripe** [comment]
Hi @TomGullen, thanks for the report. `PaymentMethodWechatPayOptions` is for the PaymentMethod methods, which do not have any fields for WeChat Pay: https://stripe.com/docs/api/payment_methods/create#create_payment_method-wechat_pay.

For creating a payment intent, please use [`PaymentIntentPaymentMethodOptionsWechatPayOptions`](https://github.com/stripe/stripe-dotnet/blob/d0324ef956c0e79cf9e4ef894e03e9f8a2c92a1e/src/Stripe.net/Services/PaymentIntents/PaymentIntentPaymentMethodOptionsWechatPayOptions.cs#L6), which does have the `client` property.

Closing as I don't believe this is a bug with the library itself.
