### ISSUE TITLE
Using latest 41.1.0 with web hook using 22-11-15 API causes API type mismatch error

### ISSUE THREAD

**Issue by GusBeare** [stripe/stripe-dotnet#2611]
### Describe the bug

I have my web hook using the latest API and I am using the latest stripe.net but I am getting this error:

Stripe.StripeException: Received event with API version 2022-08-01, but Stripe.net 41.1.0 expects API version 2022-11-15. We recommend that you create a WebhookEndpoint with this API version. Otherwise, you can disable this exception by passing `throwOnApiVersionMismatch: false` to `Stripe.EventUtility.ParseEvent` or `Stripe.EventUtility.ConstructEvent`, but be wary that objects may be incorrectly deserialized.
   at Stripe.EventUtility.ParseEvent(String json, Boolean throwOnApiVersionMismatch) in /_/src/Stripe.net/Services/Events/EventUtility.cs:line 47

I have worked around this for now setting throwOnApiVersionMismatch to false. But why is Stripe using older API when I have set to latest in my account?  I am not experiencing this on a test site only on the live Stripe account.

Am I misunderstanding something here or has Stripe.NEt not fully switched to latest API for my account or am I missing something silly?

### To Reproduce

Set up web hook with latest API. 
Use latest stripe.Net with default setting for version mismatch error.

    var objStripeEvent = EventUtility.ParseEvent(json);

### Expected behavior

The error should not be raised when the API version matches that expected by stripe.Net 41.1.0.

### Code snippets

```csharp
setting API mismatch to false fixes it.
 
var objStripeEvent = EventUtility.ParseEvent(json, false);
```

### OS

windows

### .NET version

.Net 7

### Library version

nuget 41.1.0

### API version

2022-11-15

**Comment by remi-stripe** [comment]
Hey @GusBeare, the current API version on the library is defined [here](https://github.com/stripe/stripe-dotnet/blob/8d884932be74eaa5f9c939138960e7f6db3ffc76/src/Stripe.net/Constants/ApiVersion.cs#L6) and is correctly set to the latest API version `2022-11-15`.

If you get that error, it must mean that your WebhookEndpoint is mis-configured to use the previous API version `2022-08-01` instead. There's no other place in the library where the API is defined so it can only be that. You should be able to look at the Event itself in the Dashboard, look at the webhook conversation details there and it would show you which API version was used to generate it.

If unsure, you might want to talk to our support team directly at https://support.stripe.com/contact or ask for help on our Discord server: https://stripe.com/go/developer-chat

**Comment by GusBeare** [comment]
Hi and thanks for your comments.

I've just looked at the web hook and I had set the API version on both the hook and the account to the latest version last night.

But it appears that the web hook has been posting back to my end point with different versions of the API today.
It's a nightmare because I have several bookings that have been left open but the customer has paid. I may now be facing over-bookings.

See attached. One image shows failed requests that have been sent using api 2022-08-01 and the other shows successful posts to the latest API version. 2022-11-15.

I am hoping it's settled down now but there appears to be something very odd happening.

![Capture1](https://user-images.githubusercontent.com/5166509/203590101-19dd90b1-617f-4cef-9ae5-8225d3b94911.JPG)

![Capture2](https://user-images.githubusercontent.com/5166509/203590083-98d98ba1-d44b-42e5-807e-49429163abb8.JPG)

**Comment by GusBeare** [comment]
Have a look at these two. At 13:58 a post was sent using the new API version. Then a post was sent using the old one and then it went back to the new one!  
![Capture3](https://user-images.githubusercontent.com/5166509/203593741-e5626d59-5993-49a7-a5fe-9db8c4441217.JPG)
![Capture4](https://user-images.githubusercontent.com/5166509/203593745-a5558092-82dc-466d-9cc6-058a32b6aedd.JPG)

**Comment by remi-stripe** [comment]
This clearly indicates that stripe-dotnet is working correctly here. Sometimes it receives Events with API version `2022-11-15` and sometimes with `2022-08-01` and it rightfully errors for the latter.

I can't speak to why here, this is specific to your own account and its configuration. It's likely that those are retries from Events generated before you created the new endpoint with newer API version. Ultimately there's no issue with the library so for now please work with our support team for help instead.

**Comment by GusBeare** [comment]
Ok, thanks. Retries would make sense.

**Comment by clement911** [comment]
Unfortunately, the Webhook API doesn't allow updating the version.
We have added some logic in our app startup logic to list all existing webhooks and compare their versions against the Stripe.NET lib version and take action accordingly.

**Comment by GusBeare** [comment]
That's a useful approach. Thanks for sharing.
