### ISSUE TITLE
Events.CheckoutSessionCompleted contains no coupon information

### ISSUE THREAD

**Issue by spaddlewit** [stripe/stripe-dotnet#2612]
### Describe the bug

The CheckoutSessionCompleted event contains no coupon information from the completed checkout session.

I thought maybe the individual LineItems might contain information about it, so I tried:
            var service = new SessionService();
            session.LineItems = await service.ListLineItemsAsync(session.Id, new SessionListLineItemsOptions
            {
                Limit = 1,
            });

Yet session.LineItems.First().Discounts is null.

### To Reproduce

On a WebHook callback for CheckoutSessionCompleted, call

            var service = new SessionService();
            session.LineItems = await service.ListLineItemsAsync(session.Id, new SessionListLineItemsOptions
            {
                Limit = 1,
            });

### Expected behavior

Line item obejcts should have Discount information with coupon ID.

### OS

windows

### .NET version

.NET 6

### Library version

stripe-dotnet v40.15.0

### API version

2022-08-01

**Comment by remi-stripe** [comment]
Hey @spaddlewit, Github issues should be limited to bugs with the library itself. This is more a question about what the API itself can or can't do which is better directed to our support team: https://support.stripe.com/contact

To unblock you quickly though, this is already available and has been for a while. There's a `total_details` [property](https://stripe.com/docs/api/checkout/sessions/object#checkout_session_object-total_details) on the `Session` that has information about how the total amount was calculated, this in turn contains the `breakdown` [property](https://stripe.com/docs/api/checkout/sessions/object#checkout_session_object-total_details-breakdown) which then has the `discounts` [property](https://stripe.com/docs/api/checkout/sessions/object#checkout_session_object-total_details-breakdown-discounts). All of this has the information you're after.

This is not returned by default and you have to use our [Expand feature](https://stripe.com/docs/expand) to access it when you retrieve the Session via the API. You can't get this directly in the Event we send to your webhook endpoint.

**Comment by spaddlewit** [comment]
Thank you, @remi-stripe . I already contacted support and they came up empty handed. Thank you!
