### ISSUE TITLE
Partial refund

### ISSUE THREAD

**Issue by deform188** [stripe/stripe-dotnet#2624]
### Describe the bug

When i try create partial refund i specify amound 

await _refundService.CreateAsync(options);

But it return full refund

### To Reproduce

1. Create refund options 
var options = new RefundCreateOptions
            {
               Charge = payment.TransactionId,
               Amount = 10
            };
2. Create refund service
await _refundService.CreateAsync(options);

### Expected behavior

Partial refund

### OS

Windows 11

### .NET version

Core 6

### Library version

Stripe.net Version="41.2.0"

### API version

2022

**Comment by remi-stripe** [comment]
@deform188 This is unlikely to be an issue with the library and more likely with the way you are testing. I'd recommend working with our support team directly and providing example transactions and they can help you figure out what is causing the issue: https://support.stripe.com/contact
