### ISSUE TITLE
Expand object on Customer for `invoice_settings.devault_payment_method` never actually expands (always null)

### ISSUE THREAD

**Issue by abelbraaksma** [stripe/stripe-dotnet#2631]
### Describe the bug

The following always fails for us, even though in Stripe we clearly see the customer having "default" on their sole CC payment.

```c#
var customer = custSvc.GetAsync(id, options = CustomerGetOptions(Expand = List("invoice_settings.default_payment_method"), requestOptions)

customer.InvoiceSettings.DefaultPaymentMethod // always null
```

What we want to do is:
* get the default payment method
* verify it's there (non-null)
* verify it is set to CC
* verify it is non-expired / valid

### To Reproduce

See snippet above

### Expected behavior

The `invoice_settings` should be expanded. But it doesn't expand, ever. Using `DefaultSource` as alternative works, but is deprecated.

### OS

any

### .NET version

.NET 6 & 7

### Library version

current

### API version

current

**Comment by remi-stripe** [comment]
Hey @abelbraaksma! This is unlikely to be a bug with the library itself and more with your setup. My guess is that you use an older integration where your Customer has a `Card` object `card_123` attached and that makes it the `default_source` automatically and you likely never set `invoice_settings.default_payment_method`. I assume the property is empty even without expansion.

You need to either make sure you properly set that value yourself, or also look at `DefaultSource` on the Customer` otherwise in your code.

I'm going to close as this is more an integration support question but you can talk to our support team [here](https://support.stripe.com/contact) or talk to developers on our Discord server [here](https://stripe.com/go/developer-chat) for further help.

**Comment by abelbraaksma** [comment]
>  I assume the property is empty even without expansion.

that's correct

> and you likely never set `invoice_settings.default_payment_method`

also correct. The documentation suggested that these settings are used for the default payment method and that `default_source` is deprecated. We don't set the default methods programmatically ourselves, but Stripe does that through Stripe Elements when a first payment is made.

@remi-stripe You seem to suggest that this setting can be either, none, or both of these and that `default_source` should not be considered deprecated for that reason. Is that correct? So, pseudocode:

```
var defSource = getDefaultSource
var defSettings = getDefaultPaymentSettings
if isNull defSource and isNull defSettings then --> no default payment method
if not(isNull defSource) then --> default payment method is default source
otherwise default payment method is from default settings
```

is that assumption ☝️ correct?

**Comment by abelbraaksma** [comment]
I've meanwhile asked this in Discord. For legacy reasons and others dealing with the rather odd discrepancy here:

![image](https://user-images.githubusercontent.com/16015770/211581354-63f2b76d-d470-4389-963f-bf70a949615f.png)

And:

![image](https://user-images.githubusercontent.com/16015770/211581488-51b8eaef-b3de-443d-830e-3bb81d99364e.png)

**Comment by abelbraaksma** [comment]
To be _"liberal in what we accept"_, and that's true for any client that tries to _read_ these properties, at the very least, we'd need to check both `customer.invoice_settings.default_payment_method` and `customer.default_source`, and pick the one that's set and has highest priority.

**Comment by remi-stripe** [comment]
Please work directly with our support team or engineers on Discord for further help with this. This really isn't specific to stripe-dotnet so it's not something I can help with here sorry

**Comment by abelbraaksma** [comment]
Ehm, I think you misread my comments above? It’s all sorted, thanks! And indeed, it’s not specific to Stripe.NET.
