### ISSUE TITLE
Dependencies in Net7

### ISSUE THREAD

**Issue by jonrmorgan99** [stripe/stripe-dotnet#2639]
### Describe the bug

The dependency list for Stripe.Net v41.5 under net6 includes:

Newtonsoft.Json (>=12.0.,3)
System.Configuration.Configuration.Manager (>=5.0.0)

However my Stripe integration runs fine thru checkout without Configuratio.Manager.
Is it really a requirement ?

### To Reproduce

1. In Visual studio 2022 go Tools>NuGet Package manager>Manage NuGet Packages for SOlution
2. Install Stripe.Net in a test app.
3. Check the Dependencies list in Package Manager>Options

### Expected behavior

I would expect to see a dependency list for Net 7

### OS

Win10

### .NET version

.Net 7

### Library version

stripe.net 41.5

### API version

2023-1-19

**Comment by pakrym-stripe** [comment]
It might be a problem with the dependency list. `System.Configuration.ConfigurationManager` is required and is included in the transitive package closure.

```
> dotnet new console
> dotnet add package Stripe.net
> dotnet list package --include-transitive
Project 'dn7' has the following package references
   [net7.0]:
   Top-level Package      Requested   Resolved
   > Stripe.net           41.5.0      41.5.0

   Transitive Package                                Resolved
   > Microsoft.Win32.SystemEvents                    6.0.0
   > Newtonsoft.Json                                 12.0.3
   > System.Configuration.ConfigurationManager       6.0.0
   > System.Drawing.Common                           6.0.0
   > System.Security.AccessControl                   6.0.0
   > System.Security.Cryptography.ProtectedData      6.0.0
   > System.Security.Permissions                     6.0.0
   > System.Windows.Extensions                       6.0.0
```

**Comment by jonrmorgan99** [comment]
Thanks for the really quick reply.
   
  
    
   
  
   Since "System.Configuration.ConfigurationManager is required and is included in the transitive package closure", does that mean I can deploy my app without including it in my deployment manifest ?
   
  
    
   
  
   Jon
   
   
   
    On 31/01/2023 17:46 GMT pakrym-stripe ***@***.***> wrote:
    
   
     
    
   
     
    
     
   It might be a problem with the dependency list. System.Configuration.ConfigurationManager is required and is included in the transitive package closure. 
   > dotnet new console
> dotnet add package Stripe.net
> dotnet list package --include-transitive
Project 'dn7' has the following package references
   [net7.0]:
   Top-level Package      Requested   Resolved
   > Stripe.net           41.5.0      41.5.0

   Transitive Package                                Resolved

**Comment by pakrym-stripe** [comment]
Yes, .NET tooling will handle that for you.
