### ISSUE TITLE
SessionAfterExpirationOptions not properly implemented

### ISSUE THREAD

**Issue by ShannonMac74** [stripe/stripe-dotnet#2641]
### Describe the bug

The code does not properly send SessionAfterExpirationOptions if not explicitly set.
Also SessionAfterExpirationOptions does not implement System.Collections.IEnumerable so it is not enumerable. 
Please provide details on how to properly implement this field since it appears to be required (although docmenation shows it as optional).
Our customers cannot complete Stripe Checkout as of today.

### To Reproduce

Attempt a Checkout Session without providing SessionAfterExpirationOptions.

### Expected behavior

Checkout Session should work.

### OS

Windows

### .NET version

.NET Framework 4.7.2

### Library version

stripe-dotnet 40.14.0

### API version

2022-08-01

**Comment by remi-stripe** [comment]
@ShannonMac74 Can you provide detailed information about the issue you're experiencing? The `after_expiration` parameter on the Create Checkout Session API is optional (see [doc](https://stripe.com/docs/api/checkout/sessions/create#create_checkout_session-after_expiration)) and it's expected that the vast majority of developers wouldn't need to pass this information.
It can be required in some cases where you enable other features of the API which require both but you should then get an error telling you what's missing.

If you could share your exact code and what the error message you get back is, I'd be happy to help.

**Comment by ShannonMac74** [comment]
I had been taking to "Rosie" with Stripe support. She's the one who told us that the after_expiration property was required. After much digging, we discovered that our issue is actually that the RedirectToStripe javascript has been deprecated, and that's what we'd been using.
Sorry about the red herring. This issue can be closed.
