### ISSUE TITLE
Can't find SubscriptionResumeAt in UpcomingInvoiceOptions object.

### ISSUE THREAD

**Issue by AlexeyMalashenko** [stripe/stripe-dotnet#2645]
### Describe the bug

I'm trying to calculate an upcoming payment for subscriptions with the "Pause" status. I get an error:

`The subscription is paused and will not generate invoices until it has been resumed. Pass the `subscription_resume_at` parameter to view the invoice that will be generated if the subscription is resumed.`

In your latest API update, I see 
- Add support for SubscriptionResumeAt on InvoiceUpcomingLinesOptions and InvoiceUpcomingOptions.

Docs for api have this parametrs https://stripe.com/docs/api/invoices/upcoming#upcoming_invoice-subscription_resume_at

But in the updated library(41.6.0) i can't find class InvoiceUpcomingOptions or InvoiceUpcomingLinesOptions  and any SubscriptionResumeAt  property. 

### To Reproduce

1. Have customer subscription with "pause" status.
2. Try to get upcoming invoice.

### Expected behavior

1. Get an upcoming invoice

### Code snippets
```
var options = new UpcomingInvoiceOptions
            {
                Subscription = subscription.SubscriptionExternalKey,
                SubscriptionProrationBehavior = "always_invoice",
                SubscriptionTrialEnd = SubscriptionTrialEnd.Now,
                SubscriptionBillingCycleAnchor = SubscriptionBillingCycleAnchor.Now,
                SubscriptionItems = items,
                SubscriptionProrationDate = prorationDate,
                AutomaticTax = new InvoiceAutomaticTaxOptions
                               {
                                   Enabled = true
                               },
               //missing subscription_resume_at
            };
```
_No response_

### OS

Windows

### .NET version

.NET Core 3.1

### Library version

https://www.nuget.org/packages/Stripe.net/41.6.0

### API version

2022-11-15

**Comment by remi-stripe** [comment]
Hey @AlexeyMalashenko Thanks for the report and sorry about the missing feature. We're working on a fix!
