### ISSUE TITLE
Terms of service checkbox

### ISSUE THREAD

**Issue by jmawebtech** [stripe/stripe-dotnet#2677]
### Describe the bug

Create Session > Content > No option for terms of service. I want users to agree to our terms of service, before subscribing.

consent_collection.terms_of_service
optional enum
If set to required, it requires customers to check a terms of service checkbox before being able to pay. There must be a valid terms of service URL set in your

https://stripe.com/docs/api/checkout/sessions/create

### To Reproduce

Install latest version of Stripe.NET
Under session create options, there is no terms of service:

            SessionCreateOptions options = new SessionCreateOptions
            {
                ConsentCollection = new SessionConsentCollectionOptions()
                {
                     
                }
}

### Expected behavior

I should see an option for terms of service.

### Code snippets

```csharp
public Stripe.Checkout.Session CreateStripeCheckoutSession(string priceId, string stripeCustomerId, string successUrl, string cancelUrl, string couponId, bool isTrial)
        {
            List<SessionLineItemOptions> items = new List<SessionLineItemOptions> 
            {
                new SessionLineItemOptions() {
                    Price = priceId,
                    Quantity = 1,
                }
            };

            SessionCreateOptions options = new SessionCreateOptions
            {
                ConsentCollection = new SessionConsentCollectionOptions()
                {
                     
                }
                SubscriptionData = new SessionSubscriptionDataOptions()
                {
                    TrialPeriodDays = isTrial ? 14 : null
                },
                Customer = String.IsNullOrEmpty(stripeCustomerId) ? null : stripeCustomerId,
                SuccessUrl = successUrl + "?sessionId={CHECKOUT_SESSION_ID}",
                CancelUrl = cancelUrl,
                PaymentMethodTypes = new List<string>
                  {
                    "card",
                  },
                LineItems = items,
                Mode = "subscription",
            };
```

### OS

Windows

### .NET version

.NET 6

### Library version

41.13.0

### API version

2020-08

**Comment by remi-stripe** [comment]
Hey @jmawebtech The stripe-dotnet library does support this option. You can see it used in [this code](https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Services/Checkout/Sessions/SessionCreateOptions.cs#L55) for `SessionCreateOptions` which references the class `SessionConsentCollectionOptions` defined in [this code](https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Services/Checkout/Sessions/SessionConsentCollectionOptions.cs) where we define the `TermsOfService` parameter at [this line](https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Services/Checkout/Sessions/SessionConsentCollectionOptions.cs#L25).

This matches what is covered in our documentation [here](https://stripe.com/docs/payments/checkout/customization#collect-a-terms-of-service-agreement) where we show
```
ConsentCollection = new SessionConsentCollectionOptions {
  TermsOfService = "required",
}
```

This feature shipped in September 2022 in the version 40.10.0 of stripe-dotnet per our [changelog](https://github.com/stripe/stripe-dotnet/blob/master/CHANGELOG.md#40100---2022-09-22).

If you don't see it, it's likely that your code uses an older version of stripe-dotnet and not the one you think. I'd recommend triple checking that library's version and making sure you upgrade. If you're unsure which version you're using, you can look at your logs in the Dashboard [here](https://dashboard.stripe.com/test/logs) and by loading a recent request it should show a `Source` section in the header of a request and it will log the exact version of stripe-dotnet you're on.

This looks more like an integration support question overall so I'm going to close but don't hesitate to contact our support team if you need further help: https://support.stripe.com/contact
