### ISSUE TITLE
BillingCycleAnchor & Trial for subscriptions in the checkout API

### ISSUE THREAD

**Issue by LeoRpc** [stripe/stripe-dotnet#2689]
### Is your feature request related to a problem? Please describe.

Hi,

You will find my constraints ans thought below. As far as I understand, this is a feature request, but if there is a way to achieve what I want with the existing API it would be perfect!

**Constraints and thoughts:**
1. I would like to write as less code as possible for my Stripe integration -> Checkout API
2. I would like all my customers to start and end cycles at the same point in the year (yearly subsription) -> BillingCycleAnchor
3. I would like to offer my customer a 14 days free trial -> TrialPeriodDays/TrialEnd

**The issue:** 'Stripe.StripeException' dans System.Private.CoreLib.dll: 'You may only specify one of these parameters: billing_cycle_anchor, trial_end.'

Thanks in advance :)
Leo.

### Describe the solution you'd like

Be able to set BillingCycleAnchor and Trial like in the Subscription API (https://stripe.com/docs/billing/subscriptions/trials#combine-trial-anchor)

### Additional context

I will also submit another feature request concerning the **ProrationBehavior** that could be related.

**Comment by remi-stripe** [comment]
Hey @LeoRpc! Thanks for the detailed feature request, unfortunately, Github issues should be limited to bugs with the library itself (here stripe-dotnet) and this is more a feature request for our API. I would recommend flagging this to our support team directly via our contact form [here](https://support.stripe.com/contact) to register your interest for this feature. It's unlikely we'll add this soon though as we just released support for `billing_cycle_anchor` and explicitly decided not to support combining both features for now but we'll track this as a request for future improvement.
