### ISSUE TITLE
Forward the Apple Pay token to Stripe using Stripe.net

### ISSUE THREAD

**Issue by demonguru18** [stripe/stripe-dotnet#2694]
### Is your feature request related to a problem? Please describe.

We have encountered a problem, after we successfully generate an Apple Pay token on our Mobile App for iOS using Ionic and Angular. We send the token to our backend written in Asp.Net to decrypt it using the Apple Decrypted Library. Using the Private Key and Provision Certificate, we are able to decrypt the token. We want to send this Decrypted to token to Stripe using Strip.net SDK. We cannot find any documentation to do so. When we contacted Stripe Support, we were told to communicate our request here on GitHub. If you can let us know if there is a way to forward the Token to Stripe or the steps to follow. 

Support Contact
![image](https://github.com/stripe/stripe-dotnet/assets/4347612/b671312c-2a48-47dc-b6b9-2abeccd5f458)
![image](https://github.com/stripe/stripe-dotnet/assets/4347612/7d13fcf3-9275-4599-863a-ccb2da8909c6)

Decrypted Token on Mobile app
![image](https://github.com/stripe/stripe-dotnet/assets/4347612/162aac91-1d6f-4fd2-a573-66d933304979)

Our Implementation
![image](https://github.com/stripe/stripe-dotnet/assets/4347612/089c89f3-6665-4631-b1df-7c6186654b5b)

Your help will be helpful as we need to implement this on 1000+ mobile apps build in Ionic and Angular. Currently our Merchants are using Stripe on their Websites and want to stick to Stripe on Mobile app as well for Payments.

### Describe the solution you'd like

Something like this  - Pass the token using 
Attach the decrypted Apple Pay token to the PaymentIntent object. You can use the following code to attach the token:
![image](https://github.com/stripe/stripe-dotnet/assets/4347612/99c3eaee-f44a-41d9-ac6e-5e713985da6a)

Once the PaymentIntent object is created and the decrypted Apple Pay token is attached, you can confirm the PaymentIntent using the Stripe.net library. You can use the following code to confirm the PaymentIntent:

![image](https://github.com/stripe/stripe-dotnet/assets/4347612/199b0fce-8ebf-4b44-a1f8-913262fba55b)

### Describe alternatives you've considered

We cannot find stripe Alternative, some suggestions say we can achieve this with Braintree, but we want to stick to stripe.net

### Additional context

This feature is very useful for us. Please do consider

**Comment by techFB** [comment]
@remi-stripe hello! I'm actually encountering a similar issue / use case on my end. We have multiple payment processors and it's critical for us to send send a decrypted apple pay token to stripe. So far wasn't able to solve this with support and found this thread maybe you can help out.

When trying to pass decrypted token to "pk_token" parameter, I'm getting "Your payment information is formatted improperly" error. But it does seem to work when passing an encrypted `paymentData` from the token.

My question here is, is there a way to actually pass a decrypted token, with our own certificates to Stripe?
This is how decrypted "paymentedData" JSON looked like in my pk_token request:
{
  applicationPrimaryAccountNumber: 'XXX',
  applicationExpirationDate: 'XXX',
  currencyCode: 'XXX',
  transactionAmount: XX,
  deviceManufacturerIdentifier: 'XXXX',
  paymentDataType: '3DSecure',
  paymentData: { onlinePaymentCryptogram: 'XXXXX' }
}
Maybe there's a different format I can use?

I've also tried to pass primaryAccount number / expiration date as normal credit card info with `/payment_intent` API, but additionally providing `three_d_secure` data. But there I'm encountering an issue that apple transaction id is not understood by stripe

 @demonguru18 where you able to solve your issue, if so how?

Thank you all in advance!

**Comment by remi-stripe** [comment]
@demonguru18 the `pk_token` parameter is not really supported anymore. We do have a beta that allows you to get access to do what you want. Unfortunately, only our support team can help. Go back to support, share a link to this Github issue and mention that I told you there's a real beta you need access to. They should be able to route you to the right place to get access to this feature.

**Comment by techFB** [comment]
@remi-stripe just a quick question. Is there some kind of specific name that this "beta" has that I can mention to support person or just linking this issue will be enough?

**Comment by remi-stripe** [comment]
Our betas don't really have names but you can tell them to look for a beta related to `wallets_decrypted_token_params` which might help

**Comment by techFB** [comment]
@remi-stripe thank you for helping out earlier! I've contacted support just as you said, they're currently working on this case 🙏

I was also able to figure out a temporary (not ideal) solution. And that is to pass 3DS cryptogram from apple pay token via [3DS api from here](https://docs.stripe.com/payments/payment-intents/three-d-secure-import). The only weird thing I had do to is to generate a random UUID for "transaction_id" there, because it seems to be incompatible with transaction_id from apple token. Approve rates seem to be fine for now. But probably won't recommend this outside of testing.

@remi-stripe I had one more question, maybe you know which direction to point me to. Let's say we have an internal database of apple pay DPANs and transaction_ids from our previous processor securely stored in accordance w/ PCI-DSS. Do you know if it's possible to perform an MIT (merchant initiated transaction) with stripe with this info? Maybe some additional verification is required from somewhere? (if we don't want to perform a general import and just do a specific MIT)

Thank you!

**Comment by remi-stripe** [comment]
@techFB I'd recommend talking to our support team for further help on those questions, I can't really answer this here sorry!

**Comment by techFB** [comment]
@remi-stripe Will do thanks!
