### ISSUE TITLE
3DS auth popup not render

### ISSUE THREAD

**Issue by carbonete** [stripe/stripe-dotnet#2719]
### Describe the bug

I'm developing using Xamarin Forms.

When calling checkout inside Webview in windows i use test card  4000002500003155 that need a second authorization step. But authorization popup not render, it's blank. Other cards works fine. If copy and paste checkout url to browser, it's work, rendering authentication popup.

 
![Capture_erro_render_3DS](https://github.com/stripe/stripe-dotnet/assets/3043885/c7767cea-b8d9-4a28-8f52-2b06671d78fa)

### To Reproduce

1. Create xamarin forms proj with webview screen.
2. Call stripe api to create checkout.
3. Pass returned url to webview and use 4000002500003155 card
4.

### Expected behavior

Render like inside any browser.

### OS

windows 10

### .NET version

.Net Standard 2.0

### Library version

Stripe.net 41.18.0

### API version

2022-11-15

**Comment by remi-stripe** [comment]
@carbonete Github issues are limited to bugs or feature requests with the stripe-dotnet library itself. Your question looks more like an integration support question rendering some client-side flow in your environment. Please work with our support team for help instead: https://support.stripe.com/contact
