### ISSUE TITLE
SourceService Class List function return null

### ISSUE THREAD

**Issue by mattleeevt** [stripe/stripe-dotnet#2726]
### Describe the bug

Tried to get a list of source by a customer id -  cus_xxxxxxxxxxxxx

by cUrl - worked as expected and return a list of sources data 
https://api.stripe.com/v1/customers/[cus_xxxxxxxxxxxxx]/sources 

Using the corresponding function in the stripe dotnet library
```
     var sourceService = new SourceService();
     var cards = sourceService.List(customerId);
```
The library generates extra object parameter at the end of the url as below
https://api.stripe.com/v1/customers/[cus_xxxxxxxxxxxxx]/sources?**object=source**

This request return no source data.

I tried to download the source code and remove the default value "source" in the Object property under SourceListOptions class (SourceListOptions.cs). The SourceService.List() function worked as expected.

```
    public class SourceListOptions : ListOptions
    {
        [JsonProperty("object")]
        **internal string Object { get; set; }**

        [JsonProperty("type")]
        public string Type { get; set; }
    }
```

### To Reproduce

```
     var sourceService = new SourceService();
     var cards = sourceService.List(customerId);
```
return no source data which is different from running with cUrl

### Expected behavior

cURL: https://api.stripe.com/v1/customers/[cus_xxxxxxxxxx]/sources

return source data as expected

### OS

Windows

### .NET version

.NET framework 4.8

### Library version

stripe-dotnet v41.23

### API version

2022-11-15

**Comment by remi-stripe** [comment]
Hey @mattleeevt! The `SourceService` class is used to list Source [objects](https://stripe.com/docs/api/sources/object) specifically which are legacy payment instrument objects with an id looking like `src_123`. If you don't use this specific API then you would get no results. Instead you are likely using another legacy API, the Card [object](https://stripe.com/docs/api/cards/object) with an id looking like `card_123`. To list those, you an use the List Cards [API](https://stripe.com/docs/api/cards/list) via the `CardService` instead.

Overall, those APIs have been deprecated for multiple years and replaced by the newer abstraction called a PaymentMethod [object](https://stripe.com/docs/api/payment_methods/object) with an id looking like `pm_123`. When we shipped that API, we made sure it was compatible with older objects so you can use the `card_123` or `src_123` objects via the API. So my advice is to switch to using the List Customer PaymentMethods [API](https://stripe.com/docs/api/payment_methods/customer_list?lang=dotnet) instead!

I'm going to close this out as there's no bug with the library here and it's more likely a misunderstanding. I'd recommend contacting our support team if you have any follow up questions instead: https://support.stripe.com/contact
