### ISSUE TITLE
parameter_invalid when providing RadarOptions on a setup intent

### ISSUE THREAD

**Issue by k3davis** [stripe/stripe-dotnet#2731]
### Describe the bug

I tried to add a Radar session ID to a setupintent request using the .NET SDK, which throws a StripeException.

This _appears_ to be a bug in the SDK, that it allows me to fill in an unsupported parameter, which I used in PaymentIntent and then saw was in SetupIntent and assumed could be used in the same manner.

It's also possible that the error message is wrong/misleading - if the parameter is supported, perhaps it wasn't applicable to the type of payment method I provided (in this case `us_bank_account`) and the API response didn't clarify the problem correctly (a messaging issue in the API itself)?

### To Reproduce

This isn't a whole request but to give you an idea of what I mean:

```cs
var setupOptions = new SetupIntentCreateOptions
{
    Customer = req.CustomerId,
    PaymentMethodData = new SetupItentPaymentMethodDataOptions
    {
        //...
        RadarOptions = new SetupIntentPaymentMethodDataRadarOptionsOptions
        {
              Session = req.RadarSessionId
        }
    }
};

var setupSvc = new SetupIntentService();
var response = await setupSvc.CreateAsync(setupOptions);
```

This request returns a StripeException, as copied from the dashboard log:

> parameter_unknown - payment_method_data[radar_options]

### Expected behavior

It isn't really clear from the Radar documentation [here](https://stripe.com/docs/radar/radar-session#create-radar-session) which payment method types it supports. Perhaps this information is only relevant for card payments, and that could be clarified if that's the case. However I can't tell from the response I received if the issue is with the parameter I actually provided via the SDK, or in the way I used it.

Ideally, it would work in the same manner as it does with PaymentIntent, since intuition and object definition in the SDK imply they are both there in the same place and should work the same.

### OS

win-x64

### .NET version

.NET 6

### Library version

41.24.0

### API version

2022-11-15

**Comment by richardm-stripe** [comment]
Hello, thank you for reporting this @k3davis. I believe you are right and this field is only relevant for card payments. This isn't a bug in `stripe-dotnet` so I am closing the issue, but I have reached out internally to try and get the responsible team to improve the experience here.
