### ISSUE TITLE
Split Payment directly to Connected Account without getting Platform Account Involved.

### ISSUE THREAD

**Issue by sagar-vaja-simform** [stripe/stripe-dotnet#2754]
### Describe the solution you'd like

When accepting payments from customers, the payment gets credited to Platform Account first and then gets transferred to Connected Accounts.

However, would it be possible to directly credit the payment to the connected account without getting the Platform Account involved? 

Also Need a feature to split the payment into multiple small amounts, so that it can be transferred to multiple connected accounts directly without getting the Platform Account involved.

I have a weird scenario of a Tipping Module in which I have to accept payment from customer for providing tip to driver and his helper. Whatever payment is received from the customer. It should be divided into two half and each half should get credited to each of the entities viz. Driver and Helper. (Who will be having connected account). Obviously, the Stripe fee should be also divided between the two entities. Basically, it's a tip, so the platform account shouldn't get involved and payment should be directly credited to connected accounts.

**Comment by remi-stripe** [comment]
@sagar-vaja-simform Github issues are limited to bugs or feature requests with the library. Your questions are integration support and are better handled by our support team instead. Please work directly with them for help: https://support.stripe.com/contact
