### ISSUE TITLE
Access to the server-driven integration in countries other than the US for European devs

### ISSUE THREAD

**Issue by GioviQ** [stripe/stripe-dotnet#2757]
### Is your feature request related to a problem? Please describe.

I know this is not the place to post this question, but on July 18 I sent an email to [stripe-terminal-betas@stripe.com](mailto:stripe-terminal-betas@stripe.com) to request access to the server-driven integration as described https://stripe.com/docs/terminal/payments/regional?integration-country=IT

I asked also Stripe Support, but no one can provide information about if and when my request will be approved, so I would like to now if there are here other European devs that were successully approved to know their experience.

**Comment by remi-stripe** [comment]
@GioviQ I'm sorry but I'm going to close for now as you know this is not the place to get help and I can't really look into your ask without more information (which shouldn't be shared publicly). Please email that alias again for more details.
