### ISSUE TITLE
AccountService not returning `business_profile`

### ISSUE THREAD

**Issue by atrauzzi** [stripe/stripe-dotnet#2799]
### Describe the bug

The response coming back from `AccountService` doesn't include any of the values for `BusinessProfile`.

### To Reproduce

Anything to the effect of:

```csharp
        var accountCheck = await (new AccountService()).GetAsync(
            completedStripeAuthorizationState.AccountId,
            new(),
            new()
            {
                ApiKey = stripeApiKey,
            }
        );
```

### Expected behavior

I expect to see `BusinessProfile` populated with values, similar to what I'm shown in the Stripe API browser.  

### OS

Linux

### .NET version

6

### Library version

43.2.0

### API version

2020-08-27

**Comment by remi-stripe** [comment]
@atrauzzi this is unlikely to be a bug with the library and more likely that you are passing an account id that doesn't have this information populated. My advice is to contact our support team and provide detailed information about your request such as the account id and the exact information you get back from the API and they will be better equipped to help you: https://support.stripe.com/contact
