### ISSUE TITLE
How can I see what version of the Stripe API goes with each version of this Stripe.net library?

### ISSUE THREAD

**Issue by rdeslonde** [stripe/stripe-dotnet#2803]
### Describe the bug

I can't figure out how to see what version of the Stripe API goes with each version of the Stripe.net library.

### To Reproduce

Go to a version of this library and try to find the compatible stripe api version. It's not there (I don't think).

### Expected behavior

You can't find the Stripe api version that corresponds with the Stripe.net versions.

### OS

Windows

### .NET version

4.6.1

### Library version

stripe-dotnet19.7.0

### API version

19.7.0

**Comment by remi-stripe** [comment]
If what you want is to find the right version of stripe-dotnet for a given API version, the easiest is to look at the changelog [here](https://github.com/stripe/stripe-dotnet/blob/master/CHANGELOG.md) and search for the API version string itself. That would give you the first major version that introduced that API version. You can then check each major version to see if it was switched to the next one or if it was released for other breaking changes.
