### ISSUE TITLE
Using starting_after returns entries before rather than after

### ISSUE THREAD

**Issue by TickettEnterprises** [stripe/stripe-dotnet#2819]
### Describe the bug

We are using the events checkout session endpoint to retrieve all checkout events and any new entries with consecutive runs of our integration. 

We understand the result are returned from newest to oldest.
We are expecting when using starting_after with the newest entry (the first object that is returned) we would get any new entries that have been created after.
But instead we are getting entries that are older than the object we used instead.

It looks like the ending_before and starting_after logic is reversed.
Is this the way it is suppose to operate?

### To Reproduce

Setting starting_after to the most recent entry with EventService.List().

### Expected behavior

Expecting strating_after would return new entries instead of older.

### OS

Windows 10

### .NET version

.Next Framework 6

### Library version

stripe-dotnet V43.7.0

### API version

2023-10-16

**Comment by remi-stripe** [comment]
@TickettEnterprises Yes that is the way our pagination logic is supposed to work. Let's assume a page that has numbered elements for 0 to 30 where 30 is the most recent/earliest created. When you fetch the first page, you will get 10 elements from 30 (first element) to 21 (last element). When you fetch results again and pass `starting_after: 21` you will then get the elements from 20 (first element) to 11 (last element). If you now pass `starting_after: 11` you will then get the elements from 10 to 1, etc.
