### ISSUE TITLE
Cannot download List of Payouts

### ISSUE THREAD

**Issue by SDmorgan** [stripe/stripe-dotnet#2824]
### Describe the bug

Returning an empty object when trying to retrieve list of payouts. 

When I log into Stripe account, it shows that there was a payout for a given date. The only difference is that in 2023, the dates are displayed MMM dd, yyyy (e.g. Dec 29, 2023). However, for 2024, the arrival dates are displayed MMM dd without a year. (e.g. Jan 1)

### To Reproduce

1. fetch list of payouts based on arrival date.

### Expected behavior

Should return a list of payouts (or at least one). Instead returns an empty object.

### Code snippets

```csharp
var service = new PayoutService();
var payouts = new StripeList<Payout>();
var startDate = new DateTime(2024, 01, 01);
PayoutListOptions options = new PayoutListOptions
{
    Limit = 100,
    ArrivalDate = startDate
};
payouts = service.List(options);
```

### OS

Windows

### .NET version

.net Framework 4.8

### Library version

43.8.0

### API version

2023-10-16

### Additional context

Last list of payouts to be downloaded was 2023-12-29 which coincides with the last payout for 2023. It appears that the issue started with list of payouts in 2024. However, when we try to download 2023, we now also recieve an empty object.

**Comment by remi-stripe** [comment]
@SDmorgan Github issues are limited to bugs or feature requests with the stripe-dotnet SDK. This is an integration support question and is better directed at our support team: https://support.stripe.com/contact

To unblock you here, `arrival_date` is a unix timestamp and if you don't pass the right value up to the second you won't get a result. It also works as a dictionary, similar to `created`, where you can pass `gte` or `lte` to use a range to for example find any Payout that landed in your bank account in 2024 for example. 
I tested this locally on my account and it works as expected so you likely have either no data for that day or a mismatch with the timestamp. Please work with our support team directly: https://support.stripe.com/contact

**Comment by SDmorgan** [comment]
@remi-stripe. I've tried it also with the date range options to no avail. Charges works fine.

PayoutService service = new PayoutService();
StripeList<Payout> payouts = new StripeList<Payout>();
var startDate = new DateTime(2024, 01, 01);
var endDate = new DateTime(2024, 01, 05);

PayoutListOptions options = new PayoutListOptions
{
    Created = new DateRangeOptions
    {
        GreaterThanOrEqual = startDate,
        LessThanOrEqual = endDate
    },
    Limit = 100
};

payouts = service.List(options);

I'll reach out to the support team as you mentioned it works for you.

**Comment by SDmorgan** [comment]
Also, you mentioned that arrival_date is a unix timestamp; however, see the following code as it clearly states it is a DateTime property. Per Stripe.Net.Dll

[JsonProperty("arrival_date")]
[JsonConverter(typeof(AnyOfConverter))]
public AnyOf<DateTime?, DateRangeOptions> ArrivalDate { get; set; }

**Comment by remi-stripe** [comment]
> Also, you mentioned that arrival_date is a unix timestamp; however, see the following code as it clearly states it is a DateTime property. Per Stripe.Net.Dll
I was talking about our API itself. The SDK is a wrapper around our API which takes a real unix timestamp. When you pass a DateTime it's converted to a specific unix timestamp and so if the `arrival_date` was at 01:00 UTC that day it wouldn't match what your code generates for Jan 1st for example. Our support team can help further though!

**Comment by SDmorgan** [comment]
@remi-stripe 

So why does it not return anything for the date range even though we have four payouts during that period?

**Comment by remi-stripe** [comment]
@SDmorgan Please work with our support team, sorry I have explained it multiple times and this is unlikely to be a bug with the SDK. Our support team can look at your code, your account and its Payouts and the calls you make to help debug.

**Comment by SDmorgan** [comment]
@remi-stripe . Thanks Remi, they have confirmed the issue. Appreciate the follow up.
