### ISSUE TITLE
Checkout Session client-side checks block testClock from working

### ISSUE THREAD

**Issue by kandaker** [stripe/stripe-dotnet#2829]
### Describe the bug

I'm writing tests using a testClock. I create the testClock and create a customer to set the clock on. Then I use those to test the Checkout Session we create in production code. Creating the Checkout session fails if the testClock is set in the past, or if it's set too far into the future. I think this is because the .Net SDK has some client-side date checks which don't take testClocks into account.

### To Reproduce

All using the Stripe .Net SDK:
1. Create a TestClock with a date either in the past, or >2 years into the future. Example here is for the past, since the .Net 8 FakeTimeProvider defaults to the date Jan 1st 2000.
2. Create a Customer which uses the TestClock.
3. Create a Checkout Session for the Customer.

### Expected behavior

That the CheckOut Session behaves as if the TestClock current date/time are the current date/time. The checks it does to block sessions being created with TrialEnd (and other dates) being in the past, or >2 years into the future, should not compare those dates to DateTime.Today or DateTime.Now.

### Code snippets

```csharp
1. Create a Test Clock
            StripeConfiguration.ApiKey = stripeSecrets.TestAPIkey;
            var testClockOptions = new Stripe.TestHelpers.TestClockCreateOptions
            {
                FrozenTime = timeProvider.GetUtcNow().DateTime, // .Net 8 default for FakeTimeProvider is "new DateTime(2000, 1, 1)"
                Name = "TestSubscribeTo3Rotations",
            };
            var testClockService = new Stripe.TestHelpers.TestClockService();
            Stripe.TestHelpers.TestClock testClock = testClockService.Create(testClockOptions);
2. Create a Stripe customer with a Stripe test clock set on it, so we can control the time that passes in Stripe
            var customerOptions = new CustomerCreateOptions
            {
                Email = "tester@sharedTestDomain.blah",
                TestClock = testClock.Id,
                PaymentMethod = "pm_card_visa",
                InvoiceSettings = new CustomerInvoiceSettingsOptions
                {
                    DefaultPaymentMethod = "pm_card_visa",
                },
            };
            var customerService = new CustomerService();
            Customer stripeCustomerWithTestClock = customerService.Create(customerOptions);
3. Create a Checkout session for this customer, with some dates in it. E.g. trial_end = new DateTime(2000, 7, 1);
            DateTime closestPaymentDate = new DateTime(2000, 7, 1);
            if (closestPaymentDate > timeProvider.GetUtcNow().Date && closestPaymentDate < timeProvider.GetUtcNow().Date.AddDays(3))    // Adding 3 days to ensure Stripe doesn't complain about the TrialEnd being too close to the CheckoutSession creation time. Stripe requires it to be at least 48hours away.
                closestPaymentDate = timeProvider.GetUtcNow().Date.AddDays(3);

            SessionCreateOptions options = new SessionCreateOptions
            {
                CustomerEmail = currentUserAlias,
                LineItems = new List<SessionLineItemOptions>
                {
                    new SessionLineItemOptions
                    {
                        Price = "price_************",
                        Quantity = 5,
                    },
                },
                Mode = "subscription",
                SubscriptionData = new SessionSubscriptionDataOptions
                {
                    Metadata = metadata,
                },
                SuccessUrl = httpBaseUrl + "stripeCheckoutSuccess?rotationId=" + rotationId,
                CancelUrl = httpBaseUrl + "Subscribe?rotationId=" + rotationId,
                Metadata = metadata,
            };
            if (Response == null) // Changes required for test cases to be able to use a Stripe TestClock
            {
                options.Customer = stripeCustomer.Id;
                options.CustomerEmail = null;
            }
            if (closestPaymentDate > timeProvider.GetUtcNow().Date)
                options.SubscriptionData.TrialEnd = closestPaymentDate;
            var service = new SessionService();
            Session session = await service.CreateAsync(options);
```

### OS

Windows

### .NET version

.Net 8

### Library version

stripe-dotnet 43.8.0

### API version

2023-10-16

### Additional context

Because of this behavior, it's not possible to write a test case with TestClock and CheckOut Session that'll work without modification for many years. Instead, we'll have to either make the dates in the test case dynamic (which is error prone), or update the hardcoded dates every ~18 months or so.

**Comment by remi-stripe** [comment]
@kandaker Github issues are limited to bugs with the stripe-dotnet SDK itself and this is more a question about the behaviour of our API and its limitations. It's better directed to our support team instead: https://support.stripe.com/contact/email

Overall though your intuition is correct. We don't directly try to support TestClocks with Checkout itself and my advice is to not use Checkout in your unit tests when you try to simulate time/advance time for a Subscription renewal.
