### ISSUE TITLE
updating subscription to automatically charge 

### ISSUE THREAD

**Issue by clarity99** [stripe/stripe-dotnet#2832]
### Describe the bug

I have a subscription that is set to send invoice and now I want to change it to automatically charge. Dashboard update creates the following json request:
```
{
  "off_session": "true",
  "enable_incomplete_payments": "false",
  "payment_settings": {
    "payment_method_options": {
      "customer_balance": ""
    },
    "payment_method_types": [
      "card"
    ]
  },
  "collection_method": "charge_automatically"
}
```

However, with stripe.net this seems impossible to create. customer_balance is a type that I don't know how to convert into "", and enable_incomplete_payments doesn't seem to exist.

### To Reproduce

```
var subscription = await subService.GetAsync(user.StripeSubscriptionId);
var subscriptionOptions = new SubscriptionUpdateOptions
{
  OffSession = true,//EnableIncompletePayments = false,
  CollectionMethod = "charge_automatically",
  
  PaymentSettings = new SubscriptionPaymentSettingsOptions
  {
    PaymentMethodTypes = new List<string> { charge.PaymentMethodDetails.Type },
    PaymentMethodOptions = new SubscriptionPaymentSettingsPaymentMethodOptionsOptions
    {
      CustomerBalance = new SubscriptionPaymentSettingsPaymentMethodOptionsCustomerBalanceOptions()
      {
        
      }
    }
  }
};

await subService.UpdateAsync(subscription.Id, subscriptionOptions);
```

### Expected behavior

change subscription to automatic charge.

### OS

macos

### .NET version

.net8

### Library version

43.10.0

### API version

2023-10-16

**Comment by clarity99** [comment]
the c# code produces this json:
`{
  "off_session": "True",
  "payment_settings": {
    "payment_method_types": {
      "0": "card"
    }
  },
  "collection_method": "charge_automatically"
}`

**Comment by remi-stripe** [comment]
@clarity99 Github issues are limited to bugs or feature requests with the stripe-dotnet SDK itself. Your question looks more like an integration support question better directed at our support team: https://support.stripe.com/contact

To unblock you though you seem to want to unset the `payment_method_options` you set before. The best option with stripe-dotnet is to use `AddExtraParam` documented [here](https://github.com/stripe/stripe-dotnet?tab=readme-ov-file#parameters) to force this as an empty string:

```
subscriptionOptions.AddExtraParam("payment_settings[payment_method_options][customer_balance]", "");
```

If you have follow up questions, make sure to work with our support team instead.

**Comment by clarity99** [comment]
thank you, the AddExtraParam solved the issue. I was going through stripe support for days on this with no resolution, so getting such a quick and correct response is awesome. :)
