### ISSUE TITLE
StripeConfiguration.ClientId getter

### ISSUE THREAD

**Issue by alexeytnm** [stripe/stripe-dotnet#2902]
### Describe the bug

https://github.com/stripe/stripe-dotnet/blob/963419d5e4183d3a255d6c6ead8d11f68c9b130e/src/Stripe.net/Infrastructure/Public/StripeConfiguration.cs#L73C42-L73C48

In the conditional check of the StripeConfiguration.ClientId getter
```
                if (string.IsNullOrEmpty(apiKey) &&
                    !string.IsNullOrEmpty(ConfigurationManager.AppSettings["StripeClientId"]))
                {
                    clientId = ConfigurationManager.AppSettings["StripeClientId"];
                }
```
shouldn't it be checking `clientId` instead of `apiKey`?
```
                if (string.IsNullOrEmpty(clientId) &&
```
looks like a copy paste from ApiKey getter above...

### To Reproduce

See description

### Expected behavior

See description

### OS

any

### .NET version

any

### Library version

master

### API version

master

**Comment by helenye-stripe** [comment]
Thanks for bringing this up! This should be resolved in the latest release 44.5.0.
