### ISSUE TITLE
Pleasse Support System.Text.Json

### ISSUE THREAD

**Issue by ismkdc** [stripe/stripe-dotnet#2910]
### Is your feature request related to a problem? Please describe.

there is no problem but we can gain performance boost :)

**Comment by ramya-stripe** [comment]
Thanks for reporting @ismkdc 
Please subscribe to https://github.com/stripe/stripe-dotnet/issues/2495 which is tracking this feature request.
Closing this one as duplicate

**Comment by jar-stripe** [comment]
Hi @ismkdc, just wanted to let you know we're starting work on using System.Text.Json as part of https://github.com/stripe/stripe-dotnet/issues/2495.  We're not fully replacing Newtonsoft yet, so I know it may not be exactly what you were looking for, but I wanted to point it out to see if you'd like to give feedback and context on our approach.  Thanks in advance!
