### ISSUE TITLE
How can I send card data from client to the server in safely manner?

### ISSUE THREAD

**Issue by DeveloperLookBook** [stripe/stripe-dotnet#2917]
### Describe the bug

Could you help me please. 

I have a **Xamarin.Forms (C#)** app that uses **Strip Source API** and **Token API**. We wont to use a new Strip version that provides new concepts like  **Payment Methods** and **Payment Intents**.

For now, there is no Stripe UI for the MAU mobile apps  that we can use  to collect payment method details  in easy and simple manner, so we use our custom Forms. I have a question that is not covered in your docs:

"**How can I send Card data from client to the server in safely manner (without your UI)?**"

In the previous stripe version there was **Token API**, that we could use to send Card details to our server. Now,  with new Stripe version that uses **Payment Methods** and **Payment Intents**, it's not clear how can I do the same  thing.

### To Reproduce

No need

### Expected behavior

No need

### OS

macOS

### .NET version

.NET 8.0

### Library version

Stripe.net v44.8.0

### API version

2024-04-10

### Additional context

Stripe.net

**Comment by remi-stripe** [comment]
@DeveloperLookBook This is more an integration support question. Please work with our support team 1:1 for help instead: https://support.stripe.com/contact

**Comment by DeveloperLookBook** [comment]
@remi-stripe They can't give a qualified answer with code some examples. Also, they use docs from your official web site, but it doesn't contain the answer on my question. All docs are oriented on the Stripe UI usage, but in my case I can't use it. So, that's why I'm here.

**Comment by remi-stripe** [comment]
@DeveloperLookBook Github issues are limited to bugs and feature requests with the stripe-dotnet SDK. Your questions are integration support questions, please work with our support team for 1:1 help instead!

**Comment by DeveloperLookBook** [comment]
I have already tried to work with support team. They don't help! They don't give a step by step instruction

**Comment by remi-stripe** [comment]
@DeveloperLookBook I'm sorry to repeat myself, but this is not the place to get that kind of help. Our support team is the right place to get help. I will lock this issue as I can't give you step by step instructions here.
