### ISSUE TITLE
There is no discernible text for the 'link' under 'secure...' section on 'Pay' tab.

### ISSUE THREAD

**Issue by msftedad** [stripe/stripe-dotnet#2934]
### Describe the bug

There is no discernible text for the 'link' under 'secure...' section on 'Pay' tab.

### To Reproduce

1. Click on https://site-ux5ko.powerappsportals.com/pay/
2. Navigate to Secure, 1-click checkout with Link and expand, turn on Accessibility insights for web and verify the issue, also
3. Then enter card details and enable Save your info for secure 1-click checkout with Link on the same page
4. Turn on Accessibility insights for web and verify the issue.

https://github.com/stripe/stripe-dotnet/assets/93735775/6c965eb8-b8ee-4d3c-a095-d2da05d9c24f

### Expected behavior

The discernible text should be defined for the 'link' under 'secure...' section on 'Pay' tab. Also, the name should be visually defined descriptively.
EX: Screen reader should announce as "Secure link". Visually on screen, the link text should appear as 'secure'.

### OS

Windows 11 Enterprise 23H2 (OS build: 22631.3737)

### .NET version

4.8

### Library version

4.6.1

### API version

2024-04-10

**Comment by remi-stripe** [comment]
@msftedad Sorry to redirect you but you're on the github repository of stripe-dotnet but you're reporting an issue with PaymentElement. I'll flag internally but I'll close this issue as it's unrelated to the SDK. Please report this issue to our support team instead so they can help you further: https://support.stripe.com/contact
