### ISSUE TITLE
There is no accessible name for the 'Country' combo box available on 'Pay' tab.

### ISSUE THREAD

**Issue by msftedad** [stripe/stripe-dotnet#2936]
### Describe the bug

There is no accessible name for the 'Country' combo box available on the 'Pay' tab.

Observation:
Narrator announces as "India+91 combo box collapsed required has popup".
JAWS announces as "Combo box Required India (+91) To change the selection use the Arrow keys".
NVDA announces as "combo box India (+91) collapsed required".

### To Reproduce

1. Launch # URL: https://site-ux5ko.powerappsportals.com/pay/
2. A new donation page appears. fill in the valid card details, Tab till 'Save your info...' checkbox. Activate it with the enter key. Content appears below.
3. Press 1- tab key to reach the 'phone number' field. Press  tab key to reach the 'Country' combo box. Turn on AI-fast pass/ screen reader.
4. Verify whether the combo box has an accessible name or not.

https://github.com/stripe/stripe-dotnet/assets/93735775/cb3e534b-faf2-49e6-801b-99217f9772ae

### Expected behavior

There should be an accessible name for the 'Country' combo box available on 'Pay' tab.
EX: Screen reader should announce as "Country/ pin code India+91 combo box collapsed required has popup".

### OS

Windows 11 Enterprise 23H2 (OS build: 22631.3737)

### .NET version

4.8

### Library version

stripe.net version - 42.3.0

### API version

2024-04-10

**Comment by remi-stripe** [comment]
@msftedad Sorry to redirect you but you're on the github repository of stripe-dotnet but you're reporting an issue with PaymentElement. I'll flag internally but I'll close this issue as it's unrelated to the SDK. Please report this issue to our support team instead so they can help you further: https://support.stripe.com/contact
