### ISSUE TITLE
There is no visual label for the form elements (like email, country combo box, mobile number, First and last name) under the 'Pay' tab.

### ISSUE THREAD

**Issue by msftedad** [stripe/stripe-dotnet#2937]
### Describe the bug

There is no visual label for the form elements (like email, country combo box, mobile number, First and last name) under the 'Pay' tab.

### To Reproduce

1. Click on https://site-ux5ko.powerappsportals.com/pay/
2. Navigate to Secure, 1-click checkout with Link and expand, verify if visual label is defined for email or not
3. Then enter card details and enable Save your info for secure 1-click checkout with Link
4. Verify if label is defined for the form elements (like email, country combo box, mobile number, First and last name) under the 'Pay' tab.

https://github.com/stripe/stripe-dotnet/assets/93735775/14af0c7b-d39c-4f5b-bb7f-f3dc97d93b3d

### Expected behavior

Visual label should be defined for the form elements (like email, country combo box, mobile number, First and last name etc..,) under the 'Pay' tab.
EX: Also, Screen reader should announce as "Phone number 081234 56789 edit required suggestions available" when focus lands on 'Phone number' field.

### OS

Windows 11 Enterprise 23H2 (OS build: 22631.3737)

### .NET version

4.8

### Library version

stripe.net version - 42.3.0

### API version

2024-04-10

**Comment by remi-stripe** [comment]
@msftedad Please report issues like this to our **support team** at https://support.stripe.com/contact and not on this Github project. I mentioned this in the first 3 issues you filed yesterday about this.

**Comment by msftedad** [comment]
@remi-stripe - Sorry for the inconvenience, will log this to https://support.stripe.com/contact.
