### ISSUE TITLE
Stripe.Events missing

### ISSUE THREAD

**Issue by PhilippRoessner** [stripe/stripe-dotnet#3024]
### Describe the bug

In Version 45.14.0 we were using the Events - Class found in Stripe.Events. This is missing in later versions.

### To Reproduce

Update from 45.14.0 to a higher version

### Expected behavior

I expected to still use this class

### OS

windows, macos

### .NET version

dotnet core 8

### Library version

47.0.0

### API version

2020-07-27

**Comment by RobinDavisTSD** [comment]
it looks like Events were renamed to EventTypes

**Comment by seanzhang-stripe** [comment]
Yes, [Stripe.Event is now Stripe.EventTypes](https://github.com/stripe/stripe-dotnet/wiki/Migration-guide-for-v46#renaming-stripeevents-to-stripeeventtypes). It's one of the breaking changes mentioned in the [changelog](
https://github.com/stripe/stripe-dotnet/blob/master/CHANGELOG.md#4600---2024-10-01)
