### ISSUE TITLE
Failure to parse response from /v1/forwarding/requests

### ISSUE THREAD

**Issue by dgregory-resnexus** [stripe/stripe-dotnet#3028]
### Describe the bug

When making a request to the /v1/forwarding/requests endpoint using v45.11 or v47.0 of the SDK, the response fails to be parsed.

It appears to me that it is the value of "created" (1731082862469) that is failing to parse. In a different successful request to a different endpoint, the value of "created" was 1731082744. The one that is failing appears to be in milliseconds and the one that is working appears to be in seconds.

### To Reproduce

Make any request to the endpoint using the SDK.
I used the suggested sample [from the API docs](https://docs.stripe.com/payments/vault-and-forward#testing-your-integration)

### Expected behavior

Parse the response correctly

### Code snippets

```csharp
{ "id": "fwdreqm_ymtq5DT1Y!LQxwPJEesM6wfg0Rf68V9QxssGDwpSzBw*EhcKFWFjY3RfMVB2blRrUFE2d2VhS3JKTw", "object": "forwarding.request", "created": 1731082862469, "livemode": false, "payment_method": "pm_1QIutzPQ6weaKrJOWhTfGN3x", "replacements": [ "card_number", "card_expiry", "cardholder_name" ], "request_context": { "destination_duration": 89, "destination_ip_address": "35.190.113.80" }, "request_details": { "body": "{\"card\":{\"exp_month\":\"02\", \"exp_year\":\"2025\", \"name\":\"REDACTED3\", \"number\":\"555555******4444\"}, \"metadata\":{\"REDACTED1\":\"1954\", \"REDACTED2\":\"4\"}}", "headers": [ { "name": "Authorization", "value": "Bearer *******************************************************************************************" }, { "name": "Content-Type", "value": "application/json" } ], "http_method": "POST" }, "response_details": { "body": "{\"id\":\"token_1\"}", "headers": [ { "name": "Content-Length", "value": "16" }, { "name": "Etag", "value": "W/\"10-eOqXY39ivjugjwCuZPjsCZw1UEE\"" }, { "name": "Via", "value": "1.1 google" }, { "name": "X-Powered-By", "value": "Express" }, { "name": "X-Robots-Tag", "value": "noindex, nofollow" }, { "name": "Content-Type", "value": "application/json; charset=utf-8" }, { "name": "Server", "value": "envoy" }, { "name": "Alt-Svc", "value": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000" }, { "name": "Date", "value": "Fri, 08 Nov 2024 16:21:02 GMT" }, { "name": "X-Cloud-Trace-Context", "value": "aa86744918565aa04aba1d2909d56221;o=1" } ], "status": 200 }, "url": "https://forwarding-api-demo.stripedemos.com/tokens"}
```

### OS

Windows 11

### .NET version

.NET 4.7.2

### Library version

stripe-dotnet-v45.11

### API version

2024-09-05

### Additional context

**System.ArgumentOutOfRangeException**
Value to add was out of range

**Partial Stack Trace**
  at System.DateTime.Add(Double value, Int32 scale) in System\DateTime.cs:line 860
   at Stripe.Infrastructure.UnixDateTimeConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in /_/src/Stripe.net/Infrastructure/JsonConverters/UnixDateTimeConverter.cs:line 87
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Stripe.Infrastructure.StripeEntityConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in /_/src/Stripe.net/Infrastructure/JsonConverters/StripeEntityConverter.cs:line 74

**Comment by dgregory-resnexus** [comment]
FYI the code snippet I provided is the redacted response I retrieved from my Stripe dashboard

**Comment by dgregory-resnexus** [comment]
https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Infrastructure/JsonConverters/UnixDateTimeConverter.cs

Line 87. Most responses (the working ones) are actually being returned in seconds (int data type), but the forwarding API is responding in milliseconds (long data type), which is why adding seconds to UnixEpoch is failing.

**Comment by dgregory-resnexus** [comment]
Possible solution

```
if (seconds > (long)int.MaxValue)
{
    return UnixEpoch.AddMilliseconds(seconds);
}
else if (seconds >= 0)
{
    return UnixEpoch.AddSeconds(seconds);
}
else
{
    throw new JsonSerializationException(string.Format("Cannot convert value that is before Unix epoch of 00:00:00 UTC on 1 January 1970 to {0}.", objectType));
}
```

**Comment by jar-stripe** [comment]
Hi @dgregory-resnexus , thanks for the report and the investigation!  We'll take a look and update here when we have more info.

**Comment by dgregory-resnexus** [comment]
Absolutely!

The value for `maxSeconds` could probably be initialized as `static readonly` like `UnixEpoch`, so it wouldn't have to be recalculated every time.

**Comment by jar-stripe** [comment]
Hi @dgregory-resnexus , thanks for your patience here!  Just wanted to let you know that we're working on a fix to the API so this will return seconds as expected.  I will update you when it is ready; in the mean time, if this is blocking you, you may be able to use stripe-dotnet Custom Request feature (introduced in v46, https://github.com/stripe/stripe-dotnet/?tab=readme-ov-file#custom-requests) as a workaround.  RawRequest does not deserialize the response, which means it will not encounter this error but you will need to parse and process the response yourself.  Hope that helps; will be back in touch when I know more!

**Comment by dgregory-resnexus** [comment]
I'll wait for the API fix, I'm not in a rush.

I already updated to v47 of the SDK, so the workaround will be helpful if my timeline becomes more urgent.

**Comment by jar-stripe** [comment]
Hi @empowerjamesgarrett , the fix is to ensure the api returns epoch time in seconds, and the plan is to gate existing users of this API into the current behavior with an option to ungate them if they would like to use the fixed behavior instead.

**Comment by empowerjamesgarrett** [comment]
@jar-stripe any updates on this?

**Comment by jar-stripe** [comment]
Hi @empowerjamesgarrett, sorry for the delay; I was OOO earlier this week.  Let me check and get back to you.

**Comment by jar-stripe** [comment]
@empowerjamesgarrett it sounds like they're finishing up the fix and it should be available shortly!  I will update you here as soon as I hear from the team working on it.

**Comment by jar-stripe** [comment]
@dgregory-resnexus , @empowerjamesgarrett I just heard from the team; the fix is deployed and y'all should see created returned in seconds as expected.  The SDK as built should work without issue with this fix.

I'm going to close this issue but please us know if you are still having trouble!
