### ISSUE TITLE
StripeException.Error.Code is null when updating a subscription with cancel_at value in the past

### ISSUE THREAD

**Issue by michielvoo** [stripe/stripe-dotnet#3034]
### Describe the bug

When updating a subscription with a cancellation date in the past, the exception thrown does not have the correct error code.

### To Reproduce

1 `stripe subscriptions update "sub_10QRWyBNNuLonfnoJuQ4m0H5" —-cancel-at="1733011200"`
2. Check response, it should be an error
3. Check the error's `message_code`, it should be `"subscription_cancel_at_in_past"`
4. Now try the same in a C# application (see code snippet)
5. Catch the `StripeException`
6. Inspect the exception's `.StripeError.Code`
7. It has a value of `null`

### Expected behavior

It should have a value of `"subscription_cancel_at_in_past"`

### Code snippets

```csharp
try
{
    SubscriptionService.UpdateAsync(subscriptionId, new SubscriptionUpdateOptions
    {
        CancelAt = request.EndDate // where this value is in the past
    });
}
catch(StripeException e) when (e.StripeError.Code == "subscription_cancel_at_in_past")
{
    // This block is not entered
}
```

### OS

macOS

### .NET version

.NET 8

### Library version

stripe-dotnet v47.1.0

### API version

2024-06-20

**Comment by xavdid-stripe** [comment]
When I run that curl command with my own test subscription, I get:

```
stripe subscriptions update "sub_1QV0GkESuHC5BW1BASa3lYWX" --cancel-at="1733011200"
{
  "error": {
    "message": "The `cancel_at` param can only be set to a date in the future.",
    "request_log_url": "https://dashboard.stripe.com/test/logs/req_PGXpwm0nJrbfYm?t=1733963391",
    "type": "invalid_request_error"
  }
}
```

Not only did I not get a `code`, looking at the [docs for error codes](https://docs.stripe.com/error-codes), I don't see `subscription_cancel_at_in_past` listed, which makes me think it wouldn't show up in `e.StripeError.Code`.

Can you post a request id that shows `subscription_cancel_at_in_past` so I can take a closer look?

**Comment by michielvoo** [comment]
I also could not find it in the documentation, but I have a screenshot of the error in the dashboard:

![image](https://github.com/user-attachments/assets/78b4810b-675e-4d46-ab26-87af5767131d)

**Comment by jar-stripe** [comment]
Hi @michielvoo, thanks for the response.  We're taking a closer look , but in the mean time, if you'd like you could you try this as a workaround.

```csharp
try
{
    SubscriptionService.UpdateAsync(subscriptionId, new SubscriptionUpdateOptions
    {
        CancelAt = request.EndDate // where this value is in the past
    });
}
catch (StripeException e) when (e.StripeError.RawJObject["message_code"]?.ToString() == "subscription_cancel_at_in_past")
{
    // This block is not entered
}
```

Using the RawJObject property will will let you access the message_code field (which is different from code/Code).  Try that and let us know if that works for you?

**Comment by jar-stripe** [comment]
Hi @michielvoo, got an answer already.  Were you issuing that command through the Dashboard's Shell?  `message_code` is only included in responses originating thru the Stripe Dashboard -- including the Dashboard Shell -- and not through the Stripe CLI or, more importantly here, the SDK (which is why we don't have a property for it in the StripeError object).  

From the looks of it, that API call also does not include the optional `code` property as part of its response (not all API calls do) but if you would like you can make a feature request through Stripe support for this.

Sorry for the confusion here!
