### ISSUE TITLE
Add Stripe.net to the Xamarin store

### ISSUE THREAD

**Issue by jaymedavis** [stripe/stripe-dotnet#456]
This is a placeholder to add this library to the Xamarin store. If you need this functionality, leave a comment. :+1:

**Comment by MagicalMaya** [comment]
Would be a good addition to Xamarin Store :+1:

**Comment by thewizster** [comment]
Thanks for your efforts on this! Just found this library via the stripe website. Will be trying it out. If works well in my Xamarin project via nuget then all is well with me. Might still be nice to see in the Xamarin store. :+1:

**Comment by MagicalMaya** [comment]
Raymond Brady, please try building the project in Visual Studio and then
import/add the dll in your Xamarin project.

It would work fine, worked for us. Thanks to Jaymedavis for all his efforts
and help.

**Comment by jaymedavis** [comment]
Thank you for the kudos @MagicalMaya. :) 

I have most of the xamarin stuff packaged up, but it looks like I need samples for each platform (and this supports all of them). That will take some time to get out - maybe they will accept it w/out samples. :+1:

**Comment by nhwilly** [comment]
I am all for this, too.  Love the library.  

I don't see how to get tokens from Stripe directly to the device without distributing my keys, though.  Are we still forced to use Checkout or Stripe.JS or use their mobile integration libraries?  Trying to keep this all in C# and/or not force credit card data though my server (even though I'm not storing it).  TIA

**Comment by jaymedavis** [comment]
Thanks! I will get this ticket moving along - pretty soon, I will be working with Stripe to prioritize what gets done in the library on our board - they were kind enough to let me open source the workflow :).  https://waffle.io/jaymedavis/stripe.net 

We are finalizing some details, but the more info I have in this issue the better. For example, how are you pulling in stripe.net now? NuGet? Would the Xamarin store make it a lot easier?

(on a side note, I am working on a component that will be a one time charge called stripe.net checkout - it only works with MVC at the moment, but I hope to build it server agnostic)

**Comment by jaymedavis** [comment]
Everyone I've asked about this, prefers to use Nuget instead. What benefit does the Xamarin store add for this? I've done the work - but it appears it has no dependency support, so it's going to be a pain to maintain. Curious why use this over nuget? Is this the 'Xamarin' way for most people?

**Comment by thewizster** [comment]
I think Nuget is sufficient. No need for extra work and maintenance. Thanks again for your efforts!

**Comment by makerofthings7** [comment]
Xamarin store would give visibility and acknowledgment to Xamarin users.  Stripe already has an xamarin component, but for the cross platform web libraries this could be useful.

Would love to hear how this library improves upon the existing Stripe component

**Comment by jaymedavis** [comment]
If I do release it, should I release json.net alongside it? Xamarin doesn't have dependency support, correct?

**Comment by paulvicky** [comment]
yes, please release json.net alongside with it. 

i can not declare the stripe.net namespace in my  xamarin forms project  (i have installed stripe.net and add into my xamarin forms project.)

using stripe.net. 
the stripe is underline with red and said the namespace can not be found.

**Comment by jaymedavis** [comment]
using Stripe is what you want, that's the namespace.

**Comment by MagicalMaya** [comment]
Json.net, isn't it same as NewtonJson?

In our project, we are using NewtonJson, and we didn't need to add any
additional JSON library when we integrated Stripe.net module.

Regards,
Puja

**Comment by makerofthings7** [comment]
I was unaware of this library until I searched the forums.  Pushing any version, that updates via nuget, to the Xam Components store w/examples is a great way to get visibility/usage

**Comment by stackunderflows** [comment]
Is there any movement on this? What is the best way to integrate stripe into a Xamarin.Forms app?

**Comment by remi-stripe** [comment]
We haven't seen any news on this for a long time. I don't think there are short term plans to offer this library on the Xamarin store at the moment. Closing out.
