### ISSUE TITLE
Stripe Event Previous Attributes

### ISSUE THREAD

**Issue by kevinswarner** [stripe/stripe-dotnet#71]
I am not sure if this is an issue or I just cannot figure out how to access the PreviousAttributes of the StripeEventData object. I am retrieving a webhook event from Stripe as follows...

```
{
  "id": "evt_1kM7DYo5giINN9",
  "created": 1367380760,
  "livemode": false,
  "type": "customer.subscription.updated",
  "data": {
    "object": {
      "plan": {
        "interval": "month",
        "name": "Monthly (TEST)",
        "amount": 300,
        "currency": "usd",
        "id": "monthly_test",
        "object": "plan",
        "livemode": false,
        "interval_count": 1,
        "trial_period_days": 1
      },
      "object": "subscription",
      "start": 1367375555,
      "status": "unpaid",
      "customer": "cus_1kKhUFPKr7c30g",
      "cancel_at_period_end": false,
      "current_period_start": 1367375615,
      "current_period_end": 1370054015,
      "ended_at": null,
      "trial_start": 1367375511,
      "trial_end": 1367375615,
      "canceled_at": null,
      "quantity": 1
    },
    "previous_attributes": {
      "status": "active"
    }
  },
  "object": "event",
  "pending_webhooks": 1,
  "request": null
}

var json = new StreamReader(Request.InputStream).ReadToEnd();
var evnt = StripeEventUtility.ParseEvent(json);

var previousStatus;

// Does not work.
previousStatus = evnt.Data.PreviousAttributes.Status;

// Does not work.
previousStatus = evnt.Data.PreviousAttributes.status;
```

When I look at the PreviousAttributes property in source it is defined as "dynamic". When I look at the type using GetType().Name, I get back "JObject". I also tried casting to a JObject and then using myJObject["status"], but had issues even casting. I also tried using JObject.Parse(evnt.Data.PreviousAttributes.ToString()) to get a good JObject, but no luck.

This also does not work when I retrieve a StripeEvent object using the StripeEventService.

I am still trying to understand dynamic object in C#, so I may just be unaware on how to access this value.

I appreciate any help I can get on this.

Thanks!

**Comment by FreedCapybara** [comment]
I'm many years late to the party, but in case it helps anyone, an ugly solution (that works!) is to serialize/deserialize it as suggested above:
```cs
var previousAttributesJson = JsonConvert.SerializeObject(stripeEvent.Data.PreviousAttributes) as string; // the 'as' is because otherwise Visual Studio still thinks it's a dynamic for some reason
var previousAttributes = JsonConvert.DeserializeObject<IDictionary<string, object>>(previousAttributesJson);
```
I used a dictionary, but you could deserialize it to a custom class that has the specific properties you want.

**Comment by CocoThePimp** [comment]
(PHP - Laravel)
If you don't find 'previous_attributes' it's because not all events contain it. I use 'customer.subscription.updated' to spot it.

`        public function webhook(Request $request){

        $payload = @file_get_contents('php://input');
        $sig_header = $_SERVER['HTTP_STRIPE_SIGNATURE'];
        $event = null;
        $endpoint_secret = config('services.stripe.secret_endpoint_key');

        try {
            $event = \Stripe\Webhook::constructEvent(
                $payload, $sig_header, $endpoint_secret
            );
        }
        // Somes catchs to add

        if ($event->type === 'customer.subscription.updated'){

            if (isset($event->data['previous_attributes'])){
                Log::info('previous_attributes exist');
            }

        }`

Hope it can help someone, I was trying to access it in invoice.paid but it doesn't exist in this event.
