### ISSUE TITLE
StripeInvoiceService ExpandSubscription

### ISSUE THREAD

**Issue by aveneld** [stripe/stripe-dotnet#741]
First, thank you so much for a great product.  I am working with Stripe for the first time am totally enjoying working with Stripe and Stripe.net...

I'd like to be able to reference the subscription that a charge (webhooks) is for.  The charge has an InvoiceId, so I can hit the InvoiceService and Get the SubscriptionId and get what I need from there with an additional call to subscription service, BUT... I see you have Invoice.ExpandCustomer and Invoice.ExpandCharge.   We add Metadata to the actual subscription Item, so if we had an Invoice.ExpandSubscription, we'd have everything we need with a single call

Thanks again for the great work !!

Cheers

**Comment by jaymedavis** [comment]
According to the stripe docs, this is not expandable :(

**Comment by farshadjahanmanesh** [comment]
hi, its expandable 
![image](https://user-images.githubusercontent.com/13612410/37554060-a7bfae2a-29e8-11e8-97c3-bd33f2ac19bc.png)

look at here, how can we pass missing properties to Querystring, for example, now we dont have ExpandSubscription in the library, but the API accept it, how can i pass it with exteraParam?

**Comment by ob-stripe** [comment]
Hi @farshadjahanmanesh. The attribute wasn't expandable when this issue was opened last year, but it is now. We'll update the library to support this.
