### ISSUE TITLE
Registering domain with Stripe and ApplePay for Stripe Connect

### ISSUE THREAD

**Issue by Kristea** [stripe/stripe-dotnet#779]
I'm trying to set up apple pay using Stripe Connect. Does this package have any functionality for authenticating a request and registering the domain for apple pay and the connect stripe account id? In a similar way to how the Stripe api describe it.

 Or would this just best be done using the usual .net Web request and passing the necessary keys in the headers?

Thanks.

**Comment by jaymedavis** [comment]
I'm not very familiar with this process. 

> Or would this just best be done using the usual .net Web request and passing the necessary keys in the headers?

Can you point me to where you read this information? If it's a web request and keys in the headers, it may be something that has been implemented, or could be implemented.

**Comment by KoanLeeroy** [comment]
https://stripe.com/docs/apple-pay/web#connect

Just a simple curl request required: 

```
curl https://api.stripe.com/v1/apple_pay/domains \
 -u {PLATFORM_SECRET_KEY}: \
 -H "Stripe-Account: {CONNECTED_STRIPE_ACCOUNT_ID}" \
 -d domain_name="example.com"
```

Would be great to see this in the SDK
