### ISSUE TITLE
Invalid timestamp: must be an integer Unix timestamp in the future.

### ISSUE THREAD

**Issue by afollestad** [stripe/stripe-dotnet#805]
When specifying a `TrialEnd` during subscription creation, I get an error:

```Gradle
Stripe.StripeException: Invalid timestamp: must be an integer Unix timestamp in the future.
   at Stripe.Infrastructure.Requestor.ExecuteRequest(HttpRequestMessage requestMessage)
   at Stripe.StripeSubscriptionService.Create(String customerId, String planId, StripeSubscriptionCreateOptions createOptions, StripeRequestOptions requestOptions)
   ...
```

**Comment by afollestad** [comment]
Sorry, I think this may have been a simple problem on my end!

**Comment by afollestad** [comment]
Nevermind, it happens consistently. The timestamp is definitely in the future.

**Comment by afollestad** [comment]
Okay, sorry, it appears to be a weird issue with DotNet Core on Mac returning the wrong value for `DateTime.Now` somehow.

**Comment by afollestad** [comment]
Okay, no it still happens.

It may be an issue with https://github.com/jaymedavis/stripe.net/blob/96cdbaffa5609ab6f8c4925342247c5a8be6f0ac/src/Stripe.net/Infrastructure/EpochTime.cs

**Comment by jaymedavis** [comment]
hmm... I added this to the subscription tests, and the trial end does not bomb with an exception. I tried the tests on osx and windows. What value are you passing specifically and can you tell me a little about your environment? It might be something related to Culture .. given my luck :)

**Comment by afollestad** [comment]
Very werid.

I was using `DateTime.Now.AddMinutes(5)` in order to test failed subscription invoices; I verified that `DateTime.Now` returns the same time that my computer displays. This is all on a Macbook Pro also. 😀

**Comment by afollestad** [comment]
Something I have noticed with epoch second conversion, you usually have to convert the date to universal time before converting it to seconds or milliseconds, e.g.:

```C#
public static long ToEpochTime(this DateTime dateTime)
{
    return (long)(dateTime.ToUniversalTime() - new DateTime(1970, 1, 1)).TotalMilliseconds;
}
```

**Comment by jaymedavis** [comment]
You may be right - can you play with adding hours and see when it breaks? If adding 8 hours works for example and 2 doesn't - could be this. Have you tried converting to utc before you add anytime?

**Comment by jaymedavis** [comment]
What would worry me about the second method, is I would be altering the value the user sent, even if it is to make it the value it should be. :)

If this is the situation,, DateTime.UtcNow.AddMinutes(5) should work. 

If stripe.net altered the time, there could be situations where trials or other dates in the system are converted without the users knowledge. Does that make sense?

**Comment by afollestad** [comment]
Well the weird thing is that if I use the method above that converts `DateTime.Now` to milliseconds, and put it into https://currentmillis.com/, it gives me the wrong local time.

If I use `DateTime.Now.ToUniversalTime()` instead, it gives me the correct local time.

I think epoch time is always supposed to be relative to UTC.

**Comment by jaymedavis** [comment]
oh interesting - I'll do some more research here, specifically finding out how stripe's other bindings handle this.

**Comment by xt0rted** [comment]
.NET 4.6 added support for Unix time with the `DateTimeOffset` class as seen here https://referencesource.microsoft.com/#mscorlib/system/datetimeoffset.cs,625. It ensures the value it's converting is UTC since Unix time is relative to UTC.

The `DateTime` class is really meant for arbitrary dates & times while `DateTimeOffset` is meant for points in time (relative to UTC). This is why `DateTimeOffset` always works with an offset/timezone and is the only one which has Unix time functions added to it. You can see the differences in how the two behave with the following code
```csharp
var offset = new DateTimeOffset(1970, 1, 1, 0, 0, 0, TimeSpan.Zero);
(offset == offset.ToUniversalTime()).Dump(); // true
(offset.ToLocalTime() == offset).Dump(); // true
(offset.ToLocalTime() == offset.ToUniversalTime()).Dump(); // true

var date = new DateTime(1970, 1, 1, 0, 0, 0);
(date == date.ToUniversalTime()).Dump(); // false
(date.ToLocalTime() == date).Dump(); // false
(date.ToLocalTime() == date.ToUniversalTime()).Dump(); // false

(offset == date).Dump(); // false
```

The `DateTime` comparisons will have different results depending on the `DateTimeKind` you pass in. By default it's `Unspecified` (using `DateTime.Now` or `DateTime.UtcNow` will use `Local` or `Utc` respectively). The point of that though is to show how there's too much variance in how it functions while `DateTimeOffset` is going to give consistent results.

By the looks of it there is a bug in the current [EpochTime](https://github.com/jaymedavis/stripe.net/blob/master/src/Stripe.net/Infrastructure/EpochTime.cs) class which can been seen with the following code
```csharp
// both give different results
EpochTime.ConvertDateTimeToEpoch(DateTime.Now).Dump();
EpochTime.ConvertDateTimeToEpoch(DateTime.Now.ToUniversalTime()).Dump();

// both give the same result
new DateTimeOffset(DateTime.Now).ToUnixTimeSeconds().Dump();
new DateTimeOffset(DateTime.Now.ToUniversalTime()).ToUnixTimeSeconds().Dump();
```

**Comment by jaymedavis** [comment]
Thanks @xt0rted for the write up!

I think from @afollestad's original request, if the use case is to request something ends in 10 minutes, it simply wont work the way it is now. I'm sort of surprised this hasn't came up yet, but most dates are probably set to days out, not minutes. That's my best guess.

On the Stripe side, they expect epoch time, so it really shouldn't matter what the user passes. It is relative to UTC so that's what it should be. I'll fix this to use `.ToUniversalTime()` in the function. 👍

**Comment by jaymedavis** [comment]
This is on master. 👍 

A test also caught the DateFilterPlugin (anywhere you filter by dates to search for data in Stripe) - that also needed to .ToUniversalTime(). This will go live next time I bump the version (soon).

**Comment by mokumax** [comment]
I'm getting this on Subscription.Create now that I upgraded to 14.0.0.

{"Invalid timestamp: must be an integer Unix timestamp in the future."}

The strange thing is I can cancel a subscription without any issues. I just can't create one.

**Comment by remi-stripe** [comment]
@mokumax  this likely means that you pass an invalid timestamp in `TrialEnd`. I'd recommend talking to our support team about this as this is not a bug in the library. You can talk to them here: https://support.stripe.com/email

**Comment by mokumax** [comment]
Thanks. Yeah, I've been back and forth with them. I don't pass a TrialEnd (never did) so I'll try doing that.

**Comment by mokumax** [comment]
Fixed it on my end. Maybe this is a bug?

**I removed** 

` BillingCycleAnchorNow = true`

**My final code was:**

` var item = new List<StripeSubscriptionItemOption>
                            {
                                new StripeSubscriptionItemOption
                                {
                                    PlanId = planId,
                                    Quantity = 1
                                }
                            };

                            StripeSubscription subscription = new StripeSubscription();
                            subscription = subscriptions.Create(user.StripeCustomerId, new StripeSubscriptionCreateOptions
                            {
                                CustomerId = user.StripeCustomerId,
                                Items = item
                                //,BillingCycleAnchorNow = true
                            });`

**Comment by remi-stripe** [comment]
@mokumax I can reproduce on my end so it definitely looks like a bug. Thank you for sending come code to reproduce! I'll work on a fix!

**Comment by remi-stripe** [comment]
@mokumax False alert! This is not exactly a bug in the library, but the way you use it. When you create a subscription you can not pass `billing_cycle_anchor: "now"`. That parameter can only be a timestamp for the future. If you want to start a subscription immediately, you would simply not pass `billing_cycle_anchor` at all (which is what you ended up doing.

`BillingCycleAnchorNow` is really only allowed for Updates and not Creation. We should still work on removing those options on creation as they are not supported!

**Comment by jaymedavis** [comment]
You could just move the billing cycle anchor stuff to the sub update options. I think it’s on the create options now if I remember right.

**Comment by remi-stripe** [comment]
@jaymedavis Yeah I mostly removed the custom options (Now and Unchanged) from the Create options as they should not be there. That makes me realize that those should be supported on Update though so I'll have to fix that part too.

**Comment by remi-stripe** [comment]
Nevermind, that's already been added: https://github.com/stripe/stripe-dotnet/blob/ff5e8b94f23387df14b988f94fd1d87bade6b057/src/Stripe.net/Services/Subscriptions/StripeSubscriptionUpdateOptions.cs#L10-L28

**Comment by jaymedavis** [comment]
Ah, lovely. So just removing from the create option _OR_ you could do this:

`enum BillingCycle { "Now", "Unchanged" }`. Then, have the BillingCycle property on the options accept a type from that enum. The [EnumPlugin](https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Infrastructure/Middleware/ParserPlugin/EnumPlugin.cs) would almost handle this as-is.  You could edit this or copy this to a new plugin. Then register your new plugin in the [RequestStringBuilder](https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Infrastructure/Middleware/RequestStringBuilder.cs) so the middleware takes care of it.

**Comment by systemd32** [comment]
You can try using [TimeStamp to Date](https://dateconvertor.com/). This website provides useful time conversion tools for various purposes.  
I hope this will be helpful for you!
