### ISSUE TITLE
Stripe Sku Service

### ISSUE THREAD

**Issue by tjmcnaboe** [stripe/stripe-dotnet#916]
Could use the Sku service to go with Orders.

This is what I am using in my project to fill the void.  :

    public class StripeSkuService : StripeBasicService<StripeSku>
    {

        public string UrlsSkus = "https://api.stripe.com/v1/skus";

        public StripeSkuService(string apiKey = null) : base(apiKey) { }

        public virtual StripeSku Get(string skuId, StripeRequestOptions requestOptions = null)
        {
            return GetEntity($"{UrlsSkus}/{skuId}", requestOptions);
        }

        public virtual StripeSku Create(StripeSkuCreateOptions createOptions = null, StripeRequestOptions requestOptions = null)
        {
            return Post(UrlsSkus, requestOptions, createOptions);
        }

        public virtual StripeSku Update(string skuId, StripeSkuUpdateOptions updateOptions, StripeRequestOptions requestOptions = null)
        {
            return Post($"{UrlsSkus}/{skuId}", requestOptions, updateOptions);
        }

        public virtual IEnumerable<StripeSku> List(StripeSkuListOptions listOptions = null, StripeRequestOptions requestOptions = null)
        {
            return GetEntityList(UrlsSkus, requestOptions, listOptions);
        }

        public virtual StripeDeleted Delete(string skuId, StripeRequestOptions requestOptions = null)
        {
            return DeleteEntity($"{UrlsSkus}/{skuId}", requestOptions);
        }
    }

**Comment by tangentmind** [comment]
thank you @tjmcnaboe ! @jaymedavis are there any plans for implementing the SKU service?

**Comment by remi-stripe** [comment]
@tangentmind I've started a PR for this in https://github.com/stripe/stripe-dotnet/pull/1022. Hopefully we can merge this in the next few weeks.
