### ISSUE TITLE
Error reported by Stripe servers

### ISSUE THREAD

**Issue by bmartyn** [stripe/stripe-dotnet#93]
I get the below error when I use the stripe.net dll to process a charge:

Error while talking with one of our backends.  Sorry about that!  We have been notified of the problem.  Please contact support@stripe.com if you have any questions.

This is probably not an issue with the code, but, I was wondering if anyone who has used Stripe.net is aware of what causes this?
Thanks

**Comment by robfe** [comment]
@jimdanz may be unrelated but may be interesting anyway, I was getting this same generic error message (which led me here) and it turned out I'd forgotten to encode my basic auth header. Might be handy for idiots like me to have a specific error message when the basic auth header is undecodable at your end...

**Comment by irongaze** [comment]
Sorry for the necrobump, but for other folks googling this issue, it's still hitting us periodically.  We run a nightly billing script, and randomly about one in 1000 charges fails with this message.  Can't be a code issue, b/c the other charges work fine.  Can't be a data problem, b/c the same charge will work the following night.  No idea what's going on here, but sometimes when it happens, our customer will be billed successfully, even though we get the failure message.

**Comment by jaymedavis** [comment]
It's quite possible on Stripe's end that the messages are being split it off into queues - one is a quick check and says good job and the other actually does the work. That's all I can think of for why it would be a successful charge even though it says failure. Sounds like you have good logs, but I wouldn't worry about it. Seems like an anomaly that get's solved.

**Comment by Dinesh-Net** [comment]
Invalid request (check your POST parameters): unable to determine value for parameter: source.
I am gettting this error while CreateBankAccount.
var bankAccountOptions = new BankAccountCreateOptions()
                {
                    SourceToken = "pk_test_lOMq82LDuL89wrZsV9JA9Jfu",
                    SourceBankAccount = new SourceBankAccount()
                    {
                        AccountNumber = "Test123456987",
                        Country = "USD",
                        Currency = "United States",
                        BankName = "HDFC Bank Ltd",
                    },
                };
                 CustomerBankAccount bankAccount = new CustomerBankAccount();
                bankAccount = bankAccountService.Create("cus_BvfDRStyCGgnjb", bankAccountOptions);
