### ISSUE TITLE
StripeChargeCreateOptions.Shipping property doesn't match the Stripe API specification

### ISSUE THREAD

**Issue by varunbabu008** [stripe/stripe-dotnet#944]
I am using the latest stripe version 10 and I am getting "Invalid Hash" stripeException when I set the Shipping property. When I looked at the Stripe documentation, the format specified is different from what is currently in Stripe.net. It expects a `dictionary <String,String>` whereas in the Stripe API, the format is as follows 
```
"shipping": {
   "address":{
        "line1" : "",
        "line2" : "",
        "city" : "",
        "state" : "",
        "postal_code" : ""
       },
    "carrier": "",
    "name": ""
}
```

I am guessing the shipping property should be changed to something like
`Dictionary<String,Dictionary<String, String>>.`  in stripe.net.

**Comment by varunbabu008** [comment]
Would love to make a pull request if this is confirmed

**Comment by jaymedavis** [comment]
I tried using the ```StripeShippingOptions``` (in the orders services folder) for this, but it didn't work. Where did you find the docs for this?

**Comment by jaymedavis** [comment]
Disregard - this was a mistake in my testing. This class will work. I have to make a few changes, but I'll take care of it.

**Comment by varunbabu008** [comment]
Thank you @jaymedavis

**Comment by varunbabu008** [comment]
Hi @jaymedavis  . I was wondering if there was any update on this ?

**Comment by jaymedavis** [comment]
Yes - this is in the latest version. This issue can be closed. Check the latest release notes (home page of this repo -> releases).
