### ISSUE TITLE
Unable to migrate legacy accounts to custom accounts

### ISSUE THREAD

**Issue by davidwkennedy** [stripe/stripe-dotnet#952]
The Strip API supports migrating legacy recipient accounts to their new connect custom accounts. Documentation may be found here:  https://stripe.com/docs/connect/migrating#migrating-existing-recipients 

It would be helpful to have this functionality supported in stripe-dotnet. Please consider adding it.

I pulled down the source and confirmed that the following change worked for me:
Added **[JsonProperty("from_recipient")]** to **StripeAccountCreateOptions.cs**

Thank you.

**Comment by remi-stripe** [comment]
@davidwkennedy Thanks for the report and for providing the example code! I'm working on a fix in https://github.com/stripe/stripe-dotnet/pull/954 so hopefully it can be merged in the next few days.
