### ISSUE TITLE
Can't Create Reusable Source

### ISSUE THREAD

**Issue by himebaugh** [stripe/stripe-dotnet#953]
The following code fails on the call to Create:

```
StripeSourceService sourceService = new StripeSourceService();
StripeSourceCreateOptions sourceOptions = new StripeSourceCreateOptions();

sourceOptions.Type = StripeSourceType.Card;
sourceOptions.Usage = StripeSourceUsage.Reusable;
sourceOptions.Token = "tok_123abc";

sourceService.Create(sourceOptions);
```

The error is a stripe exception of "Invalid positive integer". I believe it's because the Amount field on the StripeSourceCreateOptions class is not a nullable int. The API says that field is optional when doing reusable sources:

https://stripe.com/docs/api#create_source

**Comment by remi-stripe** [comment]
@himebaugh Thanks for the report! I'm working on a fix in https://github.com/stripe/stripe-dotnet/pull/955 so it should hopefully be merged in the next few days.

**Comment by himebaugh** [comment]
Looks like you fixed it - thank you! Any idea how long before the nuget package is updated? This is holding us up on a project.

**Comment by remi-stripe** [comment]
I don't have a firm timeline. Hopefully in the next few days!

**Comment by anelder-stripe** [comment]
@himebaugh - This has been added into the latest v10.3.0 release.  Let me know if anything is sour.
