### ISSUE TITLE
Amount property in StripeChargeCreateOptions should not be of Type [int] but [decimal]

### ISSUE THREAD

**Issue by kruijs** [stripe/stripe-dotnet#972]
Right now I'm forced to cast my calculated sum to int, although that might not be the actual total.

```c#
var charge = new StripeChargeCreateOptions
{
  Amount = (int)total,
  Currency = "EUR",
             
  Description = description,
  ReceiptEmail  = receiptEmail,
  SourceTokenOrExistingSourceId = token
};
```

**Comment by remi-stripe** [comment]
@kruijs our API expects all amounts as integers and never as decimals. If you want to charge $19.99 USD you would pass `amount: 1999` in that case. It's on you to convert the amount to the right integer.
