### ISSUE TITLE
Level 2 - Feature Request

### ISSUE THREAD

**Issue by mpdillon** [stripe/stripe-dotnet#978]
The current interface works great. However, we now have customers requesting level 2 processing. Have you expanded your code to include level 2 transactions? Do you have plans to expand the code base include level 2 transactions?
Thank you,
Pat

**Comment by jlomas-stripe** [comment]
Hi Pat!

That's really more a general Stripe functionality question, rather than an issue with the Stripe.net library, so I'd suggest you reach out to Support for more information about that: https://support.stripe.com/email/login

**Comment by ob-stripe** [comment]
Closing this since it's not an issue with the library.
