### ISSUE TITLE
Support ExternalAccount Create, Edit, and List methods

### ISSUE THREAD

**Issue by anelder-stripe** [stripe/stripe-dotnet#980]
Currently ExternalAccountService only supports the `Delete` method.  This needs to be expanded.

**Comment by hagronnestad** [comment]
I was just about to integrate this in our project when I found out it isn't possible. Any ETA on this?

**Comment by remi-stripe** [comment]
@hagronnestad no ETA just yet unfortunately. We can help with reviewing a PR if you're up for this though!
