### ISSUE TITLE
Support for serialization from POCO

### ISSUE THREAD

**Issue by yoat** [stripe/stripe-dotnet#991]
This issue is related to https://github.com/stripe/stripe-dotnet/issues/949
The JSON data structures for Card sources are flat JS Objects (a single objects with many key/value pairs). The .NET objects representing Card sources begin with a flat structure, but these in turn contain other objects.

This in itself is not a problem. However, when I re-serialized the .NET object (AKA POCO) to JSON and passed it to another server in my network, the JSON could not be parsed using the StripeNet package. 

For reference, the original JSON structure compared to the JSON serialized .NET output can be seen in this gist:
https://gist.github.com/yoat/272a2bfd57da81013f622fc407d54c21

Note the specific paths:
source.data[0].last4
vs
source.data[0].Card.last4

This is not the only issue, but I think it represents the problem as a whole: the structure of the data is changed when importing from the raw API JSON into POCOs.  This problem can be worked around, and so I do not consider it a BUG.  I consider the following a FEATURE REQUEST:
Make the (default) object serializers for the StripeNet package emit structures that (perfectly?) match the raw JSON structures from the API.
A test to verify that the following is done correctly could be:
1. take sample JSON from the Stripe docs pages
2. deserialize it with StripeNet package
3. reserialize it to JSON (using NewtonSoft v10's JsonConvert function)
4. redeserialize output of step 3 to StripeNet objects

As it stands, step 4 is not a design goal and is impossible.  I suggest it would be a good design goal.
Thanks for your time and excellent library!

(Note: I have discussed this issue on the IRC channel and then with Stripe Support. They agreed that it was working as designed, suggested workarounds, which worked, and suggested I could submit a bug.)

**Comment by anelder-stripe** [comment]
Hey @yoat, thank you for filing this!  We'll try and get around to this soon.

Just so it's clear to anyone else who faces this issue in the meantime, you can obtain the original JSON of the object from the POCO by accessing the `StripeRequest` attribute of the object.

https://github.com/stripe/stripe-dotnet#responses

If you hit any hurdles while trying to get that JSON, please feel free to reach out to our support team @ https://support.stripe.com/email.

**Comment by ob-stripe** [comment]
This should be fixed in 20.0.0. The library now uses interfaces for polymorphic resources, so the class nesting structure should match the API's.
