### ISSUE TITLE
Start targeting .NET Standard 2.0

### ISSUE THREAD

**Issue by olegburov** [stripe/stripe-dotnet#992]
So, [.NET Standard 2.0 ](https://blogs.msdn.microsoft.com/dotnet/2017/08/14/announcing-net-standard-2-0/) has been release with a wide support by different frameworks (.NET Core 2.0, .NET Framework 4.6.1, Mono 5.4, Xamarin and UWP later this year). The full list can be found [here](https://github.com/dotnet/standard/blob/master/docs/versions.md).

I think it's time to upgrade the project and start targeting .NET Standard 2.0 instead of 1.2 + .NET Framework 4.5.

**Comment by softwareguy74** [comment]
+1

**Comment by anelder-stripe** [comment]
I'm into this plan!  👍

**Comment by flagbug** [comment]
@olegburov  What benefit would this library get from targeting .NET Standard 2.0?

Since it works fine with .NET Standard 1.2 and doesn't require any APIs from .NET Standard 2.0, I'd leave it as-is, to get the most surface area for consumers of this library

**Comment by jaymedavis** [comment]
The way net standard is defined everything in the future will just work. Changing this to a future version has no benefits I'm aware of either (like language support)?

**Comment by flagbug** [comment]
@jaymedavis Yup! The way .NET Standard works is that you should target the minimum version that works for you in order to ensure maximum compatibility with consumers of the library

**Comment by ob-stripe** [comment]
Per the discussion above, I'm closing this issue. We want the library to be usable by as many people as possible, which means we need to target the lowest possible version [1].

[1] https://github.com/dotnet/standard/blob/master/docs/versions.md#how-do-i-know-which-net-standard-version-i-should-target
