### ISSUE TITLE
EphemeralKey end Point

### ISSUE THREAD

**Issue by carvalho-oak** [stripe/stripe-dotnet#996]
Please add support for creating the **Ephemeralkey** endpoint in .net.
I could not find anywhere about how to return the **EphemeralKey** in .net.

**Comment by remi-stripe** [comment]
@carvalho-oak thanks for raising. I'll try to prioritize this over the next few days.

**Comment by carvalho-oak** [comment]
Hi Guys, any update on this?

**Comment by remi-stripe** [comment]
@carvalho-oak We're working on it in https://github.com/stripe/stripe-dotnet/pull/997 but it will take a few weeks for this to be finalized and merged.

**Comment by carvalho-oak** [comment]
Hi Guys, any update on this?

**Comment by remi-stripe** [comment]
@carvalho-oak no update yet. For now you can build this version of stripe-dotnet yourself on your end if you need this feature and it should just work. We plan to do a release with this feature over the next few weeks.

**Comment by ob-stripe** [comment]
Fixed in #997 and released in 11.2.0.
