### ISSUE TITLE
Feature Request - Two Step Payment Flows

### ISSUE THREAD

**Issue by simonalexandergilbert** [stripe/stripe-dotnet#998]
Does the Stripe.net library support "two step payment flows", as documented here - https://stripe.com/blog/auth-capture

**Comment by remi-stripe** [comment]
@simonalexandergilbert We do support it and you simply have to pass `Capture: false` https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Services/Charges/StripeChargeCreateOptions.cs#L31
